### ISSUE TITLE
Attempting to restore game backup yields an empty file picker

### ISSUE THREAD

**Issue by mrkirby153** [ValveSoftware/steam-for-linux#10120]
#### Your system information

* Steam client version (build number or date): 
```
Steam Version:  1696541351
Steam Client Build Date:  Thu, Oct 5 13:54 UTC -08:00
Steam Web Build Date:  Thu, Oct 5 13:57 UTC -08:00
Steam API Version:  SteamClient020
```
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

When attempting to restore a game backup, or doing any operation that would open up the file picker, an empty file picker opens instead. This is similar to #10028, but the resolution (Installing `xdg-dekstop-portal`) did not resolve the issue.

#### Steps for reproducing this issue:

1. Select Steam -> Restore Game Backup -> Browse...

Runtime Diagnostics: https://gist.github.com/mrkirby153/4dbb9c68905249cf632bac395f5e57d6

Noteworthy: 
```
"The 'version' property is not available for 'org.freedesktop.portal.Email', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.FileChooser', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.Inhibit', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.OpenURI', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.ScreenCast', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.Settings', either there isn't a working xdg-desktop-portal or it is a very old version",
 ```

these messages imply that my xdg-dekstop-portal implementation is not configured correctly, but as far as I'm aware both `xdg-desktop-portal` and `xdg-desktop-portal-gtk` are functioning correctly and are up to date

```
local/xdg-desktop-portal 1.18.0-2
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-gtk 1.14.1-3
    A backend implementation for xdg-desktop-portal using GTK
```

**Comment by mrkirby153** [comment]
This is either a defect with `xdg-desktop-portal` `1.18.0` or with Steam and I suspect the latter. Downgrading `xdg-desktop-portal` to 1.16.0 resolves the issue and the file picker opens normally.

**Comment by Zi-SH** [comment]
> This is either a defect with `xdg-desktop-portal` `1.18.0` or with Steam and I suspect the latter. Downgrading `xdg-desktop-portal` to 1.16.0 resolves the issue and the file picker opens normally.

I can confirm the fix as well. The following was done on Arch Linux:

```
sudo pacman -U https://archive.archlinux.org/packages/x/xdg-desktop-portal/xdg-desktop-portal-1.16.0-1-x86_64.pkg.tar.zst
sudo pacman -Rs xdg-desktop-portal-gtk xdg-desktop-portal-gnome xdg-desktop-portal-gtk
```

This resulted in a a functioning popup of the FilePicker and a popup as expected.

**Comment by cl-parsons** [comment]
I had the same issue on an ArchLinux fresh install with the i3 WM and xdg-desktop-portal 1.18, started with startx (no lightdm, gdm)

The following commands were executed to fix that :

```
pacman -Qqs xdg-desktop-portal | sort -r | sudo pacman -R -
# Remove any xdg-desktop-portal package

sudo pacman -U https://archive.archlinux.org/packages/x/xdg-desktop-portal/xdg-desktop-portal-1.16.0-1-x86_64.pkg.tar.zst
# Reinstall xdg-desktop-portal and select xdg-desktop-portal-gtk (3) (!IMPORTANT)

sudo sed -in '/UseIn/s/$/;i3/' /usr/share/xdg-desktop-portal/portals/gtk.portal
# Add "i3" to the "UseIn" section of the gtk portal definition

# Assert that you have set the DISPLAY and XDG_CURRENT_DESKTOP environment variables set
echo $DISPLAY
echo $XDG_CURRENT_DESKTOP

# If DISPLAY is not set, you should start X
# If XDG_CURRENT_DESKTOP is not set, you should set it (I use 'dex' in my i3 autostart script)

systemctl --user import-enviroment DISPLAY XDG_CURRENT_DESKTOP
# Import the enviroment variables in systemd

systemctl --user daemon-reload
systemctl --user restart xdg-desktop-portal xdg-desktop-portal-gtk
# Restart the xdg-desktop-portal services

systemctl --user status  xdg-desktop-portal xdg-desktop-portal-gtk
# Check that there was no error on service startup

# Launch steam and add a library folder!
```

Note that this is a temporary fix, we should report this to the ArchLinux maintainers.

**Comment by HairBomb7** [comment]
For myself, running KDE Plasma, the following fixed my issue with Steam FileChooser.

1. I started the xdg-desktop-portal service, as it wasn't running. 
`systemctl start --user xdg-desktop-portal`
2. I installed xdg-desktop-portal-kde, as it wasn't installed.
`pacman -S xdg-desktop-portal-kde`
3. I rebooted my PC.
4. Now it is working.

**I am running the following versions of xdg:**
- xdg-desktop-portal 1.18.0-2
- xdg-desktop-portal-kde 5.27.9-1

**Comment by AungKoKoLin1997** [comment]
I am facing the same problem and I see only installation destination screen and can't choose folder.
I installed [xdg-desktop-portal-gtk](https://archlinux.org/packages/?name=xdg-desktop-portal-gtk). 

And I only see this error>
`"The 'version' property is not available for 'org.freedesktop.portal.ScreenCast', either there isn't a working xdg-desktop-portal or it is a very old version",`

I think this error should not impact file chooser. Can you please help me how to fix the problem?

**Comment by DominikM60** [comment]
I have the same problem on Nobara, fork of Fedora.
Issue applies both to the Nobara repo version and flatpak one.
Has anyone managed to deal with the issue there?

**Comment by kisak-valve** [comment]
Hello @mrkirby153, can you test if the xdg-desktop-portal 1.18.0 regression you described in the opening post was resolved by subsequent updates upstream?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by ChristophFranzen** [comment]
In the recent beta update, the issue of "unpopulated" folder trees has been fixed, but one last problem remains:

1. Go to the "Steam settings" -> "In Game"
2. "External screenshots folder" -> "Choose folder": a new window opens: "Select external screenshots folder"
3. At first this seems to be fully functional, you can browse to any filesystem location.
4. Choosing "Select", however, leads to an immediate crash, no matter which folder is chosen.
No error messages or further log entries can be seen.

On my machine, this happens **everywhere** where the fallback file picker is used: as soon as I click on select after choosing a folder from the directory tree, the steam client crashes immediately.
