### ISSUE TITLE
Remote Play is Broken

### ISSUE THREAD

**Issue by Callinmyname** [ValveSoftware/steam-for-linux#10461]
#### Your system information
Steam Deck OLED 1 TB
* Steam client version (build number or date): preview 20231122.1
* Distribution (e.g. Ubuntu): N/A
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes
* Steam Logs: N/A
* GPU: Nvidia/Intel/AMD N/A - computer is Nvidia 
![IMG_8609](https://github.com/ValveSoftware/steam-for-linux/assets/158784153/fb541a57-a40b-407a-ad73-a56a00329538)

#### Please describe your issue in as much detail as possible:
I installed the preview build 20231122.1 on my steam deck and now remote play does not work. Instead of loading into a game the screen only shows the steam logo in the center and there is a ring that keeps going around in a circle. I am forced to press B to abort, otherwise it will stay like that indefinitely. Remote play works fine on stable channel.

#### Steps for reproducing this issue:

1. Download latest preview build 20231122.1
2. Stream game via remote play
3. Observe the infinite loading screen

**Comment by alosarjos** [comment]
Same happening to me

**Comment by break11** [comment]
i have the same issue. After last update steam deck oled remote play broken. It is work only in stable build not in beta or preview. But only in preview version start from 3.5.11Preview was fixed bug with GAMMA in remote play.

----------------------
" SteamOS 3.5.11Preview: Until Morale Improves"
General
-Fixed consistency of application fade-ins/fade-outs
-Fixed slightly blurry image when streaming from the Deck with Steam Remote Play
-Fixed crashes when streaming to/from the Deck with Steam Remote Play
-Fixed black screen when launching Forza Horizon 4 and other titles on Steam Deck OLED
-Added a timeout to the boot selection screen

Firmware 120 (LCD) / 107 (OLED)
-Fixed several USB compatibility issues
-Developer note: This changes the default USB mode back to XHCI (host-only) while issues with dual-role device mode are investigated
-------------------------

If i switch on stable version of steam deck remote play will work, but only with disable "hardware acceleration" GAMMA was normal, else it screen still to dark. But without "hardware acceleration" not work steam left and right menu.

**Comment by break11** [comment]
I finded temporary solution for restore work remote play.

1) Go to Settings-->System->Enable developer mode

2) Go to Settings-->Developer and enable "Show extended update channels"

3) Go to Settings-->System and select OS update channel to Release-Candidate instead of Stable version

Check updates, install it, restart steam deck.

After this steap in my steam deck OLED all works fine, remote play works and GAMMA bug not present.

**Comment by waspennator** [comment]
Still seems to be borked with latest beta client.

**Comment by waspennator** [comment]
Any update on this, a little worried this issue is going to silently slip into the next stable client update?

**Comment by SupDos** [comment]
Looks like this slipped into the stable release that came out just now

**Comment by waspennator** [comment]
I had a feeling this was going to happen. 

@kisak-valve

**Comment by SorceressLyra** [comment]
Yup it is now present on stable.

**Comment by Solid-Designs** [comment]
Yup, broken for me now too

**Comment by legit-jb** [comment]
Broken for me as well

**Comment by thedefside** [comment]
Absolutely ridiculous that this got pushed to stable. Whose doing QA over there?

**Comment by Benroyz** [comment]
Broken for me too.

**Comment by geeksville** [comment]
@kisak-valve  broken in the new sable release please stop new deployments!

**Comment by waspennator** [comment]
Why is there even preview and beta channels if issues just get silently ignored and pushed onto stable until people make a big enough stink for devs to noticeM

**Comment by break11** [comment]
remote play in gaming mode completely broken in all versions after last update (

**Comment by SausageDog** [comment]
@kisak-valve - I presume Valve has its own way of managing the Steam Client software lifecycle, but where I've worked in the past we would classify issues based on criticality, and issues that are breaking changes for core features would be blockers for purposes of releasing a stable new release. You simply couldn't release with those issues still open.

I'm not sure if that was considered here and Remote Play is just no longer considered a critical feature of the Steam Client, but if it is I'd suggest Valve adopt a similar categorization for issues and regressions. Over the past 6 months Remote Play has been repeatedly broken on the Steam Client stable branch. The fact that this wasn't just an unknown bug that was missed in regression testing, but a known issue that was just pushed into the stable branch isn't a great way to treat your customers.

It's okay to have breaking changes in a beta channel as people can sacrifice cutting edge features for stability. It's not okay to have breaking changes in your stable branch if the user can no longer work around them. If Valve is going to continue to make the Steam Client auto-update, you need to lift your game around preventing regressions from making it into the "stable" branch.

**Comment by d-rez** [comment]
b0rk3d on stable and beta. 

Also stupid that pressing B to cancel connecting on the Deck just... kills the game on th PC that it's been attempted to be streamed from lol, regardless if it the game has been started before attempting to remote play, or started by remote play.

**Comment by mpkonmbk** [comment]
Adding to what @SausageDog already perfectly captured: I thought that, thanks to having WiFi 6E on-board and Remote Play being an advertised Steam feature, the Steam Deck would be a perfect streaming device for me. Imagine my deep disappointment when not only did it not work (where the many times cheaper Raspberry Pi 5 worked perfectly well), it's been broken for 3 months now.

**Comment by MightyMushka** [comment]
Chiming in to note this is an issue for me on stable as well.

**Comment by arrrggghhh** [comment]
You could have warned us in the changelog.

**Comment by waspennator** [comment]
Is there any eta for a hotfix or rollback given this issue and the verifying install issue that popped up with this update, not touching my deck for the time being, especially with how easy it is for the device to forcibly auto update like windows if you go onto desktop mode.

**Comment by Daniel-Griffiths** [comment]
Same issue here, remote play was crashing on the beta and now it's crashing on stable too.

Tested using the steam link app on Apple TV

**Comment by Burnshausen** [comment]
Like Heaven-Crow already said: 

This is honestly baffling, as I work within the IT field as well. You have TWO channels prior to the stable release to catch bugs/problems, ans this is a well-documented (!) issue within the beta and this and other problems (verifying install at boot-ups, severe performance drops for occasional games) slip into the stable release? How is this possible? Who is responsible for testing within Beta/Preview? I thankfully catched the warning signs prior to updating and will now turn auto-update off forever. I lost officially trust in your update schemes, Valve. Well done. After owning a Deck for about 3 weeks.

And update your news channel. The least you can do. Shocking how you currently handle the situation. I actually hope this results in consequences. Because if that happens to me at my area, I would lose my job asap.

**Comment by Mamoon-B** [comment]
Chiming in, this is baffling. I used the Steam Deck EXCLUSIVELY as a remote play device. How was this not caught? This is absurd, I have no use for my Steam Deck OLED now.

Now I know not to trust Valve's so called "stable" updates. Lesson learned.

**Comment by Btrain22** [comment]
Now broken on stable. works in desktop mode. Was working fine before the update.

**Comment by Zer0FluxGiv3n** [comment]
Confirming broken on all release channels, including stable. Rollback to previous build/steamOS recovery disk is a temporary workaround.

**Comment by arrrggghhh** [comment]
remote play has NEVER worked since I got an oled model. now it's completely broken, abandoned for months now.

**Comment by break11** [comment]
@kisak-valve is there a fix coming soon? Remote Play allows to play AAA Game in home with max qaulity and max battery life.It is real importatain function.

**Comment by araujorm** [comment]
A new update just dropped stating it should fix this issue. Can anyone confirm it's good?

**Comment by break11** [comment]
> A new update just dropped stating it should fix this issue. Can anyone confirm it's good?

Now it can start in stable channel, but steel present GAMMA color bug - picture is to dark.

**Comment by waspennator** [comment]
> > A new update just dropped stating it should fix this issue. Can anyone confirm it's good?
> 
> Now it can start in stable channel, but steel present GAMMA color bug - picture is to dark.

Saw another post on the remote play community hub also saying the infinite loading is fixed but the darker picture while using hardware rendering is still there.

Is there another issue report for that issue?

**Comment by SupDos** [comment]
Gamma bug is supposedly fixed in Preview according to https://github.com/ValveSoftware/SteamOS/issues/1246 and https://github.com/ValveSoftware/SteamOS/issues/1166

**Comment by araujorm** [comment]
Tried it now, unfortunately still crashes and restarts steam (stable channel).

**Comment by break11** [comment]
In the beta channel everything is the same as in the stable version - remote play works, but with a GAMMA color bug.

In the early build channel, everything works fine - remote play starts and the image color is normal.

**Comment by break11** [comment]
> Tried it now, unfortunately still crashes and restarts steam (stable channel).

Sounds like another issue: this thread has an issue with the Steam client freezing when starting remote play, as shown in the picture in the first post of the thread.

**Comment by break11** [comment]
If select channel for update separately for os and steam client like in this post https://github.com/ValveSoftware/steam-for-linux/issues/10461#issuecomment-1925925804
all work in all version combination except stable version for steam os. Only in stable OS channel color GAMMA bug still present. Freeze bug do not present in all combination of version.

**Comment by shobu13** [comment]
> If select channel for update separately for os and steam client like in this post [#10461 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/10461#issuecomment-1925925804) all works in all version combination except stable version for steam os. Only in stable OS channel color GAMMA bug still present. Freeze bug do not present in all combination of version.

i have absolutely no idea why this work, but it's work.

**Comment by waspennator** [comment]
Checking around, it seems like the infinite loading screen bug for remote play is fixed, though checking around here, seems like I'm seeing some comments talking about crashing  via streaming steam deck via steam link. Maybe a new report should be opened up?

https://steamcommunity.com/app/1675200/eventcomments/4300445619228315331?snr=2_9_100003_

**Comment by SupDos** [comment]
OS update just got pushed to stable, @kisak-valve this issue, https://github.com/ValveSoftware/SteamOS/issues/1246 and https://github.com/ValveSoftware/SteamOS/issues/1166 should be fine to close now

**Comment by kisak-valve** [comment]
Closing per the last several comments.

**Comment by sylv256** [comment]
Not fixed. Please reopen. This has been broken for ages
