### ISSUE TITLE
Steam games crash after start up screen.

### ISSUE THREAD

**Issue by dmndwlf** [ValveSoftware/steam-for-linux#10896]
#### ryzen 7 5800x 
amd radeon 6700 xt

* Steam client version : Stable Client 1715635533
* Distribution : Arch linux 6.8.9-arch1-2
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

 Steam games like Counter Strike 2 and Overwatch 2 crash after initial launch,after last steam update on Gnome Xorg Arch linux updated.

If i install games on external drives full of free space there is a message that 0 bytes of system file memory are available.I tried to install at main drive where steam is installed and games keep crashing after start up screen.
Things that didn't solve the problem are:
1)Updating both arch distribution and amd drivers.
2)Uninstalling and reinstalling steam.
3)Clearing download cache.
4)Repairing storage library folder
5)Making library folder as default.

After running steam from terminal i receive the below log after crash.

''crash_20240515150207_2.dmp[15059]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240515150207_2.dmp
crash_20240515150207_2.dmp[15059]: Finished uploading minidump (out-of-process): success = yes
crash_20240515150207_2.dmp[15059]: response: Discarded=1
crash_20240515150207_2.dmp[15059]: file ''/tmp/dumps/crash_20240515150207_2.dmp'', upload yes: ''Discarded=1''
pid 15059 != 15058, skipping destruction (fork without exec?)''

**Comment by kisak-valve** [comment]
Hello @dmndwlf, this is a kernel regression which was tracked and fixed in https://gitlab.freedesktop.org/drm/amd/-/issues/3343. You can reboot into an older kernel (6.6.30 doesn't count as older) until the fix is backported to a kernel shipped by Arch.

**Comment by dmndwlf** [comment]
Rebooting into an older kernel didn't solve the problem.I tried many kernels.Some were very old.
I suppose it has to do with latest update of steam maybe?
