### ISSUE TITLE
Team Fortress 2 is always launch in 640x480 window and ignore -full option

### ISSUE THREAD

**Issue by RussianNeuroMancer** [ValveSoftware/steam-for-linux#110]
In my case Team Fortress 2 is always launch in 640x480 window and ignore -full option. That probably happen because of my a little unusual display configuration:
krandr: http://i.imgur.com/4JA59.png
xorg.conf: http://pastebin.com/wwRvhj8g
xrandr startup command from krandrrc: xrandr --output LVDS --pos 0x180 --mode 1600x900 --refresh 60.307\nxrandr --output DFP1 --pos 1600x0 --mode 1920x1080 --refresh 60\nxrandr --output DFP1 --primary

Issue is reproducible with both of radeon and fglrx drivers.
Issue is not reproducible when I disable LVDS panel in krandr settings.

**Comment by mastercoms** [comment]
Hi, I am having this issue again:

<details>
  <summary>Steam Information</summary>
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  4700 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Fedora release 33 (Thirty Three)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.9.8-200.fc33.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  12009000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20201104.0

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 455.45.01
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x10de
    DeviceID:  0x1b80
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 4480 x 1440
    Primary Display Size: 27.44" x 15.43" (31.46" diag)
                                            69.7cm x 39.2cm (79.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  64256 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  400001 Mb
    Largest Free Hard Disk Block:  52390 Mb
```
</details>

**Comment by mastercoms** [comment]
Fixed with https://www.reddit.com/r/Fedora/comments/jxuh9i/cant_go_full_screen_mode_in_csgo/gczrzqq.

**Comment by nergdron** [comment]
just ran into this trying to play TF2 with a friend, on Ubuntu 20.04 with the NVidia binary drivers. this is definitely not fixed in current releases.

**Comment by nergdron** [comment]
note that using `-windowed` allows it to start in a window, choosing a fullscreen mode doesn't actually set things to fullscreen or switch out of windowed mode. so something is more broken now than it was initially in 2013.

**Comment by bartico6** [comment]
I'm getting this on Ubuntu 20.10 too, with nVidia 455.xx drivers.

The game always starts in a 640x480 window unless I force the width/height parameters on it, and bricks whenever I make any changes via the settings prompt. The "fullscreen" option never works, but setting it from within the game settings window *sometimes* works and sometimes doesn't.

**Comment by kisak-valve** [comment]
Hello @mastercoms, @bartico6, both of you were probably seeing a GNOME 3.38.1 specific regression, the same as https://github.com/ValveSoftware/csgo-osx-linux/issues/2551 and fixed in mutter 3.38.2. Fedora 33 should have already gotten an update while Ubuntu 20.10 is waiting on https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1908158.

In any case, the issue tracked here was resolved in 2013 and issues with Team Fortress 2 should be tracked in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.

**Comment by felipsmartins** [comment]
I'm getting this on Ubuntu 20.10 too, with nVidia 455.xx drivers as well
