### ISSUE TITLE
Massive Lag & Corruption in Big Picture mode Under latest Nvidia Driver  Works correctly under Gamescope - Repeat of #8918

### ISSUE THREAD

**Issue by tlneondo** [ValveSoftware/steam-for-linux#11255]
#### Your system information

* Steam client version (build number or date): Latest Stable as of 9/12/24, issue persists in Beta as well
* Distribution (e.g. Ubuntu):  Fedora
* Opted into Steam client beta?: Yes, Does not make a difference
* Have you checked for system updates?: Yes
* Steam Logs: [
[steam-logs.tar.gz](https://github.com/user-attachments/files/17000139/steam-logs.tar.gz)
](url)
* GPU: Nvidia Geforce RTX 4070 Super

#### Steps for reproducing this issue:

1. Launch RPM Fusion Steam Package
2.  Enter Big Picture mode
3.  Observe Low framerate and corruption
4. Launch inside of gamescope, notice framerate is much much improved

Without Gamescope:

https://github.com/user-attachments/assets/6fdad3f1-e622-4d97-a74b-e0e6f1482e5b

With Gamescope:

https://github.com/user-attachments/assets/16a561ce-5b77-45e9-a67c-0c376626e5af

**Comment by CptCookies12** [comment]
I don't think this is a Nvidia specific issue, I'm also seeing a similar problem on an AMD Radeon RX 6700 XT on Fedora, except the non-Gamescope performance is drastically worse than your Nvidia footage is. RPM Fusion install, tried both beta and stable, and launching with Gamescope solves the performance issue. Rest of the desktop Steam client works fine otherwise.

**Steam Version:** 1726256783
**OS:** "Fedora Linux 40 (KDE Plasma)" (64 bit)
**Kernel Version:** 6.10.9-200.fc40.x86_64
**CPU:** AMD Ryzen 7 5800X3D 8-Core Processor
**Driver:** AMD AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 18.1.6, DRM 3.57, 6.10.9-200.fc40.x86_64)
**Driver Version:** 4.6 (Compatibility Profile) Mesa 24.1.7
**Logs here:** [logs.tar.gz](https://github.com/user-attachments/files/17003733/logs.tar.gz)

**Comment by Proxycon** [comment]
Can confirm, this also applies for AMD drivers. Performance in BigPicture is extremly poor, and Steam Client crashes when connecting for remote play. Streaming only works when a game is already running in fullscreen. 

**Steam Beta Branch:**  Stable Client
**Steam Version:**  1726256783
**OS:** Nobara Linux 40 (KDE Plasma) x86_64
**Kernel:** 6.10.7-200.fsync.fc40.x86_64
**CPU:** AMD Ryzen 7 5800X3D (16) @ 4.550GHz 
**GPU:** AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 18.1.6, DRM 3.57, 6.10.7-200.fsync.fc40.x86_64
**Driver:** OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.1

**Comment by tnbp** [comment]
This also affects AMD systems. Running in Gamescope works fine here, as does Remote Play (even without Gamescope).

The difference in performance (some report 15 FPS, some 3 FPS) may stem from running Big Picture in different resolutions (it's much slower in 2160p than 1080p).

**Comment by davernos** [comment]
Same issue here. 

Steam Beta Branch:  Stable Client
Steam Version:  1726256783
OS: Nobara Linux 40 (KDE Plasma) x86_64 
Kernel: 6.10.2-200.fsync.fc40.x86_64 
CPU: AMD Ryzen 5 5600 (12) @ 4.468GHz 
GPU: AMD ATI Radeon RX 7700 XT / 7800 XT 



Before the update it ran fine.

**Comment by Bloodninj** [comment]
Also having this same issue on Ubuntu 24.04.1. I thought it was due to changing monitors and the previous one having a higher refresh rate. This is happening on Ubuntu too so maybe the `Distro Family: Fedora` tag should be removed?

**Steam Beta Branch:**  Steam Beta Update
**Steam Version**:  1726256783
**OS:** Ubuntu 24.04.1 LTS
**Kernel:** 6.8.0-44-generic x86_64
**CPU:** AMD Ryzen 7 5800X
**GPU:** AMD Radeon 6700XT

[System report](https://gist.github.com/Bloodninj/57f20e647d812703e0f3cf8a073a7068)

**Comment by davernos** [comment]
> Also having this same issue on Ubuntu 24.04.1. I thought it was due to changing monitors and the previous one having a higher refresh rate. This is happening on Ubuntu too so maybe the `Distro Family: Fedora` tag should be removed?
> 
> **Steam Beta Branch:** Steam Beta Update **Steam Version**: 1726256783 **OS:** Ubuntu 24.04.1 LTS **Kernel:** 6.8.0-44-generic x86_64 **CPU:** AMD Ryzen 7 5800X **GPU:** AMD Radeon 6700XT
> 
> [System report](https://gist.github.com/Bloodninj/57f20e647d812703e0f3cf8a073a7068)

Probably. Also the title description should remove the mention to Nvidia. Let see if we get more reports.

**Comment by tlneondo** [comment]
I'm surprised that AMD users are having issues. This was one of the big downgrades I had to deal with going from my 5700XT to my current 4070 Super. The 5700XT i have running in my GF's PC now and It's not showing any issues, meanwhile my 4070 Super has the issues as described in my post.

**Comment by tnbp** [comment]
Weirdly, I do *not* seem to have this problem if I launch `steam` with the `-bigpicture` (or `-tenfoot`) flag outright, *regardless* of whether or not I'm using gamescope.

**Comment by davernos** [comment]
> Weirdly, I do _not_ seem to have this problem if I launch `steam` with the `-bigpicture` (or `-tenfoot`) flag outright, _regardless_ of whether or not I'm using gamescope.

Just tested it on my desktop and I can confirm the issue is gone, using the -bigpicture flag.

**Comment by dmitsuki** [comment]
> Weirdly, I do _not_ seem to have this problem if I launch `steam` with the `-bigpicture` (or `-tenfoot`) flag outright, _regardless_ of whether or not I'm using gamescope. **EDIT** to clarify: The issue is still there (i.e. performance is awful if you open Steam first and then switch to Big Picture Mode), but it does not seem to occur if you launch Steam directly into BPM. (It will re-occur if you exit and re-enter BPM.)

I'm on a 6700 xt, and I experience this same behavior. It's laggy, unless I run it with the -bigpicture flag.

**Comment by 99kennetn** [comment]
same experience here. It runs smooth when opened with -bigpicture, but begins to lag if exiting BPM and re-entering it, or having been in the normal launcher before entering BPM.

Kubuntu 24.04 (wayland)
RX 7900 GRE
i5-.8600K
32GB memory

As a maybe related side note, before upgrading to the AMD gpu a couple of months back, the launcher would tank performance in som games if it was open in the background. I had to minimize the window in order for it to not take the ressouces, here BPM correctly handled ressources when it was launching games.
Before upgrading i had a 1070TI and 16GB memory, but same cpu.

**Comment by tlneondo** [comment]
Can confirm on my Nvidia Card that launching with the -bigpicture flag fixes performance. It does appear that the left side menu shows black before the Store,library, Media etc Panel slides into place, but the performance isn't unusable.

**Comment by Zolfbs** [comment]
I'm also having the same issue on Ubuntu 24.04. Valve finally fixed the "Steam is not responding" issue that kept happening, but now this new problem has come up. I tried disabling hardware acceleration and enabling/disabling the GPU blocklist, but unfortunately, nothing works

**Comment by theLucasAntunes** [comment]
Having the same exact issue in Windows 11.

This is not Linux-related.

Tried in both the official version and Beta version, same issue.

**Comment by bradsevy** [comment]
Observing the same thing on Fedora 40. RX 6800, mesa 24.1.7, kernel 6.10.11-200.

**Comment by Proxycon** [comment]
I want to add to my previous comment that the crashes in steam link streaming were caused by pipewire, so unrelated to this issue.

**Comment by XDM-Inc** [comment]
im having the same issue with my radeon 7900 XTX. it gets a super lag for some reason on first launch.(no visual glitches though) if i kill the overlay it will relaunch itself and fix the issue.
my monitor is 2k resolution @170hz
and my tv is 4k @120  it lags worse on my tv

Fedora 40 (KDE edition)
ryzen 5950x
radeon 7900 XTX
Mesa 24.1.7

**Comment by NakuKoro** [comment]
I'm also having the exact issue with my Radeon RX 7900 XTX

Nobara 40
Ryzen 9 7950x
Radeon RX 7900 XTX
Mesa 24.2.3

**Comment by NakuKoro** [comment]
> I'm also having the exact issue with my Radeon RX 7900 XTX
> 
> Nobara 40 Ryzen 9 7950x Radeon RX 7900 XTX Mesa 24.2.3

So my issue seems to resolve itself when I launch steam gamepadui directly from the terminal (steam -gamepadui) but if I launch steam directly without -gamepadui the issue comes back

**Comment by pfych** [comment]
Launching with `-bigpicture` fixes the issue but exiting back to normal view then returning to big picture causes the performance issues to return.

**Steam Beta Branch**:  Stable Client
**Steam Version**:  1726604483
**OS**: EndeavourOS
**Kernel**: 6.11.3-arch1-1
**CPU**: AMD Ryzen 7 5800X3D
**GPU**: AMD Radeon RX 5700 XT
**Driver Version**: 4.6 (Compatibility Profile) Mesa 24.2.4-arch1.1

**Comment by Joseph-DiGiovanni** [comment]
Same results as above. Very low FPS unless I use `-bigpicture`. Seems to run much slower with larger resolutions indicating a hardware acceleration issue.

Steam Beta Branch: Stable Client
Steam Version: 1726604483
OS: NixOS 24.05
Kernel: Linux 6.6.54
CPU: AMD Ryzen 7 7800X3D
GPU: AMD Radeon RX 7900 XT
Driver Version: Mesa 24.0.7

**Comment by benleppke** [comment]
I can confirm the same behavior described here by others. Poor performance in Big Picture mode unless Steam is launched in Big Picture mode. I also notice transparency/layering issues with the left steam panel

I am using Gnome/Wayland.

Steam Beta Branch:  Stable Client
Steam Version:  1726604483
OS: Bazzite 40.20240930
Kernel: 6.9.12-205.fsync.fc40.x86_64
CPU: Intel i7-9700K
GPU: Nvidia RTX 2080
Driver: NVIDIA 560.35.03

**Comment by DanMan** [comment]
FWIW, I can not confirm this on Fedora 40 and the NV 560.35.03 driver. The only thing that matters performance wise is, if I have enabled hw-accel in web views. It's noticeably slower without it.

But if I enable hw-accel, the videos in the store become awfully choppy and slow. So I have to keep it off, still. But that's clearly a different issue altogether.

**Comment by perroboc** [comment]
Same thing happens in Fedora 40 (KDE) + AMD GPU. Logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/17461733/steam-logs.tar.gz)

Happens on both flatpak and rpm fusion versions.

**Comment by InsaneCake** [comment]
Same issue. Starting with `-bigpicture` helps.

Steam Beta Branch: Stable Client
Steam Version: 1726604483
OS: EndeavourOS Linux x86_64 
Kernel: 6.11.4-zen2-1-zen 
DE: Plasma 6.2.1 
CPU: AMD Ryzen 9 3900X (24) @ 4.673GHz 
GPU: AMD ATI Radeon RX 7700 XT / 7800 XT

**Comment by everettperiman** [comment]
Launching with -bigpicture fixes the issue but exiting back to normal view then returning to big picture causes the performance issues to return.

Steam Beta Branch: Stable Client
Steam Runtime Version: steam-runtime_0.20240806.97925
OS: Debian GNU/Linux trixie/sid x86_64
Kernel: 6.11.4-amd64 
CPU: AMD Ryzen 7 5800X
GPU: AMD Radeon RX 6750 XT
Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.4-1

**Comment by korewaChino** [comment]
I can also confirm. Happens too on Beta branch.

Operating System: Ultramarine Linux 41
KDE Plasma Version: 6.2.2
Kernel Version: 6.11.5-300.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Steam Beta Branch:  Steam Beta Update
Steam Version:  1730253536
[runtime-info.json](https://github.com/user-attachments/files/17567902/runtime-info.json)

Seems like Steam for some reason reverts to Software rendering when switching from desktop to Big Picture.

**Comment by hardpenguin** [comment]
Quick update: the problem is that GPU accelerated views perform REALLY bad in the desktop mode of the client. I prefer to keep them disabled. So to get **best smooth Big Picture experience** I need to:

1. Turn on GPU accelerated views
2. Turn off Steam client
3. Turn on Gamescope
4. Turn back on Steam client (either in desktop then click BPM button or in Big Picture mode directly)

...and when I want to get back to **best smooth desktop experience** I need to perform these steps in reverse.

Not ideal!

**Comment by perroboc** [comment]
Same behaviour on Flatpak version: launching with `-gamepadui` makes everything work as expected. But upon exit I encounter #9565, and launching Big Picture Mode from this window makes this issue (#11255) happen again.

Launching Steam with `-gamepadui` from terminal:
```
flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam --file-forwarding com.valvesoftware.Steam -gamepadui
```

Steam version:
```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1730253536
Steam Client Build Date:  Tue, Oct 29 10:27 PM UTC -04:00
Steam Web Build Date:  Tue, Oct 29 10:01 PM UTC -04:00
Steam API Version:  SteamClient021
```

**Comment by coreybruce** [comment]
Yeah very weird, if I launch Steam in my terminal with ```steam -bigpicture``` it's fine but as soon as I go out of big picture mod and go back in with the button on the top right hand corner it's back to laggy again and I have to close and relaunch Steam with that argument again to run correctly.

**Comment by libboj** [comment]
Same issue with AMD Vega 64 and 5800X3D CPU.

Is Valve on it or ??
Also the Xbox/home button doesn't trigger the Big picture mode on the beta release but does on the stable release.

**Comment by coreybruce** [comment]
> Same issue with AMD Vega 64 and 5800X3D CPU.
> 
> Is Valve on it or ?? Also the Xbox/home button doesn't trigger the Big picture mode on the beta release but does on the stable release.

I noticed this issue as well

**Comment by Noctis-Bennington** [comment]
I have a MSI laptop installed with Ubuntu 24.04, AMD as CPU & GPU. The graphic card's a Radeon RX 5600m. 

I can confirm I have the same issue, it happens when you change from Steam desktop mode to Big Picture, but not if you enable the "Start in Big Picture mode" option and you open Steam again.

**Comment by GameKing505** [comment]
Same issue here - I'm on Arch with a 6800XT. Starting in big picture mode directly (either with the UI checkbox or with a command flag) results in a smooth experience but as soon as I exit into desktop mode and go back into Big Picture Mode it's a laggy mess.

What is the command to use if I want to launch big picture mode via gamescope? That seems to have fixed the problem for others and I'd like to try.

**Comment by misterright1** [comment]
I also have the same performance issues on Windows 10, with an RTX 3090.

**Comment by Remy-10** [comment]
On Arch with a 6950XT, got the same issue. Disabling smooth scrolling seems to help.

**Comment by Ebenwaldner-Mario** [comment]
Fedora, latest Kernel, 6950XT, same issue here. As previously mentioned, starting steam in Big Picture does not fault any issues but switching from desktop to big picture gives you horrendous experience.

**Comment by Heatsreef** [comment]
Same issue here: Fedora 41, latest Kernel, Wayland, 6950XT. As previously mentioned starting steam in big picture does not yield any problems but enabling big picture afterwards gives you at most 5fps. Turning off gpu accelerated web-rendering kind of makes it a bit better, but still not usable.

**Comment by perroboc** [comment]
Happy to report that latest beta (updated today) seems to have fixed this issue.

```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1731716808
Steam Client Build Date:  Fri, Nov 15 7:15 PM UTC -04:00
Steam Web Build Date:  Fri, Nov 15 9:11 PM UTC -04:00
Steam API Version:  SteamClient021
```

**Comment by NakuKoro** [comment]
> Happy to report that latest beta (updated today) seems to have fixed this issue.
> 
> ```
> Steam Beta Branch:  Steam Beta Update
> Steam Version:  1731716808
> Steam Client Build Date:  Fri, Nov 15 7:15 PM UTC -04:00
> Steam Web Build Date:  Fri, Nov 15 9:11 PM UTC -04:00
> Steam API Version:  SteamClient021
> ```

Not for me

**Comment by perroboc** [comment]
> > Happy to report that latest beta (updated today) seems to have fixed this issue.
> > ```
> > Steam Beta Branch:  Steam Beta Update
> > Steam Version:  1731716808
> > Steam Client Build Date:  Fri, Nov 15 7:15 PM UTC -04:00
> > Steam Web Build Date:  Fri, Nov 15 9:11 PM UTC -04:00
> > Steam API Version:  SteamClient021
> > ```
> 
> Not for me
> 
> Steam Beta Branch: Steam Beta Update Steam Version: 1731716808 Steam Client Build Date: Sat, Nov 16 1:15 AM UTC -08:00 Steam Web Build Date: Sat, Nov 16 3:11 AM UTC -08:00 Steam API Version: SteamClient021

Might be related to the distro, maybe? I'm using the flatpak release.

**Comment by deanrih** [comment]
@tlneondo may I know the specific running script for the Gamescope case one? I want to try the related issue with it (#9834)

**Comment by misterright1** [comment]
> I also have the same performance issues on Windows 10, with an RTX 3090.

I have noticed that this issue happens as if it's struggling to load stuff, sometimes I wanna open the side menu, it will be like half open and I'll see the cover and background images load one by one on the home screen and after it's done doing that the menu just opens. I'm guessing as big picture is basically just a web page it doesn't cache the images/or constantly reloads them. I have a 3900x and steam is installed on a 1TB M.2 1.5Gbit Gigabyte SSD. I'll check if it does this without an internet connection later.

**Comment by techienz** [comment]
Hi all, newish to helping troubleshoot this stuff and not a dev but wanted to share my experience. Sorry in advance for long comment. I am having the same issue on:

Steam Version: 1731433018
Package type: .deb
OS: Ubuntu 24.04
GPU: AMD Radeon RX7800XT
Monitor: Dell 2560 x 1440 resolution (and a secondary 4k LG monitor)

To me it looks like an upscaling issue (maybe stating the obvious).

Everything works fine when launching the Steam client directly into BPM, no lag. If I instead turn on windowed mode and launch the client into BPM, the windowed resolution that loads is 1280 x 800. If close BPM, then open it again and expand that window to fullscreen (1440p), the lag comes back. If I minimize again back down to 1280 x 800, lag pretty much goes away.

Next I tried disabling the scaling settings in BPM. **I turned off Automatically scale user interface** under Display settings and put the slider right to the left for "More content". The went into Interface and disabled **Scale text and icons to match monitor settings**. The performance after this change was much better. Still some lag but overall a much nicer experience.

I read in [this article](https://wiki.archlinux.org/title/Gamescope) that gamescope uses AMD FidelityFX Super Resolution for upscaling. Is it possible that launching the client directly into BPM or using gamescope enables this setting? I also noticed these settings in my config.vdf file. Might be nothing but thought I'd share in case someone knows if there is anything here. I tried changing them but they get overwritten when the client launches. Is there some way to play around with these settings in the file without it being overwritten?

### Windowed

`	}
	"UI"
	{
		"Window"
		{
			"SP"
			{
				"x"		"4490"
				"y"		"548"
				"width"		"1280"
				"height"		"800"
			}
		}
		"display"
		{
			"Current"
			{
				"MinScaleFactor"		"0.5"
				"MaxScaleFactor"		"1.49847817420959473"
				"IsExternalDisplay"		"1"
				"name"		"External: DP-4 27\"|||Fullscreen-1280x800"
				"AutoScaleFactor"		"1"
				"ScaleFactor"		"1"
			}
			"External: DP-4 27\"|||Fullscreen-2560x1440"
			{
			}
			"External: DP-4 27\"|||Fullscreen-2560x1305"
			{
				"ScaleFactor"		"1.80486476421356201"
			}
			"External: DP-7 27\"|||Fullscreen-1280x800"
			{
			}
		}
	}
	"BigPicture"
	{
		"Windowed"		"1"
	}`

### Not Windowed, scaling settings turned off / right down
`	}
	"UI"
	{
		"Window"
		{
			"SP"
			{
				"x"		"3840"
				"y"		"235"
				"width"		"2560"
				"height"		"1440"
			}
		}
		"display"
		{
			"Current"
			{
				"MinScaleFactor"		"0.948683321475982666"
				"MaxScaleFactor"		"2.84316229820251465"
				"IsExternalDisplay"		"1"
				"name"		"External: DP-4 27\"|||Fullscreen-2560x1440"
				"AutoScaleFactor"		"1.89736664295196533"
				"ScaleFactor"		"0.948683321475982666"
			}
			"External: DP-4 27\"|||Fullscreen-2560x1440"
			{
				"ScaleFactor"		"0.948683321475982666"
			}
			"External: DP-4 27\"|||Fullscreen-2560x1305"
			{
				"ScaleFactor"		"1.80486476421356201"
			}
			"External: DP-7 27\"|||Fullscreen-2560x1440"
			{
			}
		}
	}
	"BigPicture"
	{
		"Windowed"		"0"
	}`

**Comment by coolymike** [comment]
Still have this issue with similar side effects as others:
```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1732746274
Steam Client Build Date:  Wed, Nov 27 11:06 PM UTC -08:00
Steam Web Build Date:  Wed, Nov 27 10:54 PM UTC -08:00
Steam API Version:  SteamClient021

GPU: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.59, 6.12.1-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1
CPU: Ryzen 5 5600
Monitor: 1920x1080@60
(Valve Index attached but not used)
```

The big picture mode client is "laggy" when in full screen and only when started by Steam itself. Starting `steam -bigpicture` resolves it temporarily, setting it to windowed resolves it temporarily. Current beta and stable branch did not change anything.

**Comment by RichmarIII** [comment]
OS: Arch Linux x86_64 
Kernel: 6.12.1-arch1-1 
Resolution: 1920x1080 
DE: Plasma 6.2.4 
WM: kwin 
CPU: Intel i9-10850K (20) @ 5.200GHz 
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A 
Memory: 17331MiB / 80282MiB 

If i start steam via `steam -bigpicture`, everything is silky smooth even with `Hardware Accellerated Web Views`, `Hardware Decoding`, and `Smooth Scrolling` enabled.  If i exit `Big Picture Mode` and then try to re-enter via the user interface... EXTREME lag.  I then have to completely shut down steam and start again with `steam -bigpicture`

**Comment by FanderWasTaken** [comment]
Steam starts with `-no-restart-on-ui-mode-change` option. Is there a way to disable it? Should fix this issue at least somewhat.

`exec ./steamwebhelper -lang=en_US -cachedir=/home/niko/.local/share/Steam/config/htmlcache -steampid=15949 -buildid=1733265492 -steamid=0 -logdir=/home/niko/.local/share/Steam/logs -uimode=7 -startcount=0 -steamuniverse=Public -realm=Global -clientui=/home/niko/.local/share/Steam/clientui -steampath=/home/niko/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-enable-site-isolation --remote-allow-origins=* --remote-debugging-address=127.0.0.1 --remote-debugging-port=8080 --enable-smooth-scrolling --password-store=basic --ignore-gpu-blocklist --log-file=/home/niko/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal,ValveFFmpegAllowLowDelayHEVC
`

**Comment by Toadlover404Git** [comment]
I should add to this by mentioning it affects the Steam Deck too. Big Picture in Desktop Mode is horribly laggy.

https://github.com/user-attachments/assets/a4544b50-f62b-476c-b22e-deb7b491ca88

**Comment by Toadlover404Git** [comment]
It affects the Steam Deck in Desktop Mode too.

https://github.com/user-attachments/assets/bf54627a-d36f-4d5f-bb49-70254ddfb5bd.mp4

**Comment by Toadlover404Git** [comment]
I should add to this by mentioning it also affects the Steam Deck in Desktop Mode. It's just as laggy. The `steam -bigpicture` workaround works on that as well, but launching BPM through Steam on the Deck is still laggy.

**Comment by Noctis-Bennington** [comment]
Don't know if only happens to me (Ubuntu 24.04, AMD Radeon 5600m as Graphic card) but if you instead in big picture go to "change account" and click on your account again or another, this lag disappear too. More easily to "fix".

**Comment by perroboc** [comment]
> Don't know if only happens to me (Ubuntu 24.04, AMD Radeon 5600m as Graphic card, .deb version) but if you instead in big picture go to "change account" and click on your account again or another, this lag disappear too. More easily to "fix".

Just tested this, and the same happens to me. I think that's the same behaviour as starting Steam in Big Picture Mode: by changing account from BPM, you basically restart steam into BPM.

**Comment by nexitem** [comment]
Same issue, workarounds dont seem to do anything. I have to start it with commandline into big picture mode for no issues.

**Comment by JackMechem** [comment]
Same issue here:
OS: Arch (6.12.4-arch1-1)
WM: Hyprland (Wayland)
CPU: 13th Gen Intel Core i7-13700KF
GPU: AMD Radeon RX 7800 XT

Ive had this issue for the longest time, just never really used big picture. Everything is fine when running with `-bigpicture`.

**Comment by Abrifq** [comment]
Hello, I haven't seen anyone mention this but it seems like every time it lags, it's actually writing to cef_log.txt, possibly writing in sync/blocking mode which causes the stutters.

The error is this, repeated per stutter frame:
`[1214/164024.026846:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 24303, .bad_value = 85983373, .minor_opcode = 0, .major_opcode = 2}`

I think this is a chromium/cef issue instead of valve, unless they are missing a check and using a parameter wrongly. I'll try to waste my time finding the issue (lmao) and maybe find a fix too

**Comment by Toadlover404Git** [comment]
> it seems like every time it lags, it's actually writing to cef_log.txt, possibly writing in sync/blocking mode which causes the stutters.

I can confirm my cef_log.txt file is flooded with that line whenever I launch BPM.

**Comment by aleguizzo** [comment]
Same issue on:
OS: Arch Linux x86_64
Kernel: 6.12.4-arch1-1
Resolution: 1920x1080
DE: Plasma 6.2.4 on Wayland
WM: kwin
CPU: AMD Ryzen 7 5700G with Radeon Graphics (16) @ 4.673GHz
GPU: AMD ATI Radeon RX 7800 XT

**Comment by Bloodninj** [comment]
I checked in the previously-mentioned cef_log.txt in the logs folder, when I boot up Big Picture mode without going directly from fresh start with `-bigpicture`, the log is flooded with errors:

<details>
<summary>Log errors</summary>

```
[1219/111620.125907:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4111, .bad_value = 33554457, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.126432:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4113, .bad_value = 33554461, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.126717:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4115, .bad_value = 33554465, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.127263:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4117, .bad_value = 33554469, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.127529:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4119, .bad_value = 33554473, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.128470:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4123, .bad_value = 33554477, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.128623:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4125, .bad_value = 33554481, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.128782:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4127, .bad_value = 33554485, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.128934:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4129, .bad_value = 33554489, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.129088:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4131, .bad_value = 33554493, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.129120:WARNING:connection.cc(56)] X error received.  Request: SendEventRequest, Error: WindowError{.sequence = 4133, .bad_value = 33554497, .minor_opcode = 0, .major_opcode = 25}
[1219/111620.184957:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4162, .bad_value = 33554463, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.184999:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4163, .bad_value = 33554459, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185009:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4164, .bad_value = 33554471, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185016:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4165, .bad_value = 33554467, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185023:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4166, .bad_value = 33554475, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185029:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4167, .bad_value = 33554479, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185041:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4168, .bad_value = 33554483, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185049:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4169, .bad_value = 33554487, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185055:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4170, .bad_value = 33554491, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185061:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4171, .bad_value = 33554495, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.185067:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4172, .bad_value = 33554499, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.225823:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglSwapBuffers: Failed to retrieve the size of the parent window.
[1219/111620.226894:ERROR:gpu_service_impl.cc(1125)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[1219/111620.228501:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4196, .bad_value = 33554463, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228522:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4197, .bad_value = 33554459, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228531:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4198, .bad_value = 33554471, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228538:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4199, .bad_value = 33554467, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228554:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4200, .bad_value = 33554475, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228564:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4201, .bad_value = 33554479, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228637:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4202, .bad_value = 33554483, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.228655:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4203, .bad_value = 33554487, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.247116:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247143:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247267:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4204, .bad_value = 33554491, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.247401:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4205, .bad_value = 33554495, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.247438:WARNING:connection.cc(56)] X error received.  Request: ChangeWindowAttributesRequest, Error: WindowError{.sequence = 4206, .bad_value = 33554499, .minor_opcode = 0, .major_opcode = 2}
[1219/111620.247628:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247636:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247652:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247656:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247670:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247675:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247688:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247693:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247707:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247711:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247725:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247729:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247742:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247746:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247761:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247766:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.247782:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.247785:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.253150:ERROR:gpu_process_host.cc(1002)] GPU process exited unexpectedly: exit_code=8704
[1219/111620.253173:WARNING:gpu_process_host.cc(1436)] The GPU process has crashed 1 time(s)
```
</details>

After those I get a lot of errors relating to things being null, presumably as a result of the above errors:
```
[1219/111620.258053:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.258068:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
[1219/111620.258312:ERROR:shared_image_interface_proxy.cc(130)] Buffer handle is null. Not creating a mailbox from it.
[1219/111620.258318:ERROR:one_copy_raster_buffer_provider.cc(348)] Creation of StagingBuffer's SharedImage failed.
...
```
I get the impression this is what's causing the slowdown, rather than just writing to the log itself, though what is causing these errors is beyond me.

**Comment by Abrifq** [comment]
> I'll try to waste my time finding the issue (lmao) and maybe find a fix too

Welp, I don't have enough storage on my PC and the Codespaces I ran also ran out of space.
The best educated guess i can make is after closing pop-up windows, they don't get cleared out properly, causing the errors to pop up.

Which also might be the reason why it doesn't lag when you launch it with "Start in Big Picture Mode" enabled.

**Comment by nokia8801** [comment]
This is also happening to me on Intel Arc A750. So it is not an NVIDIA, AMD or Intel issue imo. Big Picture Mode is incredibly slow and laggy.

**OS:** Arch Linux
**Kernel:** Linux 6.12.7-arch1-1
**Resolution:** 2560x1400
**DE/WM:** GNOME 47.2 on Wayland (Mutter)
**GPU:** Intel Arc A750
**Mesa:** 24.3.2-1 (Using Xe driver instead of i915)

**Comment by SHiLLySiT** [comment]
Also reporting this occurs for me too.

Things I've tried:
- Running in Window mode at least makes it usable, but not ideal on a big screen.
- [Launching steam in big picture mode](https://github.com/ValveSoftware/steam-for-linux/issues/11255#issuecomment-2356271049) does nothing.
- I had originally installed the the `.deb` since that's what [the Steam website directs you to do](https://store.steampowered.com/about/) but I found that [the Steam flatpak](https://flathub.org/apps/com.valvesoftware.Steam) had better performance. Still doesn't fix performance issue in big picture mode.
- I had tried [enabling the "Enable GPU accelerated rendering in web views"](https://github.com/ValveSoftware/steam-for-linux/issues/11261) which had a mild improvement in big picture mode, but a noticeable performance impact to desktop mode.

System details:
* Steam client version (build number or date): 1733265492
* Distribution (e.g. Ubuntu): Ubuntu 24.04.1 LTS
* GPU: Nvidia RTX 2080
* CPU: Intel  i7-8700 
* RAM: 32 GB
* Kernel: Linux 6.8.0-51-generic

**Comment by ZeroKun265** [comment]
Same issue here on Fedora 41
Steam Beta Branch:  Stable Client
Steam Version:  1733265492
Steam Client Build Date:  Mon, Dec 2 10:26 PM UTC -08:00
Steam Web Build Date:  Mon, Dec 2 10:20 PM UTC -08:00
Steam API Version:  SteamClient021

Launching steam from the desktop icon or from the cmd with "steam", then opening big picture, causes this issue
I have an entry for "Big Picture - Steam" (don't know if it's default for everyone) and when launching that or using the cmd "stea, -bigpicture" the performance is great

I have all hardware acceleration options enabled, and i even tried enabling "disable GPU blocklist" to no avail

Hardware:
CPU: i5-1235U
GPU: Intel Iris Xe Graphics
RAM: 16GB
Kernel: 6.12.4-200.fc41.x86_64

**Comment by JustCryen** [comment]
I have a similar conclusion.

I have a 21:9 display which has a resolution of 3440 x 1440 and Big Picture is unusable.
(It was fine for a while, but that was a long time ago)  

When I launch Steam straight to Big Picture via the terminal, the performance is fine until I exit and re-enter Big Picture. Then it's horrible again.

Few days ago I launched a game through the Steam Link app and I had the main monitor disabled, with the PC displaying to a dummy HDMI plug in 1080p, 16:9.

I was shocked that the Big Picture mode launched not only quickly, but also was buttery smooth.

Well, the main menu still wasn't appearing (the one that allows you to exit big picture, shut down the controller, shut down the system or go to settings) but it was still way better than my previous experience.

**Comment by schM0ggi** [comment]
> Still have this issue with similar side effects as others:
> 
> ```
> Steam Beta Branch:  Steam Beta Update
> Steam Version:  1732746274
> Steam Client Build Date:  Wed, Nov 27 11:06 PM UTC -08:00
> Steam Web Build Date:  Wed, Nov 27 10:54 PM UTC -08:00
> Steam API Version:  SteamClient021
> 
> GPU: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.59, 6.12.1-zen1-1-zen)
> Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1
> CPU: Ryzen 5 5600
> Monitor: 1920x1080@60
> (Valve Index attached but not used)
> ```
> 
> The big picture mode client is "laggy" when in full screen and only when started by Steam itself. Starting `steam -bigpicture` resolves it temporarily, setting it to windowed resolves it temporarily. Current beta and stable branch did not change anything.

Just wanted to point out, if not already known, that the lag is still absent when starting Steam with the "- bigpicture" argument, exiting Big Picture mode and returning to Big Picture mode via the icon in the top right corner.

So, in summary, whatever the argument "- bigpicture" does differently on Steam's startup than launching Steam without the argument is a key factor.

**Comment by ChronicledMonocle** [comment]
I can report the same behavior.  If I close steam and then relaunch with "/usr/games/steam steam://open/bigpicture", it's fine.  I'm assuming this is the same as the -bigpicture launch argument, essentially.

**Comment by TheOneAndOnlyFox** [comment]
Same bug in POP!_OS with steam deb-package

OS: Pop!_OS 22.04 LTS
KERNEL: 6.9.3-76060903-genericCPU: Intel Core i7-9700KF @ 3.60GHzGPU: 
NVIDIA GeForce RTX 4060 Ti
GPU DRIVER: NVIDIA 565.77
RAM: 32 GB

**Comment by schM0ggi** [comment]
The lag completely disappeared for me since the newest Steam update from today.

Thank you!

**Comment by Zamundaaa** [comment]
Can confirm, also on AMD

**Comment by nokia8801** [comment]
I can also confirm the issue is fixed with Intel Arc A750

**OS:** Arch Linux
**Kernel:** Linux 6.12.10-arch1-1
**GPU:** Intel Arc A750 (Xe driver instead of i915)
**Mesa:** Mesa 24.3.3-arch1.2
**DE/WM:** GNOME 47.3 on Wayland
**Steam Version:**  1737404083

Tested with both Steam (Runtime) and Steam (Native). Exited and re-entered Big Picture Mode multiple times to be sure. Works fine so far.

**Comment by ZeroKun265** [comment]
Can confirm, after updating to the latest verions it works fine on Fedora 41

Hardware:
CPU: i5-1235U
GPU: Intel Iris Xe Graphics
RAM: 16GB
Kernel: 6.12.4-200.fc41.x86_64

**Comment by misterright1** [comment]
I'm not sure but it might be a bit more stable.
I still have slowdowns and hangs.
RTX 3090
AMD R9 3900X
16GB DDR4
All on NVME SSD'S.

**Comment by Toadlover404Git** [comment]
Can also confirm, it's fixed on Arch with KDE Plasma.

CPU: i9-9900K
RAM: 32GB DDR4-3000 (clocked at 3200)
GPU: RX 7900 XTX
Kernel: 6.12.10-zen1-1-zen

**Comment by vitorboschi** [comment]
It seems better here too, as it's now usable. That said, it's not yet as smooth as I'd expect it to be in this system. I tried to get more info by enabling Nvidia's "Graphics API Visual Indicator" and found it to behave a bit weird, as if there were two+ overlapping GL contexts, as seen in the screenshot below. That indicator looks fine/crispy on other openGL applications.

![Image](https://github.com/user-attachments/assets/438d297c-0f4a-4964-931a-26b9f10c46ea)

I'm not sure that is related to this performance problem at all, but I thought it was worth reporting.

CPU: AMD Ryzen 9 5900X
GPU: NVIDIA RTX 3090 - driver 550.120 (Open)
Kernel: 6.8.0-51

**Comment by ZeroKun265** [comment]
@vitorboschi (and anyone that still feels like the UI lags a bit) do you feel a difference when starting it in regular mode and switching to big picture VS starting in Big picture (maybe using --bigpicture argument)

I'm on an Intel iGPU and yet I don't notice any difference, so yes it might be a separate issue, maybe to do with Nvidia

**Comment by dahenry** [comment]
I confirm it works nice on AMD:

CPU: AMD Ryzen 7 7840U
GPU: AMD Radeon 780M
Arch with kernel 6.12.10
Mesa 24.3.3
Wayland

However, it still lags as hell on NVIDIA:

CPU: Core i7 6700K
GPU: NVIDIA GTX 980M
Ubuntu 24.04.1 with kernel 6.8.0-51
NVIDIA driver 550.120
Xorg

CPU: Core i7 4790
GPU: NVIDIA RTX 4070
Ubuntu 24.10 with kernel 6.11.0-13
NVIDIA driver 565.57.01 (beta)
Both Xorg and Wayland

**Comment by perroboc** [comment]
Can confirm this seems fixed too on Fedora 41 + flatpak steam, with AMD GPU

**Comment by ZeroKun265** [comment]
@dahenry i think this confirms that this issue is different and relative to Nvidia, while the starting with --bigpicture or not is now fixed

**Comment by TheAndroidx1** [comment]
OS: Arch Linux
Kernel: Linux 6.12.10-arch1-1 (64-bit)
GPU: RTX 3080
DE/WM: KDE Plasma 6.2.4 (Wayland)
Steam Version: 1737404083

Hardware acceleration works now and framerate is stable, however the steam menu remains corrupted, all other menus render normally including the QAM

**Comment by urbenlegend** [comment]
Can confirm that hardware acceleration seems to be consistently enabled now on my Nvidia 3090. Still seeing the occaisional menu corruption issues like @TheAndroidx1, but its progress!!

Operating System: Arch Linux 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.1
Kernel Version: 6.12.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 9800X3D 8-Core Processor
Memory: 60.4 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090/PCIe/SSE2 w/ 565.77
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X870E AORUS ELITE WIFI7

**Comment by Joseph-DiGiovanni** [comment]
Fixed and working great on my AMD 7900XT on NixOS / GNOME / Wayland.

Thanks to everyone for the reports.

**Comment by dahenry** [comment]
No, it's still very laggy on RTX 4070 @ Ubuntu 24.10.

**Comment by perroboc** [comment]
> No, it's still very laggy on RTX 4070 @ Ubuntu 24.10.

Are you using the Steam beta release?

**Comment by dahenry** [comment]
> > No, it's still very laggy on RTX 4070 @ Ubuntu 24.10.
> 
> Are you using the Steam beta release?

Yes, steam client beta (february 6th).

**Comment by Abrifq** [comment]
> > > No, it's still very laggy on RTX 4070 @ Ubuntu 24.10.
> > 
> > 
> > Are you using the Steam beta release?
> 
> Yes, steam client beta (february 6th).

 just downloaded the beta but it's still not lagging on my machine. 
can you check if you have a package that cant be updated?

**Comment by dahenry** [comment]
> > > > No, it's still very laggy on RTX 4070 @ Ubuntu 24.10.
> > > 
> > > 
> > > Are you using the Steam beta release?
> > 
> > 
> > Yes, steam client beta (february 6th).
> 
> just downloaded the beta but it's still not lagging on my machine. can you check if you have a package that cant be updated?

Well, I tested after a fresh system update + reboot. I'm using NVIDIA drivers 565 (beta), as this is the latest version provided and recommended by ubuntu.

**Comment by perroboc** [comment]
> > Replying to [#11255 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/11255#issuecomment-2657671487)
> 
> Well, I tested after a fresh system update + reboot. I'm using NVIDIA drivers 565 (beta), as this is the latest version provided and recommended by ubuntu.

Just a hunch, but if you’re not using the flatpak version, can you test it, please?

**Comment by pfych** [comment]
I'm still having issues on my AMD 5700xt on wayland when going from standard steam to big picture mode. The UI lag in big picture mode is unbearable.

**Steam Beta Branch:** Steam Beta Update
**Steam Version:** 1732590255
**OS:** EndeavourOS
**Kernel:** 6.13.2-arch1-1
**CPU:** AMD Ryzen 7 5800X3D
**GPU:** AMD Radeon RX 5700 XT
**Driver Version:** 4.6 Mesa 24.3.4-arch1.1

I've also noticed that when opening & then exiting big picture, it seems like scaling is incorrect as well.

| Before launching big picture | after launching big picture & exiting |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/11119eaf-2ecb-41ee-a6be-0a35149f60ac) | ![Image](https://github.com/user-attachments/assets/d951bab8-9ff1-410c-9048-a67b012f06ef) |

**Comment by perroboc** [comment]
> I'm still having issues on my AMD 5700xt on wayland when going from standard steam to big picture mode. The UI lag in big picture mode is unbearable. I've installed steam through pacman & I'm not using Flatpak or AppImages.
> 
> **Steam Beta Branch:** Steam Beta Update **Steam Version:** 1732590255 **OS:** EndeavourOS **Kernel:** 6.13.2-arch1-1 **CPU:** AMD Ryzen 7 5800X3D **GPU:** AMD Radeon RX 5700 XT **Driver Version:** 4.6 Mesa 24.3.4-arch1.1
> 
> I've also noticed that when opening & then exiting big picture, it seems like scaling is incorrect as well.
> 
> Before launching big picture	after launching big picture & exiting
> ![Image](https://github.com/user-attachments/assets/11119eaf-2ecb-41ee-a6be-0a35149f60ac)	![Image](https://private-user-images.githubusercontent.com/11114594/413471863-d951bab8-9ff1-410c-9048-a67b012f06ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1NzQyMzcsIm5iZiI6MTczOTU3MzkzNywicGF0aCI6Ii8xMTExNDU5NC80MTM0NzE4NjMtZDk1MWJhYjgtOWZmMS00MTBjLTkwNDgtYTY3YjAxMmYwNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDIyNTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MTkwNzUyNDRjNzQ2YTYwNDJkYTBmOGI5ZDUyZWFmYjdmODdiYjI2N2MwNTFlNzk4MGExNWFiYjNjNWY2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hFaifAO1hq1yWXsB4nuCbaLakMejPi9ePZI7W7FXpNE)

Please update to the latest Steam beta: 1739497777 and try again

**Comment by BEEFY-JOE** [comment]
Hi, I was also experiencing lag in big picture mode, Arch Linux distribution repo release version, not flatpak.
System Info:
```
OS: Arch Linux x86_64
Host: ASUS TUF Gaming A16 FA617NT_FA617NT (1.0)
Kernel: Linux 6.13.2-arch1-1.1-g14
DE: KDE Plasma 6.3.0
WM: KWin (Wayland)
CPU: AMD Ryzen 7 7735HS (16) @ 4.83 GHz
GPU 1: AMD Radeon RX 7700S [Discrete]
GPU 2: AMD Radeon 680M [Integrated]
Memory: 9.26 GiB / 30.59 GiB (30%)
```
Updated to the latest Steam beta as last comment suggested
```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1739497777
Steam Client Build Date:  Thu, Feb 13 11:29 AM UTC -08:00
Steam Web Build Date:  Thu, Feb 13 4:41 PM UTC -08:00
Steam API Version:  SteamClient021
```
Big Picture Mode was still lagging. 

However! I copied the steam.desktop file from `/usr/share/applications/` to `/home/user/.local/share/applications/` and changed line 37 `PrefersNonDefaultGPU=true` to `PrefersNonDefaultGPU=false`

Now big picture mode does not lag. 

I believe that I had tried the same .desktop file modifiation and it did not fix the issue there. I will have to roll back and see if it works.

**Comment by pfych** [comment]
> Please update to the latest Steam beta: 1739497777 and try again

I've just learned that my steam hasn't been properly updating with the following error when an update is attempted:

```
failed to rename package/tmp/./compatibilitytools.d/LegacyRuntime/compatibilitytool.vdf_ -> ./compatibilitytools.d/LegacyRuntime/compatibilitytool.vdf
BCommitUpdatedFiles: failed to process ./compatibilitytools.d/LegacyRuntime
``

This was due to my `~/.local/share/Steam/compatibilitytools.d/` folder being a symlink to a folder on a larger drive. Once I converted this to a normal folder - an update applied on restart & this lag issue is gone.

I only realized this since I launched steam via my terminal since I had a hankering that my updates weren't applying - It'd be nice if these errors popped as a warning if an update fails to apply since right now it just endlessly says "A Steam Client update is available" when you manually check for updates.

**Comment by ClassicOldSong** [comment]
Quite the opposite, on my GPD Win Max i5-1035-G7 running Bazzite, Big Picture Mode runs smoothly without Gamescope, but in GS it's only 10fps, and CPU usage is noticably high, like it's only using CPU rendering.

**Comment by kisak-valve** [comment]
Closing because the issue in the opening post appears to have been resolved. If you're seeing a follow up or similar issue, that should be tracked separately.

**Comment by awsms** [comment]
Was it resolved? I'm still having the laggy big picture UI (basically unusable, way more considerable than in OP's video), and when exiting Big Picture, the whole Steam client has a 2* scale UI, just like in https://github.com/ValveSoftware/steam-for-linux/issues/11255#issuecomment-2660317608
For the reference, I'm using an NVIDIA RTX4070 + 570.144 drivers, on Steam beta

**Comment by tnbp** [comment]
> Was it resolved?

It should be. If you're using an NVIDIA GPU, make sure both "Enable GPU accelerated..." and "Disable GPU blocklist" are enabled. The latter is only available in Big Picture Mode, under the "Display" tab.

**Comment by awsms** [comment]
> > Was it resolved?
> 
> It should be. If you're using an NVIDIA GPU, make sure both "Enable GPU accelerated..." and "Disable GPU blocklist" are enabled. The latter is only available in Big Picture Mode, under the "Display" tab.

Unfortunately... enabling GPU acceleration for me still results in Steam becoming a black window (https://github.com/ValveSoftware/steam-for-linux/issues/11488), and this includes the big picture mode. Which is now, one big black picture in fullscreen. 😄 
I will have to wait for #11488 to be fixed first, before sending any more feedback regarding the Big Picture mode. Thank you for the help.

**Comment by ghost** [comment]
its seems like this issue popped up again, its laggy for me too.

**Comment by ghost** [comment]
Disable GPU Blocklist | Enabled -> Lag
Disable GPU Blocklist | Disabled -> Glitches

**Comment by Deedeezhehe** [comment]
Happens for me even with blocklist enabled. Not having lag issues with that tho, so idk if it's working. Running arch in a wayland compositor with an Nvidia gpu

Edit: Seemingly only the menu pop-up though.

**Comment by jgtvares** [comment]
Still laggy for me too...

I have both **GPU acceleration** and **Disable GPU blocklist** enabled.

Starting Steam from the terminal with the `-bigpicture` flag reduces a lot of the lag, but it's not 100% smooth.

Still no definitive solution here, guys?

Also, I noticed that the lag is even worse in a dual/multiple monitor setup. In my case, I use a laptop. If I keep only one screen on and start Steam in Big Picture from the terminal, it gets butter smooth. But that's still far from ideal.

EDIT: I realized that disabling fractional scaling and using a single display makes it butter smooth. With fractional scaling disabled, I don't need to start Steam from the terminal.

**Steam Beta Branch**: Steam Beta Update
**Steam Version**: 1754001374
**OS**: Ubuntu 24.04 LTS
**Kernel**: 6.14.0-27-generic
**CPU**: Intel Ultra 7 165H 1.40GHz
**GPU**: Nvidia RTX 4060 Laptop
**Driver** **Version**: 550.163.01

**Comment by Deedeezhehe** [comment]
I used to have this issue, with both hyprland and river, but after switching to Niri it hasn't been an issue. With this context, my guess is it may be an issue with either specific compositors (i.e, hyprland, sway, gnome) or specific Wayland protocol libraries (i.e, wlroots, smithay)

**Comment by Techbane** [comment]
Same issue here, exclusively on my main desktop of course. Mint 21.3 Cinnamon, GTX 1660 Ti, Ryzen 7 2700, everything up to date. This has been a constant for me ever since Big Picture was introduced years ago. BPM interface spikes CPU usage like crazy and runs like laggy trash, so much so that it occasionally drags the entire system to an unrecoverable full halt. GPU acceleration on, GPU blocklist disabled, tested with regular and beta branches. Have not tested with Gamescope because I haven't been able to get that installed. Launching steam directly with -bigpicture improves framerate _slightly,_ running BPM in windowed mode improves framerate _slightly,_ but something is still evidently amiss.

Secondary machine 1: a near decade-old Intel HD APU mini-PC still running Windows 10. Runs BPM buttery smooth.

Secondary machine 2: slightly newer AMD APU mini-PC with Linux Mint 22.2 Xfce. Runs BPM buttery smooth.

**Comment by atassis** [comment]
I think I have resolved this issue. But first I want to mention next thing- big picture, looks like, is just a steamwebhelper process, which is a chrome webview. When you start steam BP- default behaviour for webviews is to ignore gpu acceleration process wise (in process output I have seen next line)
```bash
exec ./steamwebhelper -nocrashdialog -lang=en_US -cachedir=/home/atassis/.local/share/Steam/config/htmlcache -steampid=24572 -buildid=1766451605 -steamid=0 -logdir=/home/atassis/.local/share/Steam/logs -uimode=4 -startcount=0 -steamuniverse=Public -realm=Global -clientui=/home/atassis/.local/share/Steam/clientui -steampath=/home/atassis/.local/share/Steam/ubuntu12_32/steam -launcher=0 -use_xcomposite_workaround --valve-initial-threadpool-size=8 --valve-enable-site-isolation --enable-smooth-scrolling --disable-gpu-compositing --disable-gpu --no-sandbox --password-store=basic --ignore-gpu-blocklist --log-file=/home/atassis/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --disable-component-update --gaia-url=http://disabled.invalid --disable-features=WinRetrieveSuggestionsOnlyOnDemand,SpareRendererForSitePerProcess,DcheckIsFatal,BlockPromptsIfIgnoredOften,ValveFFmpegAllowLowDelayHEVC
```
Here we can see that `--disable-gpu` flag is passed, which might override any other options you have toggled in BP settings.


_So below is the setting, that got it fixed:_
**Navigate to Settings > Interface and ensure "Enable GPU accelerated rendering in web views" is ON.**


CONTEXT: Disable GPU Blocklist doesn't change anything in my case, with both options BP is working well
With this option ON in my installation I see no `--disable-gpu` flag as well as some others related. Both standard on BP steam are working smoother now.

Operating System: CachyOS Linux 
KDE Plasma Version: 6.5.4
KDE Frameworks Version: 6.21.0
Qt Version: 6.10.1
Kernel Version: 6.18.2-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 32 GiB of RAM (31,2 GiB usable)
Graphics Processor: NVIDIA GeForce RTX 3080 Ti


Please, let me know if this has fixed an issue for you, I had troubles with this for a long time, too, pretty annoying

**Comment by Noxfield** [comment]
Thanks atassis, that worked for me.

I previously tried the rest like enabling "Enable GPU accelerated..." and "Disable GPU blocklist" , but that didn't seem to affect it.

Computer Information:
CPU Brand: AMD Ryzen 7 1700 Eight-Core Processor
Pop!_OS 24.04 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.17.9-76061709-generic
Steam Runtime Version: steam-runtime_1.0.20251202.187498
Browser GPU Acceleration Status: Enabled
Driver: NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 580.82.09
RAM: 64245 Mb

**Comment by lonkalsim** [comment]
I fixed it just by turning GPU Acceleration Off and then back On. Crazy this still hasn't been fixed...

**Comment by Techbane** [comment]
I have now updated my main desktop to Mint 22.3 Cinnamon with a fresh install. Tried toggling the other options off and on again to no avail, have tried this before but tried it again anyway:

> **Navigate to Settings > Interface and ensure "Enable GPU accelerated rendering in web views" is ON.**

No effect. BPM still runs like laggy trash.

**Comment by atassis** [comment]
@Techbane have you checked the flag existence on steam web helper process? And have you completely restarted the process after enabling the flag?

**Comment by Techbane** [comment]
> [@Techbane](https://github.com/Techbane) have you checked the flag existence on steam web helper process? And have you completely restarted the process after enabling the flag?

Have to admit I have no idea how to check that. That code block you pasted above is an output as opposed to input, right? But I have restarted Steam in full more than once after toggling the mentioned setting, yes.

Moreover, having "GPU accelerated rendering in web views" enabled actually tanks the performance while browsing the storefront outside of BPM. Trailer videos won't even play at full framerate. I have to turn this back off.

**Comment by atassis** [comment]
My code block is just a part or terminal output os process list commands, like next
```shell
ps aux | grep steamwebhelper
```
You can try to run it while different steam windows are opened, to check how each of them runs. You can try to check when flag is passed, and when it is not, to find any difference. 
Related to the performance, I still have a suggestion that these are rendered via chromium, so if any chromium based browsers do well on your machine- so the steam might. We just have to make it pass proper config for rendering.
Also, I see you use mint 21.3 cinnamon, it might default to X, I was testing on wayland, it can make a difference, too

**Comment by Techbane** [comment]
> Also, I see you use mint 21.3 cinnamon, it might default to X, I was testing on wayland, it can make a difference, too

Mint still uses X11, yeah. There's an experimental Wayland mode but it's still _very_ experimental, like "flip a coin as to whether the entire desktop environment crashes and fails to relaunch anytime a program is run" experimental.

I set aside a little time to kick the wheels on it, and turns out that on my main desktop, if using Wayland, enabling "GPU accelerated rendering in web views" DOES fix Big Picture's performance. Sadly it doesn't fix Wayland being basically unusable on Mint, and actually exacerbates performance issues on X11. So that might be a Wayland-exclusive fix.

Meanwhile for some reason my mini-PC running a roughly equivalent Mint installation on far lesser hardware, also using X11, remains without performance issues.

**Comment by Ketoro** [comment]
still a problem on my Framework 16 (amd graphics) running fedora, also it seems like other people in here also still have this issue or need a workaround to fix it, so why is this closed?

**Comment by Netwell09** [comment]
I still have this issue in Cachyos.
