### ISSUE TITLE
Steamwebhelper is not responding: ./libcef.so: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by jpkhawam** [ValveSoftware/steam-for-linux#11312]
#### Your system information

* Steam client version: Latest beta (October 3rd, the 455mb one with the in game recording changes. I can't access the GUI to get you the build number)
* Distribution: Fedora 40
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [logs.zip](https://github.com/user-attachments/files/17242448/logs.zip)
* GPU: NVIDIA GeForce RTX 3060 Laptop GPU
* CPU: 11th Gen Intel Core™ i7-11800H × 16
* Kernel: Linux 6.10.11-200.fc40.x86_64
* Steam installed as a [flatpak](https://flathub.org/apps/com.valvesoftware.Steam)

#### Please describe your issue in as much detail as possible:
I just updated to the latest beta, and after restarting to apply, the steamwebhelper keeps giving me a not responding message on launch
![Screenshot from 2024-10-03 12-53-26](https://github.com/user-attachments/assets/4a276bbb-55f4-40ed-8b6c-dbb84b4066ab)
I have tried:
1. Restarting my laptop
2. Restarting Steam
3. Restarting Steam with GPU acceleration disabled
4. Restarting Steam with Browser Sandboxing disabled
5. Restarting steamwebhelper
6. Switching to X11
7. Switching to Wayland
8. Turning off my monitor to use my laptop's display only
9. Turning off wifi to boot into offline mode

None of the above worked. I am on the latest NVIDIA drivers.

**Comment by smcv** [comment]
The characteristic log line in `webhelper-linux.txt` here and on recent comments on https://github.com/flathub/com.valvesoftware.Steam/issues/1347 seems to be:

```
./steamwebhelper: error while loading shared libraries: ./libcef.so: cannot allocate memory in static TLS block
```

@kisak-valve, please could you retitle this to something like "Steamwebhelper is not responding: ./libcef.so: cannot allocate memory in static TLS block" to distinguish this from other steamwebhelper fatal errors?

I think this should probably also be labelled "Flathub-provided steam package" instead of, or as well as, "Distro Family: Fedora". For Flatpak users, for anything except kernel issues, "it's the Flatpak app" is more likely to be a key factor than any specific host distro.

**Comment by smcv** [comment]
> I can't access the GUI to get you the build number

`console-linux.txt` says it's build 1727910361 (2024-10-02T23:06:01Z).

**Comment by smcv** [comment]
> Latest beta (October 3rd)

Looking at [its release notes](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4659626709189608599) this is probably triggered by the updated version of CEF (Chromium) in the steamwebhelper.

**Comment by smcv** [comment]
Discussion on https://github.com/flathub/com.valvesoftware.Steam/issues/1347 suggests that

> Steam most likely needs to backport https://github.com/chromiumembedded/cef/commit/be4085981cf2035576dee64813ace9d6b1930305 or update to a fixed libcef build

which seems plausible (thanks @bbhtt).

**Comment by tytan652** [comment]
If `sentencepiece` static TLS is not patch is the CEF 126 build of Steam, this issue will only affect the Flatpak.

**Comment by smcv** [comment]
My understanding is that the workaround for this is to downgrade from beta to stable (which of course you can't easily do from the GUI, because it isn't starting).

It seems that, so far, this issue mostly affects users of the unofficial Flatpak app provided by Flathub. For that app, running `flatpak run com.valvesoftware.Steam -clearbeta` or deleting the file `~/.var/app/com.valvesoftware.Steam/.steam/root/package/beta` might help.

If this also affects users of the ordinary non-sandboxed Steam client as @tytan652 suggests, then the equivalent is to run `steam -clearbeta` or delete the file `~/.steam/root/package/beta`.

For completeness, the equivalent for users of the unofficial Snap app provided by Canonical is `snap run steam -clearbeta` or deleting `~/snap/steam/common/.steam/root/package/beta`.

**Comment by bbhtt** [comment]
This is fixed in the latest beta version. 1729208001

**Comment by E-D-W-I-N** [comment]
Yep, latest beta 1729208001 fixed this problem for me
Arch Linux, Flatpak Steam

**Comment by kevenwyld** [comment]
I'm not using the flatpak, just the steam package from the arch repos, and I'm still having this problem.  Logs are below.  According to that output I'm running build version `1729208001`

<details><summary>Click to expand logs</summary>

```
steam.sh[3096540]: Running Steam on arch rolling 64-bit
steam.sh[3096540]: STEAM_RUNTIME is enabled automatically
setup.sh[3096587]: Steam runtime environment up-to-date!
steam.sh[3096540]: Steam client's requirements are satisfied
CProcessEnvironmentManager is ready, 5 preallocated environment variables.
[2024-10-25 16:15:20] Startup - updater built Oct 17 2024 23:14:07
[2024-10-25 16:15:20] Startup - Steam Client launched with: '/home/<username>/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened'
[2024-10-25 16:15:20] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
10/25 16:15:20 minidumps folder is set to /tmp/dumps
10/25 16:15:20 Init: Installing breakpad exception handler for appid(steam)/version(1729208001)/tid(3096644)
[2024-10-25 16:15:20] Loading cached metrics from disk (/home/<username>/.local/share/Steam/package/steam_client_metrics.bin)
[2024-10-25 16:15:20] Using the following download hosts for Public, Realm steamglobal
[2024-10-25 16:15:20] 1. https://client-update.fastly.steamstatic.com, /, Realm 'steamglobal', weight was 900, source = 'update_hosts_cached.vdf'
[2024-10-25 16:15:20] 2. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2024-10-25 16:15:20] 3. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-10-25 16:15:20] 4. https://client-update.steamstatic.com, /, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-10-25 16:15:20] Verifying installation...
[2024-10-25 16:15:20] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/<username>/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xdb4cddc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xdb4cc500
steamwebhelper.sh[3096759]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3096759]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3096759]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3096759]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 3096852
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=0 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=0 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
steamwebhelper.sh[3097253]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3097253]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3097253]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3097253]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=0 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=1 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
steamwebhelper.sh[3097588]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3097588]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3097588]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3097588]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=0 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=2 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
src/steamUI/steamuisharedjscontroller.cpp (666) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (666) : Failed creating offscreen shared JS context
10/25 16:15:45 Init: Installing breakpad exception handler for appid(steam)/version(1729208001)/tid(3096644)
assert_20241025161545_29.dmp[3097803]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241025161545_29.dmp
src/common/linux_setenvwrapper.h (74) : Assertion Failed: ERROR: unsafe call to setenv count:1 var:'STEAMVIDEOTOKEN'

src/common/linux_setenvwrapper.h (74) : Assertion Failed: ERROR: unsafe call to setenv count:1 var:'STEAMVIDEOTOKEN'

assert_20241025161546_33.dmp[3097861]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241025161546_33.dmp
ERROR: unsafe call to setenv count:1 var:'STEAMVIDEOTOKEN'
/usr/share/themes/Adwaita-dark/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Adwaita-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
assert_20241025161545_29.dmp[3097803]: Finished uploading minidump (out-of-process): success = yes
assert_20241025161545_29.dmp[3097803]: response: CrashID=bp-cccf3c5f-448b-4f31-b562-a09292241025
assert_20241025161545_29.dmp[3097803]: file ''/tmp/dumps/assert_20241025161545_29.dmp'', upload yes: ''CrashID=bp-cccf3c5f-448b-4f31-b562-a09292241025''
assert_20241025161546_33.dmp[3097861]: Finished uploading minidump (out-of-process): success = yes
assert_20241025161546_33.dmp[3097861]: response: CrashID=bp-786de4fd-a1c5-47a9-8a9a-8ee482241025
assert_20241025161546_33.dmp[3097861]: file ''/tmp/dumps/assert_20241025161546_33.dmp'', upload yes: ''CrashID=bp-786de4fd-a1c5-47a9-8a9a-8ee482241025''
BRefreshApplicationsInLibrary 1: 63ms
Desktop state changed: desktop: { pos:    0,   0 size:    0,   0 } primary: { pos:    0,   0 size:    0,   0 }
Caching cursor image for , size 24x24, serial 2, cache size = 0
Proton: Upgrading prefix from GE-Proton9-4 to 8.0-104 (/home/<username>/.local/share/Steam/steamapps/compatdata/0/)
Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
steamwebhelper.sh[3098178]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3098178]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3098178]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3098178]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=76561197978739905 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=3 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioconvert.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioconvert.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstadder.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstadder.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioresample.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioresample.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioparsers.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstaudioparsers.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstautodetect.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstautodetect.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.805: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstavi.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstavi.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstapp.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstapp.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstid3demux.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstid3demux.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstnavigationtest.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstnavigationtest.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstsoup.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstsoup.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstogg.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstogg.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdebug.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdebug.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstlibav.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstlibav.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstmpg123.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstmpg123.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgsttheora.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgsttheora.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdeinterlace.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdeinterlace.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstopus.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstopus.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstcoreelements.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstcoreelements.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstopengl.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstopengl.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideofilter.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideofilter.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvorbis.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvorbis.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvpx.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvpx.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstcoretracers.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstcoretracers.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstmatroska.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstmatroska.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstpbtypes.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstpbtypes.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgsttypefindfunctions.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgsttypefindfunctions.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstximagesink.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstximagesink.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstisomp4.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstisomp4.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstplayback.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstplayback.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideobox.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideobox.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstwavparse.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstwavparse.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideoconvertscale.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstvideoconvertscale.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdav1d.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libgstdav1d.so: wrong ELF class: ELFCLASS64

(wine:3098289): GStreamer-WARNING **: 16:15:56.806: Failed to load plugin '/home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libprotonmediaconverter.so': /home/<username>/.local/share/Steam/compatibilitytools.d/Proton-Experimental-modded/files/lib64/gstreamer-1.0/libprotonmediaconverter.so: wrong ELF class: ELFCLASS64
wine: configuration in L"/home/<username>/.local/share/Steam/steamapps/compatdata/0/pfx" has been updated.
Initializing D3D11.
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Fossilize INFO: Overriding serialization path: "/home/<username>/.local/share/Steam/shader_cache_temp_dir_d3d11_64/fozpipelinesv6/steamapprun_pipeline_cache".
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
steamwebhelper.sh[3098750]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3098750]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3098750]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3098750]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
Initializing D3D12.
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Fossilize INFO: Overriding serialization path: "/home/<username>/.local/share/Steam/shader_cache_temp_dir_d3d12_64/fozpipelinesv6/steamapprun_pipeline_cache".
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=76561197978739905 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=4 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
Proton: Upgrading prefix from 8.0-104 to GE-Proton9-4 (/home/<username>/.local/share/Steam/steamapps/compatdata/0/)
Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.
fsync: up and running.
src/steamUI/steamuisharedjscontroller.cpp (666) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (666) : Failed creating offscreen shared JS context
reaping pid: 3097588 -- unknown
src/steamexe/main.cpp (319) : Assertion Failed: ReapProcess: waitid failed: 'No child processes'. Possibly leaking a zombie.

src/steamexe/main.cpp (319) : Assertion Failed: ReapProcess: waitid failed: 'No child processes'. Possibly leaking a zombie.

10/25 16:16:08 Init: Installing breakpad exception handler for appid(steam)/version(1729208001)/tid(3096644)
assert_20241025161608_40.dmp[3099143]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241025161608_40.dmp
assert_20241025161608_40.dmp[3099143]: Finished uploading minidump (out-of-process): success = yes
assert_20241025161608_40.dmp[3099143]: response: CrashID=bp-b3660a44-d7bd-4f21-8ded-42cd72241025
assert_20241025161608_40.dmp[3099143]: file ''/tmp/dumps/assert_20241025161608_40.dmp'', upload yes: ''CrashID=bp-b3660a44-d7bd-4f21-8ded-42cd72241025''
steamwebhelper.sh[3099354]: Using supervisor /home/<username>/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[3099354]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[3099354]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[3099354]: Starting steamwebhelper with Sniper steam runtime at /home/<username>/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/<username>/.local/share/Steam/config/htmlcache -steampid=3096644 -buildid=1729208001 -steamid=76561197978739905 -logdir=/home/<username>/.local/share/Steam/logs -uimode=7 -startcount=5 -steamuniverse=Public -realm=Global -clientui=/home/<username>/.local/share/Steam/clientui -steampath=/home/<username>/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=12 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/<username>/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
wine: configuration in L"/home/<username>/.local/share/Steam/steamapps/compatdata/0/pfx" has been updated.
Fossilize INFO: Overriding serialization path: "/home/<username>/.local/share/Steam/shader_cache_temp_dir_d3d11_64/fozpipelinesv6/steamapprun_pipeline_cache".
fsync: up and running.
src/common/workthreadpool.cpp (959) : Assertion Failed: Work Item (16CProcessWorkItem) for Work Pool CJobMgr::m_WorkThreadPool completed but job no longer existed to notify
src/common/workthreadpool.cpp (959) : Assertion Failed: Work Item (16CProcessWorkItem) for Work Pool CJobMgr::m_WorkThreadPool completed but job no longer existed to notify
assert_20241025161620_43.dmp[3099785]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241025161620_43.dmp
assert_20241025161620_43.dmp[3099785]: Finished uploading minidump (out-of-process): success = yes
assert_20241025161620_43.dmp[3099785]: response: CrashID=bp-d5d8a2f9-ec5e-4c41-9676-65a252241025
assert_20241025161620_43.dmp[3099785]: file ''/tmp/dumps/assert_20241025161620_43.dmp'', upload yes: ''CrashID=bp-d5d8a2f9-ec5e-4c41-9676-65a252241025''
Removing HIDAPI device 'Arduino LLC HAND BRAKE' VID 0x2341, PID 0x8037, bluetooth 0, version 256, serial HIDFH, interface 2, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw3, driver = NONE (DISABLED)
Removing HIDAPI device 'Sim © Alex Oz 2021 VKBsim Gladiator EVO L' VID 0x231d, PID 0x0201, bluetooth 0, version 8482, serial NONE, interface 0, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw17, driver = NONE (DISABLED)
Removing HIDAPI device 'Thustmaster T500 RS Gear Shift' VID 0x044f, PID 0xb660, bluetooth 0, version 256, serial NONE, interface 0, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw11, driver = NONE (DISABLED)
Removing HIDAPI device 'Sim © Alex Oz 2021 VKBsim Gladiator EVO R' VID 0x231d, PID 0x0200, bluetooth 0, version 8482, serial NONE, interface 0, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw16, driver = NONE (DISABLED)
Removing HIDAPI device 'Heusinkveld Sim Pedals Ultimate' VID 0x30b7, PID 0x1003, bluetooth 0, version 0, serial SP24CB020358DEF856, interface 0, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw5, driver = NONE (DISABLED)
Removing HIDAPI device 'Open FFBoard FFBoard' VID 0x1209, PID 0xffb0, bluetooth 0, version 256, serial 33424141429295124540490064, interface 2, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0004, path = /dev/hidraw9, driver = NONE (DISABLED)
Removing HIDAPI device '3Dconnexion SpaceMouse Pro' VID 0x046d, PID 0xc62b, bluetooth 0, version 1078, serial NONE, interface 0, interface_class 0, interface_subclass 0, interface_protocol 0, usage page 0x0001, usage 0x0008, path = /dev/hidraw4, driver = NONE (DISABLED)
[2024-10-25 16:16:22] Shutdown
```

</details>

![Screenshot_2024-10-25_16-20-37](https://github.com/user-attachments/assets/e6e00c50-3c39-421f-baec-2f14482fd886)

**Comment by smcv** [comment]
@kevenwyld wrote:
> having this problem

Please note that the "Steamwebhelper is not responding" dialog is a symptom, not a root cause. It appears whenever the `steamwebhelper` crashes, freezes or is unresponsive, and there is an unlimited number of reasons why this could happen.

Please check `~/.steam/steam/logs/webhelper-linux.txt`. If you see a line like

```
./steamwebhelper: error while loading shared libraries: ./libcef.so: cannot allocate memory in static TLS block
```

from a recent attempt to run Steam, then that is this issue. But if you do not see that line, then what you are experiencing is some different issue and it should be reported separately.

Steam's output to your terminal is not enough information to diagnose whether the crash/freeze you are seeing is this issue or not.

**Comment by kisak-valve** [comment]
Closing as fixed.
