### ISSUE TITLE
Cannot change preferred copy of Steam Family game once all DLCs are common

### ISSUE THREAD

**Issue by Jonathing** [ValveSoftware/steam-for-linux#11319]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Nobara Linux 40 (KDE Plasma)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/user-attachments/files/17264330/steam-logs.tar.gz)
* GPU: AMD Radeon 7700S (Framework Laptop 16 dGPU)

#### Please describe your issue in as much detail as possible:

Steam Family is great, but there's an issue with the "change preferred copy" component. Here is my precise issue: I recently purchased all the remaining DLC for Darkest Dungeon, a game my family member owns. However before that, I was using his copy of the game since he already owns all DLC. Now that we have common DLC, there is no need to change the preferred copy. However, Steam still has the perferred lender of the game set to my family member, and I have no way to change it.

- I poked around in Steam's console and found no commands for Steam Family (reasonably so, as it involves sharing literal game copies)
- We can no longer play the game at the same time as I have no way of changing the preferred lender.
- Steam is very clearly capable of doing this, as when I change the preferred copy of Civilization VI (another game we have in common but with differing DLCs), that goes through. This can be seen in the `librarysharing_log.txt` log.

This is something I have gone to Steam Support for, but they turned me away when I told them that I was running the Steam Client on Nobara linux, which is not Ubuntu (not officially supported). Coming here is my last resort.

#### Steps for reproducing this issue:

1. Join a Steam Family and make sure at least two people have the same game but different DLCs.
2. Buy the remaining DLCs into the account that does not have common DLCs.
3. You are no longer able to change the preferred copy back to your own.

**Comment by austinp-valve** [comment]
Thanks, we'll get a fix out for this

**Comment by kisak-valve** [comment]
Hello @Jonathing, are you still experiencing this issue on an up to date system?

**Comment by Jonathing** [comment]
I unfortunately don't have an immediate way to test. But as far as I remember, I was able to switch back to my copy when DLCs matched and then the switch button disappeared. So, it looks like the problem is fixed.

**Comment by trxxpa** [comment]
> Hello [@Jonathing](https://github.com/Jonathing), are you still experiencing this issue on an up to date system?

im still having this issue, 2 copies in my steam library of halo mcc with the same dlcs, can no longer see any change preferred copy anywhere on steam, so can no longer use the 2 copies, shame

**Comment by kisak-valve** [comment]
Closing per the last comment.
