### ISSUE TITLE
Steam Recording won't save clips

### ISSUE THREAD

**Issue by gg537** [ValveSoftware/steam-for-linux#11433]
#### Your system information

* Steam client version (build number or date): Steam Client Build Date:  Tue, Nov 5 9:33 PM UTC -08:00
* Distribution (e.g. Ubuntu): Fedora kinoite 41 Steam Flatpak [System gist](https://gist.github.com/gg537/2d15359eda168fae96a5d8cc2a5ecb6c#file-gistfile1-txt)
* Opted into Steam client beta?: Yes (broken in stable too)
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD 5700XT

#### Please describe your issue in as much detail as possible:
When trying to save a clip using "Save in Steam" nothing happens, when trying "Export Video File" I get this UI error "Unable to retrieve clip information(2)". Both give the following error in the terminal:

```Attempting to save a clip to clip_405820_20241107_202752 from background, timeline_40582020241107_191426[3261] to timeline_40582020241107_191426[15260]: 1 timelines, NOT including current, BACKGROUND recording
libav: No support for codec h264 profile 100.

libav: No support for codec h264 profile 100.
libav: Failed setup for format vaapi: hwaccel initialisation returned error.

libav: Failed setup for format vaapi: hwaccel initialisation returned error.
Failed to get HW surface format
libav: decode_slice_header error

libav: decode_slice_header error
libav: no frame!

libav: no frame!
libav: No support for codec h264 profile 100.

libav: No support for codec h264 profile 100.
libav: Failed setup for format vaapi: hwaccel initialisation returned error.

libav: Failed setup for format vaapi: hwaccel initialisation returned error.
Failed to get HW surface format
libav: decode_slice_header error

libav: decode_slice_header error
libav: no frame!

libav: no frame!
Failed to get thumbnail frame from MPD /var/home/gh/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/10041264/gamerecordings/clips/clip_405820_20241107_202752/video/bg_405820_20241107_191428/session.mpd
Clip save failed with Failure
```

I only get these errors when trying to "Save in Steam" or "Export Video File" If using "Create a Share Link" it exports the clip fine.

Back when the recording feature was release I was able to save clips fine, I'm not sure when it stopped working.

#### Steps for reproducing this issue:

1. Open View > Recordings & Screenshots > Select a recording
2.  Clip > Save / Share > click "Save in Steam" or "Export Video File"
3. Fails to create clip

**Comment by gg537** [comment]
I'm not sure if the overlay label is correct for this issue as I can record video fine, the problem is when trying to clip the video, and I'm doing that in desktop mode with the game closed.

**Comment by gg537** [comment]
Should I close this issue and make a report on the Steam Flatpak tracker?

**Comment by crispyricepc** [comment]
I think this issue should stay open. I have the same problem on Steam for Fedora installed using dnf

**Comment by rocinante333** [comment]
Also using Fedora 41 rpm install, not flatpak , seeing the same.  I am able to copy to clipboard successfully though.

Steam Beta Branch:  Stable Client
Steam Version:  1733265492
Steam Client Build Date:  Mon, Dec 2 1:26 PM UTC -08:00
Steam Web Build Date:  Mon, Dec 2 1:20 PM UTC -08:00
Steam API Version:  SteamClient021

**Comment by OtterCodes101** [comment]
can confirm this happends to me as well

**Comment by KDHofAvalon** [comment]
I can confirm that is happening to me as well on Steam installed through dnf on Fedora 41 (KDE Plasma, if that makes a difference)

**Comment by OtterCodes101** [comment]
The problem happened to be before and after upgrading to 41. I'm also using KDE plasma.

**Comment by gg537** [comment]
The Steam Flatpak just updated and now it's working again.

This was the fix https://github.com/flathub/com.valvesoftware.Steam/commit/28481f09f33c12b6ac7421d13af9ed1523c54ec4

**Comment by OtterCodes101** [comment]
the problem is this happens on the dnf version of steam

**Comment by TarsiSurdi** [comment]
It's still not working for me even after updating to 1.0.0.81. Clips are recorded just fine and can be played back from anywhere within Steam, however no single export option works. 
The error I get is "Unable to retrieve clip information (9)", the logs show the following when trying to save any clips to a file:

```
[2024-12-22 22:15:50] flock /run/user/1000/doc/28ceb368/Steam Recordings/video/fg_268910_20241223_010246/session.mpd LOCK_SH failed. errno = 38flock /run/user/1000/doc/28ceb368/Steam Recordings/video/fg_268910_20241223_010246/session.mpd LOCK_SH failed. errno = 38Attempting to save a clip to clip_268910_20241223_011558 from background, timeline_26891020241223_010237[56675] to timeline_26891020241223_010237[61283]: 1 timelines, NOT including current, BACKGROUND recording
[2024-12-22 22:15:58] flock /run/user/1000/doc/28ceb368/Steam Recordings/video/fg_268910_20241223_010326/session.mpd LOCK_SH failed. errno = 38Unable to hard link clipped recording from /run/user/1000/doc/28ceb368/Steam Recordings/video/fg_268910_20241223_010326 to /run/user/1000/doc/28ceb368/Steam Recordings/clips/clip_268910_20241223_011558/video/fg_268910_20241223_010326 - NOT ACTIVE start offset 7303   duration 4608
[2024-12-22 22:15:58] Clip save failed with File Not Found
```

It seems like there is an issue when creating hard links between different files in the game recordings files structure?
System: Fedora 41 GNOME Wayland NVIDIA 565.77 - Steam Flatpak

**Comment by LucaPisl** [comment]
In case anyone else is having similar problems, for me the fix was to go and select Custom (when saving the replay) and choose `H.264` instead of `H.265 (HEVC)`. I'm on ArchLinux and have an AMD GPU + CPU, and have the required drivers to play games, in case that's relevant.

**Comment by YuiNekomata** [comment]
> In case anyone else is having similar problems, for me the fix was to go and select Custom (when saving the replay) and choose `H.264` instead of `H.265 (HEVC)`. I'm on ArchLinux and have an AMD GPU + CPU, and have the required drivers to play games, in case that's relevant.

Was getting "steam failed to export try again (2)" however once I swapped to H.264 instead of H.265 (HEVC) the issue was resolved! Thank you!

**Comment by murlakatamenka** [comment]
> In case anyone else is having similar problems, for me the fix was to go and select Custom (when saving the replay) and choose `H.264` instead of `H.265 (HEVC)`

how is it a fix though? Merely a crutch.

I also run Arch with AMD CPU and GPU (Ryzen 5600 + RX 5700 XT), the latter is capable of hardware encoding HEVC. For example, venerable `gpu-screen-recorder` encodes 10-bit HEVC with hardware acceleration _no problemo_. So I'm not happy with Steam not usint the superior codec for exporting video.

**Comment by itmecho** [comment]
Changing to H.264 works for exporting to a file but I still get the failed to export error when trying to create a shared link. This still happens even when disabling the H.265 setting in the game recording settings

**Comment by Thynix** [comment]
For what it's worth, I'm seeing this problem on Windows 11 as well (I'll try to find a better place to report as well) - I have an RTX 5090 so it's not just AMD and it's not (at least in terms of symptoms) just Linux. I'm using Steam client version 1751405894. H.264 works for me too. Strangely, I get this error even for exporting the clip at original quality. Perhaps it's reencoding?

**Comment by Radmang** [comment]
> In case anyone else is having similar problems, for me the fix was to go and select Custom (when saving the replay) and choose `H.264` instead of `H.265 (HEVC)`. I'm on ArchLinux and have an AMD GPU + CPU, and have the required drivers to play games, in case that's relevant.

This worked as an alternative (not a fix) on Steam (official `.deb` file) running Ubuntu 25.10, with an AMD Ryzen 5 5600x (CPU) and AMD RX 7900 GRE (GPU).
