### ISSUE TITLE
Steam Window disappears after closing game

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#11479]
#### Your system information

* Steam client version (build number or date):  1731433018
* Distribution (e.g. Ubuntu): Manjaro Gnome
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/user-attachments/files/17788671/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD RX 6700 XT

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Play a game
2.  Quit game
3.  Steam will disappear and I have to close steam just to see the Window again but the tray icon will be there but the only thing that works on the tray is exit steam

**Comment by dom1torii** [comment]
Same on my side, but i dont even need to close the game, it just randomly disappears when the game is open.

**Comment by underspiffy** [comment]
This has been happening to me as well. its very frustrating! Its happened with both beta and stable
Distro: EndeavourOS

**Comment by Perfectio07** [comment]
This also happens to me. Sometimes it closes while in-game, sometimes it closes when I close a game.

Worth noting as well, there are a few times it does not close but starts the "shutting down steam" popup and just hangs there with the only option being force close steam. Running Arch/Hyprland

**Comment by sim590** [comment]
I have this also. It has started recently. Steam seems to also try to uninstall stuff. A window pops and asks if I am sure that I want to uninstall something but I didn't ask to uninstall anything.

**Comment by coreybruce** [comment]
> I have this also. It has started recently. Steam seems to also try to uninstall stuff. A window pops and asks if I am sure that I want to uninstall something but I didn't ask to uninstall anything.

I noticed that also, it kept coming up with a window to uninstall content

**Comment by Bodyash** [comment]
similar to my issue, can confirm that steam UI can crash sometimes when closing game, but for me it also happening during playing the game + other bugs:
https://github.com/ValveSoftware/steam-for-linux/issues/11449

**Comment by Skiftstar** [comment]
Same issue, I had noticed it back when the game recording beta was a thing, back then it was not an issue on stable
Currently an issue on stable again with game recording on, maybe it's an issue with that?

**Comment by dom1torii** [comment]
> Same issue, I had noticed it back when the game recording beta was a thing, back then it was not an issue on stable Currently an issue on stable again with game recording on, maybe it's an issue with that?

I don't have game recording enabled and i still have the bug

**Comment by coreybruce** [comment]
Idk if anyone has tried or had the same experience but I think the issue may be fixed or doesn't happen on the beta client. Can anyone test to verify?

**Comment by Perfectio07** [comment]
> Idk if anyone has tried or had the same experience but I think the issue may be fixed or doesn't happen on the beta client. Can anyone test to verify?

When I made my comment 5 days ago I was using the beta client and it was still happening. Unless something changed in the last 5 days... I will retest and see if it happens again

**Comment by coreybruce** [comment]
> > Idk if anyone has tried or had the same experience but I think the issue may be fixed or doesn't happen on the beta client. Can anyone test to verify?
> 
> When I made my comment 5 days ago I was using the beta client and it was still happening. Unless something changed in the last 5 days... I will retest and see if it happens again

Ahh ok I see, I have been having been constantly dealing with this issue even when I launch a gaming making Steam almost unusable, unstable and unreliable but after switching to the beta I haven't been able to recreate the issue so far at least. 

Hopefully they have fixed the issue and this does fix the issue for others.. I don't understand how a bug like this could have entered stable without testing as it's been a frustrating experience with the other issue I have reported about big picture mode performance.

**Comment by sim590** [comment]
I did try Beta and I think it is indeed fixed in Beta. Thanks.

EDIT (2025-04-24): The issue seems back on the Beta version. At least, I get the issue when launching Oblivion Remastered.

**Comment by ChairmanbAd** [comment]
I am also having this issue, however from my limited testing it seems as if adding `gamemoderun %command%` in the launch options of a title resolves the issue.
I haven't tried playing around with other extra arguments to see if it's merely the fact of having launch options that works for me or if it's specifically tied to gamemode.

**Comment by dom1torii** [comment]
> I am also having this issue, however from my limited testing it seems as if adding `gamemoderun %command%` in the launch options of a title resolves the issue. I haven't tried playing around with other extra arguments to see if it's merely the fact of having launch options that works for me or if it's specifically tied to gamemode.

Gamemode doesn't resolve anything for me. Been running gamemode since before this issue started happening.

**Comment by joranm1** [comment]
Hi, I am having the same issue on Fedora 41, supposedly since yesterday's Xorg update (but I didn't try to downgrade the package so I can't say I'm sure of anything...)
The Steam window is disappearing every time I quit game, doesn't matter whether it's native or Proton, so I tried to launch Steam from command-line, reproduced the bug and noticed this: 
`reaping pid: 23072 -- gameoverlayui`
I don't know if it is Steam's normal behaviour, but I tried disabling Steam Overlay, and now things work as intended.
Is anyone able to confirm this?

**Comment by Bodyash** [comment]
Here I have error in systemctl logs (related to steamwebhelper crash) - https://github.com/ValveSoftware/steam-for-linux/issues/11449#issuecomment-2507000226

**Comment by coreybruce** [comment]
I really wish they would fix this bug

**Comment by box-dev** [comment]
I am finding that turning off "Enable GPU accelerated rendering in web views" stops the crashes. Otherwise I have this annoying problem very very often, maybe 50% or higher of times I'm using Steam. It seems to be that the UI crashes once in-game overlay loads? (With GPU acceleration turned on)

**Comment by joranm1** [comment]
> I am finding that turning off "Enable GPU accelerated rendering in web views" stops the crashes. Otherwise I have this annoying problem very very often, maybe 50% or higher of times I'm using Steam. It seems to be that the UI crashes once in-game overlay loads? (With GPU acceleration turned on)

I can confirm that this workaround is also valid on my system

**Comment by porcupinecoder** [comment]
still having this issue here as well, happened frequently yesterday

**Comment by razzeee** [comment]
Seems to indeed be caused by the steamwebhelper crashing https://github.com/ValveSoftware/steam-for-linux/issues/11449

```
Dez 17 08:10:49 fedora-desktop systemd-coredump[47438]: [🡕] Process 47256 (steamwebhelper) of user 1000 dumped core.
                                                        
                                                        Module /run/host/usr/lib64/libGLX_mesa.so.0.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-glx.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libXxf86vm.so.1.0.0 from rpm libXxf86vm-1.1.5-7.fc41.x86_64
                                                        Module /run/host/usr/lib64/libudev.so.1.7.9 from rpm systemd-256.9-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libcap.so.2.70 from rpm libcap-2.70-4.fc41.x86_64
                                                        Module /run/host/usr/lib64/libwayland-client.so.0.23.0 from rpm wayland-1.23.0-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libunistring.so.5.0.0 from rpm libunistring-1.1-8.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxml2.so.2.12.8 from rpm libxml2-2.12.8-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libedit.so.0.0.74 from rpm libedit-3.1-53.20240808cvs.fc41.x86_64
                                                        Module /run/host/usr/lib64/libpciaccess.so.0.11.1 from rpm libpciaccess-0.16-13.fc41.x86_64
                                                        Module /run/host/usr/lib64/libffi.so.8.1.4 from rpm libffi-3.4.6-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-dri2.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libdrm_intel.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libdrm_amdgpu.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libelf-0.192.so from rpm elfutils-0.192-7.fc41.x86_64
                                                        Module /run/host/usr/lib64/libdrm_radeon.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libsensors.so.4.5.0 from rpm lm_sensors-3.6.0-20.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxshmfence.so.1.0.0 from rpm libxshmfence-1.3.2-5.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-sync.so.1.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-xfixes.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-present.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-dri3.so.0.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libX11-xcb.so.1.0.0 from rpm libX11-1.8.10-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libglapi.so.0.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libidn2.so.0.4.0 from rpm libidn2-2.3.7-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libzstd.so.1.5.6 from rpm zstd-1.5.6-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/liblzma.so.5.6.2 from rpm xz-5.6.2-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libgallium-24.2.8.so from rpm mesa-24.2.8-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-shm.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb-randr.so.0.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libwayland-server.so.0.23.0 from rpm wayland-1.23.0-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libXau.so.6.0.0 from rpm libXau-1.0.11-7.fc41.x86_64
                                                        Module /run/host/usr/lib64/libGLdispatch.so.0.0.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module /run/host/usr/lib64/libGLX.so.0.0.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module /run/host/usr/lib64/libz.so.1.3.1.zlib-ng from rpm zlib-ng-2.1.7-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libxcb.so.1.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module /run/host/usr/lib64/libexpat.so.1.10.0 from rpm expat-2.6.4-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libgbm.so.1.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libdrm.so.2.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module /run/host/usr/lib64/libGL.so.1.7.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module /run/host/usr/lib64/libX11.so.6.4.0 from rpm libX11-1.8.10-2.fc41.x86_64
                                                        Module /run/host/usr/lib64/libXfixes.so.3.1.0 from rpm libXfixes-6.0.1-4.fc41.x86_64
                                                        Module /run/host/usr/lib64/libXext.so.6.4.0 from rpm libXext-1.3.6-2.fc41.x86_64
                                                        Stack trace of thread 47392:
                                                        #0  0x0000000000000000 n/a (n/a + 0x0)
                                                        ELF object binary architecture: AMD x86-64
```

**Comment by razzeee** [comment]
Can confirm disabling `Settings > Interface > Enable GPU accelerated rendering in web views` seems to help.

Has anyone seen this on other DEs, that are not gnome?

**Comment by njdom24** [comment]
> Can confirm disabling `Settings > Interface > Enable GPU accelerated rendering in web views` seems to help.
> 
> Has anyone seen this on other DEs, that are not gnome?

I'm seeing it on Sway, and disabling that setting has fixed it for me.

**Comment by Bodyash** [comment]
> Seems to indeed be caused by the steamwebhelper crashing #11449
> 
> ```
> Dez 17 08:10:49 fedora-desktop systemd-coredump[47438]: [🡕] Process 47256 (steamwebhelper) of user 1000 dumped core.
>                                                         
>                                                         Module /run/host/usr/lib64/libGLX_mesa.so.0.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-glx.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libXxf86vm.so.1.0.0 from rpm libXxf86vm-1.1.5-7.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libudev.so.1.7.9 from rpm systemd-256.9-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libcap.so.2.70 from rpm libcap-2.70-4.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libwayland-client.so.0.23.0 from rpm wayland-1.23.0-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libunistring.so.5.0.0 from rpm libunistring-1.1-8.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxml2.so.2.12.8 from rpm libxml2-2.12.8-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libedit.so.0.0.74 from rpm libedit-3.1-53.20240808cvs.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libpciaccess.so.0.11.1 from rpm libpciaccess-0.16-13.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libffi.so.8.1.4 from rpm libffi-3.4.6-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-dri2.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libdrm_intel.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libdrm_amdgpu.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libelf-0.192.so from rpm elfutils-0.192-7.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libdrm_radeon.so.1.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libsensors.so.4.5.0 from rpm lm_sensors-3.6.0-20.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxshmfence.so.1.0.0 from rpm libxshmfence-1.3.2-5.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-sync.so.1.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-xfixes.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-present.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-dri3.so.0.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libX11-xcb.so.1.0.0 from rpm libX11-1.8.10-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libglapi.so.0.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libidn2.so.0.4.0 from rpm libidn2-2.3.7-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libzstd.so.1.5.6 from rpm zstd-1.5.6-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/liblzma.so.5.6.2 from rpm xz-5.6.2-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libgallium-24.2.8.so from rpm mesa-24.2.8-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-shm.so.0.0.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb-randr.so.0.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libwayland-server.so.0.23.0 from rpm wayland-1.23.0-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libXau.so.6.0.0 from rpm libXau-1.0.11-7.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libGLdispatch.so.0.0.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libGLX.so.0.0.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libz.so.1.3.1.zlib-ng from rpm zlib-ng-2.1.7-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libxcb.so.1.1.0 from rpm libxcb-1.17.0-3.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libexpat.so.1.10.0 from rpm expat-2.6.4-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libgbm.so.1.0.0 from rpm mesa-24.2.8-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libdrm.so.2.124.0 from rpm libdrm-2.4.124-1.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libGL.so.1.7.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libX11.so.6.4.0 from rpm libX11-1.8.10-2.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libXfixes.so.3.1.0 from rpm libXfixes-6.0.1-4.fc41.x86_64
>                                                         Module /run/host/usr/lib64/libXext.so.6.4.0 from rpm libXext-1.3.6-2.fc41.x86_64
>                                                         Stack trace of thread 47392:
>                                                         #0  0x0000000000000000 n/a (n/a + 0x0)
>                                                         ELF object binary architecture: AMD x86-64
> ```

Can you provide more info from journalctl?

I have similar issue (I opened an issue 5 weeks ago https://github.com/ValveSoftware/steam-for-linux/issues/11449)
And also steamwebhelper is crashing. But after stack trace I have something like:

>Dec 03 00:57:14 arch kernel: traps: steamwebhelper[122064] trap invalid opcode ip:7e6ddb4cabcf sp:7ffe36752010 error:0 in libcef.so[66c9bcf,7e6dd71ed000+a36d000]

For me it looks like some error in libcef (chromium embedded)

You can check more here: https://github.com/ValveSoftware/steam-for-linux/issues/11449#issuecomment-2507000226

**Comment by Plyply99** [comment]
Can confirm disabling Settings > Interface > Enable GPU accelerated rendering in web views seems to help.

This is on Gnome and Hyprland.

**Comment by razzeee** [comment]
> > Replying to [#11479 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/11479#issuecomment-2547664855)
> 
> Can you provide more info from journalctl?
> 
> I have similar issue (I opened an issue 5 weeks ago #11449) And also steamwebhelper is crashing. But after stack trace I have something like:
> 
> > Dec 03 00:57:14 arch kernel: traps: steamwebhelper[122064] trap invalid opcode ip:7e6ddb4cabcf sp:7ffe36752010 error:0 in libcef.so[66c9bcf,7e6dd71ed000+a36d000]
> 
> For me it looks like some error in libcef (chromium embedded) And I don't understand why random steam windows (dialogs) are spawning after crash. Also crash happens after I launch games. You can check more here: [#11449 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/11449#issuecomment-2507000226)

grepping my log after the failure for `libcef` or `opcode` doesn't return a thing

**Comment by coreybruce** [comment]
Should I provide another journal log?

**Comment by Bodyash** [comment]
> Should I provide another journal log to help more with diagnosing the issue?

just do it

**Comment by gbrlsnchs** [comment]
This is happening kind of consistently with Marvel Rivals. When I open the game, 95% of the time the Steam window will disappear, and not even killing Steam processes will make it appear again. A restart is needed for Steam to reopen.

**Comment by ryao** [comment]
When in the turret as Punisher (via E), after beginning to fire, the game will keep playing the firing sound, even if you stop firing.

**Comment by ryao** [comment]
`NVRM: nvAssertFailedNoLog: Assertion failed: pEventNotificationList->pendingEventNotifyCount == 0 @ event_notification.c:289` spams dmesg. The dmesg spam is a race condition according to NVIDIA/open-gpu-kernel-modules#716. A fix is queued for Nvidia has a fix for the 570 driver.

Also, the game sometimes freezes. I wonder if the two are related.

**Comment by ryao** [comment]
The game will often freeze during the intro movies when nvidia reflex is enabled.

**Comment by kparal** [comment]
@ryao Please stop adding unrelated comments here. Create a separate issue.

**Comment by ryao** [comment]
@kparal I thought I was posting these in the right issue. I had the wrong tab. :/

**Comment by ryao** [comment]
> @ryao Please stop adding unrelated comments here. Create a separate issue.

You did not need to ask. I had multiple tabs opened and thought that this was the marvel rivals issue tab. I just deleted the comments and put them in the correct issue upon seeing that.

**Comment by Syntrait** [comment]
This happens for me too, but it seems like the Friends List window is the only window that can appear (a bit buggy, though). Other windows just dont show up, like others said.

**Comment by zakk4223** [comment]
Disabling GPU accelerated web views fixes the crashes, but disabling that now makes big picture mode unbearably laggy (basically unusable).

**Comment by Pahasara** [comment]
Still this happening to me on hyprland.

**Comment by sim590** [comment]
The issue seems back on the Beta version. At least, I get the issue when launching Oblivion Remastered. I run Sway (wayland on Archlinux).

**Comment by joranm1** [comment]
The issue didn't trigger any longer when Fedora updated to 42...
And today it's been triggering again, I don't know why

**Comment by lelgenio** [comment]
I believe I've seen this issue occur in a fresh install of Fedora Silverblue, using the Steam Flatpak.

**Comment by HcgRandon** [comment]
This is happening to me as well after switching to hyprland

**Comment by RexSonic** [comment]
Has started happening again recently on Arch

**Comment by HcgRandon** [comment]
As a heads up. It only seems to occur when launching or exiting games for me.

**Comment by Pahasara** [comment]
> As a heads up. It only seems to occur when launching or exiting games for me.

For me as well. More than 6 months, still no fix!!

**Comment by joranm1** [comment]
> > As a heads up. It only seems to occur when launching or exiting games for me.
> 
> For me as well. More than 6 months, still no fix!!

On Fedora we just had a mutter update last Sunday (mutter-48.3-2) with those release notes:
- Fix window tracker regression

Since this package update the problem is gone, so I think this is getting fixed within the compositor, and not within Steam...

**Comment by rubengees** [comment]
I am on the latest mutter version (`48.3.1-1`) on arch and this still happens to me, together with the sudden uninstall windows.

<details>

<summary>Crash details</summary>


```
Process 12853 (steamwebhelper) of user 1000 dumped core.

Stack trace of thread 1:
#0  0x00007f1d170cb0af n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x66cb0af)
#1  0x00007f1d170cab7b n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x66cab7b)
#2  0x00007f1d170cb129 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x66cb129)
#3  0x00007f1d133b3f8a n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x29b3f8a)
#4  0x00007f1d174af021 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6aaf021)
#5  0x00007f1d174bd7bb n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6abd7bb)
#6  0x00007f1d174aad35 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6aaad35)
#7  0x00007f1d13325e7f n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x2925e7f)
#8  0x00007f1d174cf7af n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6acf7af)
#9  0x00007f1d1711b15f n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x671b15f)
#10 0x00007f1d1713c076 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x673c076)
#11 0x00007f1d170d1f9c n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x66d1f9c)
#12 0x00007f1d1713c811 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x673c811)
#13 0x00007f1d170fc7ae n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x66fc7ae)
#14 0x00007f1d1cd6bb54 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0xc36bb54)
#15 0x00007f1d16bac4e5 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x61ac4e5)
#16 0x00007f1d16bacbf9 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x61acbf9)
#17 0x00007f1d16badcc5 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x61adcc5)
#18 0x00007f1d16babb50 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x61abb50)
#19 0x00007f1d132ecf1c n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x28ecf1c)
#20 0x00007f1d132d5c87 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x28d5c87)
#21 0x00007f1d13244b11 cef_execute_process (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x2844b11)
#22 0x00005649204b89ae n/a (/home/user/.local/share/Steam/ubuntu12_64/steamwebhelper + 0x7cb9ae)
#23 0x00005649201d550f n/a (/home/user/.local/share/Steam/ubuntu12_64/steamwebhelper + 0x4e850f)
#24 0x00005649201ddfe8 n/a (/home/user/.local/share/Steam/ubuntu12_64/steamwebhelper + 0x4f0fe8)
#25 0x00007f1d0fa376b5 n/a (/run/host/usr/lib/libc.so.6 + 0x276b5)
#26 0x00007f1d0fa37769 n/a (/run/host/usr/lib/libc.so.6 + 0x27769)
#27 0x000056491ffec02a n/a (/home/user/.local/share/Steam/ubuntu12_64/steamwebhelper + 0x2ff02a)

Stack trace of thread 3:
#0  0x00007f1d0faade22 n/a (/run/host/usr/lib/libc.so.6 + 0x9de22)
#1  0x00007f1d0faa264c n/a (/run/host/usr/lib/libc.so.6 + 0x9264c)
#2  0x00007f1d0faa4d1e n/a (/run/host/usr/lib/libc.so.6 + 0x94d1e)
#3  0x00007f1d17173726 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6773726)
#4  0x00007f1d1719e469 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x679e469)
#5  0x00007f1d17117f5c n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6717f5c)
#6  0x00007f1d1715717d n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x675717d)
#7  0x00007f1d17156158 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6756158)
#8  0x00007f1d17155d8d n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6755d8d)
#9  0x00007f1d17155c9d n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6755c9d)
#10 0x00007f1d17173f13 n/a (/home/user/.local/share/Steam/ubuntu12_64/libcef.so + 0x6773f13)
#11 0x00007f1d0faa57eb n/a (/run/host/usr/lib/libc.so.6 + 0x957eb)
#12 0x00007f1d0fb28fb4 n/a (/run/host/usr/lib/libc.so.6 + 0x118fb4)
ELF object binary architecture: AMD x86-64
```

</details>

**Comment by darkylein** [comment]
Well, this seems to be a generic problem. So posting +1's over and over again won't help much. Just give the initial issue a thumbs up, subscribe to this issue, wait for the fix and spare peoples inboxes.

Eventually Valve will work on that problem. Until then you can try disabling GPU acceleration if you don't need that feature.

**Comment by snaillyy** [comment]
Same here on Gentoo, this is the error I get when running from the terminal, anyone else getting the same?
`(process:3680): GLib-GObject-CRITICAL **: 11:27:03.185: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`

**Comment by HcgRandon** [comment]
I agree with @darkylein I wanted to mention however that disabling GPU **does not** fix the issue for me 100% but it seems to occur somewhat less often with it disabled

**Comment by joranm1** [comment]
> Replying to https://github.com/ValveSoftware/steam-for-linux/issues/11479#issuecomment-2940441689

My mistake, this does not solve it at all.
Actually,  it seems when updating the compositor (in my case, mutter) the bug goes away for a certain period of time, then comes back again. Looks like it could be related to cache or something...

**Comment by Bodyash** [comment]
Steam issue again. Mutter had focus and unclickable windows problem that is now fixed (https://gitlab.gnome.org/GNOME/mutter/-/issues/4138).

Disabling GPU acceleration for web content in steam setting again solves the issue.
