### ISSUE TITLE
Steam not launching after updating to Kubuntu 24.10 (from 24.04)

### ISSUE THREAD

**Issue by retroDEG** [ValveSoftware/steam-for-linux#11499]
#### Your system information

* Steam client version (build number or date): not sure
* Distribution (e.g. Ubuntu): Kubuntu 24.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs(i used the command it said to use here and got this):

 ```retro@Nix:~$ tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs
tar: Removing leading `/' from member names
tar: /home/retro/.steam/steam/logs: Cannot stat: Too many levels of symbolic links
tar: Exiting with failure status due to previous errors
```

* GPU: AMD RX 7900XTX

#### Please describe your issue in as much detail as possible:
Trying to launch steam makes the little loading icon by my cursor show up, but steam never opens. Checking in the system monitor shows it running (multiple times if you try to open multiple times), but it never shows up in the system tray or opens. Trying to open in the terminal results in the terminal just sitting there and nothing happens, in this case the process doesn't even show up in the system monitor.  

#### Steps for reproducing this issue[METHOD 1] :

1. Click shortcut
2. See it show up in system monitor
3. Nothing happens

#### Steps for reproducing this issue[METHOD 2] :

1. open terminal
2. ```steam```
3. Nothing happens

**Comment by retroDEG** [comment]
note to self: i am stupid
how i fixed it: ```remove steam-libs-i386``` and ```remove steam```, then just reinstalling fixed it

**Comment by evphoryyyc** [comment]
>tried opening steam normally
opens and closes in the same instant forever until i force shut
>tried opening through konsole
opens and runs normally
>***question mark***

its my first day using the kubantu ( i dont even know where tf is question mark ) and steam was working normally until i restarted my pc now its like that, any clue on how to fix it***question mark*** i wouldnt mind having to launch it through konsole everytime but id be happy to know if theres a fix

**Comment by PhilippGackstatter** [comment]
I have the same issue on Kubuntu 24.04. I removed steam entirely, deleted everything in `~/.local/share/Steam/` and `/usr/lib/steam/` and reinstalled. But the problem persists. Launching through the command line works, but would be nice to have a fix for this.
