### ISSUE TITLE
Make Community section popups true popups

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#14]
The mouseover popups in Community section seem to behave as general top-level windows, instead of mere popup windows, so when they are displayed, focus goes from the Steam main window to the popup. This is incorrect, popups should behave same as for example popups in Store section.

I noticed this because I have set my window manager (KDE) to make unfocused windows somewhat transparent, and this is what happens: http://imageshack.us/photo/my-images/831/steampopup.png/

**Comment by eiglow** [comment]
I'm pretty sure this issue has been fixed? Could we maybe get some other re-tests, since this is a very old issue

**Comment by 7RST1** [comment]
Nope, it's been 9 years and this (albeit, not that huge) issue still persists. (Sorry for the horrible quality GIF)
![untitled](https://user-images.githubusercontent.com/16783057/141382976-ae1389d7-d298-4c0e-b06f-c835921681d8.gif)

**Comment by kuraida** [comment]
Fedora 43 KDE Plasma 6.6.3 Wayland

While in newer versions the task manager "focus" indicator no longer flips back and forth with these menus open as in the image posted a few years ago, these menus still have some odd focus behavior. 

The mouse exiting through the bottom of the dropdown leaves the dropdown on screen until you click elsewhere in the steam client.  

Additionally, should you have a window open in front of the steam client and accidentally mouse over one of the top 'Store, Library' etc menus, the dropdown will open over the other front window, "sandwiching" the front window between the dropdown and the steam client,  and  will not disappear unless you refocus steam and click outside of the menu.

Edit: I also went into desktop mode on the Steam Deck to confirm it's happening there as well. The taskbar "focus indicator" highlighting still changes there as in the 2021 post above.

<img width="384" height="208" alt="Image" src="https://github.com/user-attachments/assets/afe09b6b-4554-4cf5-a9c1-f1b24f4e1347" />
