### ISSUE TITLE
Steam wants to install libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, remove libgl1-mesa-dri-lts-raring:i386, libgl1-mesa-glx-lts-raring:i386 and other packages

### ISSUE THREAD

**Issue by johan666** [ValveSoftware/steam-for-linux#2800]
I upgraded my Ubuntu installation from 12.04.2 to 12.04.3. In this process I switched from the quantal kernel and X server to the raring kernel and X server.

Now when I start Steam, it wants to install the old packages libgl1-mesa-dri:i386, libgl1-mesa-glx:i386. This is really bad, because it will remove a lot of raring packages.

The apt-get log:

```
Steam needs to install these additional packages: 
    libgl1-mesa-dri:i386, libgl1-mesa-glx:i386
[sudo] password for johan: 
.................................................................................................................................................................................................................................................................................................................................
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libxrandr-ltsq2 libwayland0 libxcb-xfixes0 libllvm3.1:i386
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libgl1-mesa-glx libglapi-mesa libglapi-mesa:i386
Suggested packages:
  libglide3:i386
The following packages will be REMOVED
  libgl1-mesa-dri-lts-raring libgl1-mesa-dri-lts-raring:i386
  libgl1-mesa-glx-lts-raring libgl1-mesa-glx-lts-raring:i386
  libglapi-mesa-lts-raring libglapi-mesa-lts-raring:i386
  libxatracker1-lts-raring ubuntu-desktop xorg xserver-xorg-lts-raring
  xserver-xorg-video-all-lts-raring xserver-xorg-video-vmware-lts-raring
The following NEW packages will be installed
  libgl1-mesa-dri:i386 libgl1-mesa-glx libgl1-mesa-glx:i386 libglapi-mesa
  libglapi-mesa:i386
0 upgraded, 5 newly installed, 12 to remove and 0 not upgraded.
Need to get 3320 kB of archives.
After this operation, 13,6 MB disk space will be freed.
Do you want to continue [Y/n]?

```

When I cancel this operation, Steam starts normally and I can play games.

**Comment by sprechsucht** [comment]
Steam shows the same errors on Ubuntu 14.04 64bit.

**Comment by Theodin** [comment]
Same error on Ubuntu 12.04.5 64 bit. Can anyone confirm this?

**Comment by dionw** [comment]
@Theodin @xamox @Ardakilic : same here, this will happen either if you freshly installed Ubuntu 12.04.2+ 64-bit or updated to Ubuntu 12.04.x 64-bit from 12.04.1 through HWE updates (see https://wiki.ubuntu.com/Kernel/LTSEnablementStack).

**Fix**: The following installs the i386 versions of the updated/HWE mesa libs and allows Steam to get through its startup check without complaining:
```bash
$ sudo apt-get install ia32-libs

The following NEW packages will be installed
gstreamer0.10-plugins-good:i386 ia32-libs ia32-libs-multiarch:i386
libdrm-nouveau2:i386 libelf1:i386
** libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 **
libglapi-mesa-lts-trusty:i386 libglu1-mesa:i386 libllvm3.4:i386 libqt4-opengl:i386
libtxc-dxtn-s2tc0:i386 libxcb-dri2-0:i386
```
This issue has status closed but Steam's startup check still needs to be tweaked. Instead of trying to apt-get install the non-HWE i386 versions of mesa-dri and mesa-glx it could just try ia32-libs (or the two relevant i386 lts libs matching any installed 64-bit mesa lts libs).

**Comment by xamox** [comment]
@dionw Thanks.  I was able to eventually figure it out just never posted solution.

**Comment by johnjelinek** [comment]
For Ubuntu 14.04.2 I had to install these manually:
```
sudo apt-get install libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 libc6:i386
``

**Comment by itweeb** [comment]
Thanks John, can confirm installing manually worked for me.

**Comment by clankill3r** [comment]
@johnjelinek 
or anyone else. When I try that I get into endless problems of dependencies. Does someone know a good way to deal with that? I just installed ubuntu and after trying to get steam to work my Ubuntu Software Center is allready giving error messages...

**Comment by johnjelinek** [comment]
Please output your error messages here.

**Comment by c3l3r1on** [comment]
Dear johnjelinek

c3l@c3l-X681X:~$ sudo apt-get install libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 libc6:i386
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
E: Nie udało się odnaleźć pakietu libgl1-mesa-dri-lts-trusty
E: Nie udało się odnaleźć pakietu libgl1-mesa-glx-lts-trusty

in english, cannot found package libgl1-*

**Comment by johnjelinek** [comment]
@c3l3r1on: you're using `14.04.2` or another version?

**Comment by c3l3r1on** [comment]
@johnjelinek I were using 15.04 dev ver. but after 4-5 hours fighting with i386 deps and others i've instaled mint 64bit, and it works without problem.

**Comment by johnjelinek** [comment]
OK, my instructions only work for 14.04.x



—

**Comment by michael-hopkins** [comment]
@johnjelinek [this](https://github.com/ValveSoftware/steam-for-linux/issues/2800#issuecomment-75881032) comment of yours solved the issue for me. `Ubuntu Gnome 14.04 LTS`

    sudo apt-get install libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 libc6:i386

**Comment by mateuspv** [comment]
install libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 libc6:i386 don't remove my current 64bit drivers?

**Comment by johnjelinek** [comment]
no

**Comment by mateuspv** [comment]
@johnjelinek oks, thanks for reply.

**Comment by skoam** [comment]
This issue still exists and it can be fixed by installing the packages the terminal prompt asks for, but I would like to remind that this makes installing steam on ubuntu (or elementary OS), which are both systems that promise some kind of a good beginners experience, really hard.

**Comment by plazmax** [comment]
@skoam too many removeable packages fır libglapi-mesa check this :
```
 sudo apt-get install -s libglapi-mesa                                                           ⏎
[sudo] password for plazma: 
Paket listeleri okunuyor... Bitti
Bağımlılık ağacı oluşturuluyor       
Durum bilgisi okunuyor... Bitti      
Aşağıdaki ek paketler de kurulacak:
  libegl1-mesa libgbm1 libgl1-mesa-dri libgl1-mesa-dri:i386 libgl1-mesa-glx
  libgl1-mesa-glx:i386 libglamor0 libglapi-mesa:i386 libgles1-mesa
  libgles2-mesa libllvm3.6 libllvm3.6:i386 libspice-server1 xserver-xorg
  xserver-xorg-core xserver-xorg-input-evdev xserver-xorg-video-ati
  xserver-xorg-video-cirrus xserver-xorg-video-fbdev
  xserver-xorg-video-glamoregl xserver-xorg-video-intel
  xserver-xorg-video-mach64 xserver-xorg-video-mga
  xserver-xorg-video-modesetting xserver-xorg-video-neomagic
  xserver-xorg-video-nouveau xserver-xorg-video-openchrome
  xserver-xorg-video-qxl xserver-xorg-video-r128 xserver-xorg-video-radeon
  xserver-xorg-video-s3 xserver-xorg-video-savage
  xserver-xorg-video-siliconmotion xserver-xorg-video-sis
  xserver-xorg-video-sisusb xserver-xorg-video-tdfx xserver-xorg-video-trident
  xserver-xorg-video-vesa
Önerilen paketler:
  xfonts-100dpi xfonts-75dpi firmware-linux
Aşağıdaki paketler KALDIRILACAK:
  libegl1-mesa-drivers-lts-utopic libegl1-mesa-lts-utopic libgbm1-lts-utopic
  libgl1-mesa-dri-lts-utopic libgl1-mesa-dri-lts-utopic:i386
  libgl1-mesa-glx-lts-utopic libgl1-mesa-glx-lts-utopic:i386
  libglapi-mesa-lts-utopic libglapi-mesa-lts-utopic:i386
  libgles1-mesa-lts-utopic libgles2-mesa-lts-utopic libopenvg1-mesa-lts-utopic
  libwayland-egl1-mesa-lts-utopic libxatracker2-lts-utopic
  xserver-xorg-core-lts-utopic xserver-xorg-input-all-lts-utopic
  xserver-xorg-input-evdev-lts-utopic xserver-xorg-input-mouse-lts-utopic
  xserver-xorg-input-synaptics-lts-utopic
  xserver-xorg-input-vmmouse-lts-utopic xserver-xorg-input-wacom-lts-utopic
  xserver-xorg-lts-utopic xserver-xorg-video-all-lts-utopic
  xserver-xorg-video-ati-lts-utopic xserver-xorg-video-cirrus-lts-utopic
  xserver-xorg-video-fbdev-lts-utopic xserver-xorg-video-intel-lts-utopic
  xserver-xorg-video-mach64-lts-utopic xserver-xorg-video-mga-lts-utopic
  xserver-xorg-video-modesetting-lts-utopic
  xserver-xorg-video-neomagic-lts-utopic xserver-xorg-video-nouveau-lts-utopic
  xserver-xorg-video-openchrome-lts-utopic xserver-xorg-video-r128-lts-utopic
  xserver-xorg-video-radeon-lts-utopic xserver-xorg-video-savage-lts-utopic
  xserver-xorg-video-siliconmotion-lts-utopic
  xserver-xorg-video-sisusb-lts-utopic xserver-xorg-video-tdfx-lts-utopic
  xserver-xorg-video-trident-lts-utopic xserver-xorg-video-vesa-lts-utopic
  xserver-xorg-video-vmware-lts-utopic
Aşağıdaki YENİ paketler kurulacak:
  libegl1-mesa libgbm1 libgl1-mesa-dri libgl1-mesa-dri:i386 libgl1-mesa-glx
  libgl1-mesa-glx:i386 libglamor0 libglapi-mesa libglapi-mesa:i386
  libgles1-mesa libgles2-mesa libllvm3.6 libllvm3.6:i386 libspice-server1
  xserver-xorg xserver-xorg-core xserver-xorg-input-evdev
  xserver-xorg-video-ati xserver-xorg-video-cirrus xserver-xorg-video-fbdev
  xserver-xorg-video-glamoregl xserver-xorg-video-intel
  xserver-xorg-video-mach64 xserver-xorg-video-mga
  xserver-xorg-video-modesetting xserver-xorg-video-neomagic
  xserver-xorg-video-nouveau xserver-xorg-video-openchrome
  xserver-xorg-video-qxl xserver-xorg-video-r128 xserver-xorg-video-radeon
  xserver-xorg-video-s3 xserver-xorg-video-savage
  xserver-xorg-video-siliconmotion xserver-xorg-video-sis
  xserver-xorg-video-sisusb xserver-xorg-video-tdfx xserver-xorg-video-trident
  xserver-xorg-video-vesa
0 paket yükseltilecek, 39 yeni paket kurulacak, 42 paket kaldırılacak ve 0 paket yükseltilmeyecek.
Remv libegl1-mesa-drivers-lts-utopic [10.3.2-0ubuntu1~trusty2]
Remv libwayland-egl1-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2]
Remv xserver-xorg-video-vmware-lts-utopic [1:13.0.2-3ubuntu1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-vesa-lts-utopic [1:2.3.3-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-trident-lts-utopic [1:1.3.6-0ubuntu6~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-tdfx-lts-utopic [1:1.4.5-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-sisusb-lts-utopic [1:0.9.6-2build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-siliconmotion-lts-utopic [1:1.7.7-2build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-savage-lts-utopic [1:2.3.7-2ubuntu3~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-ati-lts-utopic [1:7.4.0-2ubuntu2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-radeon-lts-utopic [1:7.4.0-2ubuntu2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-r128-lts-utopic [6.9.2-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-openchrome-lts-utopic [1:0.3.3-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-nouveau-lts-utopic [1:1.0.11-1ubuntu2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-neomagic-lts-utopic [1:1.2.8-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-modesetting-lts-utopic [0.9.0-1build1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-mga-lts-utopic [1:1.6.3-2build1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-mach64-lts-utopic [6.9.4-2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-intel-lts-utopic [2:2.99.914-1~exp1ubuntu4.2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-fbdev-lts-utopic [1:0.4.4-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-cirrus-lts-utopic [1:1.5.2-2build1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-all-lts-utopic [1:7.7+7ubuntu2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-wacom-lts-utopic [1:0.25.0-0ubuntu1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-vmmouse-lts-utopic [1:13.0.0-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-synaptics-lts-utopic [1.8.1-1ubuntu1~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-mouse-lts-utopic [1:1.9.0-1build2~trusty1] [xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-input-evdev-lts-utopic [1:2.9.0-1ubuntu2~trusty1] [xserver-xorg-lts-utopic:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-core-lts-utopic [2:1.16.0-1ubuntu1.2~trusty2] [xserver-xorg-lts-utopic:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libxatracker2-lts-utopic [10.3.2-0ubuntu1~trusty2] [xserver-xorg-lts-utopic:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libopenvg1-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2] [xserver-xorg-lts-utopic:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgles2-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2] [xserver-xorg-lts-utopic:amd64 xserver-xorg-video-all-lts-utopic:amd64 gstreamer1.0-plugins-bad:amd64 vlc:amd64 ]
Remv xserver-xorg-lts-utopic [1:7.7+7ubuntu2~trusty1] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 gstreamer1.0-plugins-bad:amd64 vlc:amd64 ]
Inst libgles2-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgles1-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 vlc:amd64 ]
Inst libgles1-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgl1-mesa-glx-lts-utopic [10.3.2-0ubuntu1~trusty2] [libopencv-core2.4:amd64 mesa-utils:amd64 xorg:amd64 x11-utils:amd64 libwebkitgtk-1.0-0:amd64 glmark2:amd64 vdpau-va-driver:amd64 libreoffice-core:amd64 libvisual-0.4-plugins:amd64 xserver-xorg-video-all-lts-utopic:amd64 simplescreenrecorder-lib:amd64 libwebkitgtk-3.0-0:amd64 openjdk-7-jre:amd64 libopencv-highgui2.4:amd64 libgtkglext1:amd64 vlc:amd64 libglu1-mesa:amd64 libwxgtk2.8-0:amd64 ]
Remv libgl1-mesa-glx-lts-utopic:i386 [10.3.2-0ubuntu1~trusty2] [libopencv-core2.4:amd64 mesa-utils:amd64 xorg:amd64 x11-utils:amd64 libqt4-opengl:i386 libwebkitgtk-1.0-0:amd64 glmark2:amd64 vdpau-va-driver:amd64 libqtwebkit4:i386 libreoffice-core:amd64 libvisual-0.4-plugins:amd64 xserver-xorg-video-all-lts-utopic:amd64 simplescreenrecorder-lib:amd64 simplescreenrecorder-lib:i386 libwebkitgtk-3.0-0:amd64 openjdk-7-jre:amd64 libopencv-highgui2.4:amd64 libgtkglext1:amd64 vlc:amd64 libglu1-mesa:amd64 libglu1-mesa:i386 libwxgtk2.8-0:amd64 ]
Inst libgl1-mesa-glx:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386]) [libopencv-core2.4:amd64 mesa-utils:amd64 xorg:amd64 x11-utils:amd64 libwebkitgtk-1.0-0:amd64 glmark2:amd64 vdpau-va-driver:amd64 libreoffice-core:amd64 libvisual-0.4-plugins:amd64 xserver-xorg-video-all-lts-utopic:amd64 simplescreenrecorder-lib:amd64 libwebkitgtk-3.0-0:amd64 openjdk-7-jre:amd64 libopencv-highgui2.4:amd64 libgtkglext1:amd64 vlc:amd64 libglu1-mesa:amd64 libwxgtk2.8-0:amd64 ]
Inst libgl1-mesa-glx (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libglapi-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libegl1-mesa-lts-utopic [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 gstreamer1.0-plugins-bad:amd64 vlc:amd64 libgstreamer-plugins-bad1.0-0:amd64 ]
Inst libegl1-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgbm1-lts-utopic [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgl1-mesa-dri-lts-utopic:i386 [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libgl1-mesa-dri-lts-utopic [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Inst libgl1-mesa-dri (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv libglapi-mesa-lts-utopic:i386 [10.3.2-0ubuntu1~trusty2] [xorg:amd64 xserver-xorg-video-all-lts-utopic:amd64 ]
Remv xserver-xorg-video-all-lts-utopic [1:7.7+7ubuntu2~trusty1] [xorg:amd64 ]
Inst xserver-xorg (1:7.7+1ubuntu8.1 Ubuntu:14.04/trusty-updates [amd64]) []
Inst libllvm3.6 (1:3.6-2ubuntu1~trusty1 Ubuntu:14.04/trusty-updates [amd64]) []
Inst libglapi-mesa:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386]) []
Inst libllvm3.6:i386 (1:3.6-2ubuntu1~trusty1 Ubuntu:14.04/trusty-updates [i386]) []
Inst libgl1-mesa-dri:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386]) []
Inst libglapi-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-core (2:1.15.1-0ubuntu2.7 Ubuntu:14.04/trusty-updates [amd64]) []
Inst libglamor0 (0.6.0+git20140801.347ef4f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-radeon (1:7.4.99+git20140806.fbf575cb-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-nouveau (1:1.0.11+git20141030.3fb97d78-0ubuntu0sarvatt~trusty2 xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-intel (2:2.99.917+git20150528.fb1643f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst libgbm1 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-glamoregl (0.6.0+git20140801.347ef4f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-r128 (6.9.2-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-mach64 (6.9.4-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-ati (1:7.4.99+git20140806.fbf575cb-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-sisusb (1:0.9.6+git20140806.293d0902-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-trident (1:1.3.6+git20140806.562c38ca-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-neomagic (1:1.2.8+git20140806.74a9a343-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64]) []
Inst xserver-xorg-video-vesa (1:2.3.3-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-tdfx (1:1.4.5-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-sis (1:0.10.7-0ubuntu6 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-siliconmotion (1:1.7.7-2build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-savage (1:2.3.7-2ubuntu2 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-s3 (1:0.6.5-0ubuntu4 Ubuntu:14.04/trusty [amd64]) []
Inst libspice-server1 (0.12.4-0nocelt2ubuntu1 Ubuntu:14.04/trusty-updates [amd64]) []
Inst xserver-xorg-video-qxl (0.1.1-0ubuntu3 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-openchrome (1:0.3.3-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-modesetting (0.8.1-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-mga (1:1.6.3-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-fbdev (1:0.4.4-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-video-cirrus (1:1.5.2-1build1 Ubuntu:14.04/trusty [amd64]) []
Inst xserver-xorg-input-evdev (1:2.8.2-1ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf libglapi-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libglapi-mesa:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386])
Conf libgles2-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libgles1-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libllvm3.6:i386 (1:3.6-2ubuntu1~trusty1 Ubuntu:14.04/trusty-updates [i386])
Conf libllvm3.6 (1:3.6-2ubuntu1~trusty1 Ubuntu:14.04/trusty-updates [amd64])
Conf libgl1-mesa-dri:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386])
Conf libgl1-mesa-dri (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libgl1-mesa-glx:i386 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [i386])
Conf libgl1-mesa-glx (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libgbm1 (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf libegl1-mesa (10.6.0~git20150528+10.6.ffd133bd-0ubuntu0ricotz~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-core (2:1.15.1-0ubuntu2.7 Ubuntu:14.04/trusty-updates [amd64])
Conf libglamor0 (0.6.0+git20140801.347ef4f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-radeon (1:7.4.99+git20140806.fbf575cb-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-nouveau (1:1.0.11+git20141030.3fb97d78-0ubuntu0sarvatt~trusty2 xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-intel (2:2.99.917+git20150528.fb1643f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-glamoregl (0.6.0+git20140801.347ef4f0-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-r128 (6.9.2-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-mach64 (6.9.4-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-ati (1:7.4.99+git20140806.fbf575cb-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-sisusb (1:0.9.6+git20140806.293d0902-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-trident (1:1.3.6+git20140806.562c38ca-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-neomagic (1:1.2.8+git20140806.74a9a343-0ubuntu0sarvatt~trusty xorg-edgers fresh X crack:14.04/trusty [amd64])
Conf xserver-xorg-video-vesa (1:2.3.3-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-tdfx (1:1.4.5-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-sis (1:0.10.7-0ubuntu6 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-siliconmotion (1:1.7.7-2build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-savage (1:2.3.7-2ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-s3 (1:0.6.5-0ubuntu4 Ubuntu:14.04/trusty [amd64])
Conf libspice-server1 (0.12.4-0nocelt2ubuntu1 Ubuntu:14.04/trusty-updates [amd64])
Conf xserver-xorg-video-qxl (0.1.1-0ubuntu3 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-openchrome (1:0.3.3-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-modesetting (0.8.1-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-mga (1:1.6.3-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-fbdev (1:0.4.4-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-video-cirrus (1:1.5.2-1build1 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg-input-evdev (1:2.8.2-1ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf xserver-xorg (1:7.7+1ubuntu8.1 Ubuntu:14.04/trusty-updates [amd64])
```

**Comment by skoam** [comment]
Yes, it's ridiculous. I wonder why this does happen, didn't the steam installer work perfectly before? What changed?

**Comment by lavacano201014** [comment]
As a workaround, you can comment out lines 248 and 252 (put a # character in the beginning) in ~/.steam/root/bin_steamdeps.py. Steam will of course complain about the dependencies every time it installs/launches, but will continue if you've actually satisfied them. Also, if at any point it lists something you don't actually have installed, you can install it.

It's probably Canonical being idiots again.

**Comment by gogromat** [comment]
Made it to work on debian jessie (xfce4) this way:
[I followed instructions from here:](https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit/454254#454254)
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
```
After that Steam works.
Without `dpkg --add-architecture i386` these packages `:i386` are not found.

**Comment by vorburger** [comment]
If you have this on Ubuntu 14.04 (LTS), here's how to fix it:

    sudo apt-get install libgl1-mesa-dri-lts-utopic:i386 libgl1-mesa-glx-lts-utopic:i386

This will install what's needed without downgrading X.

**Comment by roysc2** [comment]
@vorburger sorry to bump this again, but that doesn't work for me. On xenial, I do 

`sudo apt-get install libgl1-mesa-dri-lts-utopic:i386 libgl1-mesa-glx-lts-utopic:i386`
but get
```
The following packages have unmet dependencies:
 libgl1-mesa-dri-lts-utopic:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
 libgl1-mesa-glx-lts-utopic:i386 : Depends: libgl1-mesa-glx:i386 but it is not going to be installed
```

What keeps causing this issue in different packages?

**Comment by vorburger** [comment]
@roysc2 I've no idea really.. have not used this in a LONG time.. perhaps this helps - best of luck:

`sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386`

**Comment by sbhaaf** [comment]
I am dealing with the same issue in 16.04, as @roysc commented.

```
$ sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The most common solution for 14.04 doesn't work:
```
$ sudo apt-get install libgl1-mesa-dri-lts-utopic:i386 libgl1-mesa-glx-lts-utopic:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri-lts-utopic:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
 libgl1-mesa-glx-lts-utopic:i386 : Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

nor the suggestion by @vorburger:

```
$ sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gkbd-capplet : Depends: libgnomekbd8 (>= 3.6.0) but it is not going to be installed
 ibus : Depends: gir1.2-gtk-3.0 (>= 3.8.5) but it is not going to be installed
        Depends: adwaita-icon-theme but it is not going to be installed
 libcheese-gtk25 : Depends: libcogl20 (>= 1.17.4) but it is not going to be installed
                   Depends: gstreamer1.0-clutter-3.0 but it is not going to be installed
 libcheese8 : Depends: libclutter-gst-3.0-0 (>= 3.0.4) but it is not going to be installed
 libclutter-1.0-0 : Depends: libcogl-pango20 (>= 1.17.4) but it is not going to be installed
                    Depends: libcogl-path20 (>= 1.17.4) but it is not going to be installed
                    Depends: libcogl20 (>= 1.21.2) but it is not going to be installed
 libclutter-gtk-1.0-0 : Depends: libcogl20 (>= 1.17.4) but it is not going to be installed
 libgl1-mesa-dri:i386 : Depends: libdrm-amdgpu1:i386 (>= 2.4.63) but it is not going to be installed
                        Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.66) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
 libgl1-mesa-glx : Depends: libglapi-mesa (= 17.0.7-0ubuntu0.16.04.1) but it is not going to be installed
                   Depends: libgl1-mesa-dri but it is not going to be installed
                   Breaks: libgl1-mesa-glx:i386 (!= 17.0.7-0ubuntu0.16.04.1) but 11.2.0-1ubuntu2 is to be installed
 libgl1-mesa-glx:i386 : Depends: libdrm2:i386 (>= 2.3.1) but it is not going to be installed
                        Breaks: libgl1-mesa-glx (!= 11.2.0-1ubuntu2) but 17.0.7-0ubuntu0.16.04.1 is to be installed
 libgtk-3-0 : Depends: libgtk-3-common (>= 3.18.9-1ubuntu3.3) but it is not going to be installed
              Depends: libwayland-egl1-mesa (>= 10.0.2) but it is not going to be installed or
                       libwayland-egl1
 libgtk-3-bin : Depends: libgtk-3-common (>= 3.18.9-1ubuntu3.3) but it is not going to be installed
 libqt5gui5 : Depends: libegl1-mesa (>= 7.8.1) but it is not going to be installed or
                       libegl1-x11
              Recommends: libqt5svg5 but it is not going to be installed
 libwebkit2gtk-4.0-37 : Depends: libegl1-mesa (>= 7.8.1) but it is not going to be installed or
                                 libegl1-x11
                        Depends: libwayland-egl1-mesa (>= 10.0.2) but it is not going to be installed or
                                 libwayland-egl1
                        Recommends: libwebkit2gtk-4.0-37-gtk2 but it is not going to be installed
 system-config-printer-gnome : Depends: adwaita-icon-theme but it is not going to be installed
                               Depends: gir1.2-gtk-3.0 but it is not going to be installed
 unity-asset-pool : Depends: adwaita-icon-theme but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Has anybody found a solution for 16.04?

**Comment by sbhaaf** [comment]
Okay, I've made some progress, but am still having issues. What I've tried:

First, I installed from the .deb. After installation I run `steam` and get a similar output: 
```
Option "-t" is no longer supported in this version of gnome-terminal.
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/v4gil/.local/share/Steam/steam.sh: line 823: /home/v4gil/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Error: You are missing the following 32-bit libraries, and Steam may not run:
libstdc++.so.6

/home/v4gil/.local/share/Steam/ubuntu12_32/steam: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

I still could not install `libgl1-mesa-dri:i386` or `libgl1-mesa-glx:i386`, but there was also a graphical error that said:

```
You are missing the following 32-bit libraries, and Steam may not run: libX11.so.6 libstdc++.so.6
```

To install `libX11.so.6` I found [this](https://github.com/nwjs/nw.js/issues/1566) solution to install each of these dependencies:

```
sudo apt-get -y install libx11-6:i386
sudo apt-get -y install libglib2.0-0:i386
sudo apt-get -y install libgtk2.0-0:i386
sudo apt-get -y install libatk1.0-0:i386
sudo apt-get -y install libgdk-pixbuf2.0-0:i386
sudo apt-get -y install libcairo2:i386
sudo apt-get -y install libfreetype6:i386
sudo apt-get -y install libfontconfig1:i386
sudo apt-get -y install libxcomposite1:i386
sudo apt-get -y install libasound2:i386
sudo apt-get -y install libxdamage1:i386
sudo apt-get -y install libxext6:i386
sudo apt-get -y install libxfixes3:i386
sudo apt-get -y install libnss3:i386
sudo apt-get -y install libnspr4:i386
sudo apt-get -y install libgconf-2-4:i386
sudo apt-get -y install libexpat1:i386
sudo apt-get -y install libdbus-1-3:i386
sudo apt-get -y install libudev0:i386
```

Then for ` libstdc++.so.6` I used @jhilmer's solution [here](https://askubuntu.com/questions/409821/libstdc-so-6-cannot-open-shared-object-file-no-such-file-or-directory):

```
apt-get install lib32stdc++6
```

After these fixes, Steam was able to load its updater and download its updates, but now when I run `steam` I still have the original errors, plus two new ones:

```
$ steam
Option "-t" is no longer supported in this version of gnome-terminal.
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
libdrm.so.2
Installing breakpad exception handler for appid(steam)/version(1535576546)
Installing breakpad exception handler for appid(steam)/version(1535576546)
Installing breakpad exception handler for appid(steam)/version(1535576546)

Failed to load steamui.so - dlerror(): libGL.so.1: wrong ELF class: ELFCLASS64
```
With a graphical error telling me I don't have libGL.so.1 or libdrm.so.2. 

TL;DR I couldn't solve the original issues, but going with the .deb installation exposed some more issues that I could solve, only to be faced with more issues.

**Comment by solar-flr** [comment]
So what message do you get when you just install the two missing packages ?

`sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386
`

just add the names of any 'Package ........  needs to be installed' to the above line and keep repeating the extended 'sudo apt-get' command until no new package names appear.

**Comment by jcalfee** [comment]
Just let steam install its own packages on debian:stretch and it worked.  I did see this message:

```
Steam needs to install these additional packages:
Steam needs to install these additional packages: 
        libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
```

After finding this ticket, I'm thinking the steam app installs specific packages maybe in a specific order.  So the message above does not tell the whole story.  So, the suggestion is to make the steam startup more verbose so we can see this information.  If this is easy to do, it will help users with additional information as this part is tricky.

**Comment by rotten** [comment]
I had been running Steam on 18.04 without issues until the most recent patches were applied.  Suddenly we are back to the error described above:

```
The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 (>= 17.3) but it is not going to be installed or
                       libtxc-dxtn0:i386 but it is not installable
              Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
              Recommends: nvidia-driver-libs-i386:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

By chasing the dependencies I end up with this list and error:
```
# apt -f install libgl1:i386 libglx0:i386 libglx-mesa0:i386 libgl1-mesa-dri:i386 libnvidia-ifr1-415:i386 libnvidia-fbc1-415:i386 gvfs-daemons libllvm7:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gvfs-daemons is already the newest version (1.36.1-0ubuntu1.2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libllvm7 : Breaks: libllvm7:i386 (!= 1:7.0.1~svn348686-1~exp1~20190113235231.54) but 1:7-3~ubuntu0.18.04.1 is to be installed
 libllvm7:i386 : Breaks: libllvm7 (!= 1:7-3~ubuntu0.18.04.1) but 1:7.0.1~svn348686-1~exp1~20190113235231.54 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

```

... which is a circular, unresolvable, error ...

It appears that the llvm project no longer supports i386 architecture on Ubuntu.

**Comment by kisak-valve** [comment]
Hello @rotten sounds like you're trying to have 2 different versions of llvm7 installed at the same time. The 32 bit and 64 bit variants need to match each other. `7-3~ubuntu0.18.04.1` would be from the recent graphics refresh for Ubuntu 18.04.2.

`apt policy libllvm7 libllvm7:i386` should give you a hint where these packages are coming from.

Regardless, your issue is a general distro packaging issue and unrelated to Steam.

**Comment by rotten** [comment]
I was using the llvm.org PPA to get llvm.  I think this was because I needed llvm7 before it was available in Ubuntu.  The llvm from llvm.org no longer supports the i386 architecture for Ubuntu.  It says it very clearly in the comments for the apt file.  I don't know if that means they'll stop supporting it altogether, or if that is a temporary thing.  I wasn't able to find a mailing list or forum discussion on the topic.  (Maybe it is in a Jira or something somewhere?)  If they are stopping support for it forever, that could be a problem for Steam (since it only works on Linux with the i386 architecture).

I upgraded to Ubuntu 18.10, and then pulled the custom PPA and removed the llvm-7 packages.  This was tricky because there were over 300 dependencies on llvm-7.  Since most of them were UI based, I did it by connecting remotely to the desktop.  I save a list of those dependencies before removing llvm.

Then I installed the Ubuntu 18.10 stock llvm, which was version 7 like I needed (just a few minor point releases older).  I re-installed all of the other packages that were dropped when I pulled out the more bleeding edge llvm-7, and everything worked fine.

**Comment by codingthat** [comment]
> So what message do you get when you just install the two missing packages ?
> 
> `sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 `
> 
> just add the names of any 'Package ........ needs to be installed' to the above line and keep repeating the extended 'sudo apt-get' command until no new package names appear.

This seems like bad advice, at least on my system.  Got as far as this before it worked: ` sudo apt-get install libglvnd0:i386 libglx0:i386 libgl1:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 ` at which point the `The following packages will be REMOVED:` list included a crazy amount of things, including audacity, ffmpeg, libqtgui5, mate-screensaver, mintsystem, virtualbox-6.0, vlc, yelp, zenity, and zoom.

**Comment by BloodyMess** [comment]
> 
> This seems like bad advice, at least on my system. Got as far as this before it worked: `sudo apt-get install libglvnd0:i386 libglx0:i386 libgl1:i386 libgl1-mesa-dri:i386 libgl1-mesa-glx:i386` at which point the `The following packages will be REMOVED:` list included a crazy amount of things, including audacity, ffmpeg, libqtgui5, mate-screensaver, mintsystem, virtualbox-6.0, vlc, yelp, zenity, and zoom.

I'm having pretty much the same problem right now. I installed LLVM 10 via the LLVM apt repository and Steam got removed. Then when I tried to roll back to an earlier LLVM, it tried to remove pretty much everything I've ever installed (applications libraries etc). And I can't even reinstall Steam.

I posted a [question on the elementaryOS stackexchange](https://elementaryos.stackexchange.com/questions/24810/apt-get-is-trying-to-uninstall-everything-ive-ever-installed). It has the commands I used and the output from the apt tools.

Enough users of Steam for linux are running into this problem that Steam/Valve needs to do something to really help these users. Investigating the problem, explaining it and how to avoid it, making a how-to to fix the problem, etc... Maybe even coming up with a change to the "apt" tools so that anything that was installed explicitly by the user (or that is a standard part of the system/distro) is prevented from being removed automatically/implicitly/indirectly (ie: unless the user explicitly removes it).

More and more people are leaving windows and using linux for gaming instead. And more and more will be running into these sort of problems, especially those who want to try getting into game development and try to install the latest compiler to build a game. Valve shouldn't be expecting their gaming customers to become linux system admins just to play or make games.

**Comment by BloodyMess** [comment]
I finally got it fixed.

I had to remove the apt.llvm.org repository from the sources.list. Then I was able to use the Force Version command in Synaptic to switch over to using LLVM builds from the kisak PPA (which still provides i386 builds of LLVM). That enabled me to reinstall steam, because it could finally get those 32-bit i386 library builds again.

Steam/Valve *really* needs to, at the very least, post prominent warnings (pinned forum topics, first-run notices in the app, etc...) about this kind of situation along with suggestions and guides for ways to avoid or fix the problem. Steam on Linux users (especially those new to linux) are highly likely to run into this sort of problem. Steam for linux users have been running into this problem for seven years now. It deserves to be addressed prominently.

**Comment by hsandt** [comment]
I removed apt.llvm.org from the Additional Repositories (/etc/apt/sources.list.d/additional-repositories.list), but I still get this when trying to install the dependencies asked by Steam on start (only when using Nvidia, switching to Intel graphics driver is fine):

$ sagi libgl1-mesa-dri:i386
> ...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

> The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libllvm10:i386 (>= 1:9~svn298832-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Trying to install the other dependency, libgl1 leads to other unmet dependencies in chain: libglx0:i386 > libglx-mesa0:i386 > libgl1-mesa-dri:i386 closing the circle.

Trying to install libllvm10:i386 leads to an impossible constraint with incompatible versions:

> The following packages have unmet dependencies:
 gvfs : Depends: gvfs-daemons (>= 1.36.1-0ubuntu1.3.3)
        Depends: gvfs-daemons (< 1.36.1-0ubuntu1.3.3.1~)

I wanted to get more info using Synaptic GUI but for some reason it doesn't even show i386 packages anymore...

**Comment by hsandt** [comment]
OK, I fixed the issue but I had to switch completely to default repositories. Removing apt.llvm.org ppa was not enough, I just continued using kisak ppa and those were preventing me from installing i386 packages along the equivalent in amd64.

First, try to follow Braiam's answer on https://askubuntu.com/questions/402066/steam-runs-but-needs-libgl1-mesa-drii386-and-libgl1-mesa-glxi386/402958#402958 and try to downgrade just libgl1-mesa-dri and libgl1-mesa-glx (and possibly disable PPA to avoid other further issues if you don't need them). Something like:

```shell
$ sudo apt install libgl1-mesa-dri:i386=19.2.8-0ubuntu0~18.04.3
```

I actually wish I did that, actually I purged everything with a blind `sudo ppa-purge ppa:kisak/kisak-mesa` which removed all related packages, including important libs and apps loosely related to kisak packages. But even then I had `libllvm9` still installed from kisak, and `libgl1-mesa-dri` depending on it (in my previous message it was libllvm10; after uninstalling the llvm-10 toolchain completely, it simply switched to llvm9...).

```shell
$ acp libllvm9
```
> libllvm9:
  Installed: 1:9.0.1-2\~kisak\~b
  Candidate: 1:9.0.1-2\~kisak\~b
  Version table:
 *** 1:9.0.1-2\~kisak\~b 100
		100 /var/lib/dpkg/status
	 1:9-2~ubuntu18.04.2 500
		500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
		500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages

So I had to downgrade this one directly:

```
$ sagi libllvm9=1:9-2~ubuntu18.04.2
```
> Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  libllvm9
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 5 not upgraded.
Need to get 14.8 MB of archives.
After this operation, 30.7 kB disk space will be freed.
Do you want to continue? [Y/n] y
```

From here I could install libgl1-mesa-dri:i386 without issue, and Steam worked again.

**Comment by vuurvoske** [comment]
Hello,
I had this problem on Ubuntu 20.04 and to cut a long story short i fixed it by doing:

`sudo apt install libqt5gui5-gles (rather than libqt5gui5)`
and
`sudo apt install dxvk`

**Comment by AND2797** [comment]
8 years on and we are still having this problem... how do i fix this on 20.04?

**Comment by fabriciorsf** [comment]
Steam should have already abandoned the i386 architecture.
I have this problem with ubuntu 18.04 and I still can't resolve it.

**Comment by hsandt** [comment]
Apparently it's not for the editor but for the 32-bit games, and there are many.
Just to be sure I tried to run Momodora from the command line by directly loading the right libraries, but since I needed i386 libs anyway, I couldn't.

In doubt, you can download a 32-bit app using OpenGL (outside Steam) and try to run it directly.

**Comment by kisak-valve** [comment]
Hello @AND2797, the issue that was being tracked here was resolved in 2013. Since then, the issues that have been mentioned are unrelated.

In general, Steam needs the host system to provide 32 bit libc.so.6 and a healthy 32 bit OpenGL render stack (in addition to the 64 bit libraries which are always installed on all major distributions).

If apt is refusing to install these packages, then it's a distribution issue that needs to be evaluated on a per-case basis. The most common situation with Ubuntu is that a newer version of a 64 bit package got installed, but the package manager doesn't have the exact same version available for 32 bit. Debian's multiarch implementation requires that all 64 bit and 32 bit variants of a package have the exact same version. Apt won't automatically pull in an older 64 bit version of a package than what's installed in order to allow the 32 bit variant to proceed and simply tells the user it's not going to happen.

This isn't a Steam issue and should be resolved by you with help from the distro's community support.

---

In general, you need to unblock the package manager to proceed.

`libgl1-mesa-dri:i386 : Depends: libllvm10:i386 (>= 1:9~svn298832-1~) but it is not going to be installed` tells us that apt is refusing to install 32 bit libllvm10. Use something like `apt policy libllvm10 libllvm10:i386` to see both variants of what's available and what's installed, then get the installed variants to match before trying again.
