### ISSUE TITLE
No sound in certain games when started from Steam.

### ISSUE THREAD

**Issue by FretWrecker** [ValveSoftware/steam-for-linux#2968]
A few days ago I started "Don't Starve" and didn't hear any sound. I tried other games and found the same behaviour but only in some of them.

Sound works:
- Half-Life: Source
- L4D2
- Serious Sam 3: BFE
- Portal

Sound doesn't work:
- Bastion
- Don't Starve
- FORCED
- Receiver
- Sparkle 2 Evo
- X3: Terran Conflict

When I start "Sparkle 2 Evo" and "Bastion" outside of Steam from the command line audio works fine. Starting steam with `STEAM_RUNTIME=0` fails due to a missing 32-bit library (and no further information on what particular library).

I didn't encounter any sound problems on my system outside of Steam since then.
### System Information

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x43
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11404000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD JUNIPER

    Driver Version:  3.0 Mesa 9.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x68ba
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 14.13" x 11.30"  (18.07" diag)
                                            35.9cm x 28.7cm  (45.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: CA0106

Memory:
    RAM:  2509 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  416295 Mb
    Largest Free Hard Disk Block:  97023 Mb

Installed software:

Recent Failure Reports:
    Tue Nov  5 20:41:55 2013 GMT: file ''/tmp/dumps/crash_20131105213728_14.dmp'', upload no: ''Failure when receiving data from the peer''
    Tue Nov  5 21:01:33 2013 GMT: file ''/tmp/dumps/assert_20131105220104_19.dmp'', upload yes: ''CrashID=bp-2f85b7ca-6561-4b65-a4c8-4816a2131105''
```

**Comment by llbraughler** [comment]
Despite being closed and supposedly fixed, some people are still encountering issues. Most recently I encountered this issue with Arch Linux and Star Conflict. The fix was to install ALSA 32-bit libs.

``pacman -Syu lib32-alsa-lib lib32-alsa-plugins``

**Comment by Tele42** [comment]
@llbraughler if that is the what needs to be done to get things working, then this is fixed on valve's end, the package maintainers need to be contacted to make that adjustment to the distro-specific packaging.

**Comment by qguv** [comment]
I had installed `lib32-alsa-lib` and `lib32-alsa-plugins` but was still having issues under Archlinux. The 8 March 2016 update to the steam client fixed this. From the changelog:

> Linux: Updated ALSA libraries in the Steam Runtime to prevent compatibility issues with newer distributions

Steam is updated outside the package manager in Arch, so to force an update, you'll need to boot Steam up and choose "File" &rarr; "Check for Steam Client Updates&hellip;".

**Comment by mlibre** [comment]
I fix my sound problem in debian in this way:
sudo apt-get install libpulse0:i386

**Comment by jrocketfingers** [comment]
I've forgotten to install `lib32-libpulse` on Arch, FWIW.
