### ISSUE TITLE
[Beta] Keyboard problems in store.

### ISSUE THREAD

**Issue by kazie** [ValveSoftware/steam-for-linux#3811]
In current beta version of the Steam Client for Linux,
Most of my keyboard interaction in typing (for example, the search field) 
has lost many important keystrokes.
Example: using erase (backspace), arrow keys, Delete etc.

Downgrading to current Stable does not have this problem.
This probably has something with the upgrade of the web engine?
(Just updated, after patch got this problem)

**Comment by Plaque-fcc** [comment]
Also, general «.» (period) doesn't work. NumPad's one works.

And frequently pages like Reply Notifications doesn't stretch to fit
the window.

Ubuntu x86 14.10. Gonna also test against 15.04 soon.

**Comment by Plaque-fcc** [comment]
Oh, also arrow keys are broken.

**Comment by sizeofbool** [comment]
I second to this bug. Backspace and Delete keys doesn't work if I use them in Community Discussions\Forums inside Steam Client on Linux.

**Comment by Plaque-fcc** [comment]
Broken Steam Store page sample: http://imgur.com/1JkG1YA

Hope it's not what you intended to implement.

**Comment by rkfg** [comment]
On the bright side, #3513 seems to be fixed. I suspect these issues are interconnected somehow, like, they decreased the number of key responses by one and as such Enter is now responds one time while other non-character keys respond zero times. Just speculating.

**Comment by Plaque-fcc** [comment]
Surprisingly, #3513 doesn't get reproduced any more.
Home/End
PgDn/PgUp
./Del/BS
←^↓→

All they don't work.

**Comment by ramma** [comment]
This may be related to the issue I've found of keys being passed to the desktop [bug #1740](https://github.com/ValveSoftware/Dota-2/issues/1740). For instance, pressing alt or the windows key will minimize both Dota 2 and CS:GO now. Previously those keys could be bound and used in game, with alt being essential in Dota.

**Comment by MrSchism** [comment]
This issue does not occur in BPM or chat.

**Comment by kwahoo2** [comment]
I can confirm the issue.
```
Informacje o procesorze:
    Dostawca: GenuineIntel
    Rodzina CPU: 0x6
    Model CPU: 0x3a
    Stepping CPU: 0x9
    Typ CPU: 0x0
    Częstotliwość: 3200 MHz
    8 rdzenie logiczne
    4 rdzenie fizyczne
    HyperThreading:  Obsługiwane
    FCMOV:  Obsługiwane
    SSE2:  Obsługiwane
    SSE3:  Obsługiwane
    SSSE3:  Obsługiwane
    SSE4a:  Nieobsługiwane
    SSE41:  Obsługiwane
    SSE42:  Obsługiwane
    
Informacje o sieci:
    Szybkość sieci:  
    
Wersja systemu operacyjnego:
    Ubuntu 15.04 (64-bitowy)
    Nazwa kernela: Linux
    Wersja kernela: 3.19.0-16-generic
    Dostawca serwera X: The X.Org Foundation
    Wydanie serwera X: 11701000
    Menedżer okien X: KWin
    Wersja biblioteki Steam: steam-runtime-release_2015-01-06
    
Karta graficzna:
    Sterownik: NVIDIA Corporation GeForce GT 645M/PCIe/SSE2

    Wersja sterownika: 4.5.0 NVIDIA 346.59
    Wersja OpenGL: 4.5
    Głębia kolorów pulpitu: 24 bitów na piksel
    Częstotliwość odświeżania monitora: 59 Hz
    Ident. producenta: 0x10de
    ID urządzenia: 0xfd9
    Liczba monitorów: 1
    Liczba logicznych układów graficznych:  2
    Rozdzielczość głównego ekranu:  1366 x 768
    Rozdzielczość pulpitu: 1366 x 768
    Rozmiar głównego ekranu: 13,54" x 7,64" (15,51" diag)
34,4cm x 19,4cm (39,4cm diag)
    Ilość pamięci VRAM: 2048 MB
    
Karta dźwiękowa:
    Dźwięk: Intel PantherPoint HDMI
    
Pamięć:
    RAM: 7845 MB
    
Dodatki:
    Język interfejsu: Polski
    JĘZYK: pl_PL.UTF-8
    Mikrofon:  Not set
    Dostępne miejsce na twardym dysku: 446350 MB
    Największy wolny blok na twardym dysku: 20846 MB
    
Zainstalowane programy:
    
Ostatnie raporty niepowodzeń:
    Wed May  6 20:43:07 2015 GMT: file ''/tmp/dumps/crash_20150506224156_10.dmp'', upload yes: ''CrashID=bp-3d8d2d13-671f-45e4-b1a3-68c052150506''
    Wed May  6 20:44:15 2015 GMT: file ''/tmp/dumps/crash_20150506224307_5.dmp'', upload yes: ''CrashID=bp-53dc50ad-3294-423f-b9fb-cbd332150506''
    

```

**Comment by Plaque-fcc** [comment]
Yeah, same thing.

But… is this thing so rare that almost nobody noticed such behaviour?
Where's the word from devs? Are we doomed?

**Comment by MrSchism** [comment]
The word from devs is the "reviewed" tab.  They know it's an issue and will resolve it when they can.

**Comment by Plaque-fcc** [comment]
Oh, I'm from email, so I didn't know that. Thanks!

**Comment by MrSchism** [comment]
New Info: Period functions as backspace.  I found this when I was attempting to make a forum post.

**Comment by MrSchism** [comment]
Additional new info: Not sure if it's related, but right clicking pastes automatically.

**Comment by sizeofbool** [comment]
All problems with keyboard keys in Steam Community Discussions are fixed in latest Beta.(steam-runtime-release_2015-01-06)

**Comment by ramma** [comment]
The issue I reported in [bug #1740](https://github.com/ValveSoftware/Dota-2/issues/1740) is still happening after the update. So I suspect it wasn't related as I original thought.

**Comment by MrSchism** [comment]
Confirmed as fixed in latest beta on my end.  @kazie can you confirm this fixes the issue for you?

**Comment by Plaque-fcc** [comment]
I can confirm it on my side. Thanks!

**Comment by Sector14** [comment]
The page up/down home/end and arrow keys still don't work on the library page (and anywhere else with a scroll bar such as friends list). Running Debian Jessie and the latest steam beta. Those keys work fine in the non-beta version.

**Comment by MrSchism** [comment]
On my Mint 17.1 system running latest Steam beta, I cannot replicate those results, @Sector14.  

I have arrow key functionality everywhere I've always had it.  I don't have page up/down/home/end functionality anywhere I've not had it before.

**Comment by Sector14** [comment]
Ignore my prior post, I've updated laptop to the beta and re-tested and the library view does scroll with the arrow keys.

Looks like the beta also fixes the quirk where the library list doesn't regain focus when you switch back to the game info window from the friends list.

**Comment by MrSchism** [comment]
Since @kazie hasn't responded, but it seems to be resolved for everyone else, I'm closing this as resolved.
