### ISSUE TITLE
Starting a Docker Container closes Steam

### ISSUE THREAD

**Issue by maaatts** [ValveSoftware/steam-for-linux#4180]
### Short Description

Whenever I start a Docker container, Steam closes with no errors.
### Steps to Reproduce
1. Start Steam
2. Start a Docker container
### System Info

```
~ % cat /etc/os-release 
NAME=Fedora
VERSION="23 (Workstation Edition)"
ID=fedora
VERSION_ID=23
PRETTY_NAME="Fedora 23 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:23"
HOME_URL="https://fedoraproject.org/" [^]
BUG_REPORT_URL="https://bugzilla.redhat.com/" [^]
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=23
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=23
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy [^]
VARIANT="Workstation Edition"
VARIANT_ID=workstation

~ % nvidia-installer -v | grep version
nvidia-installer: version 358.16 (buildmeister@swio-display-x64-rhel04-12)

~ % uname -r
4.2.6-301.fc23.x86_64
```

**Comment by s3than** [comment]
I'm getting the same issue as well.

**Comment by ace13** [comment]
Same issue here as well.

```
$ cat /etc/os-release 
NAME=Sabayon
ID=sabayon
PRETTY_NAME="Sabayon/Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.sabayon.org/"
SUPPORT_URL="http://forum.sabayon.org/"
BUG_REPORT_URL="https://bugs.sabayon.org/"
$ glxinfo
...
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.0-rc2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
...
$ uname -r
4.2.0-sabayon
$ docker --version
Docker version 1.9.0, build 76d6bc9
```

**Comment by minecraft2048** [comment]
It also happens to me
What I did in Docker:
```
feanor@silmarili ~> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
928059a30af8        ubuntu              "bash"              4 minutes ago       Up 1 seconds                            maedhros            
feanor@silmarili ~> docker restart maedhros
maedhros
```
Steam terminal log:
```
feanor@silmarili ~> steam
Running Steam on ubuntu 15.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0124/172612:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
[0124/172612:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160121201049)
Installing breakpad exception handler for appid(steamwebhelper)/version(1453407049)
[0124/172612:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160121201049)
Installing breakpad exception handler for appid(steamwebhelper)/version(1453438201)
Installing breakpad exception handler for appid(steamwebhelper)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)

** (steam:7713): WARNING **: Unknown device type 14

** (steam:7713): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type

** (steam:7713): WARNING **: Unknown device type 14

** (steam:7713): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type
Installing breakpad exception handler for appid(steam)/version(1453438201)

** (steam:7713): WARNING **: Ignoring invalid property 'hidden'

** (steam:7713): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/89 settings: (1) mode

** (steam:7713): WARNING **: Ignoring invalid property 'hidden'

** (steam:7713): WARNING **: Ignoring invalid property 'address-labels'

** (steam:7713): WARNING **: Ignoring invalid property 'address-labels'

** (steam:7713): WARNING **: Ignoring invalid property 'address-labels'

** (steam:7713): WARNING **: Ignoring invalid property 'address-labels'

** (steam:7713): WARNING **: Ignoring invalid property 'hidden'

** (steam:7713): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/89 settings: (1) mode
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442.37 KB
Installing breakpad exception handler for appid(steam)/version(1453438201)
Installing breakpad exception handler for appid(steam)/version(1453438201)
roaming config store loaded successfully - 7335 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1453438201)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1453438201)
ExecCommandLine: ""/home/feanor/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1453438201)
System startup time: 4.71 seconds
Generating new string page texture 188: 256x256, total string texture memory is 704.51 KB
Generating new string page texture 189: 64x256, total string texture memory is 770.05 KB
Generating new string page texture 190: 128x256, total string texture memory is 901.12 KB
Generating new string page texture 191: 32x256, total string texture memory is 933.89 KB
Generating new string page texture 192: 8x256, total string texture memory is 942.08 KB
Generating new string page texture 196: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 197: 128x256, total string texture memory is 1.07 MB
Installing breakpad exception handler for appid(steam)/version(1453438201)
Generating new string page texture 206: 24x256, total string texture memory is 1.10 MB
Running Steam on ubuntu 15.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/feanor/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/feanor/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 212: 16x256, total string texture memory is 1.11 MB

** (steam:7713): WARNING **: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/18: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist


** (steam:7713): WARNING **: Unknown device type 14

** (steam:7713): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type

** (steam:7713): WARNING **: Unknown device type 14

** (steam:7713): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type
assert_20160124172610_1.dmp[8099]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160124172610_1.dmp
/home/feanor/.local/share/Steam/steam.sh: line 756:  7713 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
assert_20160124172610_1.dmp[8099]: Finished uploading minidump (out-of-process): success = yes
assert_20160124172610_1.dmp[8099]: response: CrashID=bp-88554331-267f-4c14-9502-251612160124
assert_20160124172610_1.dmp[8099]: file ''/tmp/dumps/assert_20160124172610_1.dmp'', upload yes: ''CrashID=bp-88554331-267f-4c14-9502-251612160124''
feanor@silmarili ~> 
```

Docker version:
```
feanor@silmarili ~> docker --version
Docker version 1.7.1, build 786b29d
feanor@silmarili ~> 
```

System info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-30-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.96
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0xde9
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 2732 x 768
    Primary Display Size: 12.17" x 6.85"  (13.94" diag)
                                            30.9cm x 17.4cm  (35.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Intel PantherPoint HDMI
    
Memory:
    RAM:  3838 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  156888 Mb
    Largest Free Hard Disk Block:  6739 Mb
    
Installed software:
    
Recent Failure Reports:
    Sun Jan 24 09:42:07 2016 GMT: file ''/tmp/dumps/assert_20160124161553_1.dmp'', upload yes: ''CrashID=bp-d2ea86d1-65d4-4b0d-bd17-b24f02160124''
    Sun Jan 24 10:24:45 2016 GMT: file ''/tmp/dumps/assert_20160124164209_1.dmp'', upload yes: ''CrashID=bp-7681a678-ed92-49bc-8480-935342160124''
    Sun Jan 24 10:26:34 2016 GMT: file ''/tmp/dumps/assert_20160124172610_1.dmp'', upload yes: ''CrashID=bp-88554331-267f-4c14-9502-251612160124''
    
```

**Comment by AgentME** [comment]
I occasionally see Steam close itself when I start up a virtualbox VM.

**Comment by maaatts** [comment]
I think that this is fixed; I'm able to use Docker at the same time as Steam now.

**Comment by boombatower** [comment]
Hehe, good to see this isn't just me. Typically, I get this when doing `docker build` from Dockerfile.

**Comment by matt11235** [comment]
This is still happening with Docker `1.13.1` on Debian Jessie.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
