### ISSUE TITLE
In home streaming won't launch any game...

### ISSUE THREAD

**Issue by ninomegadriver** [ValveSoftware/steam-for-linux#4371]
I have two different machines running ubuntu, one with 12.02 and another with 14.04, both are using the latest original video drivers from Nvidia. And I have two windows 7 PCs. What I'm trying to do is stream games from my windows PCs to my linux PCs.

When I try to start the stream on both linux PC while having for host any of my windows 7 PCs, nothing happens. I can se the "preparing" pop-up, but when it closes, nothing happens. Apparently a new window pops up and closes instantly. On the windows host, the game launches, but on the client, nothing happens.

Trying to debug is being very difficult, because I don't see any error messages on the console, I also don't see any error message on the logs.

I manage to "bootstrap" the "streaming-client" and got a strace of it here:
http://www.megadriver.com.br/stream.txt.27096

It doesn't matter what options I set on "in home streaming" settings, be it on the host or PC. I've tried all combinations possible. And if I try to stream from a win7 PC to another win7 it works fine. So it doesn't look like a firewall problem. Also, if I try to launch a local game on any of the linux PCs, it works fine.

What's in common with these linux PCs: Both are using Ubuntu, but different versions; both are using official nvidia drivers; same behavior, start stream, nothing happens, no errors displayed on console or logs. 

Any clues?

Thanks.

**Comment by wdeignan** [comment]
Did you ever figure this out? I'm having the exact same issue.

**Comment by Jimi-James** [comment]
I'm having this issue now too, after upgrading steam-native to 1.0.0.52 from 1.0.0.51. I can't see if the issue is my using native runtime, because Steam runtime doesn't work, because of this bug that I have yet to fix in months (the fix in the thread didn't fix it for me): https://bbs.archlinux.org/viewtopic.php?id=193802

**Comment by outlyer-net** [comment]
I also have this issue. Windows 10 x64 host with Nvidia card (GTX 750 Ti) and Debian Sid x64 guest. Streaming was working properly some days ago. Streaming to a Windows guest works.

No error displayed nor printed to the terminal, window pops up and disappears instantly, the game starts on the host properly.

Tried Steam package version 1461972496
also tried with beta update to package version 1465507923

Tried both versions 365.19 and 368.39 of the Nvidia driver on the host.

**Comment by Jimi-James** [comment]
What I had to do to fix it was use a new (not ancient) version of libudev0 with native runtime. In Arch, you can do that by installing libudev.so.0 and lib32-libudev.so.0 in the AUR (assuming you already have steam-native set up and fully updated). They just make symlinks when they're installed.

**Comment by outlyer-net** [comment]
Installing libudev0 didn't solve the issue in my case (Debian x64)

**Comment by outlyer-net** [comment]
Upon further testing, installing PulseAudio makes streaming work again.

I have my own reasons not to use PulseAudio, so I'd rather have this dependency removed if at all possible. However if it's mandatory then the package should reflect that.

As an aside, this also re-enabled Big Picture mode, which had stopped working for me (probably same issue as #4472).

**Comment by Tele42** [comment]
For what it's worth, pulseaudio should not need to be running  (but there will be no sound on the client), just have a couple of the libraries available.

**Comment by outlyer-net** [comment]
That must be the theory, Libraries were installed on my system, but streaming only works when the binary is present and running (and it's launched automatically if it wasn't).

If I disable _autospawning_ in PA's configuration, then streaming stops working.

**Comment by RMKD** [comment]
I'm also having this issue from a Windows 10 host to a Manjaro 16.06 client. I tried the libudev.0.so install but no luck. I've also attempted starting the client with the `-tcp` flag (as suggested in some older posts)

[crash dump](https://gist.github.com/RMKD/ca2d0a50505fbac7b8e77f7359cb7ba0)

Could `SetHTTPRequestRequiresVerifiedCertificate` be the culprit?
```
Warning, someone is using SetHTTPRequestRequiresVerifiedCertificate on Linux, where it doesn't work, and we won't actually verifyHTTP Response for https://store.steampowered.com/api/featured/?cc=US&l=english: 200, 18402
Store/Community web auth request failed: Auth error
Warning, someone is using SetHTTPRequestRequiresVerifiedCertificate on Linux, where it doesn't work, and we won't actually verifyHTTP Response for https://store.steampowered.com/api/featured/?cc=US&l=english: 200, 18443
HTTP Response for https://store.steampowered.com/api/featured/?cc=US&l=english: 200, 18443
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 594 (1231 input number was)
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 356 (828 input number was)
Installing breakpad exception handler for appid(steam)/version(1468023329)
```

**Comment by outlyer-net** [comment]
As pointed out by _czarnyckm_ at #4472, the issue appears to be solved now. I no longer need to run PulseAudio to stream (nor to launch Big Picture)

**Comment by Uramekus** [comment]
fixed a big time ago

**Comment by kisak-valve** [comment]
Thanks, closing.

**Comment by realGeorgeWashington** [comment]
This is absolutely not fixed. I've had this problem for years and I still can't figure it out. I'm streaming from one Slackware PC to another Slackware PC and it's completely broken. Game launches on desktop but no window on laptop even shows up, and vice versa.

**Comment by kisak-valve** [comment]
Hello @realGeorgeWashington, please open a new issue report.
