### ISSUE TITLE
Steam doesn't see network in ubuntu 16.10

### ISSUE THREAD

**Issue by sweeze** [ValveSoftware/steam-for-linux#4661]
#### Your system information

* Steam client version: 1:1.0.0.52-5ubuntu1
* Distribution (e.g. Ubuntu):  Ubuntu 16.10
* Opted into Steam client beta?: [Yes/No] Yes, but original problem seen without beta
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam was starting fine, but unable to download anything (download would be stuck at "starting" forever).  Opted into the beta to see if that would fix things, and now steam doesn't even start, with the following console output:
```

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by terzag** [comment]
I have a lot of trouble starting Steam on Ubuntu (Mate) 16.10 but when it's on, I don't seem to have a network issue, games download and patch fine. So not sure if there's an issue specific to your config or if there's a difference between the regular Ubuntu and Ubuntu Mate related to the network (like your assumption about systemd).

**Comment by sweeze** [comment]
Running wireshark, it looks like steam gets a 302 from client-download.steampowered.com/client/steam_client_ubuntu12, then does a DNS query for media.steampowered.com and gets several records back, but then does no network traffic other than a "QM" MDNS question query.

**Comment by sweeze** [comment]
installing `libnss-resolve:i386` fixes the issue!

**Comment by terzag** [comment]
Did you have libnss-resolve (64-bit) installed? I don't seem to have (or need) the 32-bit version.

**Comment by mjog** [comment]
Installing libnss-resolve:i386 fixed this for me on Yakkety as well. I do have the 64 bit version installed.

**Comment by sweeze** [comment]
Yes I have the 64 bit one installed, and resolv.conf pointing at the systemd-resolved resolv.conf managed file

**Comment by ack0329** [comment]
Had the 64-bit version install also but alas 
installing 
sudo apt install libnss-resolve:i386 

fixed the issue! Thanks!

**Comment by nekromoff** [comment]
Still happens on 17.* and steam installation just fail ugly without any explanation and crashes

**Comment by sagesan** [comment]
Also happens on 18.04 with libnss-resolve:i386 and libcurl3:i386 installed
