### ISSUE TITLE
PDF game manuals not show whne press link.

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#4688]
#### Your system information

* Steam client version: steam-runtime-beta-release_2016-09-02
* Distribution (e.g. Ubuntu): 16.04.1 LTS
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

#### Steps for reproducing this issue:
1. You go in game library and select game. 
2. in game page is right list in links
3. Press manual (game manual)
4. if manual are pdf format. Only white screen show in steam browser. Nothing happens.

5. why i cannot download a manual? Steam browser is not any pdf-reader or downloader.

**Comment by lahtis** [comment]
fixed.

**Comment by thetargos** [comment]
This issue is still happening in 2019 as of latest Beta update on Linux (Fedora 30) for June 2019. Albeit it is the first time I've seen this. Short video of the issue...

https://youtu.be/Yobjw_HChoA
