### ISSUE TITLE
Download Dota 2 broken

### ISSUE THREAD

**Issue by Rxon7** [ValveSoftware/steam-for-linux#4752]
#### Your system information

* Steam client version: 1481318740
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
After leaving the night downloading back to the outset
	

#### Steps for reproducing this issue:

1. Download dota 2
2. Pause download
3. start download (restart download)

**Comment by sixsupersonic** [comment]
Is your steam library on a NTFS filesystem?

I have a similar problem on Arch that is only affected when the library is on a NTFS filesystem.

**Comment by sixsupersonic** [comment]
There was an update for steam on Dec 12 that fixed ZFS drives.  Which is when the NTFS issue started to show up.

**Comment by Rxon7** [comment]
I use ext4

try again tomorrow

**Comment by sixsupersonic** [comment]
Also try and verify other games and see if they pass. Most of the games on my NTFS drive will download and be playable (except CS:GO which is getting the same issue as you), but all of them will fail verification.

The games that do pass verification (including CS:GO) are installed on a BTRFS filesystem.

**Comment by tryton-vanmeer** [comment]
I have the same issue as @sixsupersonic. With how the WD Black² hybrid drive works, I could format the SSD partition to ext4 but had to keep the HDD partition NTFS. Hoping this issue gets fixed soon.

**Comment by kendase3** [comment]
Switching filesystems from ntfs to ext4 resolved this for me on Debian Sid.  Smaller games were fine on NTFS, but CSGO and Dota 2 would fail repeatedly.

**Comment by sixsupersonic** [comment]
@kendase3  What are these "smaller games?" All of the games I have on the NTFS drive fail verification, big or small.

**Comment by kendase3** [comment]
"Papers, Please" downloaded and passed verification, though I didn't try to launch it.  I believe I tried Teleglitch as well and that downloaded without issue.

**Comment by sixsupersonic** [comment]
The smallest game I have "Uplink (42MB)" failed verification, but successfully downloads and is playable.

**Comment by klarkc** [comment]
I can't play Dota 2, it's a external hard-drive, but with EXT4. I tried everything, even clearing download Three times.

**Comment by ecryptfs6** [comment]
Do you guys have steam library in an encrypted home folder?

**Comment by sixsupersonic** [comment]
My main steam library is sitting on an separate NTFS (no encryption) partition that I share with Windows 10.
The games that don't work on the NTFS partition are on my root/home Arch Linux BTRFS partition (no encryption).

The NTFS Library will always fail verification, but the games will download, run, and update with the only exception being CS:GO, which fails to download.

I don't know if this is of any use, but here is my NTFS-3G mount options
"noatime,defaults,windows_names,big_writes"

**Comment by SethDusek** [comment]
Any progress on this?

**Comment by shadowman79** [comment]
Please let us know if fix is in next update

**Comment by Rxon7** [comment]
Trying to install now on ext4 (before in ntfs ) wait for news

**Comment by SethDusek** [comment]
I wish Valve was less secretive about their progress on issues like this. They're obviously giving it attention, since they're closing duplicates, but they're not telling us what they're doing about it, and where they are in terms of fixing it. Whether they've reproduced the error, what caused it, etc. We basically know nothing until the fix is finally released to the public, god knows when

**Comment by SethDusek** [comment]
3 weeks and not even as much as a response from Valve. I've seen open source projects with much smaller budgets (or none at all) which respond faster than you guys do

**Comment by Rxon7** [comment]
Apparently after the upgrade they fixed

**Comment by kisak-valve** [comment]
Is anyone else experiencing this issue with the steam beta client? (CS:GO / Dota 2 on NTFS or F2FS)

**Comment by AkAntA** [comment]
Just tested it out. Still experiencing the issue. CS:GO won't work due the corrupted update files.

**Comment by SethDusek** [comment]
Tested with dota 2 on Steam Beta. Still the same issue

**Comment by sixsupersonic** [comment]
Now the games won't download to my NTFS library. (Same issue as CS:GO and Dota 2, but affecting all games I tried to download to a NTFS library.)

**Comment by Rxon7** [comment]
Resolved after update

**Comment by kisak-valve** [comment]
Hello @Rxon7, I'm not aware of a specific fix that went in for this issue. What update are you referring to?

**Comment by AkAntA** [comment]
Yeah, I haven't got any updates on Steam since my last test on 3 days ago and tested this one again and it's still broken.

**Comment by SethDusek** [comment]
Yes, please reopen this issue

**Comment by SethDusek** [comment]
@kisak-valve If you don't mind me asking, and this is more of a technical detail, but shouldn't Steam and pretty much every program on Linux be file-system agnostic? Why would you need to specifically add support for ZFS, or why would support on a certain filesystem suddenly break?

**Comment by kisak-valve** [comment]
@Rxon7, I see what happened here, the original issue is about download corruption when pausing and resuming a download on ext4 which appeared at about the same time as the NTFS issue, and these two issues got accidentally combined. Glad to hear your ext4 issue is resolved. Now what to do now that the majority of the issue report is about NTFS.

@SethDusek, you may want to skim over #4670, where this was recently discussed.

**Comment by kisak-valve** [comment]
Okay, I have decided the original issue report should take priority, let's continue tracking the NTFS issue on the newly created #4800.

**Comment by Rxon7** [comment]
@kisak-valve I'm sorry. I do not speak English

ext4 === Perfect
NTFS === broke

**Comment by Heybye44** [comment]
This issue still has not been fixed. I'm still having this problem.

**Comment by Fastjur** [comment]
Still not a single response from Valve. I cannot play any games right now on my Linux machine. The issue still persists

**Comment by kamild1996** [comment]
The problem is still here. I copied my TF2 files from Windows to Linux (to a different folder on the same NTFS partition) and tried to launch it using Steam. Steam downloads ~22 MB worth of Linux libraries, then shows me the "corrupt update files" error (file: /host/Steam_Linux/steamapps/downloading/440/bin/bsppack.so) over and over.

**Comment by ChazyTheBest** [comment]
I can also confirm that this is still a problem. I'm on Manjaro (Arch) Linux and my library is on a NTFS HDD. Can't download/install CS:GO.

**Comment by simbalion** [comment]
Still a problem. At random times CSGO crashes out and complains about invalid PAK files, it's a different file each time. I perform a file validation and it fixes the issue for 5 minutes and then when I join a game after about 5-10 minutes it crashes out again with the same error, different PAK file.

**Comment by AlejandroC90** [comment]
Issue not solved yet, I have two game libraries, one on a ext4 drive and another on a ntfs drive, having dota installed in ext4 and still the update files are being downloaded on the ntfs drive so I get this Issue (maybe it picks the ntfs drive because of more available space). Pretty annoying still.

**Comment by simbalion** [comment]
my issue was apparently caused by a bad stick of ram, so I would recommend testing that
