### ISSUE TITLE
Dualshock 4 Controller Light Brightness cant set on linux

### ISSUE THREAD

**Issue by MrCapone** [ValveSoftware/steam-for-linux#4790]
#### Your system information

* Steam client version:
![Steam Version](https://cloud.githubusercontent.com/assets/5929042/21584697/2fc014a8-d0ea-11e6-9b9e-2956542776a2.jpg)
* Distribution (e.g. Ubuntu): Linux Mint 18.1 Cinnamon 64 bit
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. Connect Dualshock 4 to PC and run Big Picture
2. Go to Settings - Controller Settings - Detected Controllers
3. Find your Dualshock 4 and open its Preferences
4. set Controller Light Brightness to non-zero value
![Brightness Before](https://cloud.githubusercontent.com/assets/5929042/21584778/5bf961ae-d0eb-11e6-943d-e97b069b01e3.png)
5. click Submit and  Controller LED goes out, if you open Preferences and look to Controller Light Brightness you will see zero value ![Brightness After](https://cloud.githubusercontent.com/assets/5929042/21584784/aa5fd3d2-d0eb-11e6-92f3-1013ba61a1ee.png)
6. Also if set Preferences on Windows, save them and then load on Linux by Steam Cloud all LED will works fine. But if you try set Preferences on Linux again, you will get this issue.

**Comment by kisak-valve** [comment]
Hello @MrCapone, What version of the steam package do you have installed via your package manager? More specifically, do you have the updated udev rule from https://steamcommunity.com/app/353370/discussions/0/490123197956024380/ which shipped with the 1.0.0.54 package?

**Comment by Nikolaj64** [comment]
Do you use a non-English locale? If I launch Steam with `LC_ALL=C` I'm able to properly set the brightness of the lightbar, but if it's running with the system's default locale (Danish) then I have the same issue.

Could this be because it doesn't handle the decimal separator being comma properly?

**Comment by MrCapone** [comment]
@kisak-valve i had 1.0.0.52, but i installed udev rule by myself. Now i updated package version. But it seems not the problem.
@Nephyrin yes i use Russian locale. Running Steam with `LC_ALL=C` solve the problem, thanks.

**Comment by jansegre** [comment]
I have this issue too. (DualShock 4, Steam on Linux)

It is as described, I can set the color and light brightness, but after hitting submit the color is saved but the brightness is reset to 0%, unless I set the brightness to 100% in that case when hitting submit it saves as 100%.

Setting `LC_ALL=C` when first starting Steam fixes it for me. I have `LANG=en_US.UTF-8` but most others are `LC_...=pt_BR.UTF-8`.

**Comment by k-e-i-z-a-i** [comment]
This issue is still present.

* Steam client version (build number or date): Apr 28, 2023
* Distribution (e.g. Ubuntu): Pop OS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I can set the DualShock4's brightness in the "regular" Settings or Big Picture mode's settings and these Brightness settings will persist for the rest of this Steam session. However, if I fully close Steam and then re-open Steam, Steam doesn't remember my Brightness settings until I either: 1) open up the screen with the Brightness slider in Destop Mode settings or 2) enter Big Picture mode. Doing either of this will retain the Brightness setting until the end of this Steam session.

This issue was opened in 2017. Is there any chance of getting it addressed soon?

**Comment by k-e-i-z-a-i** [comment]
> Do you use a non-English locale? If I launch Steam with `LC_ALL=C` I'm able to properly set the brightness of the lightbar, but if it's running with the system's default locale (Danish) then I have the same issue. This also happens with the Steam Controller by the way.

Pardon my ignorance, but how can I launch Steam with `LC_ALL=C`?

**Comment by jsjolen** [comment]
@k-e-i-z-a-i , In a terminal write `export LC_ALL=C` and then run steam with `steam`

**Comment by k-e-i-z-a-i** [comment]
> @k-e-i-z-a-i , In a terminal write `export LC_ALL=C` and then run steam with `steam`

@jsjolen, Is there any downside to exporting this globally?

**Comment by jsjolen** [comment]
> > @k-e-i-z-a-i , In a terminal write `export LC_ALL=C` and then run steam with `steam`
> 
> @jsjolen, Is there any downside to exporting this globally?

`export LC_ALL=C` affects the locale (language, currency, time) which in turn affects the formatting of texts by locale-aware programs. It basically overrides and customization to be 'the most basic' formatting. Run `locale` on your system to see how this may affect you. For example, for me it will affect `sudo apt upgrade` as the text will now be in English instead of Swedish.

You can read more here: https://wiki.archlinux.org/title/Locale https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do

**Comment by k-e-i-z-a-i** [comment]
@jsjolen I ran export `LC_ALL=C` and it isn't fixing the problem because it's not persisting after restarting my machine. Is it supposed to persist? I even tried it with `sudo` but it didn't work.

**Comment by k-e-i-z-a-i** [comment]
Inferring advice from others in this thread, I've run the command `LC_ALL=C steam` in order to run Steam with these locale settings. Steam successfully launches but it actually has the opposite of my aims and actually makes it impossible for me to change the LED settings even in just that session.

When I run Steam normally I continue to be able to set my desired LED settings on the Dualshock 4 but it only implements these settings after I go into the controller LED settings, and not when Steam launches. So at every relaunch of Steam, it "forgets" my LED settings until I go into the controller LED settings, which is very undersirable.
