### ISSUE TITLE
Hardware decoding offset (off center) using in home streaming for Dec 12 2017

### ISSUE THREAD

**Issue by CrackerJackMack** [ValveSoftware/steam-for-linux#5281]
#### Your system information

* Steam client version (build number or date): Dec 12 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

Visual Aid: https://imgur.com/a/gsTUE
Only since the Dec 12 2017 update (was working just the night before this update) that in-home streaming with hardware decoding enabled results in the mouse and video offset inside of the steam full screen X window.  

In the screenshots you can see that VAAPI decoding is properly working and no updates to the libraries were detected via apt.

Client: 2160x1080@144hz
Host: 1920x1080@59.95hz

Client machine appropriately adds black bars and centers the steam client window even with though the game is rendered off center.  __I believe it might be an artifact of aspect ratio's not be accounted for when applying the offsets__

#### Workaround
Changing the client's resolution to match the host's resolution w/hardware decoding enabled does **not** produce the offset issue.  This workaround isn't ideal as it requires extra steps to play a game.

#### Steps for reproducing this issue:

1. enabled in home stream client hardware decoding (using an intel video card)
2. stream 1080p60 to 21:9 monitor observe the offset
3. disable hardware decoding in in home streaming client options
4. launch game and it should be centered.

**Comment by CrackerJackMack** [comment]
Retested with the Dec 15 2017 release.  Still occurs.  Thank you again for in home streaming, it's awesome.

**Comment by tombriden** [comment]
I'm having a similar issue which is probably related to the same change that caused this. When streaming from a 1080p host to a 2160p client (both Linux), the streaming window used to be full screen and 1080p. Since a recent update, the streaming info still says its capturing at 1920x1080 but the streaming window is zoomed in to the top left quarter of the screen. Changing the client resolution to 1080p or disabling hardware decoding works fine

**Comment by tombriden** [comment]
If you're familiar with compiling C code, I knocked up an app to detect the streaming window getting focus and auto-switching the resolution, then back again on loss of focus: 
https://gist.github.com/tombriden/e634d44847f65a769d785cb8e98446c5

`gcc resolution-switcher.cpp -lX11 -lXrandr -oresolution-switcher`

Change line 95 if you're switching to something other than 1920x1080

It's not perfect but does the job well enough. You can also run as a daemon with `-d` option.

**Comment by grimandreas** [comment]
Reporting same problem with VAAPI decoding on Ubuntu 16.04.4 Client. Screen resolution - 1920x1080 
Host - Windows 10 with the same resolution.
Game launchers and in-game videos (which have resolution less than 1920x1080) zoomed in to the top left quarter of the screen.
I know that there was the same problem in 2014, but in 2015 Valve developers said the problem was solved.
I've tried using this fix http://voltaicforge.com/linux/steam-vaapi-fix-linux/
It doesn't fix problem.
This is my output of **vainfo** command:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.39 (libva 1.7.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Bay Trail - 1.7.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
```
Any ideas for fixing?

**Comment by grimandreas** [comment]
So, moderator closed my issue, then I'll ask here. 
The problem identified in mid-December 2017. Four months after, problem still exists. Any chance it will be solved? Or it will be continuously ignored by developers?

**Comment by Pandiora** [comment]
Finally I found what I was looking for and I have to report the same bug/problem. 

In example I'm using the Wargaming-Launcher called "Game Center" and it also appears offset and additionally the mouse is offset too. If I resize the Window on my client via "Alt+Enter" only the launcher gets displayed, has the correct size and the mouse doesn't have some offset anymore. But then I have the next problem with starting the game in fullscreen. If I try to switch back with "Alt+Enter", the stream sometimes still uses the previous (lower) resolution. This is a serious problem, since I need to use software like anydesk/teamviewer (Remotedesktop would kill the game, since it is using its own graphic driver) to switch between gamelauncher and the game itself on the host-machine. Sometimes I need to start the game several times to get it to work in fullscreen. This is very frustrating and it worked like a charm before this update.

My configuration:
Host - Windows 10 Beta-Client (iGPU)
Client - Arch Linux (Cinnamon) Beta-Client HW-Decoding (iGPU) VAAPI

I have a dedicated GPU on my Host-machine, but Intel Quicksync seems to work much better and lagfree for me. (patch your network-manager if you're using WiFi ;)

**Comment by lostgoat** [comment]
This issue should be fixed in the latest steam client beta.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by karasuhebi** [comment]
This is most definitely still not fixed. I switched over to the Steam Client beta just to test. Steam Link is still presenting this issue. I'm running a 21:9 host and a 16:9 client.

**Comment by kisak-valve** [comment]
Hello @karasuhebi, looking this issue report over, the issue tracked here was specifically about hardware accelerated decode on Intel hardware. Please open a new issue report so that your issue can be tracked properly.
