### ISSUE TITLE
OK button in Steam's settings unconditionally gives a restart client prompt

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5495]
#### Your system information

* Steam client version (build number or date): 1526683293
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Nickname change in Settings triggers a Steam restart prompt. If Ok is pressed, Steam restarts, but with the old name, i.e. without changes. If Cancel is pressed (postponing the restart), the nickname is changed immediately, not requiring a restart. After a directly following manual restart the new nickname remains preserved.

The restart prompt should not appear in the first place. If it's required now, after the restart the nickname should be changed.

#### Steps for reproducing this issue:

1. Settings -> change nickname.
2. Restart prompt appears.

**Comment by Leeo97one** [comment]
For me, the restart prompt is triggered every time I press OK in the Settings dialog.

**Steps for reproducing:**
1. Open Settings
2. Do not change anything
3. Press OK
4. Restart prompt appears

**Comment by light2yellow** [comment]
I can confirm @Leeo97one's simpler repro.

**Comment by sylware** [comment]
same pb here, I though it was only my settings which were corrupted

**Comment by MaxXor** [comment]
Same here on Arch Linux with latest Steam runtime.

**Comment by ml-** [comment]
Information: https://gist.github.com/ml-/5cfc0530b114a0a835a53aae03c2b0a6
Arch Linux as well.
I see Arch (+Manjaro) people reporting this issue in here. Is this solely an Arch issue or can someone with another distribution also reproduce?

**Comment by sylware** [comment]
Distro independant.
Even in the beta client.

**Comment by Managor** [comment]
Yeah, I'd like to chime in that this issue is quite annoying. Especially for new users.

**Comment by Plagman** [comment]
Fixed in next Beta.

**Comment by Leeo97one** [comment]
> Fixed in next Beta.

What do you mean by "next Beta"? The problem persists after yesterday Beta update.

**Comment by Leeo97one** [comment]
Same in the last update.

**Comment by sylware** [comment]
Maybe they are talking about the clean 64bits steam client, the one which is
properly packaged with most of its dependencies and does not expect a huge
mainstream distro?

(irony inside)

**Comment by kisak-valve** [comment]
The safe assumption here is that there's a fix queued in the next beta fork off of the developer's version of Steam. Keep an eye out for a Steam client beta update with a larger set of patch notes compared to the small fixes that regularly get pushed.

**Comment by kisak-valve** [comment]
Per "Fixed settings dialog incorrectly always prompting for a client restart" in the [2019-01-16](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1703951108822305086) Steam client beta update, please opt into the beta and retest this issue.

**Comment by Managor** [comment]
Yes, it's fixed now. You can add that to the long list of fixes in this patch

**Comment by kisak-valve** [comment]
Thanks for retesting, fix has gone into the stable client as well.
