### ISSUE TITLE
Chat window closes by itself on the new steam chat beta

### ISSUE THREAD

**Issue by conrev** [ValveSoftware/steam-for-linux#5527]
#### Your system information

* Steam client version (build number or date): Jun 12 2018
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Every time i tried to message someone (opened the steam chat window), the steam chat window for that person opens for a split second then closes. This prevents me from chatting anyone. This happens consistently after i played and closed a game. (Steam chat is functional before and while playing the game). Can someone else reproduce this issue?

GIF demonstration: https://media.giphy.com/media/QfIGD6M0pwRVCD4xvF/giphy.gif

#### Steps for reproducing this issue:

1.  Play then close a game on steam.
2.  Open friendlist, try to send a message to someone.
3.  The chat window opens then instantly closes.

Thanks in advance!

**Comment by conrev** [comment]
Update : i just updated to Jun 13 2018 build which is supposed to solve the problem, however the problem still persist on my end.

**Comment by sizeofbool** [comment]
This bug affects multiple users on both **Linux** and **Windows**.

Same problem, chat window stays opened for a split second and closes after.
Unable to use chat with new UI.
Restarting Steam Client restores Chat functionality until described bug triggers again.

**Full steps to reproduce:**
1. Start Steam Client.
2. Double-click on Friend's name in Friends List, or use RMB+select "Send message".
3. Observe Chat window shows up and stays open, working as intended.
4. Run any game (My Game is Left4Dead 2) and open Steam In-Game Overlay.
5. Double-click on Friend's name in Friends List, or use RMB+select "Send message".
6. Observe Chat window shows up and stays open, working as intended.
7. Close opened Chat windows, close In-Game Overlay and Exit the game.
8. Double-click on Friend's name in Friends List, or use RMB+select "Send message".
9. Observe Chat window shows up for a half of a second and gets closed automatically.

**Comment by sizeofbool** [comment]
Looks like this bug is fixed in Steam Client Beta - June 14, 2018 update. It was required for me to restart Steam Client to get it fixed, despite "Steam Client is Up-To-Date" message.
I can't reproduce this bug anymore.

**Comment by conrev** [comment]
I can also confirm this issue is fixed by the June 14, 2018 update. I will test this a bit more and close this issue afterwards.

**Comment by corpsinhere** [comment]
Windows7 64bit - just this morning (8/15/2018) started having this problem. restart or reboot does not fix.

**Comment by tmzhuang** [comment]
This is a problem for me on linux. It is as the problem was originally described. Trying to start a chat will immediately close the window.

Steam client version (build number or date): 1683944175
![image](https://github.com/ValveSoftware/steam-for-linux/assets/1159725/2df8f621-2284-49e4-b5d8-bfad8cb4bcb3)
Distribution (e.g. Ubuntu): Arch Linux (Linux jupiter 6.3.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 x86_64 GNU/Linux)
Opted into Steam client beta?: [Yes/No] Yes
Have you checked for system updates?: [Yes/No] Yes
