### ISSUE TITLE
Proton - Cloud saves does not sync with Windows

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5640]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/64.
@kgudalov posted on 2018-08-22T09:44:00:

When you start games that have already been run in wine steam (Gothic 3, Skyrim SE ), you can not find the old save.
***
@tingvarsson commented on 2018-08-22T09:47:16

Same applies to Mirrors Edge (save game is not synced).
However it does work for Final Fantasy VII, but could be because it has a launcher which seems to handle the sync potentially.
***
@kgudalov commented on 2018-08-22T10:15:13

The situation even worse. The games mentioned above can't save the settings at all.

**Comment by Mushoz** [comment]
Possibly related, but with the Steam for Windows running through Wine, I also had a synchronization issue of save games with Kingdom Come: Deliverance. The reason why this happened, is because 'SHGetKnownFolderPath' didn't handle certain flags that were being used. Kingdom Come gracefully defaulted to a different path for the save games, but Steam was then unable to find them for synchronization.

Some users above are also complaining about some games saving nothing at all. These games might not have a graceful fallback to a different location, and hence nothing is saved.

Since Proton seems to be based on Wine 3.7, while said bug was only fixed in Wine 3.11, it might be a proton bug after all.

The bug report regarding this bug can be found here: https://bugs.winehq.org/show_bug.cgi?id=45359
The commit that fixes the issue can be found here: https://source.winehq.org/git/wine.git/?a=commit;h=ff7c2c51718e8f64c9b708847f3a322bd136eb75

A cherry pick of that commit to Proton could be all that's needed to fix these issues. I apologize if this commit was already cherrypicked to Proton, because I did not verify this.

**Comment by kisak-valve** [comment]
Per https://github.com/ValveSoftware/wine/pull/6#issuecomment-415819068, please retest this issue.

**Comment by tingvarsson** [comment]
Thanks for the info.
Do I need to rebuild manually to test? Or are new versions pushed out frequently (if so, what's the easiest way to check if this is in or not?)

**Comment by kisak-valve** [comment]
From what I've been hearing, restarting the steam client should be enough to make sure Proton is up to date. (unconfirmed)

**Comment by jonpile** [comment]
Whenever we update the Proton build on Steam, it should automatically download either when you restart the Steam client or on the next game launch. We don't currently have a super-explicit process that will tie individual checkins here to the releases on the Steam platform.

**Comment by tingvarsson** [comment]
Thanks for the info.
My current WoW to check if I have a newer Proton is to check the modified date on the bin files.

**Comment by nmiell** [comment]
The Steam client appears to not see AutoCloud files despite them existing.

For example:
```
[2018-09-02 17:26:32] [AppID 210970] Running AutoCloud on exit. Looking for new and updated files
[2018-09-02 17:26:32] [AppID 210970]     Evaluating rule 0 with root="WinAppDataRoaming" path="The Witness" pattern="*.witness_campaign"
[2018-09-02 17:26:32] [AppID 210970]         Found 0 files that match /home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/*.witness_campaign
[2018-09-02 17:26:32] [AppID 210970]     Evaluating rule 1 with root="WinAppDataRoaming" path="The Witness" pattern="*.png"
[2018-09-02 17:26:32] [AppID 210970]         Found 0 files that match /home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/*.png
[2018-09-02 17:26:32] [AppID 210970]     Skipping rule 2 because it does not run on our platform
[2018-09-02 17:26:32] [AppID 210970]     Skipping rule 3 because it does not run on our platform
[2018-09-02 17:26:32] [AppID 210970] AutoCloud complete
[2018-09-02 17:26:32] Starting sync job
[2018-09-02 17:26:32] [AppID 210970] Starting sync (upload)
[2018-09-02 17:26:32] [AppID 210970] Upload complete in build list
```

And yet:
```
$ ls "/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/"@(*.witness_campaign|*.png)
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_09.49.06.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_09.49.06.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_11.05.03.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_11.05.03.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_19.21.57.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.29__time_19.21.57.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_11.14.04.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_11.14.04.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_17.20.49.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_17.20.49.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_23.47.23.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.30__time_23.47.23.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.31__time_20.17.07.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.08.31__time_20.17.07.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.09.02__time_09.01.59.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.09.02__time_09.01.59.witness_campaign
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.09.02__time_12.53.00.png
/home/nicholas/.local/share/Steam/SteamApps/compatdata/210970/pfx/drive_c/users/steamuser/Application Data/The Witness/2018.09.02__time_12.53.00.witness_campaign
```

**Comment by nmiell** [comment]
Oh...Sir! The Hollywood Roast (AppID 575330) has a Linux AutoCloud configuration despite not having a native Linux port.

The Steam client uses the Linux AutoCloud rules instead of the Windows AutoCloud rules.

```
[2018-09-03 21:37:38] [U:1:40259229] [AppID 575330] Init cache request complete
[2018-09-03 21:37:38] Starting sync job
[2018-09-03 21:37:38] [AppID 575330] Starting sync (eval)
[2018-09-03 21:37:39] [AppID 575330] Eval complete
[2018-09-03 21:39:44] Starting sync job
[2018-09-03 21:39:44] [AppID 575330] Starting sync (eval)
[2018-09-03 21:39:44] [AppID 575330] Eval complete
[2018-09-03 21:39:44] [AppID 575330] Running AutoCloud on launch. Looking for existing files to watch:
[2018-09-03 21:39:44] [AppID 575330] AutoCloud done. Watching 0 files
[2018-09-03 21:42:41] [AppID 575330] Running AutoCloud on exit. Looking for new and updated files
[2018-09-03 21:42:41] [AppID 575330]     Evaluating rule 0 with root="WinMyDocuments" path="OhSirTheHollywoodRoast" pattern="*.oss"
[2018-09-03 21:42:41] [AppID 575330]         Found 0 files that match /home/nicholas/.local/share/ /OhSirTheHollywoodRoast/*.oss
[2018-09-03 21:42:41] [AppID 575330] AutoCloud complete
[2018-09-03 21:42:41] Starting sync job
[2018-09-03 21:42:41] [AppID 575330] Starting sync (upload)
[2018-09-03 21:42:41] [AppID 575330] Upload complete in build list
```

**Comment by veikk0** [comment]
I've had sync issues with multiple games, the latest being Worms Revolution. One device (laptop) that ran the game via Proton was able to sync the save file to the cloud just fine, but another machine (desktop, also running the game via Proton) was unable to download that save and threw the "Steam was unable to sync your files" error. I attempted to launch the game multiple times to give it more chances to attempt to sync but that did nothing. I went to type this issue report and attempted to re-launch after about 5 minutes, just in case, and Steam apparently had successfully downloaded the save and the game recognised it just fine. I can't recall if I also restarted Steam, I might have but can't say for sure.

Most of my sync issues have resolved themselves in a similar manner and I'm not eager to deliberately reproduce them (in case I accidentally override my saves or something) which is why I haven't ended up filing a report before.

One thing you can do if Steam absolutely refuses to download your game saves is download them manually by logging into Steam in your browser and going to https://store.steampowered.com/account/remotestorage. From here you can manually download save files for all your games or just check the timestamps to see if your save files are actually up to date. This can also be helpful when Linux and Windows versions of games don't synch with each other, if the save files are compatible across versions you can just download the Windows save to a Linux machine and vice versa.

**Comment by lucifertdark** [comment]
It is working for some games, Batman Arkham Asylum found my previous save from the last time I played it in Windows 3 years ago.

**Comment by Sebastian1978** [comment]
Syncing works for Dishonored.
Doesn't work for Bioshock 2.

**Comment by Plagman** [comment]
The problem with The Witness above should be fixed in the new Steam Client Beta. Can people affected by cloud problems re-test on the Beta, and attach their cloud_log.txt along with a description of what save files aren't getting copied?

**Comment by kadogo** [comment]
No syncing for Tekken7.

I reinstall the game yesterday on a new computer and it didn't take back my save.
I remember it say something about the save being corrupted.

If we can force sync I can try it back to see if it happen again.

**Comment by Sebastian1978** [comment]
Tested for Bioshock 2. Still not sincing. Where is  cloud_log.txt? I haven't found it.

**Comment by Pobega** [comment]
> No syncing for Tekken7.
> 
> I reinstall the game yesterday on a new computer and it didn't take back my save.
> I remember it say something about the save being corrupted.

Sorry for bumping this old thread but it comes pretty high in Google searches.

The issue for Tekken 7 is that only the base game is whitelisted in Proton, if you own any DLC you need to enable SteamPlay for all titles in settings and then it should successfully be able to use your cloud save.

**Comment by linsaftw** [comment]
I am having the same issue with Sims 4.
