### ISSUE TITLE
Uneven network load and low download speed

### ISSUE THREAD

**Issue by OneAdder** [ValveSoftware/steam-for-linux#6126]
#### System information

* Steam client version (date): Feb 18 2019
* Distribution: Debian Buster
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Description:
I upgraded my Steam client to Feb 18 build and faced a severe issue.
The download speed is extremely low (0-100 Kb/s). Before the upgrade the speed was 10-15 Mb/s (on January build).
When I monitor the network load, I can see that it is extremely uneven (sequence of peaks, the third row in the screenshot).
![screenshot_20190306_185439](https://user-images.githubusercontent.com/19834976/53894600-6b5fc080-4041-11e9-9943-bc1229a0f668.png)

This issue appeared right after I upgraded from Jan 4 2019 build to Feb 18 2019.
I tried using beta version as well, the issue is present.
Perhaps, it is connected with [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/6087).

P.S. Sorry for two issues in a row.

**Comment by OneAdder** [comment]
My system info:
[https://gist.github.com/OneAdder/e84b14b6e3d9ea9f5db634b58fa5be5e](https://gist.github.com/OneAdder/e84b14b6e3d9ea9f5db634b58fa5be5e)

**Comment by kisak-valve** [comment]
Hello @OneAdder, please copy `<steam install dir>/logs/content_log.txt` to a [gist](https://gist.github.com/) and include a link in this issue report.

Possibly related to #5907.

**Comment by OneAdder** [comment]
Here is the [log](https://gist.github.com/OneAdder/163228d62bff6f3bcfc8c3fc8868336f).

**Comment by tonysh3** [comment]
Have same issue
Ubuntu 18.04
Steam version: Feb 18 2019

My download speed is 100 bytes but when CS GO download its modifications it was normal(700 kb/s)
I try to reinstall steam and system, nothing changed.
Here is [log](<script src="https://gist.github.com/tonysh3/a5b5b10452f8467cc618204c688230b6.js"></script>).

**Comment by tonysh3** [comment]
I don`t know what happened,  download was 100 bytes/s for 1-2 minute and now speed increased to normal 800kb/s.
Here is log which includes yesterday and today launches, if you need this.
https://gist.github.com/tonysh3/180bd6903b70c3f21ae4489bc8ad2e5c.js

**Comment by OneAdder** [comment]
Is there any progress or some idea about what might be causing it? I tried purging Steam and reinstalling it from scratch, the result is still the same. I cannot find any workaround to solve the issue.

**Comment by tonysh3** [comment]
I still have this issue. Download start with 1 second 500kb speed, than it became 3-4 kb/s, it increases from time to time a bit at the end of 10 mb donwload it became 50kb/s. Still have this peaks at download.
![Снимок экрана от 2019-03-12 19-03-19](https://user-images.githubusercontent.com/26820340/54212540-8b3d2b80-44fc-11e9-83c7-7fa6eb3dcd60.png)
![Снимок экрана от 2019-03-12 19-17-06](https://user-images.githubusercontent.com/26820340/54212569-92643980-44fc-11e9-9bd6-4b5b199ab0e9.png)
![Снимок экрана от 2019-03-12 19-04-13](https://user-images.githubusercontent.com/26820340/54212585-97c18400-44fc-11e9-80cb-cbe6f6ca3c60.png)

**Comment by tonysh3** [comment]
I don`t understand. Start downloading game 1 minute after taking screenshots above.
Speed is normal without any peaks
![Снимок экрана от 2019-03-12 19-28-07](https://user-images.githubusercontent.com/26820340/54213086-42d23d80-44fd-11e9-8d2e-4c4c60f0f98e.png)

**Comment by ThomasStegbuchner** [comment]
try disabling ipv6 on your system

**Comment by OneAdder** [comment]
Wow, that helped. @ThomasStegbuchner Thank you very much!
@kisak-valve Could you fix this issue with IPv6? I have to disable it systemwide to download something. It's not a perfect workaround.

**Comment by tonysh3** [comment]
ipv6 disabled didn`t work out for me
same speed like before

**Comment by bcrochet** [comment]
I am (was?) seeing the same thing. Once I disabled ipv6 (sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6') downloads *immediately* started up again.

**Comment by OneAdder** [comment]
@bcrochet Interesting whether this issue appears randomly under both Debian and Ubuntu or under Debian only. If the second, I think it could be solved by investigating the difference in how ipv6 works under both systems

**Comment by Emanem** [comment]
Hi, I also suffer form this issue. The only workaround is to disable IPv6 - but this is very suboptimal.
I've also opened a discussion on the forums here: https://steamcommunity.com/app/221410/discussions/0/3247565033758861331/

**Comment by bvn13** [comment]
the same issue on Fedora 29

**Comment by Emanem** [comment]
In general my IPv6 works fine, perhaps is the API Valve are using that may be not performant?
Perhaps they're using async-io on Linux (instead of epoll)?

**Comment by Seil0** [comment]
Hi, I also got this issues, but disabling IPv6 doesn't relay solve the problem. The download speed toggles between 0 kb/s and 6 mb/s. [log](https://gist.github.com/Seil0/3903541a36be0919d8e6c6df36a1c035)

**Comment by b4ux1t3** [comment]
Having this issue as well. Manjaro Linux, no IPv6 on network and disabled in OS. Speed tests consistent at 45-80 Mbps.

![DeepinScreenshot_select-area_20190417175716](https://user-images.githubusercontent.com/5150833/56324107-f0a7bc00-613b-11e9-9516-a4a2a9d5d201.png)

That's a pretty significant difference. Any telemetry we can pick up in Steam to help diagnose?

**Comment by msrb** [comment]
I can confirm that disabling IPv6 on my Fedora 29 machine "fixed" the problem.

**Comment by h1z1** [comment]
You can as a test try 
```
ip6tables -I INPUT -m state --state NEW -j LOG --log-prefix "valvetest:"
ip6tables -I INPUT -j REJECT
ip6tables -I FORWARD -j REJECT
ip6tables -I OUTPUT -m state --state NEW -j LOG --log-prefix "valvetest:"
ip6tables -I OUTPUT -j REJECT
````

If you see hosts getting logged it's posible somethings retrying ipv6 because it's not either honoring a reset or, more likely, waiting for ipv6 to timeout.    

Assuming you're not using v6,
```
ip -6 route get 2002::
```
Should return network is unreachable or some such.

**Comment by vinzv** [comment]
Can confirm this problem with openSUSE Tumbleweed.
Disabling IPv6 did _not_ help.

**Comment by MalteJoe** [comment]
I have the same issue in Ubuntu 19.04 and disabling ipv6 did nothing. However, changing my download region to Netherlands instead of Germany made my download speeds go from ~50KB/s to 5 MB/s (which I would expect from my connection).

[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3159176/content_log.txt)

**Comment by sunmachine** [comment]
Linux Mint 19.1 Cinnamon, 4.15.0-50-generic. 
Disabling IPv6 did help immensely. `20 KB/s` to `46.4 MB/s`.

**Comment by tonysh3** [comment]
After steam update speed is better but it is not as high and constant as if we disable ipv6
These commands work for me
`sysctl -w net.ipv6.conf.all.disable_ipv6=1 
 sysctl -w net.ipv6.conf.default.disable_ipv6=1`

**Comment by Emanem** [comment]
> After steam update speed is better but it is not as high and constant as if we disable ipv6
> These commands work for me
> `sysctl -w net.ipv6.conf.all.disable_ipv6=1 sysctl -w net.ipv6.conf.default.disable_ipv6=1`

Same here - the update made it better, but with IPv4 I get to use my 1 Gbps at full speed...

**Comment by sunmachine** [comment]
Ammending previous post: adjusting IPv6 settings no longer works. Back to slow speeds.

**Comment by bcrochet** [comment]
> @bcrochet Interesting whether this issue appears randomly under both Debian and Ubuntu or under Debian only. If the second, I think it could be solved by investigating the difference in how ipv6 works under both systems

I'm on Fedora. And I've seen it across Fedora 29/30, and Fedora 30 Silverblue.

**Comment by dpatou** [comment]
Hello there,

This might not be a match with the issues that everyone is experiencing here, but I had the "slow download speed by short bursts" using ubuntu 18.04

It turned out the steam library I was using was on an ntfs drive (dual boot system so some of my drives are ntfs, the only with room left in it was) mount. As per the first answer right here https://gaming.stackexchange.com/questions/253695/abnormally-slow-speeds-downloading-from-steam I changed the fstab config of this mount to `async` (was `sync`). After unmounting and remounting, the problem was fixed (comparable download/update speeds as windows).

For the record, I do have dnsmasq installed (since i'm using it for other purposes). I didn't touch any IPV6 conf.

I hope it helps anyone (although I doubt it's the cause of most people posting here issues).

**Comment by Emanem** [comment]
It seems the same issue resurfaced again. After disabling IPv6 download speeds seems to have picked up. Ubuntu 18.04 LTS with HWE 4.18.0-25-generic.

**Comment by sodd** [comment]
I have same problem with download speed. If i disable IPv6 i can reach maximum downloading speed.

```
OS: Ubuntu 18.04
kernel: 4.15.0-54-generic
Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2
```

**Comment by Emanem** [comment]
Had to resort disable IPv6 to get full download speeds (1 Gbps)... Weird, I thought it was fixed some weeks back?
Ubuntu 18.04 with HWE.

**Comment by ehudnoleft** [comment]
As of today this problem still exists. I'm on 4.16.18-galliumos.
Turning off ipv6 did correct the problem.
I followed this guide to do it: https://easyengine.io/tutorials/linux/disable-ipv6/

Good luck!

**Comment by RemoteRen** [comment]
@ehudnoleft solution fixed it for me on Ubuntu 18.04

**Comment by Emanem** [comment]
Unfortunately the issue still persist. Valve should give us the option to turn off IPV6 at app level instead of having to manually disable at OS level...

**Comment by Emanem** [comment]
Thanks - is there any update on this?

@kisak-valve any way to disable IPv6 from Steam client as a workaround instead of disabling it system-wide?
Any way to set socket creation as _IPv4 stream_ instead of IPv6 (i.e. force specify *AF_INET* instead of *AF_INET6* in the _domain_ [parameter](http://man7.org/linux/man-pages/man2/socket.2.html)) when steam creates a connection?

**Comment by bcrochet** [comment]
> Thanks - is there any update on this?
> 
> @kisak-valve any way to disable IPv6 from Steam client as a workaround instead of disabling it system-wide?
> Any way to set socket creation as _IPv4 stream_ instead of IPv6 (i.e. force specify _AF_INET_ instead of _AF_INET6_ in the _domain_ [parameter](http://man7.org/linux/man-pages/man2/socket.2.html)) when steam creates a connection?

This seems to be fixed in the beta client at least. I would give that a shot.

**Comment by Emanem** [comment]
> This seems to be fixed in the beta client at least. I would give that a shot.

Not really? Download speed of pacthes was around 300 KiB/s...?

**Comment by pralhadsapre** [comment]
Disabling IPv6 with the following commands worked for me on Ubuntu 18.04 LTS

`sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1`
`sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`
`sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1`
`sudo systemctl restart networking`

I was getting abysmal speeds of 100 Kbps before, after that it spiked up to 7 Mbps.

**Comment by Emanem** [comment]
If only there was an easy way to _LD_PRELOAD_ the steam client, I could pre load a library with a modified _socket_ API to fake the system doesn't support IPv6...

**Comment by Vitorvlv** [comment]
Just wanted to say that this issue it's still alive and well.

Disabling Ipv6 returns downloads to the expected speed. The issue is that I need to have Ipv6 enabled, so this workaround is not very useful for my situation.

**Comment by Emanem** [comment]
Hi Valve (@kisak-valve), this has been open for almost a year.

Having the workaround to _always_ disable IPv4 when downloading a big game/update is ok for some months - but now, after such long time, could you at least provide the option to switch off IPv4 usage for the Steam client?

Thanks!

**Comment by Emanem** [comment]
Hi, any update about this ask?
Would it be possible to implement it?

**Comment by Emanem** [comment]
Update: looks like things are now working ok (I'm on latest beta) and can use 100% my bandwidth without disabling IPv6.

**Comment by Emanem** [comment]
@kisak-valve should we close this?

**Comment by kisak-valve** [comment]
Is anyone else still experiencing this issue on an up to date system?

**Comment by sodd** [comment]
ipv6 seems to works if you are on latest beta

**Comment by kisak-valve** [comment]
Closing per recent comments.

**Comment by baumi1337** [comment]
Unfortunately I'm still experiencing this behavior. I tested OpenSUSE TW and Leap, Manjaro and Ubuntu 20.04 all of these four distributions had this problem although all systems were up to date and the steam beta was enabled.

**Comment by Seil0** [comment]
I'm also experiencing this behavior. I'm not sure since when exactly it's happening again, but i'm sure it was not there 2/3 months ago. Disabling IPv6 solves the Problem.

**Comment by Emanem** [comment]
Working ok on Ubuntu 20.04.1 - Steam beta.

**Comment by msschw** [comment]
Experiencing this on archlinux in steam and steam beta. Disabling ipv6 fixes download issues.

**Comment by UserCommon** [comment]
Experiencing this on arch and ipv6 disabling not working for me.

**Comment by UnknownGitX** [comment]
Experiencing this on Kubuntu 20.04 (Ubuntu 20.04.3 LTS x86_64). Kernel: 5.11.0-41-generic . Disabling IPv6 fixes this problem.

**Comment by shaunrd0** [comment]
Also seeing this on Kubuntu 20.04. Disabled IPv6 and all is good now, download speeds are normal again.

Linux 5.13.0-22-generic #22~20.04.1-Ubuntu SMP Tue Nov 9 15:07:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by KassabNova** [comment]
I'm on Ubuntu 20.04. Got a peak of 133Kb/s.  Disabled IPv6, but still slow.

**Comment by xadips** [comment]
If anyone stumbles upon here currently experiencing slow download issues: https://github.com/ValveSoftware/steam-for-linux/issues/10248
