### ISSUE TITLE
steam-runtime on ubuntu 19.04

### ISSUE THREAD

**Issue by superbonaci** [ValveSoftware/steam-for-linux#6492]
Install steam on ubuntu 19.04 from /usr/bin/gnome-software

After first launch prompts to update, do it, then it will close. 

When you try to reopen it says:

    ~$ steam
    tar: This does not look like a tar archive
    xz: (stdin): File format not recognized
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    find: ‘/home/user/.steam/ubuntu12_32/steam-runtime’: No such file or directory

Fixed with
    mkdir /home/user/.steam/ubuntu12_32/steam-runtime

Now launching steam shows:

    ~$ steam
    Running Steam on ubuntu 19.04 64-bit
    STEAM_RUNTIME is enabled automatically
    Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
    Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
    Forced use of runtime version for 64-bit libcurl.so.4. Host: 4.5.0 Runtime: 4.2.0
    Forced use of runtime version for 64-bit libSDL2-2.0.so.0. Host: 0.9.0 Runtime: 0.9.0
    Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
    Forced use of runtime version for 32-bit libSDL2-2.0.so.0. Host: 0.9.0 Runtime: 0.9.0
    Forced use of runtime version for 32-bit libdbus-1.so.3. Host: 3.19.9 Runtime: 3.5.8
    [2019-09-15 10:33:50] Startup - updater built Sep 10 2019 10:37:04
    [2019-09-15 10:33:50] Verifying installation...
    [2019-09-15 10:33:50] Unable to read and verify install manifest /home/user/.steam/package/steam_client_ubuntu12.installed
    [2019-09-15 10:33:50] Verification complete
    [2019-09-15 10:33:50] Downloading update...
    [2019-09-15 10:33:50] Checking for available updates...
    [2019-09-15 10:33:50] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
    [2019-09-15 10:33:50] Download complete.
    [2019-09-15 10:33:50] uninstalled manifest found in /home/user/.steam/package/steam_client_ubuntu12 (1).
    [2019-09-15 10:33:50] Extracting package...
    [2019-09-15 10:33:59] Installing update...
    [2019-09-15 10:34:17] Cleaning up...
    [2019-09-15 10:34:17] Update complete, launching Steam...
    [2019-09-15 10:34:17] Shutdown
    Restarting Steam by request...
    Running Steam on ubuntu 19.04 64-bit
    STEAM_RUNTIME has been set by the user to: /home/user/.steam/ubuntu12_32/steam-runtime
    Pins up-to-date!
    [2019-09-15 10:34:18] Startup - updater built Sep 10 2019 10:37:04
    [2019-09-15 10:34:18] Verifying installation...
    [2019-09-15 10:34:18] Verification complete
    STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy

**Comment by Tallicia** [comment]
`mkdir /home/$(whoami)/.steam/ubuntu12_32/steam-runtime`

worked great, thanks!

Fixed:
$ mkdir /home/$(whoami)/.steam/ubuntu12_32/steam-runtime
$ steam
Running Steam on ubuntu 19.04 64-bit
STEAM_RUNTIME is enabled automatically

before the ugh....

$ steam
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/$(whoami)/.steam/ubuntu12_32/steam-runtime’: No such file or directory

**Comment by MasterCATZ** [comment]
ugh this issue still exists years later ,, 

thanks for reminding me what yet another quick fix for installing steam was
