### ISSUE TITLE
Remote Play Together not working

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6605]
#### Your system information

* Steam client version (build number or date): October 19
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

System info: https://gist.github.com/LiamDawe/4a7e176995f34180a944c0bab702bbbf

#### Please describe your issue in as much detail as possible:

Trying to connect with someone from the Uk to Finland doesn't seem to work. Unsure if it's the country or not, just mentioning in case it is.

We both tried as host, it just gives a connection error after the Steam loading screen with the spinner in the corner.

Tested across CRYPTARK, Wizard of Legend and Enter the Gungeon. All three mention Remote Play Together supported.

Log: https://gist.github.com/LiamDawe/468f94e3f492f7b4ff4102f378edb3fe

Here is log from the other person, when they were trying to connect to me: https://gist.github.com/LiamDawe/a21f0621b7193e4782f8d3244ac6b281

**Comment by Nemoder** [comment]
Same issue here, I tested with different machines on different networks, the only way it would work is if a windows client was connecting, never worked with a Linux client.

**Comment by hexdsl** [comment]
Same issue here. Can HOST a game for a windows user but cant not JOIN a windows OR linux host.

**Comment by NTMan** [comment]
Same issue on Fedora Rawhide
Here output: https://gist.github.com/NTMan/13ca98b495ee27735af8300acd28e89e

**Comment by NoXPhasma** [comment]
Same here, even opening ports, as described in the FAQ, doesn't help.

**Comment by kadogo** [comment]
I had first an connection issue (and I didn't saw the remote play together menu).
After passing from Steam beta -> Steam -> Steam beta again I saw the menu.

I can host for my friend to join but I cannot join him (he used a Windows).
My log when try to join him is this one.

https://gist.github.com/kadogo/b9a3b8e3197cfbf65aa4500799a506ec

**Comment by Bumbadawg** [comment]
Seems like X window is not correctly set: BadWindow
Connecting from KDE Linux => Win10

https://gist.github.com/Bumbadawg/cde4d3672881d448941cfc522e0b8006

**Comment by ThaChillera** [comment]
Exact same issue as posted [here](https://steamcommunity.com/groups/homestream/discussions/1/3159763879062781724/), all API calls fail for some reason

I'm on Arch, latest updates

**Comment by ThaChillera** [comment]
Update: someone on the steam forums seems to have triaged the issue - curl calls 0.0.0.0:0 - Link: https://steamcommunity.com/groups/homestream/discussions/1/3159763879062781724/?tscn=1572272619

**Comment by LiamDawe** [comment]
Seems to be fixed now, tested with someone earlier.

Could someone else update to the latest beta and confirm so I can close this?

**Comment by NoXPhasma** [comment]
Doesn't work for me with a friend. While we are now able to connect to each other, the client always only gets a black screen:

1) Host sends invite
2) Client accepts and gets a black screen with a loading icon
3) Host gets notification that client has connected
3) Client still has a black screen with loading bar, can see hosts mouse movement
4) Client window clothes
5) Host doesn't get notified about Client not connected anymore
6) When Host exists the game,  Steam completely freezes and needs to be hard killed

This was reproducible on both sides.

**Comment by LiamDawe** [comment]
@NoXPhasma weird, was perfect here. Are you on AMD GPUs?

**Comment by NoXPhasma** [comment]
No we were both with Nvidia (GTX 660 & GTX 1080). Also distributions differ, I'm on Linux Mint 19.2, my friend is on Arch.

**Comment by hexdsl** [comment]
While I can now connect to friends an they can connect to me (tested with Arch and Manjaro) the overlay often freezes making it impossible to play as well as often it simply fails to launch properly. however i think these are different issues at this point.

**Comment by tuomount** [comment]
I had to install on both machine Steam Beta client just to see each others in Steam. Having one machine newest beta it still did not show up in machine list if another was official steam client. After trying to stream game from one to other. Client steam timeouts and one which is running the game steam client crash. Both machines are running Ubuntu 16.04.

**Comment by TTimo** [comment]
The HTTP 500 / CURL error code 1 problems have been fixed in most recent betas and client release. If there are still problems they are likely something else, please provide new sets of logs (or open new bugs).

**Comment by NTMan** [comment]
I confirm that problems with accepting the invite in the play together were fixed.

But still some problems are not fixed:
1) streaming client crashes when the user switched in another application. Here is crash dump:
[crash_20191101001100_2.dmp](https://github.com/ValveSoftware/steam-for-linux/files/3796628/crash_20191101001100_2.zip)
[mikhail_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3796629/mikhail_log.zip)
[mikhail_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/3796630/mikhail_stdout.zip)


2) streaming host capture all sounds (not only from the game) which means what streaming client hears the self voice from chat this is very annoying.

**Comment by kisak-valve** [comment]
Hello @NTMan, [1] is being tracked at #6401, [2] is at #6625.

**Comment by LiamDawe** [comment]
Well connecting works for me now as it seems it does other too, the other problems seem to be new issues so I guess this can be closed?

**Comment by edoantonioco** [comment]
If a person with windows pc host, and me a linux user try to connect to his stream, it wont work, it says that it was not able to connecto to the remote system
