### ISSUE TITLE
Most of my Proton games are unable to enable remote play.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6705]
I was able to play the Proton games via Remote Play, but now I can't.
#### Your system information

* Steam client version (build number or date): 2019/11/20
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Some of the games are unable to enable remote play, there is no streaming option.

#### Steps for reproducing this issue:

1. Try to stream the game.
2. I can't, the streaming button just doesn't appear.

**Comment by laichiaheng** [comment]
I is solved without any tweaking, weird.

**Comment by megatog615** [comment]
Please re-open this bug. There are days when this bug affects me, and other days when it suddenly starts working again. This bug is not resolved, and its temperamental nature is particularly frustrating.

Right now I'm trying to stream Mordhau to my laptop, and my laptop can only "see" Linux games on the host. However, both computers connect to each other(giving the Remote Play "the other computer is available" notification).

**Comment by megatog615** [comment]
So, today it stopped working again on the beta client. I switched back to the stable client, then switched back to the beta client and it allowed me to stream again.

Definitely still a bug. Please re-open.
