### ISSUE TITLE
Steam cannot be installed - python is gone, can't install the dependency (Ubuntu 20)

### ISSUE THREAD

**Issue by AkashaP** [ValveSoftware/steam-for-linux#6869]
#### Your system information

* Distribution (e.g. Ubuntu): Ubuntu 20
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, updating caused the problem

#### Steps for reproducing this issue:

1. Updated system from software center (apt update && apt upgrade)
2. Restart
3. Steam is gone

Check apt history with cat /var/log/apt/history.log
Shows:

Remove: steam-launcher:amd64 (1.0.0.61), python:amd64 (2.7.17-1), libgcc1:i386 (1:9.2.1-25ubuntu1), libpython-stdlib:amd64 (2.7.17-1), python-scour:amd64 (0.37-2), python-minimal:amd64 (2.7.17-1)

#### Attempts to fix
1.
> \> apt install python

```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal:i386 python2:i386 python2-minimal python2 2to3

E: Package 'python' has no installation candidate
```

2. 
> Bind python to python3 in ~/.bashrc

doesn't work, apt still thinks python is not there

3.
> Use aptitude to install python

same error as 1.

Anyone know how to reroute the python package to python3?

**Comment by Draika** [comment]
I found a workaround thanks to a blog:

https://coderwall.com/p/hes3ha/change-the-dependencies-of-a-deb-package

1. download steam latest deb from steam website
2. Unpack deb: ar x steam-latest.deb (will create i.e. three files: debian-binary control.tar.gz data.tar.gz)
2. Unpack control archive: tar xzf control.tar.gz (will create: postinst md5sums control)
3. Open control in a text editor and change the dependency "python" to "python3"
4. Repack control.tar.gz: tar c postinst md5sums control | gzip -c > control.tar.gz
5. Repack deb: ar rcs steam-launcher.deb debian-binary control.tar.gz data.tar.gz
6. install with dpkg -i steam-launcher.deb

**Comment by arrowgent** [comment]
python2 is EOL, is python3 what Ubuntu 20.04 ships with by default?

**Comment by AkashaP** [comment]
Both python 2 and 3 are available, but the package "python", which used to be python 2, appears to be removed and can no longer be installed

**Comment by kaimast** [comment]
> Both python 2 and 3 are available, but the package "python", which used to be python 2, appears to be removed and can no longer be installed, and that is what steam lists as a dependency

Correct. The `python` package has been renamed to `python2`. 

Steam really should not depend on an obsolete package like this until there is some really good reason.

**Comment by kaimast** [comment]
By the way, an easier mechanism to circumvent this is to use dpkg --force-depends it seems.

**Comment by pkkid** [comment]
The workaround from @AkashaP worked for me. It's interesting that it ended up installing the Python2 packages even though we specified Python3 as the dependency.

**Comment by kaimast** [comment]
> The workaround from @AkashaP worked for me. It's interesting that it ended up installing the Python2 packages even though we specified Python3 as the dependency.

The package is fixed by now, isn't it? At least the one from the Ubuntu sources works without problems.

**Comment by pkkid** [comment]
Ohh, I downloaded the deb from the website and it was still broken today.

**Comment by bmhm** [comment]
> By the way, an easier mechanism to circumvent this is to use `dpkg --force-depends` it seems.

It will be uninstalled the next time you run `apt`.

**Comment by smcv** [comment]
Launcher version 1.0.0.62 (currently considered to be a beta, because there are quite a lot of changes since 1.0.0.61) uses `python3`. Please try it: https://repo.steampowered.com/steam/archive/precise/steam-launcher_latest-beta_all.deb

**Comment by pkkid** [comment]
I unfortunately went back to Ubuntu 19.10 due to other unrelated issues the beta, so will not be able to test this myself.

**Comment by bmhm** [comment]
> Launcher version 1.0.0.62 (currently considered to be a beta, because there are quite a lot of changes since 1.0.0.61) uses python3. Please try it: 
> https://repo.steampowered.com/steam/archive/precise/steam-launcher_latest-beta_all.deb


I was able to install it just fine. I don't know if it helps, here is the stdout when starting steam:

```
(user@host)[~/Downloads] $ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
$HOME/Steam/ubuntu12_32/steam
[2020-04-09 09:52:39] Startup - updater built Apr  3 2020 22:37:06
[2020-04-09 09:52:39] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
[2020-04-09 09:52:40] Verifying installation...
[2020-04-09 09:52:42] Verification complete
Gtk-Message: 09:52:49.273: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 09:52:49.275: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 09:52:49.276: Failed to load module "gail"
Gtk-Message: 09:52:49.276: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1585956310)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
CAppInfoCacheReadFromDiskThread took 267 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
[0409/095257.500567:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Local Device Found
  type: 045e 028e
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      XInput Controller
  Release:      681
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Disconnecting zombie controller 0
Scheduled disconnect of controller 0
CApplicationManagerPopulateThread took 1711 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
[0409/095259.151178:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0409/095259.151245:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1585953461
[0409/095259.151250:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0409/095259.151254:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
Local Device Found
  type: 045e 028e
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      XInput Controller
  Release:      681
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)

** (steam:10164): WARNING **: 09:53:01.159: Unknown device type 13

** (steam:10164): WARNING **: 09:53:01.159: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:10164): WARNING **: 09:53:01.159: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:10164): WARNING **: 09:53:01.172: Unknown device type 14

** (steam:10164): WARNING **: 09:53:01.172: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type

** (steam:10164): WARNING **: 09:53:01.173: Unknown device type 13

** (steam:10164): WARNING **: 09:53:01.173: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type
Installing breakpad exception handler for appid(steam)/version(1585956310)
Setting VR Path Registry runtime path to $HOME/Steam/SteamApps/common/OpenVR
Setting VR Path Registry config path to $HOME/Steam/config
Setting VR Path Registry log path to $HOME/Steam/logs
Setting VR Path Registry runtime path to $HOME/Steam/SteamApps/common/OpenVR
Setting VR Path Registry config path to $HOME/Steam/config
Setting VR Path Registry log path to $HOME/Steam/logs
Setting VR Path Registry runtime path to $HOME/Steam/SteamApps/common/OpenVR
Setting VR Path Registry config path to $HOME/Steam/config
Setting VR Path Registry log path to $HOME/Steam/logs
Loaded client id: 1037948166255398894
Installing breakpad exception handler for appid(steam)/version(1585956310)
Listening for IPv4 broadcast on: 27036
Listening for connections on: 0.0.0.0:27036
Opted-in Controller Mask for AppId 0: 6
Installing breakpad exception handler for appid(steam)/version(1585956310)

** (steam:10164): WARNING **: 09:53:02.331: Unknown setting 'proxy'

** (steam:10164): WARNING **: 09:53:02.331: Ignoring invalid property 'route-data'

** (steam:10164): WARNING **: 09:53:02.331: Ignoring invalid property 'address-data'

** (steam:10164): WARNING **: 09:53:02.331: Ignoring invalid property 'address-data'

** (steam:10164): WARNING **: 09:53:02.331: Ignoring invalid property 'route-data'

** (steam:10164): WARNING **: 09:53:02.331: Ignoring invalid property 'interface-name'

** (steam:10164): WARNING **: 09:53:02.332: Unknown setting 'proxy'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'address-data'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'dns-priority'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'route-data'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'address-data'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'dns-priority'

** (steam:10164): WARNING **: 09:53:02.332: Ignoring invalid property 'route-data'

** (steam:10164): WARNING **: 09:53:02.332: Unknown setting 'bridge'

** (steam:10164): WARNING **: 09:53:02.332: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/2 settings: (3) type
Controller 0 connected, configuring it now...
Installing breakpad exception handler for appid(steam)/version(1585956310)
Controller has an Invalid or missing unit serial number, setting to '45e-28e-54ccb8e'
Controller 0 disconnected
Controller 0 connected, configuring it now...

(steam:10164): Gtk-WARNING **: 09:53:02.746: gtk_disable_setlocale() must be called before gtk_init()
BYieldingQueryAccountsRegisteredToController
BYieldingQueryAccountsRegisteredToController
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:10164): Gtk-WARNING **: 09:53:02.952: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
local (potentially out of sync) copy of roaming config loaded - 17066 bytes.
!! Controller 0 attributes:
  Type: 31
  ProductID: 654
  Serial: 45e-28e-54ccb8e
  Capabilities: 001843ff
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Could not load local selection (), local override ($HOME/Steam//controller_config/bigpicture_gamepad.vdf), or user path ($HOME/Steam/userdata/88918926/config/controller_configs/bigpicture_gamepad.vdf), checking last resort path: $HOME/Steam//controller_base/bigpicture_gamepad.vdf
Fossilize INFO: Overriding serialization path: "$HOME/Steam/shader_cache_temp_dir_vk_64/fozpipelinesv4/steamapprun_pipeline_cache".
Loaded Config for Last Resort Path for App ID 413090, Controller 0: $HOME/Steam//controller_base/bigpicture_gamepad.vdf
[413090]Non-Steam Controller Configs Enabled: 1
Loaded Config for Local Selection Path for App ID 413090, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/1557881022/956347096063773104_legacy.bin
Opted-in Controller Mask for AppId 413080: 6
Loaded Config for Local Selection Path for App ID 413080, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/922638163/818937737353552570_legacy.bin
[413080]Non-Steam Controller Configs Enabled: 1
!! Controller 0 attributes:
  Type: 31
  ProductID: 654
  Serial: 45e-28e-54ccb8e
  Capabilities: 001843ff
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Loaded Config for Local Selection Path for App ID 413080, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/922638163/818937737353552570_legacy.bin
Fetching Config Sets 0
CClientJobFetchPersonalizationFileID
Installing breakpad exception handler for appid(steam)/version(1585956310)
Installing breakpad exception handler for appid(steam)/version(1585956310)
Set Account Config Sets 0 1 1
[0409/095305.911757:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0409/095305.911869:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1585953461
[0409/095305.911878:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0409/095305.911891:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0409/095305.913094:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
Scheduled disconnect of controller 0
roaming config store loaded successfully - 17066 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 43ms
[0409/095307.183900:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0409/095307.184017:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1585953461
[0409/095307.184027:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0409/095307.184036:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0409/095307.243717:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Local Device Found
  type: 045e 028e
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      XInput Controller
  Release:      681
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Installing breakpad exception handler for appid(steam)/version(1585956310)
Controller 0 disconnected
Controller 0 connected, configuring it now...
Controller has an Invalid or missing unit serial number, setting to '45e-28e-54ccb8e'
BYieldingQueryAccountsRegisteredToController
[0409/095311.341341:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0409/095312.288930:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0409/095312.999584:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[413080-650764041]: Successfuly started tracking playtime
Installing breakpad exception handler for appid(steam)/version(1585956310)
Unable to read VR Path Registry from $HOME/.config/openvr/openvrpaths.vrpath
ExecCommandLine: "'$HOME/Steam/ubuntu12_32/steam'"
System startup time: 30.82 seconds
Fetching Config Sets 0
CClientJobFetchPersonalizationFileID
!! Controller 0 attributes:
  Type: 31
  ProductID: 654
  Serial: 45e-28e-54ccb8e
  Capabilities: 001843ff
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Loaded Config for Local Selection Path for App ID 413090, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/1689651975/1007024772344596662_legacy.bin
[413090]Non-Steam Controller Configs Enabled: 1
Loaded Config for Local Selection Path for App ID 413090, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/754616467/266097744495173226_legacy.bin
Loaded Config for Local Selection Path for App ID 413080, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/650764041/controller_configuration.vdf
[413080]Non-Steam Controller Configs Enabled: 1
[0409/095318.684958:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0409/095318.693984:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Warning: failed to set thread priority: set failed for 4: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 4
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Set Account Config Sets 0 1 1
Installing breakpad exception handler for appid(steam)/version(1585956310)
Unable to read VR Path Registry from $HOME/.config/openvr/openvrpaths.vrpath
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Selection Path for App ID 413080, Controller 0: $HOME/Steam/SteamApps/workshop/content/241100/650764041/controller_configuration.vdf
Warning: failed to set thread priority: set failed for 4: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 4
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
BuildCompleteAppOverviewChange: 201
RegisterForAppOverview 1: 16ms
RegisterForAppOverview 2: 16ms
Unable to read VR Path Registry from $HOME/.config/openvr/openvrpaths.vrpath
Unable to read VR Path Registry from $HOME/.config/openvr/openvrpaths.vrpath
```

**Comment by rgreid** [comment]
> Launcher version 1.0.0.62  
> https://repo.steampowered.com/steam/archive/precise/steam-launcher_latest-beta_all.deb

@smcv thanks. It's failing to load here: Ubuntu Focal 20.04 beta at 12th April. 

<details>
    <summary>Heres the console output after a complete reinstall using the beta deb above: </summary>

```
[2020-04-12 21:08:38] Installing update...
[2020-04-12 21:08:38] Cleaning up...
[2020-04-12 21:08:38] Update complete, launching...
[2020-04-12 21:08:38] Shutdown
Restarting Steam by request...
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/user/.local/share/Steam/ubuntu12_32/steam-runtime
Forced use of runtime version for 32-bit libdbus-1.so.3. Host: 3.19.11 Runtime: 3.5.8
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 32-bit libvulkan.so.1. Host: 1.2.131 Runtime: 1.2.135
Found newer runtime version for 64-bit libopusfile.so.0. Host: 0.4.2 Runtime: 0.4.4
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libopusurl.so.0. Host: 0.4.2 Runtime: 0.4.4
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Forced use of runtime version for 64-bit libcurl.so.4. Host: 4.6.0 Runtime: 4.2.0
Found newer runtime version for 64-bit libvulkan.so.1. Host: 1.2.131 Runtime: 1.2.135
/home/user/.local/share/Steam/ubuntu12_32/steam
[2020-04-12 21:09:16] Startup - updater built Apr  4 2020 00:37:13
Installing breakpad exception handler for appid(steam)/version(1586022601)
Installing breakpad exception handler for appid(steam)/version(1586022601)
[2020-04-12 21:09:16] Verifying installation...
[2020-04-12 21:09:16] Verification complete
Failed to load steamui.so - dlerror(): /usr/lib/i386-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref
[2020-04-12 21:09:20] Shutdown
```
</details>

**Comment by kisak-valve** [comment]
Hello @rgreid, please open a new issue report so your issue can be tracked properly.

**Comment by smcv** [comment]
> Failed to load steamui.so - dlerror(): /usr/lib/i386-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref

That looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955331, which is a Debian/Ubuntu bug, not a Steam bug. (We have no idea why it happens to some users, but not to most users.)

**Comment by rgreid** [comment]
@smcv it's working, thanks!  This Ubuntu install has been upgraded a few times and there was some stale i386 libs around circa 2015. Removed them and it loads fine, thanks. 
  
@kisak-valve sorry I see now this wasn't a Python3 issue!

**Comment by kisak-valve** [comment]
@rgreid, for the random user who discovers this down the road, can you list the stale package(s) you suspect caused your issue?

**Comment by smcv** [comment]
It isn't a stale package, it's a stale file installed by a package. For some reason old versions of `/lib/*-linux-gnu/libglib-2.0.so.0*` don't always seem to have been deleted by dpkg when the `libglib2.0-0` package is upgraded, and they are treated as "more important than" the newer version in `/usr/lib/*-linux-gnu/libglib-2.0.so.0*`.

The GLib maintainers don't know why this happens, and neither do the dpkg maintainers.

**Comment by amanda-santini** [comment]
I still can't get it to run. I'm on a fresh install of Ubuntu 20.04.

I haven't tried smcv's solution yet. But still, it's 2020, we shouldn't have these kinds of problems.

**Comment by amanda-santini** [comment]
@smcv By "move out of the way", do you mean I can delete the 'libglib-2.0.so.0' and 'libglib-2.0.so.0.6400.3' files from '/lib/x86_64-linux-gnu/'? Or do I have to copy the files from '/usr/lib/x86_64-linux-gnu/' to '/lib/x86_64-linux-gnu/' after deleting them?

**Comment by amanda-santini** [comment]
Before doing anything I decided to see if the files are actually identical. Turns out they are:

amanda@amanda:~$ sha1sum /lib/x86_64-linux-gnu/libglib-2.0.so*
c4bf1432a364e59574029dc6ef320bf6e39bd9cd  /lib/x86_64-linux-gnu/libglib-2.0.so.0
c4bf1432a364e59574029dc6ef320bf6e39bd9cd  /lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3
amanda@amanda:~$ sha1sum /usr/lib/x86_64-linux-gnu/libglib-2.0.so*
c4bf1432a364e59574029dc6ef320bf6e39bd9cd  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
c4bf1432a364e59574029dc6ef320bf6e39bd9cd  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.3

I think this can't be my issue.
