### ISSUE TITLE
Music library update thread using more cpu resources than expected

### ISSUE THREAD

**Issue by StatusCode404** [ValveSoftware/steam-for-linux#7372]
#### Your system information

* Steam client version (build number or date): **Sep 102020 at 05:50:00**
* Distribution (e.g. Ubuntu): **Ubuntu 18.04.5 LTS; Kernel: 5.8.8-050808-generic**  **Using Kisak-mesa 20.1.8**
* Opted into Steam client beta?: [Yes/No] **Yes**
* Have you checked for system updates?: [Yes/No] **Yes**

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

**After starting Steam, the process goes to 100% and stays there constantly and never terminates.  It's been doing that since the last update.  Restarting or killing the process and restarting does not stop the issue.**

#### Steps for reproducing this issue:

1. **Start Steam or Restart Steam**

**Comment by StatusCode404** [comment]
Is there any update on this?  Anything that I should provide to help resolve this?  I killed the process over the weekend but restarted it today.  It hovered around 10%-20% for about half-hour.  Now it is a flat 100% after running for half a day.  What is it doing?
![image](https://user-images.githubusercontent.com/63637406/93739153-efc96280-fc2a-11ea-95f2-e9eeb6d9b0f4.png)

**Comment by TTimo** [comment]
To confirm: the Steam client otherwise works (it did not hang during startup for instance). And your issue is that one (or more) of the threads in the steam process are stuck using 100% CPU.

I think there are some open issues in this database that related to this.

- Is this specific to steam beta, or does the main release client do this as well.

- Can you identify which thread(s) is stuck. A good way to do this is to use htop: "To enable thread views in htop, launch htop, and press F2 to enter htop setup menu. Choose "Display option" under "Setup" column, and toggle on "Tree view" and "Show custom thread names" options. Presss F10 to exit the setup."

- Check your `~/.steam/steam/logs` folder for any information that may be relevant. Such as some warnings / messages spamming and constantly repeating?

**Comment by StatusCode404** [comment]
> To confirm: the Steam client otherwise works (it did not hang during startup for instance). And your issue is that one (or more) of the threads in the steam process are stuck using 100% CPU.
> 
> I think there are some open issues in this database that related to this.
> 
>     * Is this specific to steam beta, or does the main release client do this as well.

**I'll try this next.  I suppose all I have to do is opt out ot Beta and the stable version will download?**
> 
>     * Can you identify which thread(s) is stuck. A good way to do this is to use htop: "To enable thread views in htop, launch htop, and press F2 to enter htop setup menu. Choose "Display option" under "Setup" column, and toggle on "Tree view" and "Show custom thread names" options. Presss F10 to exit the setup."

**I have pasted the image at the bottom of this message**
>
>     * Check your `~/.steam/steam/logs` folder for any information that may be relevant. Such as some warnings / messages spamming and constantly repeating?

**I opened every single log file in that folder using glogg and enabled "follow" for each.  There were no repeating red flags you tend to see with infinite error exceptions in a loop.  Half the files were not even update today. Out of those that were updated today, all stopped logging anything after initial bootstrap startup of the client.  
The only 3 files that updated after an hour or so basically showed nothing important (no: failures, warnings, errors).  The 3 files that updated were appinfo, configstore, and connection logs.  All of them just logged normal sort of info stuff.  None of them repeating and filling up disk space.  All 3 log intervals are large at 15mins (appinfo and configstore) to an hour (connection).**

![image](https://user-images.githubusercontent.com/63637406/93834488-7039a300-fcbf-11ea-83fb-479c92ff5d88.png)

**Comment by StatusCode404** [comment]
>     * Is this specific to steam beta, or does the main release client do this as well.
I have tested with the main release client for a day and it works fine.  The high core usage did not happen.  It is only happening with the beta.

**Comment by TTimo** [comment]
Is this due to the friends list? See https://github.com/ValveSoftware/steam-for-linux/issues/7241 - you are not reporting high cpu in `steamwebhelper` though so I think this is something else.

**Comment by StatusCode404** [comment]
> Is this due to the friends list? See #7241 - you are not reporting high cpu in `steamwebhelper` though so I think this is something else.

I don't think so because I'm always offline.

**Comment by luni3359** [comment]
I'm not sure if this applies here, but I was experiencing 100% CPU usage as well, and it turned out to be that the ``Allow background processing of Vulkan shaders`` option that was making it do so. The problem went away after Steam finished processing the shaders.

**Comment by StatusCode404** [comment]
I have that disabled and still experienced the 100%

**Comment by robobenklein** [comment]
Also seeing this issue on the stable branch:
![image](https://user-images.githubusercontent.com/5423266/94404902-b8344c00-013d-11eb-9bc9-65fecdb37bee.png)

Background shader processing is on, but I don't think it's that because it's been stuck at 100% for many hours.

![image](https://user-images.githubusercontent.com/5423266/94405130-1cefa680-013e-11eb-9c89-a065b2e20b11.png)
(Game running 05:00-17:00, I was not at my computer 17:00-03:00 and nothing else was consuming CPU)

Steam built Sep 3 2020, 21:18:20 (package `1599174997`)

**Comment by TTimo** [comment]
@robobenklein can you identify which of your steam threads (by name) is using a full core (it was 2074097 in your screenshot)? Notice that in @StatusCode404's report all the steam threads are idle except the main one.

**Comment by robobenklein** [comment]
I will try to capture as much info when I encounter the bug again, I restarted steam before making a full stack trace to have it's stdout in a terminal.

**Comment by leon-matthews** [comment]
I'm also seeing 100% CPU usage on Ubuntu 20.04, stable steam, on the thread _CLocalLibraryCr_:
![steam-100-percent](https://user-images.githubusercontent.com/921614/95527618-4d82ea80-0a32-11eb-911d-a918aa8e960b.png)

**Comment by TTimo** [comment]
That's the music library crawl. It gets bogged down and very slow, especially when you have titles with high file count installed. Unturned for instance, with 37k files in Maps/Germany/Foliage ..

**Comment by mlassnig** [comment]
Can confirm. Disabling the music library crawl solved the 100% CPU issue for me.

**Comment by StatusCode404** [comment]
Excellent @TTimo !

The latest stable Steam release started doing the same thing of consuming 100% of a core.
I switched to Beta again, and same thing!

I removed all paths in the Music settings and disabled "Scan at startup", "Scan Steam folders for soundtracks", and I reset the music database so there were no items.

Voila!!!!  no more 100% cpu usage!

Now someone has to bisect the code to figure out why this has suddenly become a problem for stable and beta when it never was before.  For now we have a workaround, but it is distastes-full to have disabled functionality because of something wrong with it especially on a stable release!

Further notes, my entire music library is in folder in a mounted btrfs RAID5 volume.  The music folder is 104.2 GB with 19,058 items.  There are no access permission issues with the folder being owned by me.  Also since this has never been a problem before with previous steam versions.

**Comment by leon-matthews** [comment]
I can confirm that the work-around of disabling scanning music library worked for me. Thanks!

**Comment by WGH-** [comment]
I noticed that it ventured into Proton directory, which contained a symlink to the root, and basically ended up with infinite recursion.

`openat(AT_FDCWD, "/mnt/games/SteamLibrary/steamapps/common/Proton 5.13/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.13/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.13/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.0/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.0/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.0/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common/Proton 5.0/dist/share/default_pfx/dosdevices/z:/mnt/games/SteamLibrary/steamapps/common", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 123`

**Comment by WGH-** [comment]
The scanner keeps reenabling itself for me, by the way.

**Comment by liskin** [comment]
Same here, the scanner gets infinitely deep:

```
[pid 3738769] access("/data/tomi/.steam/steamapps/common/Proton 4.11/dist/share/default_pfx/dosdevices/z:/proc/1/root/proc/1/root/proc/1/root/proc/1/root/data/hudba/Children of Bodom/2000 - Hate Me (single)", F_OK) = 0
```

**Comment by robobenklein** [comment]
So a temporary workaround could be either disabling following of symlinks in the scan or add a symlink depth cutoff? (I think following a maximum of 2 symlinks would be acceptable.)

Although I normally would not think that anything in the auto-generated wine prefix needs to be searched for music, right?

**Comment by Plagman** [comment]
Please re-test today's Beta client, thanks!

**Comment by mlassnig** [comment]
@Plagman Thanks!

I added a Proton bundle (just to make sure one exists, judging from the ChangeLog), reset the music database, and restarted. Took a minute or so and my albums were found again, with no excessive CPU usage anymore.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2021-03-22](https://store.steampowered.com/news/app/593110/view/3006688962897471639) Steam client update.

**Comment by kkartaltepe** [comment]
It seems like this is still an issue with an Oct 13 2021 build, Steam package version: 1634158817. One core was burning 100% cpu until disabling the music library scanning in settings. Perf reported CLocalLibraryCr as someone had reported earlier.

**Comment by exa18** [comment]
confirm, opened only Deck and rised CPU usage to 1/3 (all cores). This issue also prevents display to blank (power manager). Also list steam in htop show over 100 pids open where ps reports only 12-15. [ref](https://github.com/ValveSoftware/steam-for-linux/issues/8553#issuecomment-1118188914)
and also despite of output 14 from **ps axjf | grep steam | wc -l**
I get this:
![Screenshot_2022-05-05_21-28-02](https://user-images.githubusercontent.com/17809954/167012178-d7e4d0e7-3e2e-4012-ad00-2c2d35434113.png)

**Comment by edenist** [comment]
Just popping in so say this is still an issue on the latest release version of the steam client. 

Removing all music library locations and disabling auto-scans resolved the issue for me, but the scan still appears to be getting bogged down somewhere.
