### ISSUE TITLE
Ubuntu Segmentation Fault

### ISSUE THREAD

**Issue by moooncube** [ValveSoftware/steam-for-linux#7477]
#### Your system information

* Steam client version (build number or date): Tried both latest from Ubuntu Software Center & .deb from Steampowered.com 
* Distribution (e.g. Ubuntu): Ubuntu 20.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I try to start the Steam client but it crashes. I expected the Steam client to open, but it won't start and doesn't get to the login screen. Console doesn't give any output or errors, just closes after "Verification complete". Error.log file shows segmentation fault error. Nvidia driver 450 with libnvidia-gl-450:i386 is installed.

Console output:
```
mooncube@PC:~$ steam
Running Steam on ubuntu 20.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/mooncube/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2020-11-19 21:07:29] Startup - updater built Oct 28 2020 23:34:22
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-11-19 21:07:29] Loading cached metrics from disk (/home/mooncube/.steam/debian-installation/package/steam_client_metrics.bin)
[2020-11-19 21:07:29] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2020-11-19 21:07:29] Using the following download hosts for Public, Realm steamglobal
[2020-11-19 21:07:29] 1. http://client-download.steampowered.com, /client/, Realm 'steamglobal', weight was 100, source = 'baked in'
[2020-11-19 21:07:29] 2. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2020-11-19 21:07:29] Checking for update on startup
[2020-11-19 21:07:29] Checking for available updates...
[2020-11-19 21:07:29] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-11-19 21:07:30] Download skipped: /client/steam_client_ubuntu12 version 1603992987, installed version 1603992987, downloaded version 0
[2020-11-19 21:07:30] Nothing to do
[2020-11-19 21:07:30] Verifying installation...
[2020-11-19 21:07:30] Performing checksum verification of executable files
[2020-11-19 21:07:31] Verification complete
mooncube@PC:~$ 
```
Error.log (~/.steam/steam/error.log):
```
Installing breakpad exception handler for appid(steam)/version(1603992987)
Installing breakpad exception handler for appid(steam)/version(1603992987)
Installing breakpad exception handler for appid(steam)/version(1603992987)
Loaded SDL version 2.0.13-6142881
Gtk-Message: 21:07:31.584: Failed to load module "gail"
Gtk-Message: 21:07:31.584: Failed to load module "atk-bridge"

(steam:54596): Gtk-WARNING **: 21:07:31.598: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:54596): Gtk-WARNING **: 21:07:31.602: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
assert_20201119210729_1.dmp[54603]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201119210729_1.dmp
/home/mooncube/.steam/debian-installation/steam.sh: line 750: 54596 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20201119210729_1.dmp[54603]: Finished uploading minidump (out-of-process): success = yes
assert_20201119210729_1.dmp[54603]: response: CrashID=bp-dd612f96-2156-42d2-8752-5a8ec2201119
assert_20201119210729_1.dmp[54603]: file ''/tmp/dumps/assert_20201119210729_1.dmp'', upload yes: ''CrashID=bp-dd612f96-2156-42d2-8752-5a8ec2201119''
```

#### Steps for reproducing this issue:

1. Start Steam (from launcher or terminal)
2. That's it
3. ..

**Comment by Tony763** [comment]
Hi, I have exactly same error.
Ubuntu 20.10 Nvidia-455

```
Installing breakpad exception handler for appid(steam)/version(1603992987)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1603992987)
Installing breakpad exception handler for appid(steam)/version(1603992987)
Loaded SDL version 2.0.13-6142881
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"

(steam:72768): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier `direction', expected character `}'

(steam:72768): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  51
xerror_handler: X failed, continuing
assert_20201123173706_1.dmp[72815]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201123173706_1.dmp
/home/tony/.local/share/Steam/steam.sh: řádek 750: 72768 Neoprávněný přístup do paměti (SIGSEGV)                     (core dumped [obraz paměti uložen]) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20201123173706_1.dmp[72815]: Finished uploading minidump (out-of-process): success = yes
assert_20201123173706_1.dmp[72815]: response: CrashID=bp-7bb75d62-e06e-4a5d-b3e0-609da2201123
assert_20201123173706_1.dmp[72815]: file ''/tmp/dumps/assert_20201123173706_1.dmp'', upload yes: ''CrashID=bp-7bb75d62-e06e-4a5d-b3e0-609da2201123''
```

**Comment by kisak-valve** [comment]
Hello @Tony763, swrast is mesa's slower cpu opengl renderer and the fact Steam is trying to use it and failing hints that you're using the nVidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you check that the 32 bit userspace is installed with something like `apt policy libnvidia-gl-455:i386`? If it's not installed, you can run something like `sudo apt install libnvidia-gl-455:i386` to add it to your system.

**Comment by Tony763** [comment]
```
$ apt policy libnvidia-gl-455:i386
libnvidia-gl-455:i386:
  Instalovaná verze: 455.38-0ubuntu0.20.10.1
  Kandidát:          455.38-0ubuntu0.20.10.1
  Tabulka verzí:
 *** 455.38-0ubuntu0.20.10.1 500
        500 http://cz.archive.ubuntu.com/ubuntu groovy-updates/restricted i386 Packages
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by kisak-valve** [comment]
Can you check if any 32 bit OpenGL application works on your system? I used to recommend a 32 bit build of `glxinfo` from `mesa-utils:i386`, however, Ubuntu no longer provides a 32 bit build of this since 20.04.

**Comment by Tony763** [comment]
If I try `glxinfo` for 64 in terminal, I got `Error: unable to open display`

**Comment by kisak-valve** [comment]
If 64 bit OpenGL is broken, you've got bigger problems than just Steam being broken. In general, the nVidia proprietary driver requires that the running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries all have exactly the same version to work properly.

**Comment by Tony763** [comment]
Sry wrong terminal tab.

name of display: :1
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  57
  Current serial number in output stream:  56

**Comment by Tony763** [comment]
32bit from [ubuntuupdates](https://www.ubuntuupdates.org/package/core/groovy/universe/base/mesa-utils)
```

name of display: :1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  99
  Current serial number in output stream:  100
```

**Comment by bonkmaykrQ** [comment]
By the way, I've been told that for some weird reason the package manager version of the Nvidia official driver doesn't seem to support 32-bit applications. I actually wasn't even able to get steam working until I installed the driver manually. 

You need to install the driver with a .run file using a TTY terminal (Ctrl Alt and any function key). 

https://www.nvidia.com/Download/driverResults.aspx/164073/en-us

If you've already done this when you set up your computer, then I'm out of ideas.

**Comment by moooncube** [comment]
> By the way, I've been told that for some weird reason the package manager version of the Nvidia official driver doesn't seem to support 32-bit applications. I actually wasn't even able to get steam working until I installed the driver manually.
> 
> You need to install the driver with a .run file using a TTY terminal (Ctrl Alt and any function key).
> 
> https://www.nvidia.com/Download/driverResults.aspx/164073/en-us
> 
> If you've already done this when you set up your computer, then I'm out of ideas.

I have installed the current driver with the .run file from NVIDIA's site you linked, but I've also tried the installation via "Additional Drivers". Same result. Thanks for the idea though!

**Comment by Tony763** [comment]
Steam started to work, Last thing I installed was `apt-get install libqt5webengine5 libqt5webenginewidgets5`.
But I can't say if it is it.

**Comment by Paxy** [comment]
Same issue. Resolved by:
`sudo apt install libnvidia-gl-455:i386
rm -rf ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*
steam`

**Comment by moooncube** [comment]
Uninstalled the software center version of the Steam launcher and installed the .deb from steampowered.com.
Now I'm at least getting console output, but it still doesn't start. Does this help at all?

`Steam client's requirements are satisfied
/home/mooncube/.local/share/Steam/ubuntu12_32/steam
[2020-11-27 22:31:05] Startup - updater built Oct 28 2020 23:34:22
Installing breakpad exception handler for appid(steam)/version(1603992987)
[2020-11-27 22:31:05] Loading cached metrics from disk (/home/mooncube/.local/share/Steam/package/steam_client_metrics.bin)
[2020-11-27 22:31:05] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2020-11-27 22:31:05] Using the following download hosts for Public, Realm steamglobal
[2020-11-27 22:31:05] 1. http://client-download.steampowered.com, /client/, Realm 'steamglobal', weight was 100, source = 'baked in'
[2020-11-27 22:31:05] 2. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1603992987)
[2020-11-27 22:31:05] Verifying installation...
[2020-11-27 22:31:05] Verification complete
Loaded SDL version 2.0.13-6142881
Gtk-Message: 22:31:05.687: Failed to load module "gail"
Gtk-Message: 22:31:05.687: Failed to load module "atk-bridge"

(steam:17679): Gtk-WARNING **: 22:31:05.705: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:17679): Gtk-WARNING **: 22:31:05.707: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
assert_20201127223105_1.dmp[17685]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201127223105_1.dmp
/home/mooncube/.local/share/Steam/steam.sh: line 750: 17679 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20201127223105_1.dmp[17685]: Finished uploading minidump (out-of-process): success = yes
assert_20201127223105_1.dmp[17685]: response: CrashID=bp-7fd31166-ad05-4486-bc69-9155e2201127
assert_20201127223105_1.dmp[17685]: file ''/tmp/dumps/assert_20201127223105_1.dmp'', upload yes: ''CrashID=bp-7fd31166-ad05-4486-bc69-9155e2201127''
`

**Comment by Tony763** [comment]
steam with `libnvidia-gl-455:i386 libqt5webengine5 libqt5webenginewidgets5` started and game launched, but was too slow. After dig in, I found that only internal graphic was running and nvidia was not used in whole system. I removed `libnvidia-gl-455:i386` and my system use nvidia card again, but no steam.

**Comment by moooncube** [comment]
> steam with `libnvidia-gl-455:i386 libqt5webengine5 libqt5webenginewidgets5` started and game launched, but was too slow. After dig in, I found that only internal graphic was running and nvidia was not used in whole system. I removed `libnvidia-gl-455:i386` and my system use nvidia card again, but no steam.
> 
> 32bit drivers seem as no go in ubuntu 20.10.

I'm not sure if your problems are related to this topic, the error outputs seem different from mine and it might be a separate issue for you to submit. I'm not certain though, so maybe someone who knows more about this can weigh in.

**Comment by moooncube** [comment]
@kisak-valve 
I still have the problem, and short of reinstalling the OS, which I can't do at the moment, I am out of ideas. Is there anything else I could try, or any other form of log I could provide that would allow you to help me solve this? Thanks.

**Comment by kisak-valve** [comment]
Re-reading this issue report, the video driver comments are not related to the original issue report. I don't think that the failed gtk modules or the gtk theme errors are fatal. So that doesn't leave any real hints to ponder how it segfaulted.

If you throw one of the assert*.dmp files in an archive I could at least tell you what library the segfault happened in, but beyond that we'll probably need to hear from a Steam dev who would take a look at the CrashID.

**Comment by moooncube** [comment]
Thank you, I can definitely do that. I tried starting Steam and these two files were generated in /tmp/dumps as a result:
[assert_202012142140.zip](https://github.com/ValveSoftware/steam-for-linux/files/5691487/assert_202012142140.zip)

**Comment by kisak-valve** [comment]
So, minidump_stackwalk tells me they're both a SIGSEGV in libc-2.32.so coming from vgui2_s.so, and appears to be a graphics thread.

**Comment by moooncube** [comment]
Ah, good to know. I looked into libc-2.32.so and vgui2_s.so to see if there are maybe any related packages that I could install since that's as far as my troubleshooting knowledge goes, but that didn't go anywhere (libc6-i386 is already installed).
What kind of problem do you think is indicated by what you found, is it missing libraries that need to be installed, or driver issues, or something completely different? Is it a bigger system issue and this is just a symptom, or is this something Steam specific?

**Comment by akalongman** [comment]
Did someone solve the problem?

**Comment by akalongman** [comment]
I fixed it via removing the Cuda PPA and after installing i386 drivers:
```
sudo apt install nvidia-driver-460 libnvidia-gl-460:i386
```

**Comment by moooncube** [comment]
No, unfortunately not. I’m now looking at a full system reinstall because of this.

**Comment by srgtlord** [comment]
Im running the NVIDIA 455 drivers and Ubuntu 20.04 with no issues on a fresh install

**Comment by moooncube** [comment]
Hey, I'm back. Had some time to experiment more, but it's still not working.
I'm thinking this here may be related to the issue: I can not install Nvidia drivers with the .so file from Nvidia's driver download page without issues.
The _/var/log/nvidia-installer.log_ says:

`nvidia-installer log file '/var/log/nvidia-installer.log'
creation time: Tue Feb  2 06:15:47 2021
installer version: 460.39

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

nvidia-installer command line:
    ./nvidia-installer

Using: nvidia-installer ncurses v6 user interface
-> Detected 8 CPUs online; setting concurrency level to 8.
-> Installing NVIDIA driver version 460.39.
-> An alternate method of installing the NVIDIA driver was detected. (This is usually a package provided by your distributor.) A driver installed via that method may integrate better with your system than a driver installed by nvidia-installer.

Please review the message provided by the maintainer of this alternate installation method and decide how to proceed:

The NVIDIA driver provided by Ubuntu can be installed by launching the "Software & Updates" application, and by selecting the NVIDIA driver from the "Additional Drivers" tab.


(Answer: Continue installation)
-> Would you like to register the kernel module sources with DKMS? This will allow DKMS to automatically build a new module, if you install a different kernel later. (Answer: Yes)
-> Install NVIDIA's 32-bit compatibility libraries? (Answer: Yes)
Looking for install checker script at ./libglvnd_install_checker/check-libglvnd-install.sh
   executing: '/bin/sh ./libglvnd_install_checker/check-libglvnd-install.sh'...
   Internal error:
   
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.`

I found this post when researching libglvnd errors: http://opensuse.14.x6.nabble.com/NVidia-driver-An-incomplete-installation-of-libglvnd-was-found-td5085305.html
I tried installing the driver as it suggested with `sh ./NVIDIA-Linux-x86_64-381.09.run -aqs --install-libglvnd ` which finished installing with no errors. System starts fine and the _Additional Drivers_ menu now lists the new 460 version, so it seems to have worked.

I installed _libnvidia-gl-460:i386_.

Steam still segfaults with the same message.

Any ideas why I might be getting these libglvnd errors in the first place, and is there a chance that this is what's messing with my installation?

I also attempted to copy some libraries as suggested here: https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Segmentation_fault_when_disabling_runtime because the error message looked similar to mine, but I'm not sure if this is even related. Did not change anything.

Thanks for your continued help, much appreciated.

**Comment by kofronpi** [comment]
No idea if this is related, but my steam client recently started crashing (good bye competitive games...) while playing and also while not playing.

```assert_20210414162647_1.dmp[105211]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210414162647_1.dmp
/home/pak/.local/share/Steam/steam.sh : ligne 771 : 104311 Erreur de segmentation  (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20210414162647_1.dmp[105211]: Finished uploading minidump (out-of-process): success = yes
assert_20210414162647_1.dmp[105211]: response: CrashID=bp-ab03cc18-98a4-4fb3-91e7-afa2a2210414
assert_20210414162647_1.dmp[105211]: file ''/tmp/dumps/assert_20210414162647_1.dmp'', upload yes: ''CrashID=bp-ab03cc18-98a4-4fb3-91e7-afa2a2210414''
```
Ubuntu 20.04 @  5.4.0-70 kernel, nvidia drivers 460

**Comment by moooncube** [comment]
I have at this point given up and reinstalled the complete system, now everything works fine again on my end.
This isn't very useful of course for anybody else having similar issues - so should I leave it open or close the issue @kisak-valve?

**Comment by byaka** [comment]
Hola guys, have same problem today after steam's update. nothing more changed, steam worked but after restart (that requested by update) it not starting anymore

in terminal:

```bash
⊨ steam                                                                           
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/byaka/.steam/ubuntu12_32/steam
[2021-05-26 19:42:14] Startup - updater built May 26 2021 00:40:35
[2021-05-26 19:42:14] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-05-26 19:42:14] Loading cached metrics from disk (/home/byaka/.steam/package/steam_client_metrics.bin)
[2021-05-26 19:42:14] Using the following download hosts for Public, Realm steamglobal
[2021-05-26 19:42:14] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-05-26 19:42:14] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-05-26 19:42:14] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2021-05-26 19:42:14] Checking for update on startup
[2021-05-26 19:42:14] Checking for available updates...
[2021-05-26 19:42:14] Downloading manifest: https://cdn.akamai.steamstatic.com/client/steam_client_publicbeta_ubuntu12
[2021-05-26 19:42:14] Download skipped by HTTP 304 Not Modified
[2021-05-26 19:42:14] Nothing to do
[2021-05-26 19:42:14] Verifying installation...
[2021-05-26 19:42:14] Performing checksum verification of executable files
[2021-05-26 19:42:15] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
⊨                                             
```

in error.log

```log
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Loaded SDL version 2.0.15-6501165
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1621998891)
[0526/192816.792157:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
[0526/192816.851743:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0526/192816.851857:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1621989654
[0526/192816.851886:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0526/192816.851910:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
[0526/192816.959123:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0526/192816.959203:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1621989654
[0526/192816.959211:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0526/192816.959217:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0526/192816.959811:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
CAppInfoCacheReadFromDiskThread took 234 milliseconds to initialize
CApplicationManagerPopulateThread took 242 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Installing breakpad exception handler for appid(steam)/version(1621998891)
Proceed to auto login
[0526/192817.294240:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0526/192817.294327:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1621989654
[0526/192817.294343:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0526/192817.294349:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0526/192817.294954:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Installing breakpad exception handler for appid(steam)/version(1621998891)
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1621998891)
assert_20210526192817_23.dmp[23905]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210526192817_23.dmp
assert_20210526192814_1.dmp[23924]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210526192814_1.dmp
/home/byaka/.steam/steam.sh: line 772: 23782 Ошибка сегментирования                   (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20210526192817_23.dmp[23905]: Finished uploading minidump (out-of-process): success = yes
assert_20210526192817_23.dmp[23905]: response: CrashID=bp-f2af0563-8a3b-4d4c-93ab-03ce52210526
assert_20210526192817_23.dmp[23905]: file ''/tmp/dumps/assert_20210526192817_23.dmp'', upload yes: ''CrashID=bp-f2af0563-8a3b-4d4c-93ab-03ce52210526''
assert_20210526192814_1.dmp[23924]: Finished uploading minidump (out-of-process): success = yes
assert_20210526192814_1.dmp[23924]: response: CrashID=bp-31f8ad2a-4c17-472a-86d1-f12442210526
assert_20210526192814_1.dmp[23924]: file ''/tmp/dumps/assert_20210526192814_1.dmp'', upload yes: ''CrashID=bp-31f8ad2a-4c17-472a-86d1-f12442210526''

```

nothing more in system updated this week. how can i fix it?

o how manually downgrade steam? i want to play my games :(

**Comment by thedimas3007** [comment]
I switched from NVIDIA video-card (gt750m) to integrated in CPU, rebooted and now steam is working properly 
OS: KUbuntu 20.04

**Comment by hoefling** [comment]
@byaka
> after removing `~/.steam/steam.sh` (without this it fails) and `steam --reset` it launch successfully

Got same log (`BadAtom`), resetting steam helps once, the next restart ends in the same error again. Current workaround is not to quit steam anymore :blush:

**Comment by zqy767** [comment]
Hi everyone, I somehow solve this problem.

Firstly, I was also focusing on the nvidia-driver issues. However, after I found that if I used "steam --reset", I could successfully login, I started to think that this problem may not be relative with nvidia -- otherwise it shouldn't be able to start at any situation.

So I read the log file carefully and was happy to find that all the "serious" bugs happened after "auto login". So I tried "steam --reset" again and disable "remember my password", and everything worked fine.

So I think this problem must be something wrong with "auto login" part, but I do not know how to actually fix it.

**Comment by kisak-valve** [comment]
Hello @hoefling, @zqy767, you've described the newer issue being tracked at #7813 instead of this issue report.

**Comment by iercan** [comment]
I have same problem. My gpu is radeon rx5700xt. Everything was working fine until last update. Then steam started crashing on startup. When I reinstall or do `steam --restart` it starts fine but can not start at second start. Here is what steam log to console 


```
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/ibrahim/.local/share/Steam/ubuntu12_32/steam
[2021-06-15 13:50:57] Startup - updater built Jun  8 2021 22:23:36
Installing breakpad exception handler for appid(steam)/version(1623193086)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-06-15 13:50:57] Loading cached metrics from disk (/home/ibrahim/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-15 13:50:57] Using the following download hosts for Public, Realm steamglobal
[2021-06-15 13:50:57] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-15 13:50:57] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-15 13:50:57] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-15 13:50:57] Checking for update on startup
[2021-06-15 13:50:57] Checking for available updates...
[2021-06-15 13:50:57] Downloading manifest: https://cdn.akamai.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-06-15 13:50:57] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-06-15 13:50:57] Nothing to do
[2021-06-15 13:50:57] Verifying installation...
[2021-06-15 13:50:57] Performing checksum verification of executable files
[2021-06-15 13:50:58] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"

(steam:80021): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier `direction', expected character `}'

(steam:80021): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1623193086)
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Could not connect to X session manager: None of the authentication protocols specified are supported
[0615/135058.669030:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
[0615/135058.683770:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0615/135058.683811:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0615/135058.683815:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0615/135058.683819:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[0615/135058.711846:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0615/135058.711888:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0615/135058.711893:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0615/135058.711897:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0615/135058.712289:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
[0615/135058.756896:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
[0615/135058.778833:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0615/135058.778873:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623191035
[0615/135058.778879:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0615/135058.778883:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0615/135058.779283:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
CApplicationManagerPopulateThread took 9 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
CAppInfoCacheReadFromDiskThread took 84 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Proceed to auto login
Installing breakpad exception handler for appid(steam)/version(1623193086)
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
assert_20210615135059_20.dmp[80255]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210615135059_20.dmp
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
assert_20210615135057_1.dmp[80258]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210615135057_1.dmp
/home/ibrahim/.local/share/Steam/steam.sh: line 772: 80021 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"

```

**Comment by reivilibre** [comment]
After confirming which packages were installed with `apt list '*nvidia*' --installed`,

`apt install libnvidia-gl-460:i386` worked for me. (MUST match the same one you have installed as a 64-bit package).

I originally installed the nVIDIA drivers using `ubuntu-drivers` CLI. I'm using KDE neon 20.04, fully-updated as of this date.

Hope this might provide encouragement for someone..

**Comment by silvan-batistella** [comment]
Hello everybody...

I'm trying the solution proposed by @reivilibre, but my Nvidia driver doesn't recognize my AOC TV's resolution of 32" and sets the resolution to 1024x768 without the option to choose another one.
However, Nvidia's driver recognizes the resolution of the TV I use as a monitor.
i think that unfortunately i will have to wait a while for a better generic driver, without being able to play.

**Comment by galvani** [comment]
The issue seems to be the autologin to me. Not remembering login does help for now.

**Comment by kisak-valve** [comment]
Hello @galvani, you've most likely encountered #7813 and not the issue reported here.

**Comment by rhaebel** [comment]
> After confirming which packages were installed with `apt list '*nvidia*' --installed`,
> 
> `apt install libnvidia-gl-460:i386` worked for me. (MUST match the same one you have installed as a 64-bit package).
> 
> I originally installed the nVIDIA drivers using `ubuntu-drivers` CLI. I'm using KDE neon 20.04, fully-updated as of this date.
> 
> Hope this might provide encouragement for someone..

This worked for me!
