### ISSUE TITLE
Fails with steamui.so missing libpipewire on Ubuntu 18.04 after May 24 update steam beta

### ISSUE THREAD

**Issue by samrocketman** [ValveSoftware/steam-for-linux#7808]
#### Your system information

* Steam client version (build number or date): Unknown (last upgraded today)
* Distribution (e.g. Ubuntu): Ubuntu 18.04 with latest system upgrades and kernel.
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam should open.

However, since upgrading it requires a dependency only available in Ubuntu 20.04.  It errors out saying 32-bit libpipewire is missing.

After some research I learned it's only available in Ubuntu 20.04.  As of now steam fails to start with a steamui.so error.

    ldd steamui.so

ldd shows that libpipewire was, in fact, missing.  As of right now I have no way to disable steam beta.

#### Steps for reproducing this issue:

1. Use Ubuntu 18.04 and upgrade to the latest steam beta.
2. Open steam
3. Watch it fail.

**Comment by kisak-valve** [comment]
Hello @samrocketman, this issue was already evaluated on #7807 and should already be resolved in a re-release of today's Steam client beta update.

You should be able to manually opt out of Steam's beta update channel by deleting `~/.steam/steam/package/beta` which should trigger an update cycle the next time you try to run Steam, then both the mainline release and the current beta should work.

**Comment by samrocketman** [comment]
How do I manually update @kisak-valve ?  My steam is still broken.

**Comment by kisak-valve** [comment]
See my last comment ... run `rm ~/.steam/steam/package/beta` in a terminal or use a file manager.

**Comment by samrocketman** [comment]
Nevermind; I read through and fixed it.  Thanks and apologies for wasting your time.
