### ISSUE TITLE
SteamCMD disk write error with force_install_dir option

### ISSUE THREAD

**Issue by deff-dev** [ValveSoftware/steam-for-linux#7843]
Hello I am using the latest steamcmd on Ubuntu 18.04, today I got an error when I tried to install the server (everything was fine yesterday)
Error: ERROR! Failed to install app '4020' (Disk write failure)
![image](https://user-images.githubusercontent.com/44276186/121150423-30feb280-c84c-11eb-821a-faa755d6875c.png)

Data of disk:
![image](https://user-images.githubusercontent.com/44276186/121150551-4ecc1780-c84c-11eb-892e-7b2018148195.png)

P.S: I use the force_install_dir option, when this parameter is empty - the server is installed

**Comment by Cherry** [comment]
I can also confirm this issue. We're seeing this across hundreds of different environments.

Some other reports too:

https://twitter.com/defenceforceorg/status/1402214880967630849?s=21

https://twitter.com/megumin2000/status/1402137709024485384?s=21

https://reddit.com/r/playrust/comments/nuxfvn/dedicated_server_setup_issues/

**Comment by Kurounin** [comment]
I'm getting the same error. I tried both in a new docker image based on ubuntu:18.04 and on the dedicated server. 
Using root or another user does not change the error.
Removing `+force_install_dir` will install the server correctly but in the default steamapps directory.

**Comment by knz87** [comment]
Happens across all our (windows) servers too. Confirmed the same issue on at least 30 nodes across Europe.

I can confirm that the workaround when **not** using the _force_install_dir_ command works.

**Comment by FelixReuthlinger** [comment]
Yea, having this issue on some servers since yesterday!

**Comment by Rai** [comment]
Also experiencing this across multiple Linux distros.

**Comment by Cherry** [comment]
As a temporary workaround, if you create a `steamapps` directory in the directory that you're passing to `force_install_dir`, this should allow the install to proceed as normal.

**Comment by ich777** [comment]
Same error here on Debian, is this something that will be fixed in an upcoming release of SteamCMD or do we have to do the workaround from @Cherry to "fix" the problem?

**Comment by billthecatt** [comment]
This error exists on debian as well. Please fix ASAP!

**Comment by billthecatt** [comment]
@kisak-valve Any chance we could get this fixed?

**Comment by rabi07** [comment]
any fix?

**Comment by billthecatt** [comment]
"how can it take this long time." The fact that they messed this up this big in the first place is pretty bad.. Whoever did it may be working harder on their resume then they now are at valve.. (or perhaps they should be..) It's pretty sad that a CDN and game platform as large as valve has such crap testing for something this core to their business. Epic/Blizzard and other CDNs aren't taking marketshare for no good reason...

Valve, step up your game. Too many people depend on your software working right for you to let stuff like this slide..

**Comment by AvienJ** [comment]
> As a temporary workaround, if you create a `steamapps` directory in the directory that you're passing to `force_install_dir`, this should allow the install to proceed as normal.
> 
> So for example if you were installing to `/home/steam/gameserver`, create the `/home/steam/gameserver/steamapps` directory first, and then you should be able to install fine.

Thanks this worked for me :)

**Comment by sandtechnology** [comment]
> 
> 
> As a temporary workaround, if you create a `steamapps` directory in the directory that you're passing to `force_install_dir`, this should allow the install to proceed as normal.
> 
> So for example if you were installing to `/home/steam/gameserver`, create the `/home/steam/gameserver/steamapps` directory first, and then you should be able to install fine.

A huge thanks for this workaround, it works for me.

**Comment by Eddie1337** [comment]
Also reported the issue here yesterday:
https://www.reddit.com/r/SteamCMD/comments/nv9oey/error_failed_to_install_app_xxx_disk_write_failure/

This morning found this thread after raising a ticket at Valve support.

I can confirm the workaround by creating the steamapps subdirectory

**Comment by schildbach** [comment]
> Can someone FIX THIS ALREADY? how can it take this long time. I cant even start the servers because the script is not even "quitting" like it should....

This repository is a free software project. No one is responsible for fixing this issue, except yourself.

**Comment by BrutalCSEjziponken** [comment]
> > Can someone FIX THIS ALREADY? how can it take this long time. I cant even start the servers because the script is not even "quitting" like it should....
> 
> This repository is a free software project. No one is responsible for fixing this issue, except yourself.

Yea that was ment to Valve or whoever actually pushes updated for STEAMDCMD.

**Comment by lostgoat** [comment]
A fix for this issue is available in the latest steamcmd release.

**Comment by BrutalCSEjziponken** [comment]
> A fix for this issue is available in the latest steamcmd release.

Seems to be working for me. Thanks.

**Comment by ich777** [comment]
Can confirm everything is working as it where before, tested two games (one of them is a Goldsource game):
[Valheim.log](https://github.com/ValveSoftware/steam-for-linux/files/6628470/Valheim.log)
[DMClassic.log](https://github.com/ValveSoftware/steam-for-linux/files/6628478/DMClassic.log)

Thank you for the fix!

**Comment by Frostflake** [comment]
Does not seem to be fixed - I tried it and it seems to ignore the force_install_dir option all together, although at least it downloads it now. I'm not sure where it is being saved to.

**Comment by deff-dev** [comment]
Fixed

**Comment by Frostflake** [comment]
After a bit of further testing, it does look like it's still broken if force_install_dir is used in conjunction with -beta to specify the branch, at least on Linux to download a Linux game.
