### ISSUE TITLE
Steam Remote Play streaming Microphone Audio on PipeWire

### ISSUE THREAD

**Issue by alou-S** [ValveSoftware/steam-for-linux#8187]
#### Your system information

* Steam client version (build number or date): Oct 29 2021
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam Remote Play streaming Microphone audio instead of Desktop audio on PipeWire Linux. 
It is using the Microphone Source instead of the Analog Stereo Monitor Source.

#### Steps for reproducing this issue:

1. Install `pipewire-pulse` (Basically use pipewire)
2. Start Steam Remote Play
3. Connect to remote play with audio enabled
4. Can't hear desktop audio on device running Steam Link but can hear Microphone Audio

**Comment by alou-S** [comment]
It doesn't seem to be related to #7833 since PipeWire had already fixed that issue. OBS seems to capture desktop audio just fine.

**Comment by david-james** [comment]
same issue 
Distro: Garuda Linux base: Arch Linux
Kernel: 5.15.4-zen1-1-zen
PipeWire v: 0.3.40 running: yes

if i remove pipewire and use PulseAudio  everything works fine via steam link if i use the default PipeWire v: 0.3.40 then then steam defaults to streaming the microphone even though i don't have one.

**Comment by david-james** [comment]
Not sure if this is helpful but i managed to get the sound working when i plug in my microphone and launch steam remote play i am able to manually pug in the connections helvum 
![Screenshot_1](https://user-images.githubusercontent.com/642438/143463482-e524c611-4130-4d2e-8f08-32fa7f5dfafb.png)

**Comment by alou-S** [comment]
Issue seems to have been fixed sometime recently. Closing Issue.

**Comment by pfych** [comment]
Still experiencing this issue, using qpwgraph to manually connect my monitor to steams input. Without this it streams my microphone.
