### ISSUE TITLE
Screenshots capture crashes Steam Overlay in Beta and Stable version

### ISSUE THREAD

**Issue by DareFox** [ValveSoftware/steam-for-linux#8871]
#### Your system information

* Steam client version (build number or date): 1666923262
* Distribution (e.g. Ubuntu): Arch Linux (kernel 6.0.2-arch1-1)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Full System Information: [Gist](https://gist.github.com/DareFox/d617589f54d18889715eedf94e164322)

#### Please describe your issue in as much detail as possible:
On beta, when I try to screenshot in any game, I hear (new?) *bulp* sound and no "Screenshot was taken" message pops up. 

Also, before taking a screenshot, Overlay was working normally with no issues. 
But after a screenshot attempt, Steam Overlay crahes.  `gameoverlayui` clones itself multiple times, and they are marked as zombie processes

##### Before screenshot:

![image](https://user-images.githubusercontent.com/47672780/198587783-af3dbcf0-f431-4f7a-8491-82669d461c8e.png)

##### Immediately After: 

![image](https://user-images.githubusercontent.com/47672780/198587878-b07c45d5-20f0-43f2-8057-d5cf6d533616.png)

##### After sometime, each `gameoverlayui` kill themselves. One by one:

![image](https://user-images.githubusercontent.com/47672780/198588119-b653f0cc-401d-4642-8f38-9e277e60bb53.png)

#### Steps for reproducing this issue:

1. Opt-in beta
2. Launch game
3. Take screenshot
4. Screenshot wasn't taken and Steam Overlay is crashed

**Comment by henrym11106** [comment]
Same here, this issue also causes CSGO to lag for a while after using the jpeg command. pretty sure this only started up in the last 24-48 hours or so.

opting out of client beta restores functionality.

**Comment by minecraft2048** [comment]
Replicated in Arch Linux and Tales of Zestiria, got a segfault notification in dmesg:
```
[Oct29 22:22] gameoverlayui[222542]: segfault at 0 ip 0000000000000000 sp 00000000ffbee9dc error 14 in gameoverlayui[5656c000+1000]
[  +0.000019] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[  +0.000044] audit: type=1701 audit(1667042590.293:18448): auid=1000 uid=1000 gid=1000 ses=3 pid=222542 comm="gameoverlayui" exe="/home/byakuya/.local/share/Steam/ubuntu12_32/gameoverlayui" sig=11 res=1
[  +0.008820] audit: type=1334 audit(1667042590.302:18449): prog-id=98 op=LOAD
[  +0.000113] audit: type=1334 audit(1667042590.302:18450): prog-id=99 op=LOAD
[  +0.000036] audit: type=1334 audit(1667042590.302:18451): prog-id=100 op=LOAD
[  +0.020706] audit: type=1130 audit(1667042590.323:18452): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@22-222700-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  +0.557475] audit: type=1131 audit(1667042590.880:18453): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@22-222700-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  +0.063055] audit: type=1334 audit(1667042590.944:18454): prog-id=0 op=UNLOAD
[  +0.000008] audit: type=1334 audit(1667042590.944:18455): prog-id=0 op=UNLOAD
[  +0.000002] audit: type=1334 audit(1667042590.944:18456): prog-id=0 op=UNLOAD
```
looking at coredumpctl dump output we can see that it crashes at libopenal.so.1:
<details>
  <summary>coredumpctl dump output</summary>

```
byakuya@ifrit-hpc ~ [1]> coredumpctl dump
           PID: 222542 (gameoverlayui)
           UID: 1000 (byakuya)
           GID: 1000 (byakuya)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-10-29 22:23:10 AEDT (4min 15s ago)
  Command Line: /home/byakuya/.local/share/Steam/ubuntu12_32/gameoverlayui -pid 222490 -steampid 149471 -manuallyclearframes 0 -gameid 351970 -reactlogin
    Executable: /home/byakuya/.local/share/Steam/ubuntu12_32/gameoverlayui
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-steam-fc0cc48a9330465a9ec7b3727ba101d8.scope
          Unit: user@1000.service
     User Unit: app-steam-fc0cc48a9330465a9ec7b3727ba101d8.scope
         Slice: user-1000.slice
     Owner UID: 1000 (byakuya)
       Boot ID: 882d80d0b7664a2c89c62fd5b0f9ef13
    Machine ID: d7354ea6503941a9acb751feb87851e9
      Hostname: ifrit-hpc
       Storage: /var/lib/systemd/coredump/core.gameoverlayui.1000.882d80d0b7664a2c89c62fd5b0f9ef13.222542.1667042590000000.zst (present)
     Disk Size: 19.7M
       Message: Process 222542 (gameoverlayui) of user 1000 dumped core.
                
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/gameoverlayui with build-id ab625e5afccc9bd70d20e07e652c813d54032802
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/serverbrowser.so with build-id b11a82041ba367cde8c21719c235cef93c878050
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/friendsui.so with build-id bb51b8541a735e87914ec624b1598001b08359fd
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libmiles.so with build-id aa23ffeef6f5e6ac34a5ff40761739f9e37fe547
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libaudio.so with build-id d44331aece4f2ca004859429430de71ce9eb075f
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/chromehtml.so with build-id 744ba57ff074b32e54662df82b298285d36398a1
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgdk-x11-2.0.so.0.2400.10 with build-id c271cfb31b9a244ab5f02bf4c941c3aaa8489def
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10 with build-id 48830dfc7e581fa5fbb5e7a2d2956b980a1e8ccc
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/vgui2_s.so with build-id e1ae2f4d26bc14808fe8cb82b7ef0bb145e24c7b
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/filesystem_stdio.so with build-id 99fed40c90dd5bc2d1a80a11fd7abe1d415ce73a
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libogg.so.0 with build-id 4c91d8f0dd8581b0ba6780e60808dc1db9ff5151
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libvorbis.so.0 with build-id cb40c3a2fd4c2e54822da9789d01113970595af6
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libvorbisenc.so.2 with build-id 5de455f0c9fcd36426e121b47995d9a75bfcecbf
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8 with build-id bea6597c238951c70269c034fdf4097216e2c970
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libudev.so.0.13.0 with build-id cf2498d52231d623047c965a5b0ca03e2084464f
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libnm.so.0.1.0 with build-id 53e4f4edd53bcde71a4a9601b072ee37c11d2568
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/steamclient.so with build-id 7e99886ea39b33648b6b5cf6f2a71df937525c89
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/crashhandler.so with build-id e362923148da0b45cf513da3a0462ca48e2fa437
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0 with build-id 556fc865c9f1ade3a643a13273a0628b488275e8
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/gameoverlayui.so with build-id 52e449a15a9707a11e04c804c3c6607e7bc91a34
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libvstdlib_s.so with build-id 6ed6c43e03993c5ece54fdf3123dc77739f4730f
                Module /home/byakuya/.local/share/Steam/ubuntu12_32/libtier0_s.so with build-id 4a16b909095c105cc64440046d2cb4b1359dc1c7
                Module linux-gate.so.1 with build-id bd8caa7fa4ef36ece75fbd9f248e3cffd1d4087b
                Module libdatrie.so.1 with build-id 505ee6a7fcb465c1a484c8c813508515e415f19b
                Module libthai.so.0 with build-id 55fe252092b25fc34ec252789c21a4f1702bfef1
                Module libfribidi.so.0 with build-id 2789c21c3223584b3251e2339b80f76ef6202729
                Module libtiff.so.5 with build-id 3140b027caba04296b50ef36babf4e8fbf7172e4
                Module libjpeg.so.8 with build-id bb111e5fbcc1c25bced2abacbc856a6410f8ad9b
                Module libpixman-1.so.0 with build-id 7761654702bfc76c1fcf3a174c792eb1e899fe14
                Module libxcb-shm.so.0 with build-id c478bab45d8cef998d3d744755528b23dd9c445b
                Module libxcb-render.so.0 with build-id 42eaec8c69b7df78937c6b9e664a98c457e5db18
                Module libXdamage.so.1 with build-id 55dd5fb5193b4ee5207ecad0d19cc6e9d7af5aa9
                Module libXcomposite.so.1 with build-id 9e8c1fe3c65614cf3fb6b4bb74acffc8ab0a5e0e
                Module libXcursor.so.1 with build-id ae3c97e2f155847562267b1707c75fb9884a2350
                Module libpango-1.0.so.0 with build-id f78655d941d31d3281b4fc5a851e56a09aa86e9f
                Module libpangoft2-1.0.so.0 with build-id 859ef18ef4411aaf39a894632e6dbb1513f3b4e6
                Module libgdk_pixbuf-2.0.so.0 with build-id f171defe470a4e6f2d052175674a8a757cf1539c
                Module libcairo.so.2 with build-id dd8d673a0e6ca9a8454e6712ef7c6d792288a7eb
                Module libatk-1.0.so.0 with build-id 2902156461a70a6958390c9c12dfa8965b6d58dc
                Module libXfixes.so.3 with build-id d04e7cb05d21774a5403cdea89e8023c4e2dbd78
                Module libpangocairo-1.0.so.0 with build-id 66cba204cdc77bbb337b6ca32e2264df08da6348
                Module libharfbuzz.so.0 with build-id 431dc25cb50edc8af6adb72e8946a62e0de1f5d2
                Module libpng16.so.16 with build-id 35e22a878f521a80406ac89f93906e7c45fb16aa
                Module libbz2.so.1.0 with build-id 3e5d97f5bb82cda221ccd14318bfae2ac77b815e
                Module libexpat.so.1 with build-id 062d01b7fec77879becee5613ed6e046f26631d4
                Module libICE.so.6 with build-id 5c398351eae18b0185f2b9512647e40c97f4e068
                Module libSM.so.6 with build-id 1cb4b8ce8ba49d0d98da7968de9ee574ed44fe6e
                Module libXinerama.so.1 with build-id ac215c8573b00954e0257efdae64546bed54c652
                Module libfreetype.so.6 with build-id ac10dea7fcb0e1dbc52d6989bfd34abbd814c1bf
                Module libfontconfig.so.1 with build-id 8a9ac4404881ead3fa46770b2da4e946201cd827
                Module libgpg-error.so.0 with build-id 6ecfdea2e1871208214eee924c1a309656c8913d
                Module libunistring.so.2 with build-id bc684570618a407fd6c4a305a38a7e3dcff87de2
                Module libbrotlicommon.so.1 with build-id 6a6095e57c732bdc9f52c5b401ccd78412b34650
                Module liblzma.so.5 with build-id a6705a420df4b1dc4a207a91982543c85bc9b1e1
                Module libgcrypt.so.20 with build-id 8ece9a72febf606ba62e6071765e3cc597a6edf0
                Module libcap.so.2 with build-id c78b82cd8dffa983442506c2f589c832159b3b5d
                Module libopus.so.0 with build-id e51af9f0b271bc2ba66d7b413a97df4aa21d1228
                Module libFLAC.so.12 with build-id 7ef37e3fea60454d87157ba0703a753f3e556dc4
                Module libblkid.so.1 with build-id afea748906b270df7b0dace3a37d063cc79bc9aa
                Module libudev.so.1 with build-id 518d32900cb8d936954c646e89fc14680960b9ef
                Module libgmp.so.10 with build-id cafef68f474308509c3feaacf0d479a30fedcace
                Module libhogweed.so.6 with build-id 7ca0f7fa561819b69cc4ded18da57cc25a27f885
                Module libnettle.so.8 with build-id 2d1fa470f77c5aab02372b0f8d0e1544467f9b9a
                Module libtasn1.so.6 with build-id f1cff42643baefb3e472a6d45a742f94ef0d5a6a
                Module libidn2.so.0 with build-id 9aa87d532915e79353e0e9181f7d890075886ce9
                Module libzstd.so.1 with build-id 442775044f6163f8c14265443311007e63d5d3e0
                Module libbrotlidec.so.1 with build-id d217b0d877303a399de12d974671e442aaf58832
                Module libbrotlienc.so.1 with build-id fa69fa6830c270de68e774719f891951658a8948
                Module libp11-kit.so.0 with build-id ef48c2739d8f80ae9a27bf632210bed2f27c9af6
                Module libasyncns.so.0 with build-id 2c3c77cfaeddfda50b66c21e3f8a86cb78933ca2
                Module libsystemd.so.0 with build-id 65cf18b7da338883211e0693d371b31ec0283bf6
                Module libsndfile.so.1 with build-id 54c2955a39f2e236c8bf27f9770ce98dd74735f4
                Module libmount.so.1 with build-id 1a0b51691abe9353156e69de06814b70d8f9f5f9
                Module libz.so.1 with build-id eef8f76603fae7a2876659fe737c1aebadb8b90b
                Module libpcre2-8.so.0 with build-id 5e23dd060ea8921ba6fb211fc1f71cbf2199da34
                Module libffi.so.8 with build-id 2bcd779cf0cb1d8583813bcf37976575a6078f4b
                Module libgudev-1.0.so.0 with build-id 19fb8a8ed10981ddb2bbc4514d5628f031fb0f24
                Module libuuid.so.1 with build-id cd66031432a77fcb9c2bf642cfd879aa170ffafe
                Module libgmodule-2.0.so.0 with build-id 1451bf13400e11b403665d7c3c58e96c4b06b3c9
                Module libgnutls.so.30 with build-id 705b834856fcc6f98d03e43a40634b5753610d9d
                Module libpulsecommon-16.1.so with build-id d1f892a3bc37a602d769b0664e50a7acb2257e5a
                Module libstdc++.so.6 with build-id 34d09c8eaf9352168f54bade53ee445983e7b634
                Module libgcc_s.so.1 with build-id 4aa4ab5f15cd88f4008add230edd3da832876123
                Module libgio-2.0.so.0 with build-id 3654ba91f6ee0ccb56024e29d13cb641b4acd2af
                Module libglib-2.0.so.0 with build-id 02c2d2c7291e8afef07437a7aef9e683282f84d6
                Module libgobject-2.0.so.0 with build-id 9b6538d858cda8e90c4d4bde64a90ab84de716c6
                Module libpulse.so.0 with build-id 8802cdae09ed16b8f9a246a1188bcc8dd26e09f9
                Module libopenal.so.1 with build-id c52c9460942f9bfb1540f5fe85c6cc9b4f4f3a02
                Module libpipewire-0.3.so.0 with build-id 5eb3ac0ad2666cf2b1248c070f5281a4288254d9
                Module libXtst.so.6 with build-id c8d14b5c1592a418613843e9ca5149154aa98f8b
                Module libXrender.so.1 with build-id 6fcaf8f5c40556f8a59e70883c51eb05d13685f8
                Module libXi.so.6 with build-id ae19d465b15227ab5e08de671bc16532450e384f
                Module libXext.so.6 with build-id 51364f7aaaad05288c6403f4cd82dc20bd1c2975
                Module libXrandr.so.2 with build-id 3295bdef0e30b5fd9da27c99bf5d6fd1c14551aa
                Module libXdmcp.so.6 with build-id d6d2063b49e333551fb395c4699ce68908342ca2
                Module libXau.so.6 with build-id 37885701fd17e23735180bb9afefba9fd93eafce
                Module libxcb.so.1 with build-id 4187de5462ea94547789043cd82a227550b36d73
                Module libX11.so.6 with build-id 54441eb873ba14650de70b96c9724da9f6dc6eb3
                Module libGLX.so.0 with build-id b50c9687f10ef138cf159f831d067396ec2e07ea
                Module libGLdispatch.so.0 with build-id 42aa31219782672b1f71f308141ffa7636f525f4
                Module libGL.so.1 with build-id 422501c22bf954ffd2b4f6227e251a5845c88454
                Module libm.so.6 with build-id 5d48ca924eef7b1c81b8e09804045f06a55c9541
                Module libpthread.so.0 with build-id 8995ebfb2098a4668599bc8b6ae45d0557058e3c
                Module librt.so.1 with build-id 822e5e6a09ff97cc5249cb865341cbfddedc2aac
                Module ld-linux.so.2 with build-id d9821b338b72b86d2caf20bb5a1c7a825348bd01
                Module libc.so.6 with build-id f9a1d140ee2962bbbc75e17ade27bf1f684eaf1c
                Module libdl.so.2 with build-id d7233d1f60c516f28df08daecfb1e8399ad96b65
                Stack trace of thread 222542:
                #0  0x0000000000000000 n/a (n/a + 0x0)
                #1  0x00000000f26744c4 alcOpenDevice (libopenal.so.1 + 0x464c4)
                #2  0x00000000ef5170cc n/a (/home/byakuya/.local/share/Steam/ubuntu12_32/libmiles.so + 0x420cc)
                #3  0x00000000ef5156f3 n/a (/home/byakuya/.local/share/Steam/ubuntu12_32/libmiles.so + 0x406f3)
                #4  0x00000000ef4f566b n/a (/home/byakuya/.local/share/Steam/ubuntu12_32/libmiles.so + 0x2066b)
                #5  0x00000000ef687c31 n/a (/home/byakuya/.local/share/Steam/ubuntu12_32/libaudio.so + 0xcc31)
                ELF object binary architecture: Intel 80386
Refusing to dump core to tty (use shell redirection or specify --output).
byakuya@ifrit-hpc ~ [1]> 
```
</details>

After the overlay crashes my controllers stopped working
Link to dump file:
[core.gameoverlayui.1000.882d80d0b7664a2c89c62fd5b0f9ef13.222542.1667042590000000.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/9893568/core.gameoverlayui.1000.882d80d0b7664a2c89c62fd5b0f9ef13.222542.1667042590000000.tar.gz)

**Comment by henrym11106** [comment]
It appears that this issue is no longer limited to the client beta. the second stable branch update today mentions a fix for a "browser crash" but the overlay still crashes after one screenshot in CS:GO.

**Comment by AmadeusTomboy** [comment]
Having same issue, taking a screenshot makes the overlay crash

**Comment by DareFox** [comment]
> It appears that this issue is no longer limited to the client beta. the second stable branch update today mentions a fix for a "browser crash" but the overlay still crashes after one screenshot in CS:GO.

Can confirm, it happens to me in stable branch too

**Comment by abhishek-rawal** [comment]
Likewise issue in latest stable build : 1668654564

Adding core, if that helps.
[core.gameoverlayui.1000.8b17508a733d4f149385ed591ec8c04f.13697.1668770263000000.zst.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/10041394/core.gameoverlayui.1000.8b17508a733d4f149385ed591ec8c04f.13697.1668770263000000.zst.tar.gz)

**Comment by SigmaSkid** [comment]
Steam stable, arch, everything up to date.

This issue also breaks steam input.
I need to restart my game every time I take a screenshot while playing with a controller.

**Comment by Mershl** [comment]
> looking at coredumpctl dump output we can see that it crashes at libopenal.so.1:

This brought up an idea. And I can confirm it's working: Disable "Play a sound" for screenshots to avoid the crash.

![image](https://user-images.githubusercontent.com/520251/203090084-721edf0e-c449-44f1-9060-8e6a71119708.png)

**Comment by henrym11106** [comment]
Disabling screenshot sound is a functional workaround for me on Arch as well.

**Comment by Unaccounted4** [comment]
Can confirm, disabling the sound is also a functional workaround for crash on Nobara 36.

**Comment by BillFleming** [comment]
I was also having this issue on Arch until disabling the screenshot audio. Not sure if this is relevant, but I recently had some new crashing issues with some mpv applications due to having a few pipewire packages installed (alongside pulse that the system was actually using). Removing pulse/jack and switching properly to pipewire didn't have any affect on this issue.

**Comment by mnn** [comment]
I am not entirely sure about the disabling audio solution. In FFXV it seemed to help, I was able to do several screenshots, but next few days it returned to its previous behavior (only takes one screenshot). Maybe it's not just one issue, but more? I remember that someone on protondb mentioned audio problems with that specific game, so it could be related to only one (or few) game(s)? It seems to work in other games I tried (same gaming session, same Steam instance).

I am on Manjaro and Steam is installed from repo (beta).

**Comment by purplebar0** [comment]
> This brought up an idea. And I can confirm it's working: Disable "Play a sound" for screenshots to avoid the crash.
At last! I thought I was going crazy when a related thread in Steam Client Beta Discussions had no activity whatsoever.

**Comment by murlakatamenka** [comment]
> > looking at coredumpctl dump output we can see that it crashes at libopenal.so.1:
> 
> This brought up an idea. And I can confirm it's working: Disable "Play a sound" for screenshots to avoid the crash.
> 
> ![image](https://user-images.githubusercontent.com/520251/203090084-721edf0e-c449-44f1-9060-8e6a71119708.png)

Thanks, great finding! And indeed a working temporary workaround, as others confirm too.

Code-wise it sounds like an unhandled exception. Surely inability to play a sound (something that you do in a separate thread) shouldn't crash the whole overlay process.

**Comment by TTimo** [comment]
This is fixed in latest steam beta, please retest (https://github.com/ValveSoftware/steam-for-linux/issues/8942)

**Comment by henrym11106** [comment]
No crash for me with the new beta.

**Comment by zany130** [comment]
still running into this on the latest beta https://github.com/ValveSoftware/steam-for-linux/issues/8898 so maybe it wasn't related to this after all

**Comment by DareFox** [comment]
> This is fixed in latest steam beta, please retest (#8942)

No crash, but now there's no sound for screenshot

**Comment by kattjevfel** [comment]
Fixed for me, no crash and sound is working (Arch Testing)

**Comment by xDShot** [comment]
Still crashes on Arch Linux

**Comment by xDShot** [comment]
Fixed

**Comment by popsUlfr** [comment]
In gamepadui/gamemode on the Steam Deck taking screenshots still does not work with the latest beta.

**Comment by feer9** [comment]
Can confirm it's fixed in the beta, still not working on stable branch

**Comment by kisak-valve** [comment]
Closing per "Fixed crash when taking screenshots through the overlay" in the [2023-02-01](https://store.steampowered.com/oldnews/189167) Steam client update.

**Comment by STaveras** [comment]
This is still occurring. When taking a single screenshot, it will work; subsequent screenshots, kills the overlay.

**Comment by kisak-valve** [comment]
Hello @STaveras, please open a new issue report with the details of what you're seeing.
