### ISSUE TITLE
Steam client crashes at launch due to audio call in Telegram messenger 

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#8926]
#### Your system information

* Steam client version (build number or date): 1668654564
* Distribution (e.g. Ubuntu): At least Fedora and Ubuntu
* Opted into Steam client beta?: Yes but it not matter (it also reproduced with stable steam client)
* Have you checked for system updates?: Yes
* Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)

#### Please describe your issue in as much detail as possible:
I and my friend noticed that when we talks with each other via telegram and one of us try restart steam during a conversation, then steam does not start until the call stops.

I use Fedora, my friend use Ubuntu.

#### Steps for reproducing this issue:

1. Download and launch Telegram messenger https://telegram.org/dl/desktop/linux 
2. Call to your friend
3. Restart steam

```
DXVK_HUD=full steam -console
steam.sh[414549]: Running Steam on fedora 38 64-bit
steam.sh[414549]: STEAM_RUNTIME is enabled automatically
setup.sh[414621]: Steam runtime environment up-to-date!
steam.sh[414549]: Steam client's requirements are satisfied
[2022-11-18 00:21:18] Startup - updater built Nov 17 2022 02:42:14
[2022-11-18 00:21:18] Startup - Steam Client launched with: '/home/mikhail/.local/share/Steam/ubuntu12_32/steam' '-console'
[2022-11-18 00:21:18] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1668654564)
[2022-11-18 00:21:18] Loading cached metrics from disk (/home/mikhail/.local/share/Steam/package/steam_client_metrics.bin)
[2022-11-18 00:21:18] Using the following download hosts for Public, Realm steamglobal
[2022-11-18 00:21:18] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2022-11-18 00:21:18] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2022-11-18 00:21:18] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1668654564)
[2022-11-18 00:21:18] Verifying installation...
[2022-11-18 00:21:18] Verification complete
Loaded SDL version 2.25.0-p7648887

(steam:414696): Gtk-WARNING **: 00:21:19.085: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:414696): Gtk-WARNING **: 00:21:19.086: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Gtk-Message: 00:21:19.088: Failed to load module "pk-gtk-module"
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xed47d0d0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xed47b840
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[414716]: Runtime for steamwebhelper: defaulting to /home/mikhail/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[414716]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
src/vstdlib/strtools.cpp (252) : n == 0 || s1 != NULL
src/vstdlib/strtools.cpp (252) : n == 0 || s1 != NULL
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
Installing breakpad exception handler for appid(steam)/version(1668654564)
assert_20221118002119_21.dmp[414887]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221118002119_21.dmp
/home/mikhail/.local/share/Steam/steam.sh: line 798: 414696 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20221118002119_21.dmp[414887]: Finished uploading minidump (out-of-process): success = yes
assert_20221118002119_21.dmp[414887]: response: CrashID=bp-2f1f5d2c-f9d1-4901-92e1-beec42221117 
```

[archive_with_steam_dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/10035029/archive_with_steam_dumps.zip)

**Comment by fabiscafe** [comment]
I can confirm this

**Comment by dacanizares** [comment]
Same here. Fedora 36.

**Comment by niihari** [comment]
I also confirm.
Running steam:i386 1:1.0.0.61-2ubuntu3 on Linux Mint 20.3.

**Comment by CoelacanthusHex** [comment]
I can confirm as well. Arch Linux

**Comment by Vezono** [comment]
Same. Artix Linux.

**Comment by cmdrneon** [comment]
Can confirm as well, Debian 11

**Comment by mish24** [comment]
can confirm for Ubuntu as well

**Comment by NTMan** [comment]
Looks like fixed in steam beta since build 1670474854

**Comment by VladimirMrzv** [comment]
Can confirm, steam launches.

**Comment by RuneZhevitz** [comment]
I still have this segfault. Steam doesn't launch when in a Telegram audio call - the log also indicates vstdlib just as in the original issue.

**Comment by TheLastProject** [comment]
This crash on launch still happens on Steam 1671236931 on Ubuntu 22.04 LTS (GNOME) and Fedora 37 (KDE).

How to reproduce:
1. Start a Telegram Desktop voice call
2. Start Steam
3. Steam crashes

It is important to note that it specifically occurs during a Telegram Desktop voice call (https://desktop.telegram.org). Voice calls through other programs or even through Telegram Web do not cause Steam to crash on launch. If Steam is already running it will keep working fine.

**Comment by userofryzen** [comment]
I have this problem too

**Comment by ask-compu** [comment]
can confirm on Kubuntu 22.04.1

**Comment by ssleert** [comment]
too

**Comment by bill88t** [comment]
too

**Comment by TTimo** [comment]
this is the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/8930 - closing this one as the other has more useful information
