### ISSUE TITLE
Steam client crash involving alcCaptureOpenDevice while initializing voice chat

### ISSUE THREAD

**Issue by bananarne** [ValveSoftware/steam-for-linux#8930]
#### Your system information

* Steam client version (build number or date): 
Nov 17 2022, at 02:45:32
* Distribution (e.g. Ubuntu): 
Gentoo
* Opted into Steam client beta?: [Yes/No]
Tried both
* Have you checked for system updates?: [Yes/No]
Yes

1. start steam
2. start dota
3. use voicechat ingame / open settings menu

Whenever I use voice inside DotA or open the settings-menu stream crashes and takes dota with it. 

[ 1565.120249] CIPCServer::Thr[5598]: segfault at 0 ip 00000000ed089ac5 sp 00000000dc1fd640 error 4 in libstdc++.so.6.0.30[ed078000+125000]
[ 1565.120265] Code: 90 66 90 66 90 55 57 56 bf 01 00 00 00 e8 82 e5 ff ff 05 53 d5 19 00 53 83 ec 1c 8b 74 24 30 89 c3 89 44 24 0c e8 9b 0f ff ff <8b> 0e 8b 5e 04 8d 6e d0 8b 10 81 c1 00 d5 d4 bc 81 d3 bc aa b1 b8
[ 1770.705965] steam[9887]: segfault at 27bc ip 00000000f7b7ab1e sp 00000000ff8c34e8 error 4 in libc.so.6[f7a1e000+17d000]
[ 1770.705972] Code: c3 8d b4 26 00 00 00 00 8d 74 26 00 f3 0f 7e 40 d7 66 0f d6 42 d7 f3 0f 7e 40 df 66 0f d6 42 df f3 0f 7e 40 e7 66 0f d6 42 e7 <f3> 0f 7e 40 ef 66 0f d6 42 ef f3 0f 7e 40 f7 66 0f d6 42 f7 0f b6
[ 1951.389246] CIPCServer::Thr[18164]: segfault at 0 ip 00000000ed089ac5 sp 00000000e03fd400 error 4 in libstdc++.so.6.0.30[ed078000+125000]
[ 1951.389252] Code: 90 66 90 66 90 55 57 56 bf 01 00 00 00 e8 82 e5 ff ff 05 53 d5 19 00 53 83 ec 1c 8b 74 24 30 89 c3 89 44 24 0c e8 9b 0f ff ff <8b> 0e 8b 5e 04 8d 6e d0 8b 10 81 c1 00 d5 d4 bc 81 d3 bc aa b1 b8

This started ~2 weeks ago in steam beta so i switched to stable, but it arrived there now.

**Comment by FF-AntiK** [comment]
Funny, I was wondering for a few days now why steam crashes on startup. Thanks to this Issue I found out that my OpenRGB setup which is listening to my Audio Monitor for cool RGB effects is causing Steam to crash. 👍🏼

**Comment by bananarne** [comment]
Uhm, yeah, I worked around that by using the flatpak version (which doesn't work if you have steam play activated, for some reason(there is an issue describing this)). So this must've something to do with how i compile stuff.

**Comment by FF-AntiK** [comment]
I'm pretty much getting away with starting Steam *before* OpenRGB ist started ;-)
Didn't test any voicechat yet, though.

**Comment by bananarne** [comment]
Some additional information:

Thread 21 "CIPCServer::Thr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xdc1ffb40 (LWP 16654)]
0xf725879f in __libunwind_Unwind_Resume () from /usr/lib/libunwind.so.8
(gdb) bt
#0  0xf725879f in __libunwind_Unwind_Resume () at /usr/lib/libunwind.so.8
#1  0xe0b66b78 in  () at /usr/lib/libopenal.so.1
#2  0xe0b99ceb in alcCaptureOpenDevice () at /usr/lib/libopenal.so.1
#3  0xddce614e in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xddce6209 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xddcd4ffb in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xdd80e224 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#7  0xdd4912d3 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xdd69da38 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xdd84887f in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xdd6a05f7 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xdd8458c2 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xdd847c85 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xdd848431 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xe5f1e42e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) ()
    at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#15 0xe5f1bd5e in  () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#16 0xe5f1c5f0 in CatchAndWriteMiniDumpExForVoidPtrFn ()
    at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#17 0xe5f1c638 in CatchAndWriteMiniDumpForVoidPtrFn ()
    at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#18 0xe5f20eb1 in SteamThreadTools::CThread::ThreadProc(void*) ()
    at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#19 0xf7a85f41 in  () at /lib/libc.so.6
#20 0xf7b21a08 in  () at /lib/libc.so.6

**Comment by MathiasSven** [comment]
I just had the same issue starting yesterday, today I opted out of steam beta and now everything is working... Hopefully this doesn't come to stable.

**Comment by kisak-valve** [comment]
Steam beta crashes along with the game when requesting sound input

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/9004.
@GregTheMadMonk posted on 2022-12-16T06:22:33:

#### Your system information

* Steam client version (build number or date): Dec 15 2022 02:03:59
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The issue first appeared after an update when I tried to launch Nightmare Reaper.
The game crashed on launch, and Steam crashed with it.
At first, I thought it was a game-specific problem, as other games worked, but when I tried to use voice chat in Half-Life it happened again.
Inspecting the core dump reveals that `alcCaptureOpenDevice()` fails and crashes both the game and steam.
Full `gdb` backtrace:

```
#0  0xf7ee4549 in __kernel_vsyscall ()
#1  0xf7a89667 in ?? () from /usr/lib32/libc.so.6
#2  0xf7a35677 in raise () from /usr/lib32/libc.so.6
#3  0xf7a1e126 in abort () from /usr/lib32/libc.so.6
#4  0xedaca235 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/vgui2_s.so
#5  0xedb61c89 in __gxx_personality_v0 () from /home/greg/.local/share/Steam/ubuntu12_32/vgui2_s.so
#6  0xf416f834 in _Unwind_RaiseException_Phase2 (exc=0xd91995a0, context=0xe97fd310, frames_p=0xe97fd390) at /usr/src/debug/gcc/libgcc/unwind.inc:64
#7  0xf416fd88 in _Unwind_RaiseException (exc=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:136
#8  0xee286836 in __cxxabiv1::__cxa_throw (obj=0xd91995c0, tinfo=0xeda3a7d8, dest=0xed988800) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:93
#9  0xed94a5fe in ?? () from /usr/lib32/libopenal.so.1
#10 0xed97cb85 in alcCaptureOpenDevice () from /usr/lib32/libopenal.so.1
#11 0xeb2f754e in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xeb2f7609 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xeb2e63fb in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xeae15544 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xeaa96113 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xeaca34e8 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xeae5067f in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xeaca2f17 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xeae4d6c2 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#20 0xeae4fa85 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#21 0xeae50231 in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/steamclient.so
#22 0xf2c0f19e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf2c0ca0e in ?? () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf2c0d2d0 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#25 0xf2c0d318 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#26 0xf2c11c21 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/greg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#27 0xf7a87485 in ?? () from /usr/lib32/libc.so.6
#28 0xf7b24efc in ?? () from /usr/lib32/libc.so.6
```

#### Steps for reproducing this issue:

1. Launch the latest Steam Beta
2. Try to run a game that uses a microphone (for me these were Nightmare Reaper and Half-Life)
3. Both game and steam would crash when trying to access the microphone
***
@bananarne commented on 2022-12-16T09:41:58:

most likely clone of https://github.com/ValveSoftware/steam-for-linux/issues/8930 but the backtrace says more than mine

**Comment by TTimo** [comment]
@gregthemadmonk please provide a crash ID for an uploaded crash for your issue. Several users have confirmed that this issue is fixed in current Steam beta for them, there may be something different about your setup.

**Comment by GregTheMadMonk** [comment]
@TTimo I'm unsure what a crash ID is, so here are the last lines of Steam output after the crash.
(I removed a bunch of `gamemode` output from here as the problem persists even if I launch the game without it).

```
Setting breakpad minidump AppID = 1051690
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198134043537 [API loaded no]
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
Created OPUS PLC voice encoder
warning: The VAD has been replaced by a hack pending a complete rewrite
crash_20221217014941_31.dmp[553889]: Uploading dump (out-of-process)
/tmp/dumps/crash_20221217014941_31.dmp
crash_20221217014941_31.dmp[553889]: Finished uploading minidump (out-of-process): success = yes
crash_20221217014941_31.dmp[553889]: response: CrashID=bp-e2fd3dd9-ae6c-4cfb-b954-d73442221216
crash_20221217014941_31.dmp[553889]: file ''/tmp/dumps/crash_20221217014941_31.dmp'', upload yes: ''CrashID=bp-e2fd3dd9-ae6c-4cfb-b954-d73442221216''
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
/home/greg/.local/share/Steam/steam.sh: line 798: 544809 Aborted                 (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
ERROR: ld.so: object '/tmp/pressure-vessel-libs-PV3VW1/${PLATFORM}/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
assert_20221217014942_14.dmp[554320]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221217014942_14.dmp
_ExitOnFatalAssert

pid 552864 != 552863, skipping destruction (fork without exec?)
assert_20221217014942_14.dmp[554320]: Finished uploading minidump (out-of-process): success = yes
assert_20221217014942_14.dmp[554320]: response: Discarded=1
assert_20221217014942_14.dmp[554320]: file ''/tmp/dumps/assert_20221217014942_14.dmp'', upload yes: ''Discarded=1''
pid 554320 != 554300, skipping destruction (fork without exec?)
```

**Comment by bananarne** [comment]
i provoked a crash for a fresh new crashid CrashID=bp-16b70289-4ad5-475e-98c8-3fa1e2221216

i created this with steam beta.

**Comment by TTimo** [comment]
Thanks - since `libopenal.so.1` is coming from your host, you may want to install a debug version of that and see if you can get a more precise backtrace of why it crashes while executing `alcCaptureOpenDevice`.

If it's like the other issues, stepping through the disassembly might help, I expect it's being confused by some of the symbols globally exported by the Steam binary.

**Comment by bananarne** [comment]
unfortunately it doesn't get much clearer by doing that, at first I thought it would be pipewire specific, but when compiling openal without that feature im presented with this:

#0  0xed489a5d in __cxa_begin_catch () at /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/32/libstdc++.so.6
#1  0xe0c7ccd9 in alcCaptureOpenDevice(ALCchar const*, ALCuint, ALCenum, ALCsizei)
    (deviceName=0xdbbfd6f4 "PulseAudio Default", frequency=24000, format=4353, samples=480000)
    at /var/tmp/portage/media-libs/openal-1.22.2-r1/work/openal-soft-1.22.2/alc/alc.cpp:3604
#2  0xdd6f754e in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#3  0xdd6f7609 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xdd6e63fb in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so

I will try to convince gdb to load sourcecode from the correct place and then step through it line by line, later.

**Comment by b51376b51ba34cec8f374c3854601a1e** [comment]
I believe I'm experiencing the same issue, possibly related to #9011. Steam crashes for me every time I try to access the settings or voice chat in Dota 2. Seems like the problem is caused by an uncaught exception thrown in the PulseAudio backend in OpenAL:

<details>
<summary><code>DEBUGGER=gdb steam</code></summary>

```gdb
$ DEBUGGER=gdb LD_DEBUG=all steam
...
(gdb) info stack
#0  0xf7fc6549 in __kernel_vsyscall ()
#1  0xf7a89667 in __pthread_kill_implementation (threadid=threadid@entry=3933682496, signo=signo@entry=6,
    no_tid=no_tid@entry=0) at pthread_kill.c:43
#2  0xf7a896ef in __pthread_kill_internal (signo=6, threadid=3933682496) at pthread_kill.c:78
#3  0xf7a35677 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#4  0xf7a1e126 in __GI_abort () at abort.c:79
#5  0xeddcf235 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/vgui2_s.so
#6  0xede66c89 in __gxx_personality_v0 () from /home/user/.local/share/Steam/ubuntu12_32/vgui2_s.so
#7  0xf4385834 in _Unwind_RaiseException_Phase2 (exc=0xe477b250, context=0xea7713d0, frames_p=0xea771450)
    at /usr/src/debug/gcc/libgcc/unwind.inc:64
#8  0xf4385d88 in _Unwind_RaiseException (exc=<optimized out>) at /usr/src/debug/gcc/libgcc/unwind.inc:136
#9  0xee686836 in __cxxabiv1::__cxa_throw (obj=0xe477b270, tinfo=0xedd3f7d8 <typeinfo for al::backend_exception>,
    dest=0xedc8d800 <al::backend_exception::~backend_exception()>)
    at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:93
#10 0xedc50315 in (anonymous namespace)::PulseCapture::open (this=0xc1527ee0, name=0xea7716f4 "PulseAudio Default")
    at /usr/src/debug/openal-soft/alc/backends/pulseaudio.cpp:1148
#11 0xedc81b85 in alcCaptureOpenDevice (deviceName=0xea7716f4 "PulseAudio Default", frequency=24000, format=4353,
    samples=480000) at /usr/src/debug/openal-soft/alc/alc.cpp:3586
#12 0xeb6f754e in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xeb6f7609 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xeb6e63fb in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xeb215544 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xeae96113 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xeb0a34e8 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xeb25067f in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xeb0a2f17 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#20 0xeb24d6c2 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#21 0xeb24fa85 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#22 0xeb250231 in ?? () from /home/user/.local/share/Steam/ubuntu12_32/steamclient.so
#23 0xf2ef219e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) ()
   from /home/user/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf2eefa0e in ?? () from /home/user/.local/share/Steam/ubuntu12_32/libtier0_s.so
#25 0xf2ef02d0 in CatchAndWriteMiniDumpExForVoidPtrFn ()
   from /home/user/.local/share/Steam/ubuntu12_32/libtier0_s.so
#26 0xf2ef0318 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/user/.local/share/Steam/ubuntu12_32/libtier0_s.so
#27 0xf2ef4c21 in SteamThreadTools::CThread::ThreadProc(void*) ()
   from /home/user/.local/share/Steam/ubuntu12_32/libtier0_s.so
#28 0xf7a87485 in start_thread (arg=<optimized out>) at pthread_create.c:442
#29 0xf7b24efc in clone3 () at ../sysdeps/unix/sysv/linux/i386/clone3.S:111
(gdb) up 10
Downloading 0.05 MB source file /usr/src/debug/openal-soft/alc/backends/pulseaudio.cpp
1148                    "Device name \"%s\" not found", name}; 
```
</details>

Here's the thrown exception:
```gdb
(gdb) catch throw al::backend_exception
(gdb) r
...
(gdb) p $_exception
$1 = {<al::base_exception> = {<std::exception> = {
      _vptr.exception = 0xedd3dcdc <vtable for al::backend_exception+8>}, mMessage = {
      _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, 
        _M_p = 0xe5f027c0 "Device name \"PulseAudio Default\" not found"}, _M_string_length = 42, {
        _M_local_buf = "+\000\000\000\bf\020\000\020:a\301\240\312a\301", _M_allocated_capacity = 43}}}, 
  mErrorCode = al::backend_error::NoDevice}
```

According to `pacmd list-sinks` and `pacmd list-devices`, I do not seem to have a device called `PulseAudio Default`, but my audio works fine in other applications (slack, zoom, chrome, etc.).

**Comment by ouassarnifahd** [comment]
I've seen this issue with ELDEN RING. Any multiplayer activity triggers it.
```
#9  0xedb4a5fe in (anonymous namespace)::PipeWireCapture::open (this=0xe08b97f0, name=0xe9cfd6f4 "PulseAudio Default") at /usr/src/debug/openal-soft/alc/backends/pipewire.cpp:1804
#10 0xedb7cb85 in alcCaptureOpenDevice (deviceName=0xe9cfd6f4 "PulseAudio Default", frequency=0x5dc0, format=0x1101, samples=0x75300) at /usr/src/debug/openal-soft/alc/alc.cpp:3586
#11 0xeb6f754e in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xeb6f7609 in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xeb6e63fb in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
```

Im not using pulseaudio (pipewire) so I hacked this by renaming the default device to "PulseAudio Default". as this value is hardcoded in steamclient.so.

```
$ strings ~/.local/share/Steam/ubuntu12_32/steamclient.so | grep PulseAudio                                                                                      
PulseAudio Default
PulseAudio connect failed (used only for Mic Volume Control) with error: %s
```

Hope this can help someone while waiting for a fix in steamclient.so

**Comment by b51376b51ba34cec8f374c3854601a1e** [comment]
@ouassarnifahd Thanks, the hack worked like a charm for me! Simply renaming my headset and mic to `PulseAudio Default` in `pavucontrol` mitigates the issue.

**Comment by bananarne** [comment]
> I believe I'm experiencing the same issue, possibly related to #9011. Steam crashes for me every time I try to access the settings or voice chat in Dota 2. Seems like the problem is caused by an uncaught exception thrown in the PulseAudio backend in OpenAL:
> 
> `DEBUGGER=gdb steam`
> Here's the thrown exception:
> 
> ```gdb
> (gdb) catch throw al::backend_exception
> (gdb) r
> ...
> (gdb) p $_exception
> $1 = {<al::base_exception> = {<std::exception> = {
>       _vptr.exception = 0xedd3dcdc <vtable for al::backend_exception+8>}, mMessage = {
>       _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, 
>         _M_p = 0xe5f027c0 "Device name \"PulseAudio Default\" not found"}, _M_string_length = 42, {
>         _M_local_buf = "+\000\000\000\bf\020\000\020:a\301\240\312a\301", _M_allocated_capacity = 43}}}, 
>   mErrorCode = al::backend_error::NoDevice}
> ```
> 
> According to `pacmd list-sinks` and `pacmd list-devices`, I do not seem to have a device called `PulseAudio Default`, but my audio works fine in other applications (slack, zoom, chrome, etc.).

This is constistent to my debugging attemps, it seems to not find a device with the name provided by the call of 

``` 0xe0c7ccd9 in alcCaptureOpenDevice(ALCchar const*, ALCuint, ALCenum, ALCsizei)
(deviceName=0xdbbfd6f4 "PulseAudio Default", frequency=24000, format=4353, samples=480000) ```

**Comment by bananarne** [comment]
> I've seen this issue with ELDEN RING. Any multiplayer activity triggers it.
> 
> ```
> #9  0xedb4a5fe in (anonymous namespace)::PipeWireCapture::open (this=0xe08b97f0, name=0xe9cfd6f4 "PulseAudio Default") at /usr/src/debug/openal-soft/alc/backends/pipewire.cpp:1804
> #10 0xedb7cb85 in alcCaptureOpenDevice (deviceName=0xe9cfd6f4 "PulseAudio Default", frequency=0x5dc0, format=0x1101, samples=0x75300) at /usr/src/debug/openal-soft/alc/alc.cpp:3586
> #11 0xeb6f754e in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
> #12 0xeb6f7609 in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
> #13 0xeb6e63fb in ?? () from /home/archer/.local/share/Steam/ubuntu12_32/steamclient.so
> ```
> 
> Im not using pulseaudio (pipewire) so I hacked this by renaming the default device to "PulseAudio Default". as this value is hardcoded in steamclient.so.
> 
> ```
> $ strings ~/.local/share/Steam/ubuntu12_32/steamclient.so | grep PulseAudio                                                                                      
> PulseAudio Default
> PulseAudio connect failed (used only for Mic Volume Control) with error: %s
> ```
> 
> Hope this can help someone while waiting for a fix in steamclient.so

I compiled openal without pipewire support and this still happens, in fact it even happens without pipewire being started. So it doesn't seem to have anything to do with pipewire.

**Comment by TTimo** [comment]
Your host OpenAL really shouldn't be trying to propagate C++ exceptions from it's pipewire backend implementation (`al::backend_exception`) up towards steam. `alc.h` is a C API ..

**Comment by userofryzen** [comment]
Either cant be launched when Telegram is usted for calls

**Comment by TTimo** [comment]
Fix went in to Jan 12th beta client, please re-test.

**Comment by bananarne** [comment]
nope, still experiencing this (with beta). The backtrack looks pretty much identical.

#0  0xf726179f in __libunwind_Unwind_Resume () at /usr/lib/libunwind.so.8
#1  0xe06f1c2a in (anonymous namespace)::PipeWireCapture::open(char const*) (this=0xc64f7ef0, name=0xdb5fd724 "PulseAudio Default")
    at /usr/src/debug/media-libs/openal-1.22.2-r1/openal-soft-1.22.2/alc/backends/pipewire.cpp:1925
#2  0xe067ee06 in alcCaptureOpenDevice(ALCchar const*, ALCuint, ALCenum, ALCsizei)
    (deviceName=0xdb5fd724 "PulseAudio Default", frequency=24000, format=4353, samples=480000)
    at /usr/src/debug/media-libs/openal-1.22.2-r1/openal-soft-1.22.2/alc/alc.cpp:3586
#3  0xdd104dfe in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xdd104eb9 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xdd0f3cab in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xdcc1c834 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#7  0xdc89d0d3 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xdcaab428 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xdcc57b0f in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xdcaaae57 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xdcc54b52 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xdcc56f15 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xdcc576c1 in  () at /home/basic/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xe61dfb6e in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#15 0xe61dd7af in  () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#16 0xe61ddca0 in CatchAndWriteMiniDumpExForVoidPtrFn () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#17 0xe61ddce8 in CatchAndWriteMiniDumpForVoidPtrFn () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#18 0xe61e25f1 in SteamThreadTools::CThread::ThreadProc(void*) () at /home/basic/.local/share/Steam/ubuntu12_32/libtier0_s.so
#19 0xf7a85fb1 in  () at /lib/libc.so.6
#20 0xf7b21b98 in  () at /lib/libc.so.6

**Comment by bananarne** [comment]
![image](https://user-images.githubusercontent.com/22680572/212375762-b4433fa9-9425-480b-b393-b2d940e52d2e.png)

**Comment by TTimo** [comment]
Might be fixed for people who were seeing `vgui2_s.so` insert itself in the C++ exception handling. What is happening on @bananarne's system may be a different flavor of problem.

**Comment by bananarne** [comment]
This has been fixed for me, most likely due to an update of openal.
