### ISSUE TITLE
Steam is failing to download some of ArmA 3 Workshop items

### ISSUE THREAD

**Issue by Nerexis** [ValveSoftware/steam-for-linux#8956]
#### Your system information

* Steam client version (build number or date):  Steam Console Client (c) Valve Corporation - version 1669249397
* Distribution (e.g. Ubuntu):  Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The command fails with an error but shouldn't:

```
Steam>workshop_download_item 107410 366425329 validate
Downloading item 366425329 ...
ERROR! Download item 366425329 failed (Failure).
```

#### Steps for reproducing this issue:

1. Opens steamcmd
2. Force install to dir some mods dir for ArmA 3
3. Use login command to login to your Steam account
4. Execute workshop_download_item 107410 366425329 validate

**Comment by DanB-dev** [comment]
Having issues with this too.

Distro: Ubuntu
Steam Beta: No
Checked System Updates : Yes

The errors we are getting:
```console
Redirecting stderr to '/home/arma3server/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1669249397
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'vikingpmc2014' to Steam Public...Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 366425329 ...
ERROR! Download item 366425329 failed (Failure).
```

**Comment by DanB-dev** [comment]
@Nerexis I just fixed my issue by going into my steamapps/workshop/downloads and clearing all the files in there.

Instantly worked the first time afterwards. Hope this helps you!

**Comment by Nerexis** [comment]
> @Nerexis I just fixed my issue by going into my steamapps/workshop/downloads and clearing all the files in there.
> 
> Instantly worked the first time afterwards. Hope this helps you!

It didn't solve my issue.

**Comment by Nerexis** [comment]
The problem is still there and is getting worse, more and more workshop items can't be downloaded.

Example:
Steam>workshop_download_item 107410 366423278 validate
Downloading item 366423278 ...
ERROR! Download item 366423278 failed (Failure).
