### ISSUE TITLE
Can't create new storage with Storage Manager in Beta version 

### ISSUE THREAD

**Issue by DareFox** [ValveSoftware/steam-for-linux#8989]
#### Your system information

* Steam client version (build number or date): 1670900101
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

##### Beta
On beta version of Steam, when trying to create new storage for games, I see no popup of choosing path for new library. 

https://user-images.githubusercontent.com/47672780/207356764-4f68ccb1-6a56-4385-ace3-ccae932dde2c.mp4

*You can work around this, when choosing installation path of game. However, it doesn't support custom paths

##### Stable
In stable version this works normally:

https://user-images.githubusercontent.com/47672780/207356744-a67168b6-7322-4f4f-870d-1330f23a7c0b.mp4

#### Steps for reproducing this issue:
1. Open Settings -> Downloads -> Steam Library Folders
2. Try to create new library
3. See no popup

**Comment by VladimirMrzv** [comment]
also broken function to move game to another storage.
Maybe the same problem, dialog window not appearing.

**Comment by DareFox** [comment]
Fixed in latest beta version 1671133406

https://user-images.githubusercontent.com/47672780/208320407-8a0226b8-f2db-46eb-a943-dff4a743b03f.mp4

**Comment by kylemonti** [comment]
@DareFox Just installed Beta Today (25/04/2023) and it's still having the same problem. Manjaro Linux (Linux 6.3.0-1 kernel).

**Comment by kisak-valve** [comment]
Hello @kylemonti, please open a new issue report.
