### ISSUE TITLE
X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/steam-for-linux#9164]
#### Your system information

* Steam client version (build number or date): Jan 31 2023, at 19:10:17
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After starting Steam the log is spammed by X errors every 5-10 seconds.

```
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Steam: An X Error occurred
Feb 02 17:48:11 domi-pc steam.desktop[16870]: X Error of failed request:  BadWindow (invalid Window parameter)
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Major opcode of failed request:  20 (X_GetProperty)
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Resource id in failed request:  0x0
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Serial number of failed request:  9
Feb 02 17:48:11 domi-pc steam.desktop[16870]: xerror_handler: X failed, continuing
```

There are no obvious issues with the Steam client itself.

Steam system information:
[steam_system_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/10571337/steam_system_info.txt)

#### Steps for reproducing this issue:

1. Start Steam
2. Wait and look at syslog

**Comment by DomiStyle** [comment]
Just noticed that a few notifications are black, maybe related to the errors above.

![Screenshot from 2023-02-02 21-33-08](https://user-images.githubusercontent.com/975131/216443506-580fe800-179a-446a-9b3d-5a588488b801.png)

**Comment by FurtadoPires** [comment]
Can confirm it's also happening in Manjaro Gnome

-steam build 1675397711
-wayland 1.21.0-2
-mutter 43.2-2
-mesa 22.3.4-1
-kernel 6.1.9-1

**Comment by nmiell** [comment]
It is continuously trying to retrieve _NET_WM_PID from window ID 0, which isn't a valid window.

I thought this was a problem with the Steam client beta, but when I reverted to the mainline release it continued happening.

**Comment by DomiStyle** [comment]
> but when I reverted to the mainline release it continued happening.

Yes, the issue started with the update that added the new Big Picture UI.

**Comment by Saroumane** [comment]
Problem reproduced with Ubuntu 22.10, I think the label "Distro Family: Fedora" can be removed (or extented)

**Comment by JordanPlayz158** [comment]
Problem reproduced on Crystal Linux 6.1.9-arch1-1

**Comment by STEVE4git** [comment]
Fedora 37, yep

**Comment by sn99** [comment]
Can confirm, unable to play `dota2`

**Comment by makusu720** [comment]
same on arch

**Comment by sn99** [comment]
@DomiStyle https://github.com/ValveSoftware/Dota-2/issues maybe make an issue here too?

**Comment by DomiStyle** [comment]
@sn99 I don't play Dota so I don't see what I should report there?

**Comment by romulasry** [comment]
Same issue Fedora Rawhide.

**Comment by TheCCraft** [comment]
Also with Gentoo

**Comment by LocalMachineOnLinux** [comment]
pop os nvidia drivers same problem. :(

**Comment by tjssoldier** [comment]
Its happening in Arch too, the games eventually launches but it takes some time. Only happens with Steam, i can launch games from Heroic with no problems.

**Comment by racerxff** [comment]
Possible bread crumb: I stopped this message by Steam>Settings>Remote Play>Advanced Client Options>Change Performance Overlay to Disabled

**Comment by jokeyrhyme** [comment]
I don't seem to be able to reproduce this with the Steam flatpak

**Comment by WhyNotHugo** [comment]
This only happens for me when Steam is unfocused, and triggers immediately when steam loses focus and then periodically while it remains unfocused.

I'm using Wayland (swaywm), so I suspect that when steam is unfocused, the currently focused X window is `0` (i.e.: `NULL`).

AFAIK, `_NET_WM_PID` exposes the id of an Xorg client. Is steam trying to track the focused window? If so, I suspect it's getting `0`/`NULL` and trying to fetch `_NET_WM_PID` with that invalid value.

**Comment by Fishhooks1945** [comment]
I am having the same issue with Gang Beasts. Here is my system specs.
System:
  Host: pop-os Kernel: 6.0.12-76060006-generic x86_64 bits: 64 compiler: N/A
    Desktop: GNOME 42.3.1 tk: GTK 3.24.33 wm: gnome-shell dm: GDM3
    Distro: Pop!_OS 22.04 LTS base: Ubuntu 22.04 LTS Jammy
Machine:
  Type: Desktop Mobo: Micro-Star model: MPG B550 GAMING PLUS (MS-7C56) v: 1.0
    serial: 07C5611_KC1E245991 UEFI: American Megatrends LLC. v: 1.50
    date: 01/14/2021
Memory:
  RAM: total: 15.55 GiB used: 8.86 GiB (57.0%)
  Array-1: capacity: 128 GiB slots: 4 EC: None max-module-size: 32 GiB
    note: est.
  Device-1: DIMM 0 size: No Module Installed
  Device-2: DIMM 1 size: 8 GiB speed: 2133 MT/s type: DDR4
    manufacturer: G.Skill part-no: F4-3200C16-8GVKB
  Device-3: DIMM 0 size: No Module Installed
  Device-4: DIMM 1 size: 8 GiB speed: 2133 MT/s type: DDR4
    manufacturer: G.Skill part-no: F4-3200C16-8GVKB
CPU:
  Info: 6-core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 32 MiB
  Speed (MHz): avg: 2200 min/max: 2200/4208 boost: enabled cores: 1: 2200
    2: 2200 3: 2200 4: 2200 5: 2200 6: 2200 7: 2200 8: 2200 9: 2200 10: 2200
    11: 2200 12: 2200 bogomips: 86407
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]
    vendor: PC Partner driver: radeon v: kernel pcie: speed: 5 GT/s lanes: 16
    ports: active: VGA-1 empty: DVI-D-1,HDMI-A-1 bus-ID: 2b:00.0
    chip-ID: 1002:6779
  Display: server: X.Org v: 1.21.1.3 compositor: gnome-shell driver: X:
    loaded: ati,radeon unloaded: fbdev,modesetting,vesa gpu: radeon
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: VGA-0 mapped: VGA-1 model: BenQ GW2270 res: 1920x1080 dpi: 102
    diag: 546mm (21.5")
  OpenGL:
    renderer: AMD CAICOS (DRM 2.50.0 / 6.0.12-76060006-generic LLVM 14.0.0)
    v: 3.3 Mesa 22.2.0 compat-v: 3.1 direct render: Yes
Audio:
  Device-1: AMD Caicos HDMI Audio [Radeon HD 6450 / 7450/8450/8490 OEM R5
    230/235/235X OEM]
    vendor: PC Partner driver: snd_hda_intel v: kernel pcie: speed: 5 GT/s
    lanes: 16 bus-ID: 2b:00.1 chip-ID: 1002:aa98
  Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 2d:00.4 chip-ID: 1022:1487
  Sound Server-1: ALSA v: k6.0.12-76060006-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: no
  Sound Server-3: PipeWire v: 0.3.63 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Micro-Star MSI driver: r8169 v: kernel pcie: speed: 2.5 GT/s
    lanes: 1 port: f000 bus-ID: 2a:00.0 chip-ID: 10ec:8168
  IF: enp42s0 state: up speed: 1000 Mbps duplex: full
    mac: 2c:f0:5d:e3:a5:85
  IF-ID-1: ham0 state: unknown speed: 10 Mbps duplex: full
    mac: 7a:79:00:00:00:00
Drives:
  Local Storage: total: 1.36 TiB used: 246.02 GiB (17.6%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 500GB size: 465.76 GiB
    speed: 31.6 Gb/s lanes: 4 serial: S64ENJ0R607865F temp: 29.9 C
  ID-2: /dev/sda vendor: Western Digital model: WD1003FBYX-01Y7B1
    size: 931.51 GiB speed: 3.0 Gb/s serial: WD-WCAW35179012
Partition:
  ID-1: / size: 449.02 GiB used: 242.85 GiB (54.1%) fs: ext4
    dev: /dev/nvme0n1p3
  ID-2: /boot/efi size: 497 MiB used: 386 MiB (77.7%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) priority: -2
    dev: /dev/dm-0 mapped: cryptswap
  ID-2: swap-2 type: zram size: 15.55 GiB used: 1.68 GiB (10.8%)
    priority: 1000 dev: /dev/zram0
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: radeon temp: 45.5 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2546 apt: 2537 snap: 9
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/appimagelauncher-team-ubuntu-stable-jammy.list
    1: deb https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/element-io.list
    1: deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main
  Active apt repos in: /etc/apt/sources.list.d/minetestdevs-ubuntu-stable-jammy.list
    1: deb https://ppa.launchpadcontent.net/minetestdevs/stable/ubuntu/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/mixxx-ubuntu-mixxx-jammy.list
    1: deb https://ppa.launchpadcontent.net/mixxx/mixxx/ubuntu/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/nextdns.list
    1: deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
  Active apt repos in: /etc/apt/sources.list.d/steam.list
    1: deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
    2: deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list
    1: deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https://linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/pop-os-apps.sources
    1: deb http://apt.pop-os.org/proprietary jammy main
  Active apt repos in: /etc/apt/sources.list.d/pop-os-release.sources
    1: deb deb-src http://apt.pop-os.org/release jammy main
  Active apt repos in: /etc/apt/sources.list.d/system.sources
    1: deb deb-src http://apt.pop-os.org/ubuntu jammy jammy-security jammy-updates jammy-backports main restricted universe multiverse
    2: deb deb-src X-Repolib-Default-Mirror: http://apt.pop-os.org/ubuntu jammy jammy-security jammy-updates jammy-backports main restricted universe multiverse
Info:
  Processes: 340 Uptime: 1d 20h 46m Init: systemd v: 249 runlevel: 5
  Compilers: gcc: 11.3.0 alt: 11/12 Shell: Sudo v: 1.9.9
  running-in: gnome-terminal inxi: 3.3.13
Here is my error.
Feb 20 19:12:06 pop-os steam.desktop[13405]: Steam: An X Error occurred
Feb 20 19:12:06 pop-os steam.desktop[13405]: X Error of failed request:  BadWindow (invalid Window parameter)
Feb 20 19:12:06 pop-os steam.desktop[13405]: Major opcode of failed request:  20 (X_GetProperty)
Feb 20 19:12:06 pop-os steam.desktop[13405]: Resource id in failed request:  0x2a003ba
Feb 20 19:12:06 pop-os steam.desktop[13405]: Serial number of failed request:  26
Feb 20 19:12:06 pop-os steam.desktop[13405]: xerror_handler: X failed, continuing
Feb 20 19:12:06 pop-os steam.desktop[50419]: ERROR: ld.so: object '/home/gamerforlife/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF cl
Thanks for the help!

**Comment by jalcam** [comment]
I have the same error with Ubuntu 22.10. (gnome, X11, linux 5.19.0-31-generic)

Steam Built Feb 14 2023, at 00:47:47
Steam API: v020
Steam package versions: 1676336721

My system is a R7 7700X, GPU: RTX 2060 Super, Asrock x670e Steel Legend

I was playing Age of Mythology, and after saving and exit to the Steam library the system I got the same message

<pre>Feb 23 13:02:48 PC1 steam.desktop[14581]: Steam: An X Error occurred
Feb 23 13:02:48 PC1 steam.desktop[14581]: X Error of failed request:  BadWindow (invalid Window parameter)
Feb 23 13:02:48 PC1 steam.desktop[14581]: Major opcode of failed request:  20 (X_GetProperty)
Feb 23 13:02:48 PC1 steam.desktop[14581]: Resource id in failed request:  0x3e00176
Feb 23 13:02:48 PC1 steam.desktop[14581]: Serial number of failed request:  23
Feb 23 13:02:48 PC1 steam.desktop[14581]: xerror_handler: X failed, continuing
Feb 23 13:02:48 PC1 steam.desktop[14581]: Steam: An X Error occurred
Feb 23 13:02:48 PC1 steam.desktop[14581]: X Error of failed request:  BadWindow (invalid Window parameter)
Feb 23 13:02:48 PC1 steam.desktop[14581]: Major opcode of failed request:  20 (X_GetProperty)
Feb 23 13:02:48 PC1 steam.desktop[14581]: Resource id in failed request:  0x3e00176
Feb 23 13:02:48 PC1 steam.desktop[14581]: Serial number of failed request:  23
Feb 23 13:02:48 PC1 steam.desktop[14581]: xerror_handler: X failed, continuing
Feb 23 13:02:48 PC1 gamemoded[16613]: ERROR: Failed to open file for read /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:0/energy_uj
Feb 23 13:02:48 PC1 gamemoded[16613]: ERROR: Skipping ioprio on client [16612,16612]: ioprio was (0) but we expected (4)
Feb 23 13:02:48 PC1 steam.desktop[16612]: ERROR: ld.so: object &apos;libgamemodeauto.so.0&apos; from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Feb 23 13:02:48 PC1 steam.desktop[16612]: ERROR: ld.so: object &apos;/home/juanjose/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Feb 23 13:02:48 PC1 steam.desktop[16619]: ERROR: ld.so: object &apos;/home/juanjose/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Feb 23 13:02:48 PC1 gamemoded[16613]: ERROR: Skipping ioprio on client [16619,16619]: ioprio was (0) but we expected (4)
Feb 23 13:02:48 PC1 steam.desktop[16619]: ERROR: ld.so: object &apos;/home/juanjose/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Feb 23 13:02:48 PC1 gamemoded[16613]: ERROR: Addition requested for already known client 16619 [/home/juanjose/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper].
Feb 23 13:02:48 PC1 gamemoded[16613]:     -- This may happen due to using exec or shell wrappers. You may want to
Feb 23 13:02:48 PC1 gamemoded[16613]:     -- blacklist this client so GameMode can see its final name here.
Feb 23 13:02:48 PC1 steam.desktop[16619]: gamemodeauto:
Feb 23 13:02:48 PC1 steam.desktop[16620]: ERROR: ld.so: object &apos;/home/juanjose/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so&apos; from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Feb 23 13:02:48 PC1 gamemoded[16613]: ERROR: Skipping ioprio on client [16620,16620]: ioprio was (0) but we expected (4)
Feb 23 13:02:49 PC1 gamemoded[16613]: ERROR: Skipping ioprio on client [16703,16703]: ioprio was (0) but we expected (4)
Feb 23 13:02:49 PC1 steam.desktop[16739]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16739]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16739]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16740]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16742]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16742]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16743]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16743]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16743]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16744]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16745]: fsync: up and running.
Feb 23 13:02:49 PC1 steam.desktop[16745]: wine: RLIMIT_NICE is &lt;= 20, unable to use setpriority safely
Feb 23 13:02:49 PC1 steam.desktop[16747]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16749]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16752]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16761]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16744
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16742
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16741
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16740
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16620
Feb 23 13:02:49 PC1 steam.desktop[16774]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16780]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16747]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[16787]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[14581]: Game process updated : AppID 266840 &quot;xres=3440 yres=1440 gamemoderun /home/juanjose/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=266840 -- /home/juanjose/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- &apos;/home/juanjose/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier&apos;/_v2-entry-poin<span style="background-color:#FFFFFF"><font color="#300A24">&gt;</font></span>
Feb 23 13:02:49 PC1 steam.desktop[16743]: Setting breakpad minidump AppID = 266840
Feb 23 13:02:49 PC1 steam.desktop[16743]: Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198453677597 [API loaded no]
Feb 23 13:02:49 PC1 steam.desktop[16789]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:49 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16747
Feb 23 13:02:50 PC1 steam.desktop[16798]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:50 PC1 steam.desktop[16812]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:50 PC1 steam.desktop[16814]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:50 PC1 steam.desktop[16789]: gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
Feb 23 13:02:50 PC1 steam.desktop[16818]: ERROR: ld.so: object &apos;/tmp/pressure-vessel-libs-SPVS01/${PLATFORM}/libgamemodeauto.so.0&apos; from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Feb 23 13:02:50 PC1 steam.desktop[14581]: Game process updated : AppID 266840 &quot;xres=3440 yres=1440 gamemoderun /home/juanjose/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=266840 -- /home/juanjose/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- &apos;/home/juanjose/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier&apos;/_v2-entry-poin<span style="background-color:#FFFFFF"><font color="#300A24">&gt;</font></span>
Feb 23 13:02:50 PC1 steam.desktop[16818]: Setting breakpad minidump AppID = 266840
Feb 23 13:02:50 PC1 steam.desktop[16818]: Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198453677597 [API loaded no]
Feb 23 13:02:51 PC1 gnome-shell[3134]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x5a00007 specified for 0x5a00005.
Feb 23 13:03:08 PC1 steam.desktop[16891]: ERROR: ld.so: object &apos;/tmp/pressure-vessel-libs-SPVS01/${PLATFORM}/libgamemodeauto.so.0&apos; from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Feb 23 13:03:08 PC1 gnome-shell[3134]: <font color="#D7D75F"><b>JS ERROR: TypeError: this._app.appInfo is null</b></font>
                                       <font color="#D7D75F"><b>_getNonDefaultLaunchGpu@resource:///org/gnome/shell/ui/appMenu.js:191:9</b></font>
                                       <font color="#D7D75F"><b>_updateGpuItem@resource:///org/gnome/shell/ui/appMenu.js:174:32</b></font>
                                       <font color="#D7D75F"><b>_onAppStateChanged@resource:///org/gnome/shell/ui/appMenu.js:130:14</b></font>
Feb 23 13:03:08 PC1 steam.desktop[14581]: Game process updated : AppID 266840 &quot;xres=3440 yres=1440 gamemoderun /home/juanjose/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=266840 -- /home/juanjose/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- &apos;/home/juanjose/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier&apos;/_v2-entry-poin<span style="background-color:#FFFFFF"><font color="#300A24">&gt;</font></span>
Feb 23 13:03:09 PC1 steam.desktop[16891]: Setting breakpad minidump AppID = 266840
Feb 23 13:03:09 PC1 steam.desktop[16891]: Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198453677597 [API loaded no]
Feb 23 13:03:09 PC1 steam.desktop[14581]: ThreadGetProcessExitCode: no such process 16818
Feb 23 13:03:09 PC1 gnome-shell[3134]: Window manager warning: Window 0x5a00003 sets an MWM hint indicating it isn&apos;t resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn&apos;t make much sense.
Feb 23 13:03:09 PC1 steam.desktop[16891]: Fossilize INFO: Overriding serialization path: &quot;/home/juanjose/.steam/debian-installation/steamapps/shadercache/266840/fozpipelinesv6/steamapprun_pipeline_cache&quot;.
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 71 with keysym 71 (keycode 18).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Feb 23 13:03:37 PC1 gnome-shell[3134]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).</pre>

**Comment by bekopharm** [comment]
Same here, Fedora 37 and Gnome Wayland.

Everything is forwarded to journald clogging the log with the same message over and over again.

I'm starting steam like this now to prevent this: `steam > /dev/null 2>&1 &`

No idea how to prevent this from happening otherwise. No Steam errors are logged now any more, of course.

**Comment by Saroumane** [comment]
If you just want to get rid of errors (including this one) and keep other steam messages, you can use `steam 2>/dev/null`

**Comment by StarterX4** [comment]
Valve should get rid of GTK2 and other legacy X11 dependencies.
It's 2023, and we need a clean Wayland experience.

**Comment by Laiot** [comment]
I just got the same error after trying to play Hollow Knight on my laptop with Fedora, Swaywm and my Nvida 3080 mobile card.
I'm surprised, I really thought it had to do with my HW + WM choice.

**Comment by PickMeNow** [comment]
Got the same error:

Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: Steam: An X Error occurred
Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: X Error of failed request:  BadWindow (invalid Window parameter)
Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: Major opcode of failed request:  20 (X_GetProperty)
Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: Resource id in failed request:  0x0
Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: Serial number of failed request:  9
Mar 03 20:10:44 ArchLinux steam-native.desktop[5161]: xerror_handler: X failed, continuing

OS: Arch Linux x86_64
Kernel: 6.2.1-zen1-1-zen
DE: GNOME 43.3
WM: Mutter
GPU: 6800XT - Mesa 22.3.6

**Comment by gregprojects** [comment]
On Manjaro Gnome getting the same error trying to launch titanfall 2 on the steam beta and regular steam. The system is up to date, started happening after Tuesday's steam update. 

Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing

Kernal 6.0.19-4
Gnome 43.3
7900 XTX on Mesa 23.1.0-devel

**Comment by RomanAverin** [comment]
Same issue on Fedora 37, wayland, nvidia

**Comment by xeals** [comment]
Noticing error messages in `steamwebhelper.log` and `cef_log.txt` at the same time with more information:

```
[...:ERROR:gl_surface_egl.cc(741)] EGL Driver message (Error) eglGetMscRateANGLE: glXGetMscRateOML failed.
[...:WARNING:xproto_util.cc(51)] X error received: serial 765550, error_code 2 (BadValue (integer parameter out of range for operation)), request_code 150, minor_code 1 (XF86VidModeGetModeLine)
```

**Comment by feer9** [comment]
Same problem here on Arch Linux. Waiting for an update on the matter, since the steam UI is getting freezes from time to time, and I presume that problem might be related to this error messages. I also see the black notifications @DomiStyle mentioned.

**Comment by DomiStyle** [comment]
If you're on Wayland the freezing issue is https://github.com/ValveSoftware/steam-for-linux/issues/7245 and has been around for quite a while.

**Comment by HenrikDK2** [comment]
I'm having the same problem on Arch Linux running Sway (Wayland)

**Comment by nikolaos-spyratos** [comment]
Had this for friends notifications but not "game finished installing" notifications, interesting.

**Comment by yassinebenarbia** [comment]
Same on Arch x86_64, Wayland, Hyprland, kernel 6.1.12 .

**Comment by p4lik4ri** [comment]
same error on ubuntu 22.04 (jellyfish) 

Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing

**Comment by Ashizian** [comment]
This bug is still here after the last Steam update. Nothing dangerous but it fill your log with an alarming speed.

My solution for now is to get rid of every Steam error messages.

**Comment by Samuuuh** [comment]
Got the same error while opening League of Legends on Arch.

However, like @WhyNotHugo said, this only happens for me when the window is unfocused. Leaving the mouse in the logo while opening, make this error vanish.

**Comment by xXTeraXx** [comment]
Have the same error, on Forza Horizon 5

Xorg (i3wm)
GPU: AMD (amdgpu driver) 6650xt

**Comment by 0xC0ncord** [comment]
Ever since I started seeing this I haven't been able to open any games' properties within Steam (to manage its files, edit launch options, etc). The window that would normally appear seems to trigger the same error and crashes.

**Comment by nmiell** [comment]
This appears to have been fixed on the beta branch.

**Comment by StarterX4** [comment]
For me the beta fixed the X errors, but now instead Glib errors appear in a similar manner between like 10 secs, and independently of the window focus. 
```
(steam:3840): GLib-CRITICAL **: 11:41:46.810: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:3840): GLib-CRITICAL **: 11:41:46.811: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

(steam:3840): GLib-CRITICAL **: 11:41:56.811: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:3840): GLib-CRITICAL **: 11:41:56.811: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

(steam:3840): GLib-CRITICAL **: 11:42:06.820: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:3840): GLib-CRITICAL **: 11:42:06.820: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

(steam:3840): GLib-CRITICAL **: 11:42:16.822: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:3840): GLib-CRITICAL **: 11:42:16.822: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
```

**Comment by 0xC0ncord** [comment]
Last night I saw that there were 2 betas. The first of which fixed the X errors, but the app properties window would be embedded inside of the Steam client instead of opened as a new window and attempting to close it would make the rest of the client unusable. This seems to have been partially reverted in the second (current) beta. As of right now, the X errors at startup are gone but they appear for me once again when opening app properties, causing the same crash I described above.

**Comment by Schmensch** [comment]
I have a similar issue, everytime I launch a game my system journal is spammed with these messages. However, what's far worse is that no games actually "launch". Steam says they're running and the process exists, but no window ever opens.

**Comment by cmnemoi** [comment]
> I have a similar issue, everytime I launch a game my system journal is spammed with these messages. However, what's far worse is that no games actually "launch". Steam says they're running and the process exists, but no window ever opens.

Same here

**Comment by Fishhooks1945** [comment]
I do not know what I did to Steam but after repeatedly launching Gang Beasts it eventually launched without any problems.
Here is the most recent log that worked:

`LogCS: Couldn't find value with key 'MENU_MUTE_BEAST' in JSON file 'english'
02/24/2023 05:01:11
LogCS.LogFormatE(). Line: 0 

LogCS: Couldn't find value with key 'JOIN_SCREEN_JOIN' in JSON file 'english'
02/24/2023 05:01:17
LogCS.LogFormatE(). Line: 0 

LogCS: InputVersion has changed, resetting all inputs
02/24/2023 05:01:30
InputUserDataStorage.LoadPref(). Line: 0 

LogCS: Couldn't find value with key 'JOIN_SCREEN_JOIN' in JSON file 'english'
02/24/2023 05:01:33
LogCS.LogFormatE(). Line: 0 

LogCS: [globalManager] Destroyed, stopped routine
02/24/2023 05:01:39
GlobalManager.OnDestroy(). Line: 0 

LogCS: ERROR (NotificationTicker): BaseplatformManager is null... panic
02/24/2023 05:01:39
NotificationTicker.ShowMessage(). Line: 0 `

**Comment by Schmensch** [comment]
> I have a similar issue, everytime I launch a game my system journal is spammed with these messages. However, what's far worse is that no games actually "launch". Steam says they're running and the process exists, but no window ever opens.

The issue with games not opening properly wasn't related to this issue, I just forgot to install lib32-vulkan-radeon

**Comment by Qervas** [comment]
same error, Fedora38-6.2.11-300.fc38.x86_64 xorg nvidia-530.41.
New installation game just crashed within 1 seconds from launching.

**Comment by kisak-valve** [comment]
Hello @Qervas, the issue being tracked here is non-fatal to Steam or any games. This is a red herring in the troubleshooting of your issue.

**Comment by meisme-dev** [comment]
Can reproduce on Fedora 38 with the Steam flatpak

**Comment by Insem** [comment]
The same issue with steam-link on Manjaro+GNOME+Wayland. It's funny but steam-links works, I can manipulate my computer by TV remote

**Comment by ivanko4elorov** [comment]
Have same issue with trying to launch XCOM on pop_os

**Comment by memchr** [comment]
This particular error message has been bombarding my journald with 2 GB of `BadWindow` logs. Is there any way to suppress it?

**Comment by Saroumane** [comment]
> This particular error message has been bombarding my journald with 2 GB of `BadWindow` logs. Is there any way to suppress it?

If you are ok to lose other messages, you can do something like `# journalctl --vacuum-size=50M`
And to prevent it from happening again, always launch steam like this until the problem is fixed :
`$ steam 2>/dev/null`

**Comment by MajorGonzo** [comment]
Using Ubuntu 22.04.  Of note - this error occurs immediately upon launching Steam (and every 5 seconds afterwards) if I'm using Wayland for my session, and does not occur if I use X11 for my session.  This error does not require a game to launch to occur.

**Comment by xcpky** [comment]
confirmed, and games can be launched normally. However when I can't quit some certain games, and have to force to stop the game in steam client.

**Comment by af7567** [comment]
I get these messages in my steamwebhelper.log, repeating non stop for as long as a steam window is visible. It seems to be BadAlloc followed by a few others most of the time, but sometimes it's just repeating BadWindow

```
Webhelper: An X Error occurred
X Error of failed request:  BadAlloc (insufficient resources for operation)
Major opcode of failed request:  151
Serial number of failed request:  35536
Webhelper: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  155
Resource id in failed request:  0x6003772
Serial number of failed request:  35537
Webhelper: An X Error occurred
X Error of failed request:  GLXBadPixmap
Major opcode of failed request:  151
Serial number of failed request:  0
Webhelper: An X Error occurred
X Error of failed request:  GLXBadPixmap
Major opcode of failed request:  151
Serial number of failed request:  0
Webhelper: An X Error occurred
X Error of failed request:  GLXBadPixmap
Major opcode of failed request:  151
Serial number of failed request:  35538
```

```
Webhelper: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  7 (X_ReparentWindow)
Resource id in failed request:  0x0
Serial number of failed request:  60142
Webhelper: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  7 (X_ReparentWindow)
Resource id in failed request:  0x0
Serial number of failed request:  60143
Webhelper: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  7 (X_ReparentWindow)
Resource id in failed request:  0x0
Serial number of failed request:  60182
Webhelper: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  15 (X_QueryTree)
Resource id in failed request:  0x520001b
Serial number of failed request:  60242
```

**Comment by derimpuls** [comment]
Can we please push this, Valve? This absolutely blocks me from upgrading my distro to Manjaro 23.0.0. I can't get any steam game in my library to run.
`X Error of failed request: BadWindow (invalid Window parameter)`

**Comment by nmiell** [comment]
This bug was fixed on the beta branch, the fix has been propagated to the release branch and this bug can now be closed, and it never interfered with your ability to run games.

**Comment by af7567** [comment]
I am still getting these errors on the latest beta 1687306661. For me they are in the steamwebhelper.log though, not syslog. It doesn't affect starting games for me, but may be the reason for getting a black steam window sometimes.

When starting steam they go non stop and create a 3MB log file, but after that it only happens when loading different pages or mousing over anything that animates. Even mousing over the top menu bar (Steam View Friends Games Help) generates the errors when it highlights the text in white.

**Comment by Saroumane** [comment]
@af7567 You are not alone, I see the same problem on Steam Version:  1686880776 (non beta) : 
black empty pages in the Store (inside the Steam client) and same error messages in `~/.steam/debian-installation/logs/steamwebhelper.log`
But maybe it should be tracked here ? https://github.com/ValveSoftware/steam-for-linux/issues/9566

**Comment by awsms** [comment]
Realized I was running low on my home partition.. because the steamwebhelper.log reached 2GB. I'm gonna drop Steam and move back to GOG since -vgui isn't a thing anymore.

**Comment by Toni500github** [comment]
Happening to have the same issue on EndeavourOS, XFCE4

**Comment by ipr** [comment]
Ok, this just happening for me.
There was another problem earlier that may have been fixed but now I am seeing this happening.

Problem is like before: first start of Steam client has error, exit and start again it works.

```
[2025-07-28 06:10:58] X Error of failed request:  BadWindow (invalid Window parameter)
[2025-07-28 06:10:58] Major opcode of failed request:  129
[2025-07-28 06:10:58] Resource id in failed request:  0x1a00006
[2025-07-28 06:10:58] Serial number of failed request:  1256
```

And
```
[2025-07-28 06:10:58] [0728/061058.389315:WARNING:connection.cc(56)] X error received.  Request: Shm::PutImageRequest, Error: DrawableError{.sequence = 1470, .bad_value = 27262984, .minor_opcode = 3, .major_opcode = 130}
```

**Comment by ipr** [comment]
Steam client version: 
Steam Beta Branch:  Stable Client
Steam Version:  1751405894
Steam Client Build Date:  Sat, Jun 28 04:07 UTC -08:00
Steam Web Build Date:  Wed, Jul 2 00:19 UTC -08:00
Steam API Version:  SteamClient022

**Comment by ipr** [comment]
After restarting computer and starting client again the problem did not appear. So this might be another "transient" bug that is timing sensitive.
