### ISSUE TITLE
Updated Big Picture Mode not working when opened from GUI

### ISSUE THREAD

**Issue by olddesklamp** [ValveSoftware/steam-for-linux#9190]
#### My system information

* Steam client version: Jan 31 2023, built at 19:10:17
* Distribution: Pop!_OS 22.04 (Ubuntu with QoL alterations) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD Radeon R9 280X using AMDGPU drivers on X11

#### The problem described

The updated Big Picture Mode doesn't start correctly when opened from either the client or the system tray, instead periodically glitching the entire display while playing a sound effect as shown in this video:

https://user-images.githubusercontent.com/74428438/217661197-eba51fb8-7f09-429a-add3-12333e21a216.mp4

It continues behaving this way until I exit Big Picture Mode. This is similar to what's been described in #8916, but unlike any reports on that issue this has nothing to do with Nvidia drivers as I'm using an aging AMD card. Accessing Big Picture Mode  by starting Steam with `steam -gamepadui` in the terminal works fine.

#### Steps for reproducing this issue:

1. Start Steam
2. Enter Big Picture Mode from either the system tray or the Steam client

**Comment by kisak-valve** [comment]
Hello @olddesklamp, this issue may have already been fixed in the current Steam client beta. Please opt into Steam's client beta and retest.

**Comment by olddesklamp** [comment]
@kisak-valve  Nope. Still happens after switching to the latest beta (Feb 6 @ 19:03).

**Comment by smcv** [comment]
Using `journalctl` to look for output from Steam in the systemd journal might provide some clues.

**Comment by olddesklamp** [comment]
<details><summary>Output of journalctl after opening Steam and entering then shortly exiting Big Picture Mode. I did all of this after a cold boot.</summary>

<p>

```

Feb 11 11:08:38 mercury systemd[1638]: app-gnome-xprop-8889.scope: Failed to add PIDs to scope's control group: No such process
Feb 11 11:08:38 mercury systemd[1638]: app-gnome-xprop-8889.scope: Failed with result 'resources'.
Feb 11 11:08:38 mercury systemd[1638]: Failed to start Application launched by gnome-shell.
Feb 11 11:08:38 mercury systemd[1]: apt-news.service: Deactivated successfully.
Feb 11 11:08:38 mercury systemd[1]: Finished Update APT News.
Feb 11 11:08:38 mercury kernel: Composite Threa[8859]: segfault at 0 ip 0000000000000000 sp 00007f93314fe668 error 14 in steamwebhelper[400000+4d4000]
Feb 11 11:08:38 mercury kernel: Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
Feb 11 11:08:39 mercury PackageKit[1413]: get-packages transaction /2954_adbaeadd from uid 1000 finished with success after 1511ms
Feb 11 11:08:39 mercury PackageKit[1413]: get-updates transaction /2955_cbdbaace from uid 1000 finished with success after 445ms
Feb 11 11:08:40 mercury PackageKit[1413]: get-details transaction /2956_cddeadda from uid 1000 finished with success after 293ms
Feb 11 11:08:44 mercury chronyd[1154]: Selected source 15.237.97.214 (paris.time.system76.com)
Feb 11 11:08:45 mercury steam.desktop[5793]: ExecuteSteamURL: "steam://open/steam://close/bigpicture"
Feb 11 11:08:45 mercury steam.desktop[5793]: ExecuteSteamURL: "steam://close/bigpicture"
Feb 11 11:08:46 mercury steam.desktop[8903]: steamwebhelper.sh[8903]: Runtime for steamwebhelper: defaulting to /home/josh/.steam/debian-installation/ubunt>
Feb 11 11:08:46 mercury steam.desktop[8903]: steamwebhelper.sh[8903]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Feb 11 11:08:47 mercury chronyd[1154]: Selected source 3.134.129.152 (ohio.time.system76.com)
Feb 11 11:08:47 mercury steam.desktop[5793]: BuildCompleteAppOverviewChange: 220 apps
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam.desktop[5793]: RegisterForAppOverview 1: 5ms
Feb 11 11:08:47 mercury steam.desktop[5793]: RegisterForAppOverview 2: 5ms
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:47 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:48 mercury steam.desktop[5793]: Could not connect to X session manager: None of the authentication protocols specified are supported
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:49 mercury steam[5793]: gtk_disable_setlocale() must be called before gtk_init()
Feb 11 11:08:54 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5634e3f60340] is on because it needs an allocation.
Feb 11 11:08:54 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5634e6ec0f10] is on because it needs an allocati>
Feb 11 11:08:54 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5634e6ec2dc0] is on because it needs an allocat>
Feb 11 11:10:39 mercury systemd[1638]: Started Application launched by gsd-media-keys.
Feb 11 11:10:45 mercury gsd-media-keys[9152]: ATTENTION: default value of option mesa_glthread overridden by environment.
Feb 11 11:10:45 mercury gsd-media-keys[9152]: ATTENTION: default value of option mesa_glthread overridden by environment.
Feb 11 11:10:45 mercury gsd-media-keys[9152]: ATTENTION: default value of option mesa_glthread overridden by environment.
Feb 11 11:10:45 mercury gsd-media-keys[9152]: ATTENTION: default value of option mesa_glthread overridden by environment.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 9 threads of 4 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Successfully made thread 9288 of process 9152 owned by '1000' RT at priority 10.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:46 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5634e3f60340] is on because it needs an allocation.
Feb 11 11:10:46 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5634e454ab40] is on because it needs an allocati>
Feb 11 11:10:46 mercury gnome-shell[1873]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5634e7a5a340] is on because it needs an allocat>
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:46 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
Feb 11 11:10:47 mercury rtkit-daemon[1238]: Supervising 10 threads of 5 processes of 1 users.
```

<p>
</details>

**Comment by smcv** [comment]
> ```
> Feb 11 11:08:38 mercury kernel: Composite Threa[8859]: segfault at 0 ip 0000000000000000 sp 00007f93314fe668 error 14 in steamwebhelper[400000+4d4000]
> Feb 11 11:08:38 mercury kernel: Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
> ```

This is a crash somewhere inside `steamwebhelper`. If you re-run Steam (for example from a terminal), does it upload a crash report? If it does, please paste the crash report ID here. It should look something like this:

```
assert_20230203145619_24.dmp[7805]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230203145619_24.dmp
GetWin32Stats: restoring previous glx context
assert_20230203145619_24.dmp[7805]: Finished uploading minidump (out-of-process): success = yes
assert_20230203145619_24.dmp[7805]: response: CrashID=bp-aaaaaaaa-bbbb-cccc-dddd-eeff11223344
assert_20230203145619_24.dmp[7805]: file ''/tmp/dumps/assert_20230203145619_24.dmp'', upload yes: ''CrashID=bp-aaaaaaaa-bbbb-cccc-dddd-eeff11223344''
```

**Comment by olddesklamp** [comment]
Several crash IDs were given when I started then closed Steam both with the desktop and gamepad UIs. Here they are:

<details><summary>Destkop UI</summary>

```
/home/josh/.steam/debian-installation/steam.sh: line 798:  8879 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
josh@mercury ~> crash_20230213132940_30.dmp[9581]: Finished uploading minidump (out-of-process): success = yes
crash_20230213132940_30.dmp[9581]: response: CrashID=bp-1b14b063-75ca-4c59-91bd-f88b12230213
crash_20230213132940_30.dmp[9581]: file ''/tmp/dumps/crash_20230213132940_30.dmp'', upload yes: ''CrashID=bp-1b14b063-75ca-4c59-91bd-f88b12230213''
assert_20230213132940_29.dmp[9578]: Finished uploading minidump (out-of-process): success = yes
assert_20230213132940_29.dmp[9578]: response: CrashID=bp-b479d199-fa1c-4fc6-b7e9-c9c1d2230213
assert_20230213132940_29.dmp[9578]: file ''/tmp/dumps/assert_20230213132940_29.dmp'', upload yes: ''CrashID=bp-b479d199-fa1c-4fc6-b7e9-c9c1d2230213''
```
</details>

<details><summary>Gamepad UI</summary>

```

/home/josh/.steam/debian-installation/steam.sh: line 798:  9788 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
josh@mercury ~> assert_20230213133205_30.dmp[10524]: Finished uploading minidump (out-of-process): success = yes
assert_20230213133205_30.dmp[10524]: response: CrashID=bp-cc3aa5e0-f63c-41d2-a021-f0f282230213
assert_20230213133205_30.dmp[10524]: file ''/tmp/dumps/assert_20230213133205_30.dmp'', upload yes: ''CrashID=bp-cc3aa5e0-f63c-41d2-a021-f0f282230213''
crash_20230213133205_31.dmp[10527]: Finished uploading minidump (out-of-process): success = yes
crash_20230213133205_31.dmp[10527]: response: CrashID=bp-8ddfaf8b-942f-4d68-964d-c69ea2230213
crash_20230213133205_31.dmp[10527]: file ''/tmp/dumps/crash_20230213133205_31.dmp'', upload yes: ''CrashID=bp-8ddfaf8b-942f-4d68-964d-c69ea2230213''

```
</details>

**Comment by oblitum** [comment]
I'm having similar issue, but I'm on i3 with ArchLinux. Here's what happens: i3 offers multiple workspaces, when I fire up steam with the new deck UI, it's working fine, if I switch to another workspace and then back, the UI gets stuck, I can hear by clicking arrow keys or joystick that behind the scenes it seems steam is actively selecting stuff, but I can't see it happening, the only thing that I see showing up is when I click the steam menu, then the side menu shows up, but popup following clicking any of the options in the menu isn't displayed, even though I can hear selection in the hidden popup when using arrows. If I click for shutdown steam, I can't see the usual shutdown popup, but I can hear browsing it.

I can't do anything in the UI, so I just terminate it in htop. This also happens often when exiting some games. I'm now using `steam -oldbigpicture` to use the old bigpicture and avoid this bug in this new UI, it just makes it completely unusable.

**Comment by olddesklamp** [comment]
The latest update in the Steam Client Beta (Feb. 17 2023 @ 23:57:13) appears to have fixed this issue. Big Picture Mode now functions as it should.

**Comment by xemafuentes** [comment]
It still happens to me even with the latest update.

**My system information**
Steam client version: March 17 2023, built at 18:27:00
Distribution: Pop!_OS 22.04 (Ubuntu with QoL alterations)
Kernel: 6.2.0-76060200-generic (Official from System76)
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
GPU: AMD Radeon 6600M / Mesa 22.3.5 / X11
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

**The problem described**
The updated Big Picture Mode doesn't start correctly when opened from either the client or the system tray, but works fine by opening it from the terminal with `steam -gamepadui`

[Screencast from 18-03-23 08:39:52.webm](https://user-images.githubusercontent.com/66127502/226092680-d91bf480-f479-4fe7-8ca6-e046726c1157.webm)



[Screencast from 18-03-23 08:43:49.webm](https://user-images.githubusercontent.com/66127502/226092691-12fd2c1f-0f5b-4ef8-9014-8c8bd8f02302.webm)

**Comment by Noctis-Bennington** [comment]
I have the same problem, I have literally the same behaviour when I try to open Steam in Big picture mode. (Actually I can't even try the Beta version because does a similar thing).

Can confirm if I open Steam via terminal with steam --gamepadui it works too.

**Comment by Noctis-Bennington** [comment]
I just found the reason Big Picture wasn't working in my case. It seems if I don't open Steam with "using the discrete graphic" option, I can't open Steam properly. So, Steam doesn't open Big Picture mode in integrated graphic AMD...

**Comment by xemafuentes** [comment]
I found a workaround, so gonna post it just in case helps someone:

Edit the application launcher on _usr/share/applications/_ with root permissions (please, backup the file somewhere before changing anything):

`sudo gedit /usr/share/applications/steam.desktop`

and then making the following change:

`PrefersNonDefaultGPU=true` -> `PrefersNonDefaultGPU=false`

That solves it for me, going to keep testing if I notice a drop in performance but everything OK so far.
