### ISSUE TITLE
[Big Picture Mode] Overlay scaling issues on 4k display

### ISSUE THREAD

**Issue by last-partizan** [ValveSoftware/steam-for-linux#9278]
#### Your system information

* Steam client version (build number or date): Mar 17 2023, at 18:27:00
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When i start a game in Big Picture mode, and then open Steam Overlay, it's super big:

![Screenshot from 2023-03-19 11-05-51](https://user-images.githubusercontent.com/301015/226166925-25721064-4715-4a4c-b41f-7e5c2843868c.png)

It can be fixed partially by disabling "Automatically Scale User Interface", but in this case - text on "Controller settings" is still to big. And text becomes too small in normal steam interface, not overlay UI.

![Screenshot from 2023-03-19 11-05-18](https://user-images.githubusercontent.com/301015/226167022-ec677bd6-82d6-4492-874d-64db413e0a6d.png)

It happens only on Linux,  on Windows overlay scaling is fine.
It happens on my display (Dell U2720Q) and TV (LG CX 55 inch Class 4K Smart OLED TV)

#### Steps for reproducing this issue:

1. Open Steam in Big Picture Mode on 4k display
2. Starte any game
3. Open Steam Overlay

**Comment by marco-calautti** [comment]
I am getting the same issue on Arch Linux, kernel 6.2, with amdgpu drivers (RX 6800).

**Comment by last-partizan** [comment]
Update: This issue is resolved when using standalone gamescope session. But still present with Gnome.

**Comment by marco-calautti** [comment]
I am still getting the issue on KDE/KWin + X11.

**Comment by ademlabs** [comment]
Same issue as well. This is really awful. I have to set my scaling to 1.6 to make the main UI usable but the overlay is blown out of proportion. Right now on Linux + KDE + X11, it's either tiny main UI and barely usable overlay, or a proper main UI with a big fat unusable overlay.

**Comment by kisak-valve** [comment]
Hello, per "Fix a case where the overlay could have dpi scaling applied twice." in the [2023-06-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770775726198) Steam client beta update, please opt into Steam's beta client and retest.

**Comment by ademlabs** [comment]
Tested and the overlay UI scaling seems much much better now. Unfortunately the rest of the UI decided to throw a fit and misbehave, glitching and crashing, so I reverted back to stable release.

**Comment by azuredusk10** [comment]
I was also experiencing this bug on Pop OS using a 4K display in big picture mode. The latest stable release on July 10 2023 has fixed it. Thanks very much!

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.

**Comment by Whayme** [comment]
This still occurs occasionally as described in the current beta.  On a GNOME Wayland session in Arch Linux.  It seems to happen more or less frequently depending on the game, the original release of Alan Wake seems to trigger it pretty regularly for me.

**Comment by pkly** [comment]
Still happens on Fedora 40, Steam version 1709846872
2 monitors connected, 1 - 3440x1440, 2 - 4k tv, X11, 100% scaling on both, overlay launched on monitor 1, moved to 2 (via options -> display -> windowed -> check -> move -> uncked).
Menu displays fine, but the overlay is broken pretty much exactly like in pic (happened in 3 games I checked, every time)
