### ISSUE TITLE
Steam client beta failing to start (pulseaudio)

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/steam-for-linux#9320]
* Steam client version: 1680578442
* Distribution: Devuan (mixed stable/testing; libc6 2.36-8)
* Opted into Steam client beta: yes
* Have you checked for system updates: yes

```
$ steam -no-cef-sandbox
steam.sh[1675]: Running Steam on devuan 4 64-bit
steam.sh[1675]: STEAM_RUNTIME is enabled automatically
setup.sh[1820]: Steam runtime environment up-to-date!
steam.sh[1675]: Steam client's requirements are satisfied
[2023-04-04 18:30:17] Startup - updater built Apr  4 2023 02:46:54
[2023-04-04 18:30:17] Startup - Steam Client launched with: '/home/steam/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
[2023-04-04 18:30:17] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
04/04 18:30:17 Init: Installing breakpad exception handler for appid(steam)/version(1680578442)/tid(1941)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-04-04 18:30:17] Loading cached metrics from disk (/home/steam/Steam/package/steam_client_metrics.bin)
[2023-04-04 18:30:17] Using the following download hosts for Public, Realm steamglobal
[2023-04-04 18:30:17] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-04-04 18:30:17] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-04-04 18:30:17] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-04-04 18:30:17] Checking for update on startup
[2023-04-04 18:30:17] Checking for available updates...
[2023-04-04 18:30:17] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_publicbeta_ubuntu12
[2023-04-04 18:30:17] Manifest download: send request
[2023-04-04 18:30:18] Manifest download: waiting for download to finish
[2023-04-04 18:30:18] Manifest download: finished
[2023-04-04 18:30:18] Download skipped: /steam_client_publicbeta_ubuntu12 version 1680578442, installed version 1680578442, existing pending version 0
[2023-04-04 18:30:18] Nothing to do
[2023-04-04 18:30:18] Verifying installation...
[2023-04-04 18:30:18] Performing checksum verification of executable files
[2023-04-04 18:30:18] Verification complete
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
Loaded SDL version 3.0.0-1396-gb6ae281e9
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe9915590
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe9913dc0
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
steamwebhelper.sh[1987]: Runtime for steamwebhelper: defaulting to /home/steam/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[1987]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[1987]: CEF sandbox already disabled
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
CAppInfoCacheReadFromDiskThread took 145 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed
Assertion 'm' failed at pulse/thread-mainloop.c:248, function pa_threaded_mainloop_in_thread(). Aborting.
crash_20230404183020_24.dmp[2141]: Uploading dump (out-of-process)
```

**Comment by roboman2444** [comment]
I also have the same exact crash. 
Installed version 1680744168
Assertion 'm' failed at pulse/thread-mainloop.c:238, function pa_threaded_mainloop_in_thread(). Aborting.

Arch Linux. I don't use pulse. Just stock alsa.

**Comment by sylware** [comment]
Yeah, probably a bug in the pulseaudio->alsa fallback table of functions (or a bug in the client lib of pulseaudio itself which is distributed with the steam client). My crash is different though.

I use the dmix (from alsa too) software mixer, hidden behind the alsa API.

**Comment by mcodax** [comment]
Yeah, it looks like I've hit a similar error, which I also solved by moving away from the beta version. Here's the output when I start both steam and steam-native:

```
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
CAppInfoCacheReadFromDiskThread took 61 milliseconds to initialize
src/clientdll/user.cpp (8153) : Calling GetUserConfigFolder before we know our SteamID
src/clientdll/user.cpp (8153) : Calling GetUserConfigFolder before we know our SteamID
assert_20230406190217_25.dmp[9762]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230406190217_25.dmp
Failed to init SteamVR because it isn't installed
Assertion 'm' failed at ../pulseaudio/src/pulse/thread-mainloop.c:248, function pa_threaded_mainloop_in_thread(). Aborting.
crash_20230406190217_28.dmp[9769]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230406190217_28.dmp
/home/username/.local/share/Steam/steam.sh: line 798:  9662 Aborted                 (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20230406190217_25.dmp[9762]: Finished uploading minidump (out-of-process): success = yes
assert_20230406190217_25.dmp[9762]: response: CrashID=bp-660e545b-c245-4f69-a07f-d8e8a2230406
assert_20230406190217_25.dmp[9762]: file ''/tmp/dumps/assert_20230406190217_25.dmp'', upload yes: ''CrashID=bp-660e545b-c245-4f69-a07f-d8e8a2230406''
crash_20230406190217_28.dmp[9769]: Finished uploading minidump (out-of-process): success = yes
crash_20230406190217_28.dmp[9769]: response: CrashID=bp-81586284-22ed-4ba6-8c4c-03e072230406
crash_20230406190217_28.dmp[9769]: file ''/tmp/dumps/crash_20230406190217_28.dmp'', upload yes: ''CrashID=bp-81586284-22ed-4ba6-8c4c-03e072230406''
```

Also on Arch Linux, fully updated. I don't use PulseAudio, only ALSA/Pipewire.

In case someone happens to land on this post looking for a way to disable beta (because the typical way would require access to the GUI), I simply went to /home/username/.local/share/Steam/package/ (replace "username" with your actual username) and deleted the beta file. When I restarted Steam, it downloaded and then launched the standard version.

**Comment by sylware** [comment]
They did announce a fix for the pulseaudio fallback to alsa, I tried, still crashing the same way.

You guys?

**Comment by romka0075** [comment]
Now it works with ALSA. At least on Arch.

**Comment by dsalt** [comment]
Working again here too.

Probably working again for everybody now, but I'm not assuming so for now.

**Comment by sylware** [comment]
Still crashing here, it still does try to use a pulseaudio context which was failed to be inited:
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
Assertion 'c' failed at pulse/context.c:1060, function pa_context_set_state_callback(). Aborting.

**Comment by sylware** [comment]
With the shiny new beta client update: I still have the same errors, but the client does load fine.

(That's why the usage of the verb "seem" is so much important)

**Comment by seek-dev** [comment]
I was also being affected by this startup crash with the previous beta build on 3 separate ALSA-only systems.

The new UI redesign beta seems to have fixed the crash, but still displays the same error:
`PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed`

TBH, this check should be removed and ALSA/PA/PW mixer levels are **none of Steam's business**.

**Comment by kisak-valve** [comment]
Closing as fixed.
