### ISSUE TITLE
[New Steam UI] Displaying local screenshots broken

### ISSUE THREAD

**Issue by Nyamiou** [ValveSoftware/steam-for-linux#9437]
#### Your system information

* Steam client version (build number or date): 1682723851
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In the new screenshot UI, every single screenshot that wasn't previously shared in the cloud is now displayed as "There was a problem loading this screenshot". Also in the post game summary, the screenshot appear as a broken image logo.

#### Steps for reproducing this issue:

1. Have screenshots not shared into the cloud
2. Open the latest Steam Beta 
3. Open the screenshot manager and observe "There was a problem loading this screenshot"
4. Start a game
5. Take a screenshot of the game using F12
6. Close the game
7. Observe the broken image link in the post game summary

**Comment by Tourfaint** [comment]
Can confirm, displaying screenshots in the client is broken in the latest beta (ver 1683253302), On Kubuntu 20.04.

**Comment by cimspin** [comment]
Fixed for me in version 1683944175

**Comment by Tourfaint** [comment]
On version 1683926267 they don't seem fixed to me, i made some new screenshots in games to see if that changes anything, and it still is broken as described By Nyamiou. They Still show up in the screenshot manager as "There was a problem loading this screenshot".

**Comment by Juppstein** [comment]
can confirm, problem persists in version 1684200926

**Comment by Nyamiou** [comment]
Can't reproduce the issue anymore in 1684372665. Closing. Thank you for the fix.

**Comment by Tourfaint** [comment]
Version 1684372665, seems to be fixed for me as well. Screenshots show up fine. Thank you.

**Comment by Nyamiou** [comment]
Broken again in 1684535786.

**Comment by Nyamiou** [comment]
Still broken as of 1684885503.

**Comment by Nyamiou** [comment]
Can't reproduce anymore in 1685483787. Hopefully this is fixed for good now.

**Comment by Mallen106** [comment]
Version 1687386907, issue is still happening to me as of today

**Comment by rudikershaw** [comment]
I am still seeing this issue, but from a slightly different perspective. I manually removed the screenshots from the file system by using the "Show on disk" button. Now it lists all the removed screenshots and I cannot delete the entries. I have tried removing their corresponding thumbnails also, but they are still there. There is no way to delete the screenshots from the Screenshot Manager.

**Comment by Sou1l1** [comment]
For anyone still having this issue, I have a fix.

> I am still seeing this issue, but from a slightly different perspective. I manually removed the screenshots from the file system by using the "Show on disk" button. Now it lists all the removed screenshots and I cannot delete the entries. I have tried removing their corresponding thumbnails also, but they are still there. There is no way to delete the screenshots from the Screenshot Manager.

Navigate to the screenshot folder for your steamID, (e.g. C:\Steam\userdata\148365575\760), and then open the screenshots.vdf file, find the steamID for your game, delete everything pertaining to the corrupted screenshots from within the file
 `	
         "999999"
	{
		"0"
		{
			"type"		"1"
			"filename"		"251570/screenshots/20230613104146_1.jpg"
			"thumbnail"		"251570/screenshots/thumbnails/20230613100146_1.jpg"
			"vrfilename"		""
			"imported"		"1"
			"width"		"1920"
			"height"		"1080"
			"gameid"		"251570"
			"creation"		"1686664906"
			"caption"		""
			"Permissions"		"2"
			"hscreenshot"		"18446744073709551615"
		}
`
For example, the above will now look like this:
`	
         "999999"
	{
	}
`
This fixes the issue.

**Comment by DaVince** [comment]
I'd like to add that for me, on Steam Deck Gaming Mode, step 7 will bring me to the Media tab automatically but just not display the new screenshots at all.

On desktop mode, it looks like this (to illustrate):
![image](https://github.com/ValveSoftware/steam-for-linux/assets/105533/1ba4cfd2-b73e-4aea-8931-535cd82a8513)

Meanwhile, the screenshots themselves are perfectly fine when showing them on disk.

**Comment by DaVince** [comment]
Oh, this seems to be fixed for me on the latest update now.
