### ISSUE TITLE
Latest beta broke Remote Play

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/steam-for-linux#9556]
#### Your system information

* Steam client version: 1685664179 
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Latest beta broke Remote Play for me. I use the Steam Link linux app on my living room PC and also on my iPhone. Both devices show a frozen connecting screen but the audio from the startup animation plays in the background and when checking the host, Steam is running normally. Both apps are unresponsive and do not send input events.

1. Open Steam Link on iPhone or Linux App 
2. Connect to host.
3. Disconnect by walking over to computer and manually stop streaming to devices or force quit on clients.
![Screenshot from 2023-06-01 21-42-37](https://github.com/ValveSoftware/steam-for-linux/assets/6760790/c1607838-52ed-4813-9ea8-76b56d29b6f6)

**Comment by joeknock90** [comment]
Same on Arch Linux

**Comment by HugLifeTiZ** [comment]
I'm using the Flathub package on KDE Neon and the beta client, and I also cannot stream games to my Deck, which is on Preview. It does not show any messages, useful or otherwise, on either the computer hosting the game, or on the Deck trying to connect to it.

**Comment by lavadrop** [comment]
Now the latest beta no longer freezes, but now the desktop is captured at 14.5 fps with a display lag of 150,000 ms and a "slow encode" warning with 0% packet loss
![Screenshot from 2023-06-06 20-30-33](https://github.com/ValveSoftware/steam-for-linux/assets/6760790/9ae2ad63-6c7b-47df-aebc-f56201c32d45)

**Comment by Disk1of5** [comment]
I can Confirm in any all the Ubuntu distro's ive tried *AND* the steam deck i am getting the spinning loading screen on proton games.
so thats Linux (host) to Linux (Client). ...  *BUT* here's the odd thing... the android steamlink is working as a client and the screen renders correctly

**Comment by lavadrop** [comment]
Seems to have been resolved now.

**Comment by Disk1of5** [comment]
I am still seeing this as an issue,   the audio works, but its like Steam isn't getting the correct window focus

**Comment by Disk1of5** [comment]
BTW, here's a trick Any one playing a lutris game with a launcher such as Battlenet with Diablo4 a workaround i used is write a bash script that starts bnet in a gamescope instance.. then add the script as a non-steam game..(this works well in Ubuntu 23.04) then streaming works... it would seem that Steam gets confused when multiple windows are launched and its not sure what focus to grab...

**Comment by lavadrop** [comment]
It's been working fine again for me @kisak-valve but I'm on a rolling distribution. Some people are still reporting issues, tough but  not related to video encoding.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
