### ISSUE TITLE
Steam UI non functioning on NVIDIA 535.43.02-245 drivers

### ISSUE THREAD

**Issue by eNTi** [ValveSoftware/steam-for-linux#9577]
#### Your system information

* Steam client version (build number or date): Beta latest (2023-06-10)
* Distribution (e.g. Ubuntu): Artix
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is starting and I can play / start games with the tray icon but the UI won't open with the NVIDIA 535.43.02-245 drivers but it does with 530.41.03-241.

#### Steps for reproducing this issue:

1. Install 535.43.02-245 drivers
2. Start steam
3. Try to open steam UI -> nothing happens
4. Install 530.41.03-241 drivers
5. Start steam
6. Open UI -> Window opens as expected.

**Comment by kisak-valve** [comment]
Hello @eNTi, this issue should also be mentioned to your video driver vendor.

**Comment by valgusk** [comment]
FYI: Same crash happens also on stable channel, but it does not affect ui or browser functionality.
Stack trace seems to end in `libcef.so` evenwhen it should be disabled.

Also on stable disabling gpu rendering helps, yet beta continues crashing.

**Comment by dylanmtaylor** [comment]
Also affects Ubuntu on the newest Nvidia 535 driver version, 535.54.03.

**Comment by dylanmtaylor** [comment]
> FYI: Same crash happens also on stable channel, but it does not affect ui or browser functionality. Stack trace seems to end in `libcef.so` evenwhen it should be disabled.
> 
> Also on stable disabling gpu rendering helps, yet beta continues crashing.

It looks like this is related to some opcode issue (found in dmesg)

[  350.674322] NVRM kgrctxUnmapAssociatedCtxBuffers_IMPL: TSG 19 Channel 20 shares a pVAS with channel 19
[  351.540697] NVRM kgrctxUnmapAssociatedCtxBuffers_IMPL: TSG 22 Channel 23 shares a pVAS with channel 22
[  351.892733] traps: Composite Threa[8876] trap invalid opcode ip:7f4c9c9db794 sp:7f4c837995c0 error:0 in libcef.so[7f4c9a0ef000+7770000]
[  361.511007] traps: Composite Threa[9091] trap invalid opcode ip:7fa936fdb794 sp:7fa91e5865c0 error:0 in libcef.so[7fa9346ef000+7770000]
[  371.815689] traps: Composite Threa[9270] trap invalid opcode ip:7ffa671db794 sp:7ffa51aab5c0 error:0 in libcef.so[7ffa648ef000+7770000]
[  381.816901] traps: Composite Threa[9553] trap invalid opcode ip:7fb1f77db794 sp:7fb1ddf7a5c0 error:0 in libcef.so[7fb1f4eef000+7770000]
[  391.837948] traps: Composite Threa[9728] trap invalid opcode ip:7f8e3b5db794 sp:7f8e223fb5c0 error:0 in libcef.so[7f8e38cef000+7770000]
[  416.626461] NVRM kgrctxUnmapAssociatedCtxBuffers_IMPL: TSG 19 Channel 20 shares a pVAS with channel 19
[  417.378363] NVRM kgrctxUnmapAssociatedCtxBuffers_IMPL: TSG 22 Channel 23 shares a pVAS with channel 22
[  418.131041] traps: Composite Threa[10312] trap invalid opcode ip:7f53c2fdb794 sp:7f53aa6955c0 error:0 in libcef.so[7f53c06ef000+7770000]
[  427.967580] traps: Composite Threa[10536] trap invalid opcode ip:7f7e07bdb794 sp:7f7df249b5c0 error:0 in libcef.so[7f7e052ef000+7770000]

**Comment by jarrard** [comment]
Guess we'll need to wait yet another 3 months for a fix...

**Comment by ahuillet** [comment]
libcef.so is not a NVIDIA driver component. That problem seems like it may not be a NVIDIA driver bug.

**Comment by lay-by** [comment]
I have this exact same issue on Nvidia drivers 535.54.03 with Void Linux.

**Comment by eNTi** [comment]
> Hello @eNTi, this issue should also be mentioned to your video driver vendor.

https://forums.developer.nvidia.com/t/steam-for-linux-client-not-showing-ui-with-535-43-02-245/256178/9

**Comment by eNTi** [comment]
As written in the thread on the the nvidia developer forums, the latest release version of the steam client works for me on the `530.41.03-247` drivers and `6.3.9-273-tkg-bmq kernel`.

**Comment by jrgiacone** [comment]
> As written in the thread on the the nvidia developer forums, the latest release version of the steam client works for me on the `530.41.03-247` drivers and `6.3.9-273-tkg-bmq kernel`.

that is not the latest version, the latest version is 535.54

**Comment by eNTi** [comment]
> > As written in the thread on the the nvidia developer forums, the latest release version of the steam client works for me on the `530.41.03-247` drivers and `6.3.9-273-tkg-bmq kernel`.
> 
> that is not the latest version, the latest version is 535.54

I've corrected the version number in my post as I'm sure (due to the flickering issues) that I had the version you mentioned installed during testing (but most likely no longer during writing of the post).

**Comment by xaropizao** [comment]
> I have this exact same issue on Nvidia drivers 535.54.03 with Void Linux.

i also had the same problem

**Comment by Elelerin** [comment]
This is also giving me issues, running Arch, using 
steam -reset
or 
steam -vgui
does not fix the issue. Steam will run maybe one in every twenty times until I restart my system and have to try again.

**Comment by Drogobo** [comment]
Yeah, my steam is cooked. I can't get anything working here on Arch.

**Comment by Infinixius** [comment]
+1 on Arch Linux. `steam -vgui` works fine for the time being.

**Comment by Drogobo** [comment]
Neither `steam -vgui` nor `steam --reset` work on my computer. The first one does work on the client, but games will not start.

**Comment by JackLeEmmerdeur** [comment]
@Drogobo

With 535-54.03-1/2, `steam-native` with the new UI manages to start only occasionally, the other half of the time only the tray-menu icon appears. If it starts, it is accompanied with two KDE error-report sad-smileys in the tray `plasma-browser-integration-host closed unexpectedly`. But at least it starts.

If you want the new Steam-UI to work consistently this is my current go-to method, which might be methodically incorrect, because I don't really know what I'm doing. But it works pretty great. Proceed at your own risk:

`sudo downgrade nvidia-dkms nvidia-utils nvidia-settings lib32-nvidia-utils libxnvctrl`

Select 530.41.03 for every package. 

Run `sudo mkinitcpio -P` after that to be sure.

Put `IgnorePkg = nvidia-dkms nvidia-utils nvidia-settings lib32-nvidia-utils libxnvctrl lib32-amdvlk lib32-vulkan-icd-loader vulkan-headers vulkan-icd-loader vulkan-tools` into /etc/pacman.conf.

Put `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` into /etc/environment.

Restart.

**Comment by Drogobo** [comment]
> @Drogobo
> 
> With 535-54.03-1/2, `steam-native` with the new UI manages to start only occasionally, the other half of the time only the tray-menu icon appears. If it starts, it is accompanied with two KDE error-report sad-smileys in the tray `plasma-browser-integration-host closed unexpectedly`. But at least it starts.
> 
> If you want the new Steam-UI to work consistently this is my current go-to method, which might be methodically incorrect and cargo-culty, because I don't really know what I'm doing. But it works pretty great. Proceed at your own risk:
> 
> `sudo downgrade nvidia-dkms nvidia-utils nvidia-settings lib32-nvidia-utils libxnvctrl`
> 
> Select 530.41.03 for every package.
> 
> Run `sudo mkinitcpio -P` after that to be sure.
> 
> Put `IgnorePkg = nvidia-dkms nvidia-utils nvidia-settings lib32-nvidia-utils libxnvctrl lib32-amdvlk lib32-vulkan-icd-loader vulkan-headers vulkan-icd-loader vulkan-tools` into /etc/pacman.conf.
> 
> Put `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` into /etc/environment.
> 
> Restart.
I got all the way to starting Steam, but then steam completely crashed X. I don't know what's up with it.

**Comment by dylanmtaylor** [comment]
This is still broken on the June 6th build of the Steam beta client

**Comment by JackLeEmmerdeur** [comment]
@dylanmtaylor Hey. Not for me anymore on 535.54.03-1/2 with Kernel 6.4.1-arch2-1. I really don't know why but the steps in [this post](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1623489003) helped. The steam-native client starts consistently now. I tried a few games and they run as good as before.

**Comment by Infinixius** [comment]
Not sure what happened, but now Steam works completely flawlessly for me on kernel `6.4.1-arch2-1` with an RTX 3060.

**Comment by dylanmtaylor** [comment]
> @dylanmtaylor Hey. Not for me anymore on 535.54.03-1/2 with Kernel 6.4.1-arch2-1. I really don't know why but the steps in [this post](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1623489003) helped. The steam-native client starts consistently now. I tried a few games and they run as good as before.

Thank you so much! I did the rm -r ~/.cache/nvidia/GLCache/ and rm -r ~/.nv/ then started with steam -vgui and went to settings. I found the option to enable GPU acceleration in web interface and turned it off and then did the rm -r again. For whatever reason that fixed it for me and it's working now.

**Comment by eNTi** [comment]
Status: WORKSFORME

I'm currently running on
`nvidia-dkms-tkg 535.54.03-247`
and
`Linux eNTi 6.4.1-273-tkg-bmq`

Steam + hardware acceleration is working for both 6.4.1 and 6.3.11 for me now. No issues with flickering (I do have a dual monitor setup) or missing/empty windows any more. The only difference is that CSGO gives me a black screen with 6.4.1 but that's for another issue.

I won't close this ticket because it seems other still have issues.

**Comment by MarkDDR** [comment]
I can confirm the fix from https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1623489003 works for me. Interestingly, I tried enabling GPU acceleration again and it initially worked after hitting the "Restart Now" button in the prompt but then failed to work after a normal exit and reopen. Thankfully using `-vgui` to turn the setting back off let me open the steam client normally again.

Happy to have the Notes feature back, and Friends as well since for whatever reason Friends doesn't connect for me anymore on `-vgui`

**Comment by Drogobo** [comment]
I wonder if I am actually facing the same issue as this would describe. Regular Steam crashes xorg for me, and `steam -vgui` just causes any game I play to crash xorg too.

**Comment by jonny64bit** [comment]
I've run into the same issue and applied https://github.com/ValveSoftware/steam-for-linux/issues/9577#issuecomment-1624624763 however i didn't have the `~/.nv` folder. Steam looking to be working fine now.

Kernal: 6.4.2-arch1-1
Driver verison: 535.54.03-7

**Comment by PercyDLR** [comment]
I'm on arch and tried removing the folders mentioned by [dylan](https://github.com/ValveSoftware/steam-for-linux/issues/9577#issuecomment-1624624763), but when running the `steam -vgui` command I get this:

```
steam.sh[42612]: Running Steam on arch rolling 64-bit
steam.sh[42612]: STEAM_RUNTIME is enabled automatically
setup.sh[42686]: Steam runtime environment up-to-date!
steam.sh[42612]: Steam client's requirements are satisfied
[2023-07-13 16:19:43] Startup - updater built Jul 10 2023 23:58:24
[2023-07-13 16:19:43] Startup - Steam Client launched with: '/home/percy/.local/share/Steam/ubuntu12_32/steam' '-vgui'
07/13 16:19:43 Init: Installing breakpad exception handler for appid(steam)/version(1689034492)/tid(42750)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-07-13 16:19:43] Loading cached metrics from disk (/home/percy/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-13 16:19:43] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-07-13 16:19:43] Using the following download hosts for Public, Realm steamglobal
[2023-07-13 16:19:43] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-13 16:19:43] Checking for update on startup
[2023-07-13 16:19:43] Checking for available updates...
[2023-07-13 16:19:43] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2023-07-13 16:19:43] Manifest download: send request
[2023-07-13 16:19:43] Manifest download: waiting for download to finish
[2023-07-13 16:19:44] Manifest download: finished
[2023-07-13 16:19:44] Download skipped: /client/steam_client_ubuntu12 version 1689034492, installed version 1689034492, existing pending version 0
[2023-07-13 16:19:44] Nothing to do
[2023-07-13 16:19:44] Verifying installation...
[2023-07-13 16:19:44] Performing checksum verification of executable files
[2023-07-13 16:19:44] Verification complete
Loaded SDL version 3.0.0-1782-g214d5daa3
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf0487db0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf0486500
/home/percy/.themes/Layan-Dark/gtk-2.0/main.rc:790: error: unexpected identifier 'direction', expected character '}'
/home/percy/.themes/Layan-Dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
GetWin32Stats: display was not open yet, good
ComputeStartupMode: forcing vgui via cli
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[42761]: Runtime for steamwebhelper: defaulting to /home/percy/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[42761]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Failed to init SteamVR because it isn't installed
Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.
crash_20230713161945_28.dmp[42951]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230713161945_28.dmp
/home/percy/.local/share/Steam/steam.sh: línea 798: 42750 Abortado                (`core' generado) "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20230713161945_28.dmp[42951]: Finished uploading minidump (out-of-process): success = yes                                                                       crash_20230713161945_28.dmp[42951]: response: CrashID=bp-0a5cf285-e370-4a34-bcb1-1e4732230713
crash_20230713161945_28.dmp[42951]: file ''/tmp/dumps/crash_20230713161945_28.dmp'', upload yes: ''CrashID=bp-0a5cf285-e370-4a34-bcb1-1e4732230713''
```

Maybe this is an unrelated problem, because I haven't used steam in a while and now can't use it.

**Comment by kisak-valve** [comment]
Hello @PercyDLR, `Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.` is #9805.

**Comment by PercyDLR** [comment]
Oh thanks, that was exactly my problem. Sorry nontheless.

**Comment by kisak-valve** [comment]
Hello @eNTi, can you recheck if you're seeing this issue with the NVIDIA 535.86.05 driver release or newer?

**Comment by eNTi** [comment]
> Status: WORKSFORME
> 
> I'm currently running on `nvidia-dkms-tkg 535.54.03-247` and `Linux eNTi 6.4.1-273-tkg-bmq`
> 
> Steam + hardware acceleration is working for both 6.4.1 and 6.3.11 for me now. No issues with flickering (I do have a dual monitor setup) or missing/empty windows any more. The only difference is that CSGO gives me a black screen with 6.4.1 but that's for another issue.
> 
> I won't close this ticket because it seems other still have issues.

As stated above... this works for me. I don't have any issues currently on the `535.98-250` drivers on the `6.4.10-273-tkg-bmq` kernel.

**Comment by kisak-valve** [comment]
Thanks, it looks like this was a video driver bug with how it handled its own on-disk shader cache in 535.43.XX and 535.54.03 that caused this issue. It was apparently quietly resolved in 535.86.05.

If anyone else is seeing a similar issue with a newer video driver, that should be pondered separately.

**Comment by gazhay** [comment]
Steam hasn't worked under 22.04 for me at all.

Tried Nvidia-545, nvidia-530 and nvidia-495.

Previously had been working fine. 
Side note : if its a driver issue, I am not experiencing any other symptoms with any other applications on my system, just steam

**Comment by Oplkill** [comment]
The same thing in Mint 21.3.  nvidia-545,535...
Tryed beta still the same effect.
Main steam window just dont drawing. i can press buttons there, but it completely invisible.
But friends&chat windows works well.
And for some reason if exit steam via "exit" menu it can crash the whole user session GUI. (cinnamon)
