### ISSUE TITLE
New Steam overlay causes games to crash upon opening (Potential Nvidia + Wayland Problem?)

### ISSUE THREAD

**Issue by returnofblank** [ValveSoftware/steam-for-linux#9586]
#### Your system information

* Steam client version: 1686779606
* Distribution: Fedora Silverblue 38
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Graphics Card: GTX 1080
* CPU: i7 8700k
* Graphics Drivers: 530.41.03
* Display Server: Wayland

#### Please describe your issue in as much detail as possible:
Since the new Steam overlay update, attempting to open it causes the game to hang for a few seconds before crashing.

#### Steps for reproducing this issue:

1. Update to current Steam version at this time
2. Open a game of your choosing
3. Press Shift + Tab to open the Steam overlay
4. Game will hang for a few moments before crashing

I'm going to attempt this with Xorg and see if the issue persists, I'll edit this post with my findings later.

**Comment by ryonistic** [comment]
Yeah, same issue here. I was just playing CSGO and did a quick Shift+Tab, but the game closed instead of opening the steam overlay. 
OS: Debian GNU/Linux 12 (bookworm)
Kernel: 6.1.0-9-amd64

**Comment by returnofblank** [comment]
It's odd, sometimes I was able to successfully open the steam overlay without it crashing, but most times I couldn't. I can't seem to reliably replicate that. 

Seems like a dice roll to see if checking some dude's profile will work or will get me a competitive cool down lol.

**Comment by kisak-valve** [comment]
Possible duplicate of #9534.

**Comment by matharman** [comment]
I can reproduce with games other than CS-GO, but only when using X. If I use Wayland, the overlay works as normal.

<details>
<summary>System Information</summary>
````
Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: ROG STRIX B550-I GAMING
Form Factor: Desktop
No Touch Input Detected

Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4950 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

Operating System Version:
Fedora Linux 38 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.3.7-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12014000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230509.49499

Video Card:
Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.5, DRM 3.52, 6.3.7-200.fc38.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.2
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4480 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 12288 MB

Sound card:
Audio device: USB Mixer

Memory:
RAM: 31987 Mb

VR Hardware:
VR Headset: None detected

Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 886792 MB
Largest Free Hard Disk Block: 124493 MB

Storage:
Number of SSDs: 3
SSD sizes: 1000G,1000G,1000G
Number of HDDs: 0
Number of removable drives: 0
````
</details>

**Comment by Andre8900** [comment]
Same issue when I play CS:GO on Mint 21 Cinnamon (using X) if I press Shift+Tab.

**Comment by deergoduc** [comment]
Same issue with TF2 on Arch Linux 6.3.7-arch1-1 (X), works fine on Factorio (Steam Linux Runtime) and Shotgun King: The Final Checkmate (Proton Experimental)

**Comment by returnofblank** [comment]
I can confirm that the steam overlay does work after a while in game, so #9534 is correct that it has something to do with the overlay not initializing that causes the crash.

**Comment by Hoofuyu** [comment]
Same issue with CS:GO, when pressing shift + tab or opening market through the inventory gui, it will immediately commit die from opening overlay.

System:
OS: Gentoo GNU/Linux
Kernel: 6.1.31-gentoo
WM: herbstluftwm
Compositor: None (ive tried picom with no success)
CPU: Core i9-9900k (9th gen)
GPU: RTX 2080

Also tried disabling all steam client hardware acceleration with no success.

**Comment by RedactedSoftware** [comment]
Can confirm.
Fedora 38
X Window System
RX 6600

**Comment by ElektroSokas77** [comment]
Same issue, after the new update the game just crashes when opening any steam overlay. Suggesting to disable the steam overlay in game settings for now. Please fix this Valve!

**Comment by LukeDearden** [comment]
I reported this during the beta here https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-1528944491

To make sure it wasn't wonky config I reinstalled Fedora and everything yesterday. Same thing happening.

**Comment by ShizuVoice** [comment]
I can confirm this, not only opening the overlay during midgame but it crashes the game before it even started. The OS is also a fresh install.

System:
OS: Arch Linux
Kernel: 6.3.7-arch1-1 
DE: Plasma 5.27.5
WM: KWin
CPU: Core i5-12400
GPU: GTX 1060

**Comment by Toni500github** [comment]
can confirm, after this new ui update, everytime i use the game overlay csgo just crashes. on the terminal log it says 'Bus error' 
here my [terminal log](https://pastebin.com/hJU1bG59)

OS: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
DE: Cinnamon 5.2.7
WM: Mutter (Muffin)
CPU: AMD Ryzen 5 5500
GPU: NVIDIA GeForce GTX 1650

**Comment by kubaa2002** [comment]
Same issue in Monster hunter World game crashes after i hit shift+tab
OS: Manjaro Linux
DE: KDE Plasma 5.27.5
Kernel: 6.2.16
CPU: AMD Ryzen 5 1400
GPU: NVIDIA gtx 1060 6gb

**Comment by Duck375** [comment]
Same. For Risk of Rain 2 crash is instant upon Shift+Tab
OS: Arch Linux
DE: KDE Plasma 5.27.5
WM: KWin
Kernel: 6.3.6
CPU: I3-13100F
GPU: Nvidia GeForce 1050 Ti
RAM: 32 Gb 2133

**Comment by Nicknakin** [comment]
I'm experiencing this issue in Hunt Showdown
Steam Runtime System Info: https://gist.github.com/Nicknakin/922a6b0010e1ab50e3a200090272ba9a
System Info: https://gist.github.com/Nicknakin/ce0b269882b7fe3c20030ecfa4d7fd04
Game Log: https://gist.github.com/Nicknakin/52542b3185993e368dec1f0a974c522b

**Comment by colleen05** [comment]
I'm experiencing the same issue with Ubuntu 22.10, using Wayland on an AMD GPU.

**Comment by ask-compu** [comment]
happens for me in tf2, had to disable the overlay to get the game to not crash when pressing shift+tab or pressing f5 or f12 to take screenshots

**Comment by TurnedUpSideDown** [comment]
I have the same issue with CS:GO crashing when I SHIFT+TAB

OS: Arch Linux x86_64 
Kernel: 6.3.8-arch1-1
Display Server: X.org
DE: Plasma 5.27.5
WM: KWin
CPU: Intel i7-9700K (8) @ 4.900GHz
PU: NVIDIA GeForce RTX 2080 SUPER

**Comment by kisak-valve** [comment]
New Steam overlay + dxvk causes startup freeze in some games.

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/9685.
@Blisto91 posted on 2023-06-20T23:50:15:

#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu):  Reborn OS (Arch based)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809119/steam-logs.tar.gz)
* GPU: AMD 7900xtx and a Zen 4 iGPU

#### Please describe your issue in as much detail as possible:
Ever since the new Steam UI update i've had issues with a few games freezing during startup the Steam overlay is enabled together with dxvk. Using wined3d with Steam overlay does does not cause the issue and turning off overlay together with using dxvk does not cause it either. At least i haven't been able to reproduce it then.
Back when the new UI was in beta going back to the old one did not reproduce the issue either.

So far i have observed it with 3 games. [Watch Dogs](https://store.steampowered.com/app/243470/Watch_Dogs/), [Tom Clancy's Rainbow Six Lockdown](https://store.steampowered.com/app/15000/Tom_Clancys_Rainbow_Six_Lockdown/) and [Melty Blood Actress Again Current Code](https://store.steampowered.com/app/411370/Melty_Blood_Actress_Again_Current_Code/).
It seems to be racy as with Rainbow Six i have managed to get to the main menu like 1 in 10 times and with Melty Blood i was not able to reproduce the issue with amdvlk until i also had proton logging turned on. With radv it happened all the time.

Proton log and Steam terminal output from Watch Dogs
[watch-dogs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809256/watch-dogs.tar.gz)

Same from Melty Blood
[melty-blood.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809263/melty-blood.tar.gz)

#### Steps for reproducing this issue:
Watch Dogs is the most consistent one for me, so describing that one.

1. Start the game with Proton with both dxvk and steam overlay enabled ( specific proton version is not important )
2. Game freezes before i even get to the main menu

**Comment by LukeDearden** [comment]
> 

Good you solved your issue but the problem can't just be about video drivers. 

There's people here reporting the Overlay crash with nVidia GPUs too and on a variety of games.

**Comment by ShujianDou** [comment]
A temporary fix seems to be launching steam with the -vgui option, which returns the old UI.

**Comment by ask-compu** [comment]
an alternative temporary fix is to just disable the steam overlay for any game that is crashing

**Comment by amverweij** [comment]
> A temporary fix seems to be launching steam with the -vgui option, which returns the old UI.

When starting steam with -vgui, it is not possible to connect with friends (it says my local net is offline). This is rather limiting for games that you play online with friends (e.g. Soulcalibur VI).

**Comment by Ameobea** [comment]
Having the same issue in Hunt: Showdown.  Was able to work around it by switching from Proton experimental to Proton 7.

Then, a few days later, it started happening again with Proton 7.  I switched back to Experimental, and ... it works again.

**Comment by grohan47** [comment]
Same issue in CS:GO. On top of this, trying to click on any item in the News feed also insta-crashes the game.

**Comment by tonikelope** [comment]
I have the same issue with CS:GO crashing when I SHIFT+TAB

OS: Arch Linux x86_64
Kernel: 6.3.9-arch1-1
Display Server: X.org
DE: Plasma 5.27.6
WM: KWin
CPU: Ryzen 5 2600
GPU: AMD RX6600
Mesa 23.1.3
Vulkan-radeon 23.1.3

**Comment by Mrr7782** [comment]
Same here in Half-Life 2: Deathmatch
Pressed `SHIFT`+`TAB`, the game froze for a few seconds and then crashed.

OS: Arch Linux (64 bit, Linux kernel 6.3.9-arch1-1)
Display server: X.Org 21.1.8-1
DE: KDE Plasma 5.27.6-1
WM: KWin 5.27.6-1
CPU: AMD Ryzen 5 1600X
GPU: AMD Radeon RX 6650 XT

**Comment by TheBigK02** [comment]
hmm... no update on this? would be great to have a fix for this

**Comment by vadiks2003** [comment]
oh my, this issue is 2 week old. well, i'll tell one thing: my gpu is mx350 and apparently its used for 3D but for graphics overall is my integrated graphics that's used. i think steam just should by default run on integrated graphics. it's not like they put 3D with epic shaders on their store pa... actually they might do it sometimes, what the hell?

**Comment by ndv99** [comment]
Dropping in to confirm I am experiencing the same issue. System info dump from steam:

```

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: MPG B550I GAMING EDGE WIFI (MS-7C92)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 3900X 12-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4672 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu 23.04 (64 bit)
Kernel Name: Linux
Kernel Version: 6.2.0-23-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101007
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 3070/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 515.105.01
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x10de
DeviceID: 0x2484
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3440 x 2520
Primary Display Size: 0.04" x 0.04" (0.04" diag), 0.1cm x 0.1cm (0.1cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Nvidia GPU 9e HDMI/DP
Memory:
RAM: 31997 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 343415 MB
Largest Free Hard Disk Block: 41169 MB
Storage:
Number of SSDs: 3
SSD sizes: 1000G,1000G,8053M
Number of HDDs: 0
Number of removable drives: 0
```

**Comment by syss** [comment]
as i found in another bug report; adding `-vulkan` to the launch options of csgo was mitigating the crash

**Comment by RedactedSoftware** [comment]
> as i found in another bug report; adding `-vulkan` to the launch options of csgo was mitigating the crash

Using "-vulkan" in cs:go isn't viable because it causes bad stutter / frametime issues.

**Comment by ayden-russo** [comment]
RX 6700XT here having the same Overlay crashing issues

**Comment by JohnTitor2036v2** [comment]
I tried to open overlay in Risk of Rain 2 in big screen mode. And It seems to work fine all of a sudden.

**Comment by besselfunct** [comment]
I am having this issue on a computer that has nearly identical specs to my home computer (where the overlay is working).

- Steam client version: 1688171965
- Distribution: Pop!_OS 22.04
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
- Graphics Card: RX 7900XT
- CPU: i5 13400
- Graphics Drivers: 22.0.0-1ubuntu0.1pop1~16771988220~22.04~2e82f80 (output of `dpkg -l xserver-xorg-video-amdgpu`)
- Display Server: X11

I've tried a myriad of things from this thread, but I can't get the steam overlay to open consistently without crashing Hunt: Showdown, on both X11 and Wayland. I was also experiencing the issue where I had to launch steam from the terminal, but that seems to have been mitigated by setting `PrefersNonDefaultGPU=false` and `X-KDE-RunOnDiscreteGPU=true` in `/usr/share/applications/steam.desktop` and restarting.

**Comment by NLBen** [comment]
Similar problem here. It's very random - with the same game it can vary per Steam session or even in-session at a later time. The update to Steam seems to still be very glitchy and buggy, and from what I understand it's a general issue, not limited only to Linux. The redesign needed way more testing before it went live.

My specs:

Steam version: 1687386907 (21 June)  
OS: Linux Mint 22.1
Beta: No  
Checked for OS updates: Yes (package versions don't seem to matter neither do kernel updates)  
GPU&CPU: ASRock Radeon RX 6600 XT Challenger D 8GB OC & Ryzen 5 3600  
RAM: HyperX FURY Black HX432C16FB4/16

**Comment by wiryfuture** [comment]
Happens for me using NixOS 23.05.
I have this occur in Factorio, Civilization V, left4dead2. CSGO does not seem to have this issue for me.
If the overlay does open, it is always very very slow. This is when smooth scrolling, gpu accelerated webviews and hardware video decoding is enabled under interface settings.

The crashing appears to stop if you disable hardware video decoding under interface settings, and then the overlay is usable, but is quite a bit slow.
This is a bit odd as I have an amd graphics card using radv, so I think it should work fine.
I have found the overlay fastest and most reliable by disabling all three of those interface options (sorry to whoever worked on implementing that!)

**Comment by Extravi** [comment]
same issue

**Comment by Extravi** [comment]
same issue opengl csgo steam flatpak

**Comment by Extravi** [comment]
![Screenshot from 2023-07-05 18 02 50](https://github.com/ValveSoftware/steam-for-linux/assets/98912029/aece53eb-9a3c-44d5-828d-4b5d0d82e0c2)

**Comment by Extravi** [comment]
valve pls fix

**Comment by toastnk** [comment]
Im on windows 10, it happens for me too, I open Hunter Call of the Wild, load into a map. then click shift+tab and it crashes my game, it also crashes when I try to use the in game camera, the in game camera is a steam screenshot. So steam overlay is crashing my game, and I haven't found a fix. Is there a way to fix this? Or will I just have to wait until steam fixes it?

**Comment by Extravi** [comment]
you probably have to wait for valve to fix it

**Comment by Extravi** [comment]
I didn't have theses issue's on the older steam client

**Comment by ask-compu** [comment]
> Im on windows 10, it happens for me too, I open Hunter Call of the Wild, load into a map. then click shift+tab and it crashes my game, it also crashes when I try to use the in game camera, the in game camera is a steam screenshot. So steam overlay is crashing my game, and I haven't found a fix. Is there a way to fix this? Or will I just have to wait until steam fixes it?

the simple workaround is to disable the steam overlay for that game, go to the game's properties in steam and there will be a checkbox for the steam overlay

**Comment by Extravi** [comment]
using proton on steam with gta5 steam overlay works but a native Linux game like csgo steam overlays crashes the game

**Comment by ask-compu** [comment]
> using proton on steam with gta5 steam overlay works but a native Linux game like csgo steam overlays crashes the game

it's not all native linux games, american truck simulator handles the overlay just fine

**Comment by Extravi** [comment]
> fine

interesting what does it use to render csgo uses opengl

**Comment by HoustonAsh** [comment]
`use -vulkan in startup options`
From [this](https://steamcommunity.com/app/730/discussions/0/3819662889089756284/) steam discussion

**Comment by JokerGermany** [comment]
> `use -vulkan in startup options` From [this](https://steamcommunity.com/app/730/discussions/0/3819662889089756284/) steam discussion

Wouldn't use it with danger zone
https://github.com/ValveSoftware/csgo-osx-linux/issues/2897

**Comment by matharman** [comment]
Sadly this is still happening on today's update.

```
Steam Version:  1689013916
Steam Client Build Date:  Sun, Jul 9 1:07 PM UTC -05:00
Steam Web Build Date:  Mon, Jul 10 1:48 PM UTC -05:00
Steam API Version:  SteamClient020
```

<details>
<summary>System Information</summary>

Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: ROG STRIX B550-I GAMING
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4950 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Freedesktop.org SDK 22.08 (Flatpak runtime) (64 bit)
Kernel Name: Linux
Kernel Version: 6.3.11-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12014000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.11-200.fc38.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4480 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 31987 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 886792 MB
Largest Free Hard Disk Block: 394807 MB
Storage:
Number of SSDs: 3
SSD sizes: 1000G,1000G,1000G
Number of HDDs: 0
Number of removable drives: 0
</details>

**Comment by vadiks2003** [comment]
one day we will have everything running on vulkan - xbox 999, windows, linux, performance is gonna probably be great - but the probem would be that learning vulkan is a lot of things to do. i hope there's gonna be simple vulkanfw like glfw with no bugs in it 

and still, fromsoft PC porters would still use directx ._. (google up elden ring's graphic library for windows they use)

**Comment by Extravi** [comment]
> `use -vulkan in startup options` From [this](https://steamcommunity.com/app/730/discussions/0/3819662889089756284/) steam discussion

does not work with stretched res

**Comment by ask-compu** [comment]
so it happens for me on TF2, but when i enable mangohud on TF2 and leave the steam overlay enabled it doesn't crash anymore, somehow mangohud prevents the crash

**Comment by zelect0r** [comment]
Still the same issue, the game crashed when i open the overlay(Alt+Tab).

Linux Mint 21.2

System:
  Host: homebase Kernel: 5.15.0-76-generic x86_64 bits: 64
    Desktop: Cinnamon 5.8.4 Distro: Linux Mint 21.2 Victoria
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X470-F GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 6063
    date: 03/13/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP cache:
    L2: 4 MiB
  Speed (MHz): avg: 2529 min/max: 2200/3600 cores: 1: 2010 2: 3009 3: 2196
    4: 1996 5: 4295 6: 2149 7: 2144 8: 2149 9: 2125 10: 3593 11: 2132 12: 2117
    13: 4208 14: 2152 15: 2117 16: 2072
Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2070 Rev. A] driver: nvidia
    v: 525.125.06
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 1920x1080~144Hz 2: 1920x1080~144Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.125.06

**Comment by ask-compu** [comment]
> so it happens for me on TF2, but when i enable mangohud on TF2 and leave the steam overlay enabled it doesn't crash anymore, somehow mangohud prevents the crash

nevermind it still crashes sometimes, just a bit less often

**Comment by Inq-B** [comment]
+1
- Steam client version: 1689034492 (Jul 11)
- Distribution: Debian 12 (Bookworm)
- Graphics Card: RTX 2070 Super
- CPU: Ryzen 5 5600X
- Graphics Drivers: Nvidia PPA 535.54.03
- Display Server: X11

**Comment by zelect0r** [comment]
Has a Fresh installation of Linux Mint 21.2 and still the issue.
OOpen Overlay in csgo and crash.

**Comment by matharman** [comment]
The only workaround I have found for this issue is to use steam in big picture mode. In BPM, the overlay doesn't crash any of my games.

**Comment by maspolive** [comment]
Cant use The Buy option in CS:GO it crashes every time i start the overlay and without its not possible :&

**Comment by matharman** [comment]
Issue is resolved on Hunt: Showdown on today's client update (flatpak version).

````
Steam Version:  1690583737
Steam Client Build Date:  Fri, Jul 28 2:44 PM UTC -05:00
Steam Web Build Date:  Fri, Jul 28 6:21 PM UTC -05:00
Steam API Version:  SteamClient020
````

<details>
<summary>
System Information
</summary>

````
Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: ROG STRIX B550-I GAMING
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4950 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Freedesktop.org SDK 22.08 (Flatpak runtime) (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.6-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12014000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230606.51628
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.4.6-200.fc38.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4480 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 31987 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 886792 MB
Largest Free Hard Disk Block: 376181 MB
Storage:
Number of SSDs: 3
SSD sizes: 1000G,1000G,1000G
Number of HDDs: 0
Number of removable drives: 0
````

</details>

**Comment by RedactedSoftware** [comment]
In the latest update you can no longer start steam with -vgui to circumvent this issue. In the latest version games still crash even if "enable the steam overlay while ingame" is disabled. When starting steam from the terminal, "steamoverlayrenderer.so" is still attached to the game. 

Browsing to **~/.local/share/Steam/ubuntu12_32** and deleting **gameoverlayrenderer.so** and **gameoverlayui.so** makes it such that the steam overlay is impossible to open and pressing the key combo or getting a steam message no longer crashes games. But every time steam is started it automatically puts these files back.

Things like this are why closed source software is bad and opensteam is a great idea :).

tl;dr The new steam ui was pushed broken. Shortly after the workaround to not use it was removed.

**Comment by AsciiWolf** [comment]
Still the same issue in CS:GO on my Fedora 38 system with AMD GPU. Opening Steam Overlay causes the game to crash.

**Comment by turtlshell** [comment]
For some reason, (even though it was working fine yesterday) removing `-novid` from my launch options completely prevents the shift+tab crash for me.

I just started having issues with this today after the latest Manjaro testing branch update, however after downgrading all the associated packages it's still persisting, which is thoroughly confusing.

I'd also like to note that pressing shift+tab in game after completely disabling the steam overlay (per-game or steam-wide, doesn't matter) still seems to cause a crash (when `-novid` is enabled)

```
OS: Manjaro Linux x86_64 (testing branch)
Kernel: 6.4.8-lqx1-1-lqx
DE: Plasma 5.27.7
CPU: 12th Gen Intel i9-12900K
GPU: NVIDIA GeForce RTX 2080 Ti
Steam Version: 1690583737
```

**Comment by AsciiWolf** [comment]
CS:GO sadly still crashes for me, even with `-novid`.

**Comment by Caddde** [comment]
I thought that by opening Steam with `flatpak run com.valvesoftware.Steam --verbose &` it would give more info on what crashes, but i can't see nothing wrong.
All the games, even if the overlay works, give back the same log.
I hope someone find a fix because right now i have the overlay disabled on the majority of my games.
And i don't know if is only me, but now, starting CSGO with the `-vulkan` argument crashes when opening the overlay, maybe something as changed.
```
OS: Debian 12
KERNEL: 6.4.0-1-amd64
CPU: Intel Core i5-7500 @ 3.40GHz
GPU: NVIDIA GeForce GTX 1050 Ti
GPU DRIVER: NVIDIA 525.125.06
RAM: 8 GB
Versione di Steam:  1690583737
Data della build del client di Steam:  ven 28 lug 20:44 UTC -08:00
Data della build Web di Steam:  sab 29 lug 0:21 UTC -08:00
Versione API di Steam:  SteamClient020
```

**Comment by RedactedSoftware** [comment]
The crash happens in **gameoverlayrenderer.so**, When looking at the x32 and x64 files in HexRays I only saw one thing which seems odd but I'm unsure if it could be the problem or not and steam is closed source so I can't see the real c++ either :shrug:

![Screenshot from 2023-08-19 14-14-20](https://github.com/ValveSoftware/steam-for-linux/assets/87786960/a2239da8-219e-47d1-9f7c-1ffc0a9cc5b7)

**Comment by Extravi** [comment]
I don't think valve is even reading this

**Comment by gsgleason** [comment]
Same issue.

**Comment by embedvr** [comment]
Been able to replicate on Fedora 38 on Ready or Not. Pressing Shift + Tab causes an immediate crash that also hangs the rest of my OS (at least the GUI part?)
```
Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: TUF GAMING X570-PLUS (WI-FI)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 3600X 6-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4408 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Fedora Linux 38 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.11-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12014000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230606.51628
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.98
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x10de
DeviceID: 0x1f06
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3150 x 1440
Primary Display Size: 31.50" x 12.99" (34.06" diag), 80.0cm x 33.0cm (86.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Nvidia GPU 93 HDMI/DP
Memory:
RAM: 31986 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 952244 MB
Largest Free Hard Disk Block: 848255 MB
Storage:
Number of SSDs: 4
SSD sizes: 8001G,1000G,1000G,1000G
Number of HDDs: 0
Number of removable drives: 0
```

**Comment by TheBigK02** [comment]
Its fixed for me in Steam Version:  1692911603

Debian 12 in CSGO

**Comment by LukeDearden** [comment]
> Its fixed for me in Steam Version: 1692911603
> 
> Debian 12 in CSGO

Unfortunately Steam Version: 1692911603.  Does not fix the overlay crash for Hunt Showdown

**Comment by IC3P3** [comment]
Can confirm it for CSGO with the Steam version 1692911603 in Fedora/Nobara 38

**Comment by zelect0r** [comment]
Linux Mint upgrade to Beta 1692911603, doesnt fix csgo overlay :(

**Comment by iSaluki** [comment]
This occurs on my system too. 

Using Fedora Workstation 38 and Steam's current stable build.

**Comment by IC3P3** [comment]
> Steam's current stable build.

The one that seems to fix it for some user is version 1692911603 which is the Steam Beta client

**Comment by iSaluki** [comment]
That's interesting, I'll give it a go shortly.

-------- Original Message --------

**Comment by iSaluki** [comment]
After switching to the client beta, the overlay opens correctly and doesn't crash. However, it remains extremely buggy and is unusable. Still, better than it was on stable.

**Comment by clairetard** [comment]
Confirming it works properly on Steam version `1692911603` (Beta Update) running Arch.

For anyone wondering how to opt-in:
Steam -> Settings -> Interface -> Client Beta Participation

**Comment by LukeDearden** [comment]
> Confirming it works properly on Steam version `1692911603` (Beta Update) running Arch.
> 
> For anyone wondering how to opt-in: Steam -> Settings -> Interface -> Client Beta Participation

Which game are you talking about? 

for example `1692911603` does not fix the Hunt Showdown Overlay crash

**Comment by Blisto91** [comment]
Adding a some more logging and a couple of notes to some of the games i am having issues with from my original comment. These ones freeze instead of outright crashing.
Proton Experimental, stable Steam client, amd 7950x + 7900xtx, Arch.

[Rainbow Six Lockdown](https://store.steampowered.com/app/15000/Tom_Clancys_Rainbow_Six_Lockdown/): When i skip the intro videos to get to the main while the Steam overlay notification (when you start a game) is up the game will freeze when it's supposed to reach the menu. Have to kill it.
Logs:
[steam-15000.log](https://github.com/ValveSoftware/steam-for-linux/files/12621283/steam-15000.log)
[lockdown-steam-terminal.txt](https://github.com/ValveSoftware/steam-for-linux/files/12621285/lockdown-steam-terminal.txt)

[Assassin's Creed Origins](https://store.steampowered.com/app/582160/Assassins_Creed_Origins/): Game renderer will freeze before reaching main menu.
Logs:
[steam-582160.log](https://github.com/ValveSoftware/steam-for-linux/files/12621340/steam-582160.log)
[origins-steam-terminal.txt](https://github.com/ValveSoftware/steam-for-linux/files/12621342/origins-steam-terminal.txt)

[Watch_Dogs](https://store.steampowered.com/app/243470/Watch_Dogs/): Game will freeze almost as soon as the game window appears.
Logs:
[steam-243470.log](https://github.com/ValveSoftware/steam-for-linux/files/12621658/steam-243470.log)
[dogs-steam-terminal.txt](https://github.com/ValveSoftware/steam-for-linux/files/12621659/dogs-steam-terminal.txt)


Note that the issue can be a bit racy so while i experience it pretty much all the time with the games above i might be lucky and get a game start where i get through. Also since it is racy it might not reproduce for others with the exact same games, but a quick thing to try would be turning logging either off or on to affect timing a bit.

**Comment by Ibaudia** [comment]
Can replicate on any game with Steam version 1694466342. Running Debian 12, Kernel Linux 6.1.0-12-amd64.
Stable version of Steam crashes, beta version occastionally crashes, but does not render overlay even if it doesn't crash (it is completely transparent). Tested with TF2 running natively and Unrailed with Proton.

**Comment by NoXPhasma** [comment]
[Soulcalibur VI](https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-1721369599) seems to be affected as well.

**Comment by Pat-JK** [comment]
Been having this issue on TF2. Things were working fine but for some reason it started happening over the past couple days.

I found [this post](https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3826414483637456689/#c3817418065215697877) and sure enough, even though TF2 doesn't actually use vulkan, adding -vulkan to the launch options has the overlay now working properly and not crashing.

**Comment by FanderWasTaken** [comment]
I think this has something to do with Steam Linux Runtime. Error from the terminal:
`ERROR: ld.so: object '/home/react/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

**Comment by NoXPhasma** [comment]
@FanderWasTaken That is no real error, the Steam Client injects the 32bit and 64bit version of the overlay library. One of each will always fail, depending on what architecture the game is.

**Comment by FanderWasTaken** [comment]
> @FanderWasTaken That is no real error, the Steam Client injects the 32bit and 64bit version of the overlay library. One of each will always fail, depending on what architecture the game is.

By running `gamescope -e -f -- steam -steamos` I was able to bypass the overlay misbehaving. I guess when run in gamescope steam doesn't care what I'm running and will display the overlay properly

**Comment by mystyq** [comment]
Enabling `Enable GPU accelerated rendering in web views (requires restart)` in `Steam Settings` -> `Interface` seems to have fixed the issue for me.

**Comment by jon-bit** [comment]
Does anybody have a work around yet with out disabling the overlay yet? I need to know because I need the overly for something tomorrow. BTW I switched to the beta. I have not found a fix but Any work around it appreciated while we wait.

**Comment by matharman** [comment]
> Does anybody have a work around yet with out disabling the overlay yet?

I can't confirm if this will work with GoW specifically, but try using Steam in Big Picture mode. If I use Big Picture with Hunt: Showdown it does not crash when I open the overlay.

**Comment by jon-bit** [comment]
Sorry but is crashed. Anything else?

**Comment by tearoww** [comment]
Still happening for me with Hunt: Showdown, but not with Sea of Thieves. Haven't tested other games.

When trying to open the overlay, the following window appears and both it and the game freeze:

![screenshot-20231020-210346](https://github.com/ValveSoftware/steam-for-linux/assets/74559498/a6bef220-b415-4d62-94c8-3ac5e950698d)

<details>
<summary>System Information:</summary>
<br>

```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.1.55-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Manufacturer: ASUS
```

</details>

**Comment by Liemaeu** [comment]
Opening the Overlay (Shift + Tab) or taking a screenshot (F12) sometimes crashes Total War: Warammer 3 and 2 running with Proton (App ID 1142710 and 594570) since the big Steam UI update.

Other games never crashed because of the Overlay.

OS: openSUSE Tumbleweed x86_64
Kernel: 6.5.6-1-default
DE: Plasma 5.27.8, X11
WM: KWin
CPU: i7 7700K
GPU: NVIDIA GeForce RTX 3070
Memory: 16GB

**Comment by RolandMarchand** [comment]
Disabling the overlay in the game's settings and in Steam causes TF2 to crash.

OS: Gentoo Linux
Kernel: 6.1.55-gentoo-dist
Display Server: X11
DE: Gnome 45.0
WM: mutter 45.0
CPU: AMD Ryzen™ 5 5600 × 12
GPU: AMD Radeon™ RX 6600

```
/bin/sh\0-c\0/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.exe' -steam -game tf -vulkan\0
chdir "/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.exe: /home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file
WARNING: discarding _NET_WM_PID 148233 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 5 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 151951 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 148233 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 5 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 151951 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
```

**Comment by kisak-valve** [comment]
Hello @RolandMarchand, `/home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.exe: /home/roland/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.exe: cannot execute binary file` is #9875 instead of this issue report.

**Comment by LukeStonehm** [comment]
I am experiencing this issue, haven't yet found a workaround for Hunt Showdown (can't invite friends into my party :cry:)

OS: Pop_OS 22.04 LTS
Kernel: 6.5.6-76060506-generic
Display Server: X11
DE: Gnome 42.9
CPU: Intel® Core™ i7-10700K
GPU: GeForce GTX 1080

If anyone has a suggestion on how I can add friends in Hunt without invoking the overlay, that would be amazing. As it stands, I can't play with friends.

**Comment by mystyq** [comment]
> Enabling `Enable GPU accelerated rendering in web views (requires restart)` in `Steam Settings` -> `Interface` seems to have fixed the issue for me.
> 
> Edit: Nevermind. I guess the crashing behavior happens intermittently.

I'm not experiencing this issue anymore with `Nvidia 535 driver`.  Could anyone with this driver version confirm that this issue is still happening for them?

**Comment by Liemaeu** [comment]
> > Enabling `Enable GPU accelerated rendering in web views (requires restart)` in `Steam Settings` -> `Interface` seems to have fixed the issue for me.
> > Edit: Nevermind. I guess the crashing behavior happens intermittently.
> 
> I'm not experiencing this issue anymore with `Nvidia 535 driver`. Could anyone with this driver version confirm that this issue is still happening for them?

I use(d) Nvidia 535 and it crashed for me.

**Comment by Liemaeu** [comment]
> I am experiencing this issue, haven't yet found a workaround for Hunt Showdown (can't invite friends into my party 😢)
> 
> OS: Pop_OS 22.04 LTS Kernel: 6.5.6-76060506-generic Display Server: X11 DE: Gnome 42.9 CPU: Intel® Core™ i7-10700K GPU: GeForce GTX 1080
> 
> If anyone has a suggestion on how I can add friends in Hunt without invoking the overlay, that would be amazing. As it stands, I can't play with friends.

Steam Big Picture Mode should work.

**Comment by LukeStonehm** [comment]
A follow up. I switched to Steam beta client, and used Big Picture mode. This allows me to invoke the overlay and invite my friends to Hunt Showdown. 

(@Liemaeu thanks, I discovered it this morning through experimentation)

**Comment by isaackhlam** [comment]
Opening Overlay crash for Sid Meier's Civilization VI

OS: Archlinux 
Kernel: 6.6.1-arch1-1
Display Server: Wayland
DE: KDE 5.112.0-1
CPU:  AMD Ryzen 7 3700X
GPU: AMD Radeon 5700XT

**Comment by YakShavingCatHerder** [comment]
Switching out between Protons might be worth a shot.

Seems to work for me but nothing solid enough to be a steadfast fix.

**Comment by JLanzuisi** [comment]
Im also getting this when launching Hollow Knight.

**Comment by shdbwa** [comment]
I disabled overlay in steam(global&pergame) , but Steam is 
still trying to load it and this freeze the game upon startup.

**Comment by Redouane64** [comment]
I am getting same error with SnowRunner on Linux:

```
26/10/2025 21:36	steam	ERROR: ld.so: object '/home/redouane/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```
