### ISSUE TITLE
Black screen on tabs powered by the built-in browser (shop, community, profile)

### ISSUE THREAD

**Issue by Cippo95** [ValveSoftware/steam-for-linux#9598]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Fedora Linux 37 (Thirty Seven) (64 bit)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When you open Steam the tabs/sections powered by the built-in browser work correctly.

The first time I use another application in the same workspace and I switch back to Steam it will show a black screen.

#### Steps for reproducing this issue:

1. Open Steam
2. Open another application in the same workspace and use it
3. Switch back to Steam and you have a black screen like this:  

![2023-06-15_1920x1080](https://github.com/ValveSoftware/steam-for-linux/assets/38652363/1ddc480a-1f56-4733-b396-00bc86d88004)

**Comment by kisak-valve** [comment]
Hello @Cippo95, can you check if there's any hints in `cef_log.txt`, `steamwebhelper.log` or `webhelper.txt` in `~/.local/share/Steam/logs`?

**Comment by Cippo95** [comment]
Yes I see a bunch of X errors in steamwebhelper.log
I'll attach the logs.

[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/11759126/cef_log.txt)
[steamwebhelper_1.log](https://github.com/ValveSoftware/steam-for-linux/files/11759057/steamwebhelper_1.log)
[steamwebhelper_2.log](https://github.com/ValveSoftware/steam-for-linux/files/11759061/steamwebhelper_2.log)
[webhelper.txt](https://github.com/ValveSoftware/steam-for-linux/files/11759145/webhelper.txt)

**Comment by karliss** [comment]
I am observing similar symptoms of black tab content but with slightly different reproduction steps on ArchLinux+Gnome+Wayland. For me it happens when maximizing or unmaximizing the window by dragging the top part of window. One more interesting observation is that  "Library" tab not only works correctly, switching between Library and the broken tab fixes the problem (until the next time it gets triggered).

1) Have the steam window smaller than screen
2) switch to "Store" or "Community" tab
3) start dragging the window by left clicking and holding on what typically be the tittle bar area
4) drag the window to the top of screen and release the mouse button thus triggering steam window to be maximized
5) observe that central area of steam became black
6) switch to Library tab -> observe that it displays correctly
7) switch to Store tab -> observe that the problem has disappeared
8) click on the title bar area and drag the window down thus causing the window to extit maximized state
9) observe that the black screen problem is back

Maximizing and demaximizing the window by clicking the button in top right corner between - and x doesn't trigger the problem. 

 

Switching between  steam and other applications works fine without causing black screen.

**Comment by kisak-valve** [comment]
Hello @karliss, you've described the issue being tracked at #9386 instead of this issue report.

**Comment by Root-Core** [comment]
Same on two machines. Both running Manjaro KDE.

1. AMD Ryzen 1700, AMD RX 6750 XT
2. Intel i7-12700H, Nvidia 3070 TI (Laptop), Intel Iris Xe (iGPU) with 96 EUs
2.1. Both GPUs behave the same

How to reproduce this behavior:

1. Open the store / some browser
4. Minimize window
5. Restore window
6. It's broken

Even easier way to reproduce this behavior - #9386:

1. Open the store / some browser in the maximized client
2. Move the window, which makes the window smaller
3. It's broken

Note: It also works the other way around 
Note: Using the buttons for maximizing / de-maximizing works flawlessly

To fix both of them:

1. Switch to the library
2. Switch back

There are several topics about that on the SteamClientBeta group's forum:

- https://steamcommunity.com/groups/SteamClientBeta/discussions/0/6717729343879905836/
- https://steamcommunity.com/groups/SteamClientBeta/discussions/0/6861841362667416086/
- https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3826414483631665291/
- https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3814034217013458322/
- https://steamcommunity.com/groups/SteamClientBeta/discussions/3/6861841362664787687/
- https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3826413850813915465/
[...]

**Comment by llunak** [comment]
I'm attaching log files from a run where I only launched the Steam Client and reproduced the problem:

- I switched to 'Community' view at ~9:12:20 (web view works at this point).
- I minimized the Client window at ~9:13:00.
- I restored the Client window at ~9:13:30 (web views are black at this point).

[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12356702/cef_log.txt)
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/12356704/steamwebhelper.log)
[webhelper.txt](https://github.com/ValveSoftware/steam-for-linux/files/12356706/webhelper.txt)

**Comment by turol** [comment]
I have the same issue on multiple computers. Debian Testing, latest Steam stable, Mate desktop with Marco WM. Happens on both Nvidia proprietary (GTX 960 and 3060M) and AMD (GCN 1.0).

Steps to reproduce:
1. Open Steam
2. Switch to store tab
3. Switch to another virtual desktop and back
4. Tab is blank and stays that way until I switch to library tab

webhelper.txt contains a bunch of these:
```
Webhelper: An X Error occurred
X Error of failed request:  BadAlloc (insufficient resources for operation)
Major opcode of failed request:  152
Serial number of failed request:  802
Webhelper: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  156
Resource id in failed request:  0x6400132
Serial number of failed request:  803
Webhelper: An X Error occurred
X Error of failed request:  GLXBadPixmap
Major opcode of failed request:  152
Serial number of failed request:  0
```

steamwebhelper.log contains these:
```
[0816/130256.338656:INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: e.rgApps is not iterable", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=2aad45a83c6aa1456d4d (1)
Invalid browser dimensions: 0 x 0
src/webhelper/html_chrome.cpp (3404) : CefCurrentlyOn( TID_UI )
[0816/130304.654819:INFO:crash_reporting.cc(271)] Crash reporting enabled for process: renderer
[0816/130306.547220:INFO:crash_reporting.cc(271)] Crash reporting enabled for process: renderer
[0816/130326.007526:WARNING:xproto_util.cc(51)] X error received: serial 6614, error_code 3 (BadWindow (invalid Window parameter)), request_code 129, minor_code 1 (X_ShapeRectangles)
[0816/130326.007617:WARNING:xproto_util.cc(51)] X error received: serial 6616, error_code 3 (BadWindow (invalid Window parameter)), request_code 129, minor_code 1 (X_ShapeRectangles)

```

Hypothesis: something is reporting a bad window size (0x0 or something that gets clamped to that) and then things start to go wrong from there.

**Comment by Root-Core** [comment]
Tested it on the Steam Deck on the latest SteamOS 3.5 with default X11 in desktop mode. It has the same issue.

**Comment by PietroPizzi69** [comment]
Same Issue.
Arch Linux, X11, KDE-Plasma, OS/Apps fully updated yesterday.

Steam-Version:  1690583737
Steam-Client: Build-Datum:  Fr., 28. Juli 20:44 UTC -08:00
Steam: Webbuild-Datum:  Sa., 29. Juli 0:21 UTC -08:00
Steam-API-Version:  SteamClient020

[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12489628/cef_log.txt)
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/12489630/steamwebhelper.log)
[webhelper.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/12489654/webhelper.previous.txt)
(Can't upload "webhelper.txt" because it is constantly growing till 8MB in size, then it get's moved to ..previeous.. and  a new one starts growing)

**Comment by Cippo95** [comment]
Latest update seems to fix this? it took some time! :smile:

**Comment by Zorrototo** [comment]
You mean THIS 1693527575?

https://i.imgur.com/wBvvBPG.png

**Comment by turol** [comment]
Latest beta 1693527575 appears to have fixed it for me.

**Comment by Fairlightish** [comment]
Beta 1693527575 still broken on my end, this is ridiculous.
Linux Mint 21.1 + KDE Plasma 
NVIDIA GeForce RTX 2060 w/ nvidia-driver-535.86.05-0ubuntu0.22.04.1

**Comment by at46** [comment]
It's finally fixed for me with latest Steam Client 1694466342

**Comment by Root-Core** [comment]
It is still broken in the latest Steam Beta Client `16944663424` and Stable `1694466342`.

BUT the behavior differs. If you use the minimize and maximize buttons on the clients window, everything works.
If you maximize by dragging the window to the top corner or maximize via the taskbar, it is still broken.
Same goes for switching to a window by dragging / force via taskbar.

Also you can fix it now by minimizing and restoring the window.
This does not work for the maximized window though.

------------

Manjaro KDE, latest 23.0 release (23-09-10), tested with AMD and Intel GPUs.
It is still present in both: native and runtime versions.

**The issue is also present on the Steam Deck.**

Thank you for the progress, I hope this help to fix the remaining issues.

**Comment by MartinX3** [comment]
Maybe the same issue but instead of the previous blackscreen I get now a "screenshot" of the last view without the ability to click anything until I restart the UI process (not steam itself).

**Comment by WMan22** [comment]
Also having this issue, both on my Arch Linux laptop and on my Steam Deck. On stable branch for steam deck, arch installed in regular linux kernel through archinstall with KDE.

It's reproducible at least on Steam Deck; As Root-Core has said, Seems to happen when a window is maximized, but instead of clicking the middle button between the _ and X in the top right corner, you drag the window somewhere with your mouse. Clicking over to your game library and then back to something like the community tab or store fixes it but only until you do this again.

Webm shows the problem in action: [2023-09-26 03-15-08-[00.01.300-00.33.183].webm](https://github.com/ValveSoftware/steam-for-linux/assets/48204719/167eb4ed-c045-4148-a0a5-06208f8fe918)

**Comment by Gruefus** [comment]
I'm still having this issue on Steam Client version 1695334486

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-33-generic (64-bit)
Graphics Platform: X11

**Comment by saffroy** [comment]
In case that would be useful, here is what I see in `webhelper.txt` while reproducing the issue. 

Starting with the Store view visible on my current virtual desktop, I switch to a different virtual desktop:
```
[2023-10-16 13:22:45] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1702x947
[2023-10-16 13:22:45] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1702x947
[2023-10-16 13:22:45] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1702x947
[2023-10-16 13:22:45] SteamBrowser-'Welcome to': WasHidden 1: (1, 92) 1178x533
[2023-10-16 13:22:45] SteamBrowser-'Welcome to': WasHidden 0: (1, 92) 1178x533
```

Then back to the virtual desktop with the Steam window:
```
[2023-10-16 13:22:48] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1702x947
```

Store view is black, with framing window (top and bottom parts) visible.

Now I minimize the window:
```
[2023-10-16 13:23:14] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1702x947
[2023-10-16 13:23:14] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1702x947
[2023-10-16 13:23:14] SteamBrowser-'Welcome to': WasHidden 1: (1, 92) 1178x533
```

Then maximize it again:
```
[2023-10-16 13:23:18] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1702x947
[2023-10-16 13:23:18] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1702x947
[2023-10-16 13:23:18] SteamBrowser-'Welcome to': WasHidden 0: (1, 92) 1178x533
```

Store view is now correctly displayed.

This is on Debian 12 using Xfce (Xfwm4) on X11, Steam beta 1697233589, GPU accel disabled on web views. I've always seen such issues with Steam since I started using it in May '23, first with the normal release then the beta. IIRC on the release channel, I had to close the window, simply minimizing/maximizing it didn't solve the problem.

**Comment by turol** [comment]
Steam just updated and the bug is back. However this might be a new bug because there are no errors in the logs.

**Comment by at46** [comment]
The bug is also back for me since the October update and the later updates didn't fix it so far. I see some X-errors in the logs: 
[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/13759507/cef_log.txt)
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/13759508/steamwebhelper.log)
[webhelper.txt](https://github.com/ValveSoftware/steam-for-linux/files/13759509/webhelper.txt)

**Comment by maxdwit** [comment]
This is still an issue March 2024

**Comment by Root-Core** [comment]
We have a regression here, as it isn't working with the maximize control provided by Steam anymore.

External maximization was never working, but it is completely broken now.

**Comment by Fairlightish** [comment]
Seems to be fixed on Steam Beta version 1714520927

**Comment by saffroy** [comment]
> Seems to be fixed on Steam Beta version 1714520927

Upgrading to this version did NOT fix the problem for me. Switching virtual desktops (under Xfce) still causes the Steam browser area to turn black.

**Comment by Root-Core** [comment]
> Upgrading to this version did NOT fix the problem for me. Switching virtual desktops (under Xfce) still causes the Steam browser area to turn black.

Working on KDE Plasma 6.

Same issue was reported here: https://github.com/ValveSoftware/steam-for-linux/issues/9386#issuecomment-2081159895

**Comment by PietroPizzi69** [comment]
I'm on the stable version 1715635533 now and it also works for me with KDE Plasma 6 on Arch. I had many problems with Wayland, including extreme flickering in the Steam client, but with X11 it's solved now.

**Comment by chev2** [comment]
I'm running stable version 1715891371 and it appears the issues have been fixed for me as well; both minimizing/maximizing Steam as well as resizing it. Running KDE Plasma 6.0.4 on Arch with Wayland (though in the case of Steam, it seems to be using Xwayland)

```
Steam Beta Branch:  Stable Client
Steam Version:  1715891371
Steam Client Build Date:  Thu, May 16 1:11 PM UTC -08:00
Steam Web Build Date:  Thu, May 16 12:36 PM UTC -08:00
Steam API Version:  SteamClient021
```

**Comment by MartinX3** [comment]
Still an issue for me on X11 XFCE4 with a GTX 940M on nvidia 555.
Or on intel skylake iGPU.
