### ISSUE TITLE
Steam UI no longer working after nvidia driver update (535.54.03-1)

### ISSUE THREAD

**Issue by Sekke123** [ValveSoftware/steam-for-linux#9620]
#### Your system information

* Steam client version (build number or date): updated to latest (steam-1.0.0.78-1) via pacman on 6/15/2023
* Distribution (e.g. Ubuntu): 6.3.8-arch1-1 with KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed the newest drivers (535.54.03-1), I installed a newer version of `lib32-nvidia-utils` from the multilib testing repo after determining that it was out of date. Then I rebooted and opened steam where the UI ceased to work. 
https://gist.github.com/Sekke123/62e7cc1ec40e90e5d518a9d4d61ff2c5
result of using 'steam' in console ^

#### Steps for reproducing this issue:

1. Install 535.54.03-1 nvidia graphics drivers 
2. Install lib32-nvidia-utils
3. reboot
4. launch steam

**Comment by yhojann-cl** [comment]
In my case, every time the client was updated or the nvidia drivers were updated, the steam client stopped working, to solve it I had to install or reinstall `mesa-utils`, it was always solved with this, I don't know why it happens, but there are several issues talking about the same topic.

Try execute `sudo apt -y install --reinstall mesa-utils` and reboot.

**Comment by agrahamlincoln** [comment]
I had a similar problem on arch linux, it was also fixed by reinstalling `mesa-utils`

in my case, I ran `sudo pacman -Sy mesa-utils`

**Comment by Sekke123** [comment]
after reinstalling `mesa-utils` via `sudo pacman -Sy mesa-utils` and then rebooting. It did not solve my problem with steam. Steam still launches but there is no UI to interact with.

**Comment by Sekke123** [comment]
I install 'lib32-mesa-utils' that fortunately worked after rebooting then launching steam.desktop. However, after closing steam and reopening it, steam no longer worked, back to square one. I tried reproducing this by uninstalling 'lib32-mesa-utils' rebooting then reinstalling it. That did not work.

**Comment by yhojann-cl** [comment]
You can try to use the flatpak package, it already comes with all its dependencies ready in stable mode, if it still doesn't work for you, it's because the problem goes beyond the software.

**Comment by Sekke123** [comment]
so far this has worked! I just uninstalled steam and installed via flatpak. although the previous steam libraries weren't able to be read and games weren't able to be transferred over to the new steam... weird
