### ISSUE TITLE
I can't input special characters in steam chat after new interface update.

### ISSUE THREAD

**Issue by C-Sophrosyne** [ValveSoftware/steam-for-linux#9631]
#### Your system information

* Steam client version (build number or date): 1686880776. Steam Web Build Date:  Thu, Jun 15 22:10 UTC -08:00
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed VERSION_ID="20230613"
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

After the new interface update I can no longer type special characters in steam chat. Also this problem already existed when using the overlay but I didn't care because I never use the overlay anyway.

I can copy and paste special characters but can't input myself.
#### My locale config:
![locale](https://github.com/ValveSoftware/steam-for-linux/assets/99696791/150ea1cf-1622-489a-9d10-8aabb31c1569)

#### Steps for reproducing this issue:

1. Open Steam>Steam Chat
2. Choose your BFF to chat with
3. Try input some special characters(ñôèéáàã)

**Comment by kisak-valve** [comment]
Hello @C-Sophrosyne, this might be the same issue as #8530.

**Comment by Mikael-Lovqvist** [comment]
I can confirm that composing characters like `^`, `~` or ` can not be input in the application.

**Comment by C-Sophrosyne** [comment]
Today I did a clean install, this time with the system language in English and the problem still exists.

![CleanInstallSameProblem](https://github.com/ValveSoftware/steam-for-linux/assets/99696791/1d38590a-e970-4d7f-878a-0f7103f0374b)


I read some old ~2016 issues that could be fixed by just adding en_US.UTF-8 locale to the system. Well... No luck.

**Comment by vagner995** [comment]
Can confirm this issue started ever since the beta for the new UI. The issue is only present on linux, no matter what distribution. I cannot input special characters, but I can copy paste them into the chat. It's specifically a bug with the input code and it is program wide. Can't type special characters anywhere.

**Comment by childoftheabyss** [comment]
Same here, after the UI update I am not able to type accent characters and neither type in Japanese (totally ignores mozc input mode).  I am using PopOS 22.04 LTS with US English alternative international layout.

   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us,us
     X11 Variant: alt-intl,

**Comment by spacescientist** [comment]
I came to report the exact same problem that I hadn't encountered before the new interface: now there is no way to write characters widely used in French, Italian, German, Spanish and other languages in the Steam chat.

**More generally, it's no longer possible to get any character requiring multiple inputs**, e.g. combining vowels with ^ (â, ê, î, ô, û, ŷ), or ´ (á, é, í, ó, ú, ý), or ` (à, è, ì, ò, ù, ỳ), or " (ä, ë, ï, ö, ü, ÿ), or ~ (ñ). Characters that do not require multiple inputs do work: i.e. if there is a dedicated 'é' key, it will work but producing it via ´ + e will not.

In fact, it's even worse than that: with Belgian or French keyboard layouts (and I would guess Spanish and German as well) there now moreover is no way to input ^, nor ` nor ´, nor ", nor ~ in the Steam chat anymore.

There is more: **unicode keyboard inputs are now broken as well**.
On Linux, you can input those by doing the following: press `Shift+Ctrl+u`, then type e.g. `2014` and press `enter`. You'll get the em-dash character '—' — well, except in the Steam chat, that is.

I am currently on Manjaro.
Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 11:18 PM UTC -08:00
Steam Web Build Date:  Thu, Jun 22 12:26 AM UTC -08:00
Steam API Version:  SteamClient020
Opted into Steam client beta? No
Have you checked for system updates? Yes

**Comment by spacescientist** [comment]
One note : according to the Steam Hardware & Software Survey, the vast majority of Linux users use English https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux 

However, that does not mean that they are native English speakers, nor that they solely speak in English. We might communicate (mostly, even) with friends who might not even be able to speak English themselves. The accented characters are required to properly speak other languages, to convey vastly different meanings.

**Comment by Zorrototo** [comment]
Indeed, my Steam is set to English because I hate achievements translation, and want my games to be defaulted to English without manual intervention, but I'm French, so I obviously write in French, but as reported I can not write correctly in French since latest update.

System info: https://gist.github.com/Zorrototo/e93cc3664ef696500b311bc3e495143c

```
System Locale: LANG=fr_FR.UTF-8
    VC Keymap: fr
   X11 Layout: fr
    X11 Model: pc105
  X11 Variant: azerty
```

**Comment by victhor393** [comment]
I am also having this problem, on the non-beta client, version 1689034492.
```
System Locale: LANG=pt_BR.UTF-8
    VC Keymap: br-abnt2
   X11 Layout: br
    X11 Model: abnt2
  X11 Options: terminate:ctrl_alt_bksp
```

**Comment by Krovikan** [comment]
Same annoying problem in non-beta client from the UI update, version 1689034492.

```
System Locale: LANG=es_ES.UTF-8
       VC Keymap: es
      X11 Layout: es
       X11 Model: pc105
     X11 Options: terminate:ctrl_alt_bksp
```

**Comment by lagerspetz** [comment]
Seems that any ´dead keys´ now don't work. For example ´ needed for making e with accent forward just appears as if it was not a dead key at all.

**Comment by KibaGasteiz** [comment]
Still not fixed, and it's a very annoying bug if you ask me.

**Comment by Gustavo17pacheco** [comment]
Still happening. I also can't type Japanese characters on GNOME Wayland on Fedora using iBus-mozc. 

This really sucks.

**Comment by senkra** [comment]
Happens on the non-beta and beta branch. Especially annoying now that it's impossible to use the old chat version as a workaround.

>System:
  Kernel: 6.4.0-3-amd64 arch: x86_64 bits: 64 Desktop: KDE Plasma v: 5.27.7
    Distro: Debian GNU/Linux trixie/sid
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 525.125.06
  Display: x11 server: X.Org v: 1.21.1.8 with: Xwayland v: 23.2.0 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080
    2: 1920x1080
  API: OpenGL v: 4.6.0 NVIDIA 525.125.06 renderer: NVIDIA GeForce GTX
    1070/PCIe/SSE2

**Comment by chozma** [comment]
I use a modified US International with deadkeys keyboard layout because I am multilingual and work with many different languages regularly, and ever since the update, I'm unable to even type an apostrophe in the Steam client now because deadkeys are not recognised at all.

As a result, I'm unable to even type in English, and this makes providing support to users for my Steam Workshop mods tedious beyond imagination to where I can no longer be bothered to actually do so or do anything else on Steam that requires typing anything anywhere. If this were the case originally, I would not have shared any of the content I created on Steam to begin with, because I would've gotten frustrated trying to type anything and given up.

The only way I'm able to type an apostrophe is by typing the character ' somewhere else and copy pasting it in whenever I need it. It is frankly absurd this very basic and essential functionality of supporting non-standard American keyboard layouts has been lost with the major update with no solution in sight, despite this being recognised as an issue since June.

**Comment by cofilippo** [comment]
I have this problem as well, and it is present across all my devices on linux. (Kubuntu as well as Tumbleweed (Slowroll) with KDE. It doesn't matter if I use X11 or Wayland either. Keyboard is set to US International with dead keys in all cases. (need it for the special characters in my own language) Unicode entry does not work either. Pasting the text from another application does work, but you can probably understand why that is very impractical.

**Comment by UNF0RM4TT3D** [comment]
I'd just like to add that not even IMEs (input method extensions) work, which are usually used to type Japanese, Chinese, etc. But can be used to input diacritics in a different way. These however completely break input in the steam overlay and don't fix it in normal chat.

**Comment by GuilleW** [comment]
No problem for special char until last week. 
Distro update on Manjaro last week break special char in game.
In the +100 packages, I don't know if Steam was updated.

Actually, Proton 7x let me use special char in chat, but Proton 8x don't.
Both can't bind special char.... so "é" on key "2" can't be use anymore. 
Aaaaand ... in MMO "12345" is really used all times, so I can't use "2" key anymore.

Trying locale fix in all posts I found doesn't work.

**Comment by Zorrototo** [comment]
This is not same issue, here we talk about the Steam chat, not in game, so I don't think it is related.

**Comment by Krovikan** [comment]
Yes. The issue of @GuilleW is not related with this thread.

**Comment by GuilleW** [comment]
Yeah, sorry about that. Since everything work in steam, but bug in game, it doesn't relate. We can remove messages to clean this issue. Sorry again, and good luck to resolve it !

**Comment by vagner995** [comment]
Today on Steam Beta Update version 1705630720 I can input these characters again. Don't know what fixed it, but it finally happened.

**Comment by Mikael-Lovqvist** [comment]
> Today on Steam Beta Update version 1705630720 I can input these characters again. Don't know what fixed it, but it finally happened.

I switched to beta participation and I can now also input composing characters (though there are other issues that prevent me from using the beta for the moment). Unfortunately I can't confirm whether older beta versions behaved differently.

**Comment by C-Sophrosyne** [comment]
> Today on Steam Beta Update version 1705630720 I can input these characters again. Don't know what fixed it, but it finally happened.

Can confirm but still broken in the Steam Overlay

**Comment by KibaGasteiz** [comment]
@kisak-valve
This issue can be closed, it's fixed here too.

**Comment by Krovikan** [comment]
Don't close very fast.

Tried Beta version 1705630720 and only is fixed in normal chat.

From Steam Overlay don't works.

Greetings

**Comment by Krovikan** [comment]
I tried this beta version but don't works from Steam Overlay. Only out of the games.

Regards

**Comment by KibaGasteiz** [comment]
This bug was fixed for me, but just came back.

**Comment by Krovikan** [comment]
Tried Beta version 1707265912 and everything remains the same.

Fixed in chat, but don't work from Steam Overlay.

Regards

**Comment by Krovikan** [comment]
Dead keys works in the new Steam Stable version: 1708985249.

Don't works yet from Steam Overlay.

Maybe the title of the Issue needs a change. The problem persists only in Steam Overlay.

Regards

**Comment by mdsmendes94** [comment]
Can confirm that I still can't input diacritic/special characters when a game is open and chatting through Steam Overlay

**Comment by kisak-valve** [comment]
Closing as fixed.

The Steam overlay variant of this issue is being tracked at #2122.
