### ISSUE TITLE
Huge VRAM Usage, Increases Until Steam Is Closed

### ISSUE THREAD

**Issue by JoshuaFern** [ValveSoftware/steam-for-linux#9638]
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu): Flatpak/NixOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
*  [Sysinfo Gist](https://gist.github.com/JoshuaFern/0677a8687a02461df7d7e6ad459263ec)

#### Please describe your issue in as much detail as possible:
I've been getting errors in my games because I'm running out of VRAM. On further examination, I discovered via `nvtop` that xorg was using most of my VRAM, which was only freed again after closing Steam. Note that I have GPU Accelerated Rendering turned off.

May be related to https://github.com/ValveSoftware/steam-for-linux/issues/9516

#### Reproducing this issue:
I'm running the window manager i3 and I found repeatedly switching between the workspace with Steam and the workspace with the terminal running `nvtop` resulted in ever increasing VRAM on my machine. Starting a game also increases VRAM usage by approximately 50MB.

**Comment by heikomat** [comment]
I have the same Problem on Pop!_OS.

One easy reproduction for me is to just resize the steam client (dragging the mouse in circles).
After just a few second of resizing all 6GB of vram is eaten up by xorg and the desktop environment crashes, dropping me to the login screen

**Comment by xjunko** [comment]
Running on Arch Linux, having the same problem.
Changing workspace and resizing the steam client increases the `xorg` vram usage by a crazy amount.
I use the `steam` package from the aur and am not subscribed to the steam client beta.

**Comment by husjon** [comment]
I am also on Arch and use the `steam` package from Multilib.
I started seeing it late in the beta but wasn't able to narrow down when / why it happened.

System info gist: https://gist.github.com/husjon/97c4cebf276b66038aaea621034b3981
Quick video showing how quickly it balloons: https://youtu.be/FCXA31aTlRw

**Comment by FredrikHson** [comment]
get the same issue on arch + my usual i3wm or even  gnome(just for testing) when resizing the window/swapping workspaces or going from the library->store page 
nvidia  Driver Version: 530.41.03

**Comment by Olexorus** [comment]
Same issue here, after a few seconds of resizing the window, Steam fills up all of my 12GB of VRAM.

As a workaround, Steam can be started with the -vgui flag to revert back to the old UI until there is a proper fix.

**Comment by KarlHornell** [comment]
I've had the same issue for some time now. I'm running latest Debian with i3wm and Nvidia GPU.
Switching windows in i3wm to and from a steam window also seems to produce this increase in VRAM usage by Steam.
For some games I really feel the need to kill steam while playing to avoid lag, which has not been the case before.
The `-vgui` workaround means I can't log in to 'Friends'
Could add more information but I think most of it has already been said by others.

**Comment by Stoneblackdog** [comment]
This is also happening for me. I'm on arch linux using awesome as my window manager and an Nvidia GPU.

**Comment by Lamieur** [comment]
-vgui stopped working in the latest beta, making me very unhappy, my game stutters like crazy when I hit VRAM limit, and, you know, it's Steam-only now, it absolutely has to be launched by Steam.

But check this out, I'm in game, can't restart Steam:
```
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1895      G   /usr/libexec/Xorg                          1597MiB |
|    0   N/A  N/A     75851      G   ...ling,SpareRendererForSitePerProcess       31MiB |
|    0   N/A  N/A    300059      G   /usr/lib64/seamonkey/seamonkey                5MiB |
|    0   N/A  N/A    711116      G   ...local/share/Steam/ubuntu12_32/steam       18MiB |
|    0   N/A  N/A    711178      G   ...re/Steam/ubuntu12_64/steamwebhelper       16MiB |
|    0   N/A  N/A    723173      G   /usr/lib64/firefox/firefox                   23MiB |
|    0   N/A  N/A    841566    C+G   ...ns\client\bin\pc\QuakeChampions.exe     3907MiB |
+---------------------------------------------------------------------------------------+
# kill -9 711178
# nvidia-smi 
(...)
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1895      G   /usr/libexec/Xorg                           384MiB |
|    0   N/A  N/A     75851      G   ...ling,SpareRendererForSitePerProcess       24MiB |
|    0   N/A  N/A    300059      G   /usr/lib64/seamonkey/seamonkey                5MiB |
|    0   N/A  N/A    711116      G   ...local/share/Steam/ubuntu12_32/steam       18MiB |
|    0   N/A  N/A    723173      G   /usr/lib64/firefox/firefox                   23MiB |
|    0   N/A  N/A    841566    C+G   ...ns\client\bin\pc\QuakeChampions.exe     3907MiB |
|    0   N/A  N/A    845410      G   ...re/Steam/ubuntu12_64/steamwebhelper        7MiB |
+---------------------------------------------------------------------------------------+
```

I can kill steamwebhelper while the game is on. The Steam window closes, new one loads on the current desktop, but the game continues running.

Oh, and of course I have DISABLED "Enable GPU accelerated rendering in web views" as well as "Enable hardware video decoding" (just in case) whenever this started, which never helped, but -vgui did. RIP -vgui [*]

Nvidia 535.54.03, MATE (marco is the WM), Xorg 1.20.14

**Comment by Lamieur** [comment]
So I've noticed nvidia driver 535.86.05 is out, promising fixes for memory leaks. It only mentioned leaks during VT switching and Wayland, so neither is our case, but it was worth a try. I'm sad to report, 535.86.05 does NOT help the Steam VRAM leak.

Steam also updated to newer beta (from yesterday), no change in this behavior (now Store goes full black when you look at it the wrong way, but even in the black state, it still leaks :))

I've tested replacing the WM (marco --replace &) - no change to VRAM usage. It's just between the embedded Chromium and Xorg, the WM doesn't matter.

I've also noticed the leak in normal usage happens when I switch desktops (specifically, when going to/from the desktop with Steam). That's why it takes me a day or so to actually achieve the 1,5 GB that breaks my game (already set to medium textures as a partial work-around).

So I tested other means of making it leak VRAM very fast:
1. You can minimize/restore the Steam window. For me it's -5 MB when minimizing, +30 when restoring, +25 MB on average.
2. You can simply grab the Steam window's edge and swipe around, so it resizes continuously. Way faster than minimizing/restoring.
3. You can do Alt-F6/F5 (maximize/restore binds if you don't have them) repeatedly, I think this is even faster than mouse dragging (that has a delay and refreshes less often).

With Alt-F6/F5 smashing, I can eat up full 10 GB of VRAM in less than 40 seconds :) Compare that to 55 seconds by dragging the mouse - who would think I'll be speedrunning VRAM exhaustion of Steam client today! :))

Again: the workaround is killing steamwebhelper. PS. Steam will restart hundreds of those after a while, ~15 more each time, doesn't matter if you kill -9 the main one, or killall steamwebhelper, they will multiply :)

**Comment by JoshuaFern** [comment]
I have another workaround, you can run Steam in software rendering mode with the following environment variables:
```
__GLX_VENDOR_LIBRARY_NAME=mesa
GALLIUM_DRIVER=softpipe
MESA_LOADER_DRIVER_OVERRIDE=softpipe
LIBGL_ALWAYS_SOFTWARE=1
```
Then just unset those variables in the launch option for the game, so that the game doesn't run in software mode.

There's some other options for software drivers, swr and llvmpipe. See what works best for you.

**Comment by husjon** [comment]
As a quick test I installed Gnome to try out a more traditional desktop environment (which is shipped with f.ex Ubuntu).
It seem to run on Wayland as default and I was not able to replicate this issue there at all, no matter how much I was resizing the window or switching desktop / workspaces.
Switching Gnome to run on Xorg however the issue is there once again and it does not take long for Steam to gobble up the available VRAM.

**Comment by jwhear** [comment]
I am experiencing this issue on Debian 11.7, kernel 5.10.0-23-amd64.  The impact is that, if I don't restart Steam, a launched game will lag horribly due to a lack of VRAM.

Steam About info:
```
Steam Version:  1689034492
Steam Client Build Date:  Mon, Jul 10 4:59 PM UTC -08:00
Steam Web Build Date:  Mon, Jul 10 10:48 AM UTC -08:00
Steam API Version:  SteamClient020
```

 I use the i3 window manager (Airblader gaps fork built from source).  After a few hours usage I routinely see Xorg VRAM usage (as reported by `nvidia-smi`) at ~5GB+.  This memory usage seems to trend upwards whether I'm interacting with Steam or not.   Quitting Steam sends Xorg VRAM usage down to ~313MB on my system.

I have a GeForce GTX 1070, `nvidia-smi` version info:
```
NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4
```

Happy to add any info if useful.

**Comment by kaarelen** [comment]
Same issue. I can get to INSANE 4 GB + xorg VRAM allocation in less than 2 minutes, just switching to workplace with steam and any other.
env: 
Steam client version (build number or date): 1689034492
Distribution (e.g. Ubuntu): Arch multylib
Opted into Steam client beta?: No
Have you checked for system updates?: Yes
Short system info: arch linux, zen kernel, nvidia + nvidia closed source driver, i3wm
<details>
  <summary>System info :</summary>
Computer Information:

Manufacturer: ASUSTeK COMPUTER INC.
Model: P8H67
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Xeon(R) CPU E31240 @ 3.30GHz
CPU Family: 0x6
CPU Model: 0x2a
CPU Stepping: 0x7
CPU Type: 0x0
Speed: 3700 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.5-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: i3
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.86.05
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 164 Hz
VendorID: 0x10de
DeviceID: 0x1b81
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC887-VD
Memory:
RAM: 15960 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 89888 MB
Largest Free Hard Disk Block: 59526 MB
Storage:
Number of SSDs: 3
SSD sizes: 1000G,500G,128G  (pay attention, detected definetily wrong, i have 1TB hdd + 500GB ssd + 128GB system ssd, all space allocated)
Number of HDDs: 0
Number of removable drives: 0
</details>

<details>
  <summary>nvidia-smi</summary>
  ```
cub@archlinux ~/tmp> nvidia-smi

Tue Aug  1 06:49:01 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070        Off | 00000000:01:00.0  On |                  N/A |
| 11%   56C    P0              47W / 151W |   7690MiB /  8192MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     30597      G   /usr/lib/Xorg                              4259MiB |
|    0   N/A  N/A     30801      G   ...144 --enable-features=WebUIDarkMode       43MiB |
|    0   N/A  N/A     38691      G   kitty                                         4MiB |
|    0   N/A  N/A     50809      G   kitty                                         3MiB |
|    0   N/A  N/A    124822      G   kitty                                         5MiB |
|    0   N/A  N/A    149092      G   ...ures=SpareRendererForSitePerProcess       47MiB |
|    0   N/A  N/A    151051      G   ...local/share/Steam/ubuntu12_32/steam        4MiB |
|    0   N/A  N/A    151059      G   ...re/Steam/ubuntu12_64/steamwebhelper        7MiB |
|    0   N/A  N/A    151117      G   ...eam/logs/cef_log.txt --shared-files       97MiB |
|    0   N/A  N/A    151831      G   ...ps/common/Factorio/bin/x64/factorio     3207MiB |
+---------------------------------------------------------------------------------------+
  ```
</details>

**Comment by kaarelen** [comment]
upd: it doesn't affect "small mode", but triggers for any other window, friends list, large mode, big picture

**Comment by husjon** [comment]
A new version of Steam has just been released and now neither beta or stable can be used with `-vgui` and we need to restart Steam a few times a day :frowning_face:

**Comment by joshuagiles** [comment]
Very happy to see that Valve has removed the workaround for this bug without providing a fix, so now Linux users can only watch while Steam gobbles up all of their VRAM, hardware acceleration enabled or not.

**Comment by J-Pai** [comment]
Also having this issue as well.

**Comment by Olexorus** [comment]
It's possible to downgrade back to the old build and continue using -vgui with this guide: https://steamcommunity.com/discussions/forum/0/6516193260168294059/

Basically it uses an archive.org link to force Steam to downgrade to that, and then disables updates. Of course this is a very ugly workaround, but at least it's usable, other than the current version.

**Comment by Lamieur** [comment]
> It's possible to downgrade back to the old build and continue using -vgui with this guide

I've followed that 30 times (archive.org throttled me to 20 Mbps after a few tries), disabling beta participation, entering either "false" or "disabled" (because the guide has 3 different versions!) into ~/.local/share/Steam/steam.cfg - nothing helped.

What I was missing was: rm -rf ~/.local/share/Steam/package/*

It finally worked. Thanks for pointing me in that direction. I have steam -vgui working again. But it's ummm... not so good.

Of course current Steam is bonkers, yesterday I had a black screen (100% reproducible if you're in the Store and switch desktops) while trying to buy a game. But I managed to buy it (you can go Store->Library->Store, refresh, it doesn't forget your order), then took screenshots of a game and the new GUI can't even display them (actually any screenshots at all). This old version with -vgui has no VRAM leak, no black screens (but a white screen when going to the Store for the first time, OBVIOUSLY :D)... but of course you can't do anything with it because of issue #9237.

I don't know what's worse, having to killall -9 steamwebhelper every hour, or having to ctrl-click everything, otherwise no menus work... I'll think about it.

**Comment by grrbhen** [comment]
> With Alt-F6/F5 smashing, I can eat up full 10 GB of VRAM in less than 40 seconds :) Compare that to 55 seconds by dragging the mouse - who would think I'll be speedrunning VRAM exhaustion of Steam client today! :))

I got inspired by this post, so here's my first PB :)

https://youtu.be/0XB9hnADQkY

**Comment by kaarelen** [comment]
@grrbhen AHAHAHAHHA, you're genius!

**Comment by husjon** [comment]
With the current Beta and Nvidia drivers I see no issues with VRAM leak, more testing needed. :crossed_fingers: 

```
Steam Version:  1692318383
Steam Client Build Date:  Fri, Aug 18 2:07 AM UTC -08:00
Steam Web Build Date:  Thu, Aug 17 11:01 PM UTC -08:00
Steam API Version:  SteamClient020
```

```bash
❯ pacman -Q nvidia
nvidia 535.98-1
```

**Comment by J-Pai** [comment]
I'm on the beta and it looks like the issue is still there.

```
Steam Version:  1692390949
Steam Client Build Date:  Fri, Aug 18 12:39 PM UTC -08:00
Steam Web Build Date:  Fri, Aug 18 1:21 PM UTC -08:00
Steam API Version:  SteamClient020
```

So it looks like it was fixed for a bit and then regressed.

**Comment by husjon** [comment]
@J-Pai I've just updated but do not see any regression like how it was.  
Now it at most increases by a few MiBs for a few seconds of rapid window resizing then corrects itself.

Have you updated your nvidia drivers?

**Comment by J-Pai** [comment]
My driver isn't exactly the same as yours, but I don't think minor versions will make that much of an impact on this issue.

```
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
```

It also seems unlikely Nvidia drivers are the cause for this issue considering the old UI did not have this issue.

**Comment by Olexorus** [comment]
I can confirm, it seems to be fixed for me on the latest beta (build date 18th August) with driver version 535.98.

> It also seems unlikely Nvidia drivers are the cause for this issue considering the old UI did not have this issue.

I don't see why, it's totally possible that the error is in the Nvidia driver but the old UI simply didn't trigger it (like most other programs), especially considering the size of the changes.

**Comment by Lamieur** [comment]
> fixed for me on the latest beta (build date 18th August) with driver version 535.98.

I'm too scared to go back to the new UI, but checking https://forums.developer.nvidia.com/t/topic/262477 - 535.86.05 → 535.98 changes tl;dr: "fixing some corner cases". [1]

I'm on 535.98 already, but it was kind of hard to revert to an objectively nicer (better looking on 1080p and way more responsive!) Steam version to try to confirm whether the new driver really fixed it. My fault. I'm only explaining why I'm sceptical.

[1] Yes, it's a bad, BAD change log, it has a *highlight* of "Fixed a bug which could cause the screen to flicker." - as if they don't know what conditions/hardware/software could ever cause that if no one complained and no one noticed improvement after installing it ;) But they have mentioned VRAM leaks in the previous one, so I fully expect them to mention fixing a Steam VRAM leak if it was their fault.

**Comment by Olexorus** [comment]
Actually it doesn't seem to be fixed after all. I have no idea why, earlier when I tested I resized the window a lot and the VRAM usage didn't change at all, now I checked again and it spiked in seconds again. Really weird and disappointing.

I also wonder why this isn't a higher priority to fix, since it seems to be fairly common (especially if you consider that many people probably have it without knowing, since you actively have to check the VRAM usage to notice it).

**Comment by jwhear** [comment]
Upgrading my nvidia drivers AND using the Steam Beta appears to resolve the issue.  I tried just the Beta and just the new drivers and experienced the problem; the combination appears to solve the issue.

```
Driver Version: 525.125.06

Steam Version:  1692390949
Steam Client Build Date:  Fri, Aug 18 12:39 PM UTC -08:00
Steam Web Build Date:  Fri, Aug 18 1:21 PM UTC -08:00
Steam API Version:  SteamClient020
```

**Comment by Lamieur** [comment]
> Driver Version: 525.125.06

We're all on 535 series for 3 months (and they got the "production" release on June 14th). Are you sure 525.125.06 (also from June, aka before this issue was opened) are the "new drivers" that fix the issue? Or are you saying rolling back to older branch fixes it? Yes, most people here, naturally, reported from nvidia 530.* and 535.* (as those were the official versions when the new Steam UI hit us), but scroll up a bit and there's a report from 470.* on a 1070, so...

[And to add to my previous rant about nvidia changelogs: 535.104.05 has the exact same "changes" (as in: actually no changes, judging by those notes) as "current production branch release" 535.98 - I understand combining beta changelogs into a production release, but these are two official production releases with the same changelog... this is why AMD crowd calls them "novideo", clearly everything at nvidia is run by interns]

**Comment by jwhear** [comment]
> Are you sure 525.125.06 (also from June, aka before this issue was opened) are the "new drivers" that fix the issue? 

I was on `470.182.03` until last night.  Before upgrading I had tested using Steam Beta but observed same high VRAM usage.  Last night I upgraded my Debian install from 11.7 to 12, which includes the new NVIDIA drivers (525.125.06).  With just new drivers I continued to experience the issue (though I didn't test very extensively), so I tried switching to Beta.  Thus far the issue seems to have been resolved.

**Comment by Stoneblackdog** [comment]
It's still happening for me. Turning off "Enable GPU accelerated rendering in web views" solves the issue but makes some things laggy (Youtube videos in announcements, achievement screen). I'm using the beta with Nvidia driver version 535.104.05.

**Comment by husjon** [comment]
@Stoneblackdog that seem to be the reason why I didn't see the issue since https://github.com/ValveSoftware/steam-for-linux/issues/9638#issuecomment-1684486284 (2023.08.19).
I had turned off GPU acceleration and Hardware video encoding quite a while ago.

Re-enabing GPU acceleration does indeed reintroduce the extreme memory usage again.

**Comment by J-Pai** [comment]
> It's still happening for me. Turning off "Enable GPU accelerated rendering in web views" solves the issue but makes some things laggy (Youtube videos in announcements, achievement screen). I'm using the beta with Nvidia driver version 535.104.05.

Looks like this fixed it for me.

Turned off a GPU accelerated related settings and steam no longer leaks.

**Comment by grrbhen** [comment]
Seems to be fixed using driver 535.104.05 and the beta client with GPU acceleration turned off.

**Comment by fcolecumberri** [comment]
I am also having this problem. I am using nvidia 535.104.05 on Garuda (Arch based distro), and up to what I have seen, the problem is not consistent, when I just open steam, the memory leak does not appear to be there, however if I keep it open, at some point the memory starts leaking again forcing me to restart.

**Comment by husjon** [comment]
@fcolecumberri for me I started noticing it as I switched workspaces.
You could try to disable hardware acceleration in Steam, this has at least worked for most here.

**Comment by awsms** [comment]
Steam eats 70% of my laptop's GPU VRAM (RTX3600, 6GB). Running 535.104.05 on EndeavourOS+Cinnamon

**Comment by emko** [comment]
wow the bug still exists

**Comment by awsms** [comment]
> wow the bug still exists

it will forever as long as a valve employee doesn't have a look. the absolute state of proprietary software

**Comment by JoshuaFern** [comment]
This has been fixed for a long time for me. I'm willing to close this issue. If you're still experiencing the problem it might be different from mine, try opening a new issue.

**Comment by matte-ek** [comment]
Glad it's fixed for OP, but I'm still having the same issue. Can anyone else also still repro or is it just me?

**Comment by heikomat** [comment]
> Glad it's fixed for OP, but I'm still having the same issue. Can anyone else also still repro or is it just me?

It's not just you, still happening for me aswell

**Comment by emko** [comment]
not fixed....

**Comment by xpander69** [comment]
Still have this issue as well. Resizing the steam window with gpu acceleration enabled will make this issue appear super fast.

```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1703100617
Steam Client Build Date:  Wed, Dec 20 21:06 UTC -08:00
Steam Web Build Date:  Wed, Dec 20 20:14 UTC -08:00
Steam API Version:  SteamClient021
```

nvidia drivers 535.43.20

everything is fine with gpu acceleration disabled, except the client is laggy and capped to 60 on scrolling.

**Comment by kodatarule** [comment]
This issue is indeed not fixed and it can still occur, just open steam maximize it a few times or resize it and the vram spikes a lot without ever freeing any vram, can reproduce on both MESA and Nvidia proprietary.
Additionally it also puts everything under Xorg.

This issue needs to be re-opened.

**Comment by Zi7ar21** [comment]
Hello, I am having the exact same problem! (resizing the Steam window causes Xorg's VRAM usage to skyrocket), please re-open the issue @xpander69!

**Comment by xpander69** [comment]
> Hello, I am having the exact same problem! (resizing the Steam window causes Xorg's VRAM usage to skyrocket), please re-open the issue @xpander69!

Sorry but i can't open it :) im not the Original poster. But the other issue with same symptoms is open if you check above.

**Comment by Zi7ar21** [comment]
> Sorry but i can't open it :) im not the Original poster. But the other issue with same symptoms is open if you check above.

Oops, I meant to @JoshuaFern! I have also added my concerns to #6715.

**Comment by JoshuaFern** [comment]
I feel bad closing the issue because so many people are having a similar problem, but as I said before my original issue is resolved on my end. I was able to use Steam without any noticeable VRAM leaks, and I've since switched away from i3wm with an Nvidia GTX 1060 3GB to hyprland with an AMD RX 6800 XT with no further VRAM issues to report.

Hope Valve figures this out for everyone.

**Comment by kaarelen** [comment]
@JoshuaFern You just turned off GPU acceleration (saw in your previous messages). But the original issue isn't solved at all. Try to use Big Picture and you will fell what it is to live without GPU acceleration.

**Comment by kaarelen** [comment]
my system up-to-date
issue is 100% valid
Steam eats out all vram

**Comment by kisak-valve** [comment]
The fragmented discussion between this issue report and #6715 is not helping advance the issue you're seeing to a resolution.
