### ISSUE TITLE
Steam Freezes on "Loading User Data" screen.

### ISSUE THREAD

**Issue by FireWingLead** [ValveSoftware/steam-for-linux#9769]
#### Your system information

* Steam client version (build number or date): 1.0.0.75
* Distribution (e.g. Ubuntu): Zorin OS 17
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
Above command does not work. Cannot generate logs. Output from running that command:
 tar: Removing leading '/' from member names
 tar: /home/perrin/.steam/steam/logs: Cannot stat: No such file or directory
 tar: Exiting with failure status due to previous errors
A file (steam-logs.tar.gz) did appear on the desktop, however, and I have attached it.

* GPU: Nvidia (GEFORCE RTX 4070)

#### Please describe your issue in as much detail as possible:
Steam does not finish loading. It starts up, checks for updates, logs in, and then says "Loading User Data". As soon as it gets to this message, it freezes and stops responding. Always. The spinner stops spinning, the window will not respond to attempting to close it or drag it around on the desktop. Sooner or later, Zorin says that it has stopped responding and asks if I want to Wait or Force Close it.

It will remain frozen in this state even after waiting several minutes.

The steam menu icon will appear in the taskbar and will open a popup menu with options for Store, Library, Etc. But none of these options will do anything except "Exit Steam", which makes the taskbar menu icon disappear.

#### Steps for reproducing this issue:
1. Perform a fresh install of steam using the Zorin Software Application.
2. Launch Steam.
3. Sign in to an existing account when prompted.
4. Watch the above problems unfold, now and every time you attempt to start it hereafter.
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11925296/steam-logs.tar.gz)

**Comment by FireWingLead** [comment]
Correction to earlier post: Not using Zorin 17. Using Zorin OS 16.2

**Comment by lostgoat** [comment]
To disable GPU acceleration via command line use: `-cef-disable-gpu`

**Comment by FireWingLead** [comment]
And this disables it only for the steam client, not other programs, correct?

**Comment by FireWingLead** [comment]
Update: I unistalled the Zorin OS Software App installation and reinstalled using
`sudo apt install steam`
instead so that I could launch steam from the terminal. I then launched using
`steam -cef-disable-gpu`

Steam once again checked for and installed updates, asked me to sign in (which I did), and then proceeded to continue with the same problem. Nothing changed except that the loading window had a plain dark-grey background instead of a fancy pattern.

**Comment by Synaxis** [comment]
Same issue here. if you run steam via terminal it works.
Steam.deb version

Steam snap version, no issues at all.

**Comment by kisak-valve** [comment]
Hello @Synaxis, symptomatically, you've described #9383.

**Comment by FireWingLead** [comment]
Install attempt #3. @Synaxis reprted that the snap install worked. So I unistalled my last install, using
`sudo apt remove steam`
I then reinstalled using
`sudo snap install steam`
I then tried running, using both
`steam`
and
`steam -cef-disable-gpu`
The terminal output was slightly different with each attempt, but the practical result was the same. Namely, it froze on "Loading User Data". Here is the terminal output from launching with `steam -cef-disable-gpu`:

`Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[14867]: Running Steam on zorin 16 64-bit
steam.sh[14867]: STEAM_RUNTIME is enabled automatically
setup.sh[14987]: Steam runtime environment up-to-date!
steam.sh[14867]: Steam client's requirements are satisfied
[2023-07-02 16:53:45] Startup - updater built Jun 21 2023 21:17:38
[2023-07-02 16:53:45] Startup - Steam Client launched with: '/home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' '-cef-disable-gpu'
07/02 16:53:45 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(15039)
[2023-07-02 16:53:45] Loading cached metrics from disk (/home/perrin/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-02 16:53:45] Using the following download hosts for Public, Realm steamglobal
[2023-07-02 16:53:45] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-07-02 16:53:45] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-07-02 16:53:45] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-02 16:53:45] Verifying installation...
[2023-07-02 16:53:45] Verification complete

(process:15039): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6a91370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6a8fcc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1782-g214d5daa3
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[15213]: Runtime for steamwebhelper: defaulting to /home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[15213]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[15213]: CEF sandbox already disabled
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 13 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13
(steam:15039): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 163 bytes.
BRefreshApplicationsInLibrary 1: 0ms
roaming config store loaded successfully - 163 bytes.
migrating temporary roaming config store

(steam:15039): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/croscore/Arimo-Italic.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
flock /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf LOCK_SH failed. errno = 13Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
System startup time: 3.08 seconds

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:15039): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
Warning: failed to set thread priority: set failed for -10: -1: setpriority() failed
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
[2023-07-02 16:55:46] Background update loop checking for update. . .
[2023-07-02 16:55:46] Checking for available updates...
[2023-07-02 16:55:46] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=4169083952
[2023-07-02 16:55:46] Manifest download: send request
[2023-07-02 16:55:46] Manifest download: waiting for download to finish
[2023-07-02 16:55:46] Manifest download: finished
[2023-07-02 16:55:46] Download skipped: /steam_client_ubuntu12?t=4169083952 version 1687386907, installed version 1687386907, existing pending version 0
[2023-07-02 16:55:46] Nothing to do
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
`

Upon force quitting the "Loading User Data" window, the terminal gave me this:
`steamwebhelper.sh[16127]: Runtime for steamwebhelper: defaulting to /home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/perrin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[16127]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[16127]: CEF sandbox already disabled
`

And upon exiting completely, using "Exit Steam" from the taskbar popup menu, it finished with this:
`(steam:15039): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:15039): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(steam:15039): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
[2023-07-02 17:10:09] Shutdown
`

**Comment by TheBicPen** [comment]
Same issue running the flatpak on KDE Neon. Running `flatpak run com.valvesoftware.Steam -vgui` works normally.

**Comment by simsanutiy** [comment]
Same issue on Linux Mint 21.1, Nvidia RTX 3050, all updates and drivers installed, Steam is installed from a .deb package a while ago. Tries to start for a long time, then fails.
`simsanutiy@simsanutiy-MS-7B84:~$ steam
steam.sh[28947]: Running Steam on linuxmint 21.1 64-bit
steam.sh[28947]: STEAM_RUNTIME is enabled automatically
setup.sh[29083]: Steam runtime environment up-to-date!
steam.sh[28947]: Steam client's requirements are satisfied
[2023-07-05 01:34:57] Startup - updater built Jun 21 2023 21:17:38
[2023-07-05 01:34:57] Startup - Steam Client launched with: '/home/simsanutiy/.local/share/Steam/ubuntu12_32/steam'
07/05 01:34:57 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(29156)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-07-05 01:34:58] Loading cached metrics from disk (/home/simsanutiy/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-05 01:34:58] Using the following download hosts for Public, Realm steamglobal
[2023-07-05 01:34:58] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-07-05 01:34:58] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-07-05 01:34:58] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-05 01:34:58] Checking for update on startup
[2023-07-05 01:34:58] Проверка на наличие обновлений...
[2023-07-05 01:34:58] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-07-05 01:34:58] Manifest download: send request
[2023-07-05 01:34:58] Manifest download: waiting for download to finish
[2023-07-05 01:34:58] Manifest download: finished
[2023-07-05 01:34:58] Download skipped: /steam_client_ubuntu12 version 1687386907, installed version 1687386907, existing pending version 0
[2023-07-05 01:34:58] Nothing to do
[2023-07-05 01:34:58] Проверка установки...
[2023-07-05 01:34:58] Performing checksum verification of executable files
[2023-07-05 01:34:59] Verification complete

(process:29156): GLib-GObject-CRITICAL **: 01:34:59.147: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:29156): GLib-GObject-CRITICAL **: 01:34:59.147: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf4004370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf4002cc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1782-g214d5daa3
Gtk-Message: 01:34:59.374: Failed to load module "gail"
Gtk-Message: 01:34:59.374: Failed to load module "atk-bridge"

(steam:29156): Gtk-WARNING **: 01:34:59.380: Загружаемый модуль тем не найден в module_path: «adwaita»,
/usr/share/themes/Mint-Y-Sand/gtk-2.0/main.rc:1045: error: unexpected identifier 'direction', expected character '}'
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
steamwebhelper.sh[29182]: Runtime for steamwebhelper: defaulting to /home/simsanutiy/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[29182]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
CAppInfoCacheReadFromDiskThread took 99 milliseconds to initialize
Failed to init SteamVR because it isn't installed

(steam:29156): Gtk-WARNING **: 01:35:03.406: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 11564 bytes.
Fossilize INFO: Setting autogroup scheduling.
roaming config store loaded successfully - 11564 bytes.
migrating temporary roaming config store

(steam:29156): GLib-GObject-CRITICAL **: 01:35:05.581: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:29156): GLib-GObject-CRITICAL **: 01:35:05.581: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Fossilize INFO: Setting autogroup scheduling.

(steam:29156): GLib-GObject-CRITICAL **: 01:35:28.811: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:29156): GLib-GObject-CRITICAL **: 01:35:28.811: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
BRefreshApplicationsInLibrary 1: 3745ms
[2023-07-05 01:38:01] Background update loop checking for update. . .
[2023-07-05 01:38:01] Проверка на наличие обновлений...
[2023-07-05 01:38:01] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=2656336943
BRefreshApplicationsInLibrary 1: 573ms
BRefreshApplicationsInLibrary 1: 3587ms
BRefreshApplicationsInLibrary 1: 938ms
BRefreshApplicationsInLibrary 1: 949ms
BRefreshApplicationsInLibrary 1: 476ms
Fossilize INFO: Setting autogroup scheduling.
BRefreshApplicationsInLibrary 1: 889ms
BRefreshApplicationsInLibrary 1: 415ms
BRefreshApplicationsInLibrary 1: 1660ms
BRefreshApplicationsInLibrary 1: 1645ms
BRefreshApplicationsInLibrary 1: 672ms
[2023-07-05 02:18:15] Manifest download: send request
[2023-07-05 02:18:15] Manifest download: waiting for download to finish

(steam:29156): GLib-GObject-CRITICAL **: 02:18:20.474: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:29156): GLib-GObject-CRITICAL **: 02:18:20.474: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
System startup time: 2630.47 seconds
src/steamUI/CloudManager.cpp (879) : Assertion Failed: eState = 1 for nAppID = 2371090

src/steamUI/CloudManager.cpp (879) : Assertion Failed: eState = 1 for nAppID = 2371090

07/05 02:20:21 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(29156)
assert_20230705022021_78.dmp[55608]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230705022021_78.dmp
assert_20230705022021_78.dmp[55608]: Finished uploading minidump (out-of-process): success = yes
assert_20230705022021_78.dmp[55608]: response: CrashID=bp-a9709d1c-b3fa-4b88-b603-7da732230704
assert_20230705022021_78.dmp[55608]: file ''/tmp/dumps/assert_20230705022021_78.dmp'', upload yes: ''CrashID=bp-a9709d1c-b3fa-4b88-b603-7da732230704''
BRefreshApplicationsInLibrary 1: 5953ms
BRefreshApplicationsInLibrary 1: 6457ms
BRefreshApplicationsInLibrary 1: 5520ms
BRefreshApplicationsInLibrary 1: 8712ms
BRefreshApplicationsInLibrary 1: 7464ms
BRefreshApplicationsInLibrary 1: 811ms
BRefreshApplicationsInLibrary 1: 2749ms
BRefreshApplicationsInLibrary 1: 6241ms
BRefreshApplicationsInLibrary 1: 7645ms
BRefreshApplicationsInLibrary 1: 6816ms
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
07/05 03:25:09 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(29156)
assert_20230705032509_107.dmp[93257]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230705032509_107.dmp
_ExitOnFatalAssert
simsanutiy@simsanutiy-MS-7B84:~$ assert_20230705032509_107.dmp[93257]: Finished uploading minidump (out-of-process): success = yes
assert_20230705032509_107.dmp[93257]: response: CrashID=bp-fff3cee6-c899-436f-8136-6e9402230704
assert_20230705032509_107.dmp[93257]: file ''/tmp/dumps/assert_20230705032509_107.dmp'', upload yes: ''CrashID=bp-fff3cee6-c899-436f-8136-6e9402230704''
`

**Comment by tady-eu** [comment]
I am having same issue on Ubuntu 23.04. I tried both snap package and deb version. Both freeze on "Loading user data..."

**Comment by lemeshovich** [comment]
Same for me Debian 11.

**Comment by appleshoops** [comment]
Same issue on Pop!OS. Using flatpak run com.valvesoftware.Steam -vgui works but friends network doesnt

**Comment by TactikalKitty** [comment]
I have this same issue on multiple Linux OS's with RTX 3070.  I have used OpenSuse Tumbleweed, both KDE and Gnome versions. I have also tried with Ubuntu 23.04, Linux Mint 21.1 and Fedora 38. Steam will only launch with X11.

**Comment by Alphenex** [comment]
Same problem!

**Comment by tfitch2140** [comment]
I'm having the same issue as well. Has been an issue for over a week. 

Trying to use cmd: steam -vgui can get me into Steam, but games that previously ran fine (i.e. Homeworld Remastered, which I was in the middle of playing) now lag to the point of crashing in that mode as well, unsure if that's related to the main issue. Other games, like FTL or Stardew Valley, encounter almost no issues.

**Comment by uncasilverthorn** [comment]
Having similar issues.  The "ubuntu" version from software won't allow me to remove either.  Working fine on older version of kernel on my laptops.

**Comment by LinuxRocks101** [comment]
I too also have this issue in Kubuntu 23.04. D:

**Comment by WoodBones** [comment]
Same issue here, Mint 21.0
I've yet to find anyone with the same issue that has a confident fix

**Comment by YerkoBarrientosOsorio** [comment]
Ubuntu 22.04.2. Steam is not running on Wayland apparently. I log in without Wayland and it works. Also isn't working on Mint

**Comment by YerkoBarrientosOsorio** [comment]
> Ubuntu 22.04.2. Steam is not running on Wayland apparently. I log in without Wayland and it works. Also isn't working on Mint

I switched back to NVIDIA driver 525 and it works too, ofc just a temporary solution.

**Comment by maxpain** [comment]
The same problem on Ubuntu 23.04 in Docker

**Comment by saweber79** [comment]
Same issue on openSUSE Tumbleweed

**Comment by appleshoops** [comment]
The issue just fixed itself randomly. It still freezes on loading user data but only for a second and then it loads the new UI. 


If it doesn’t work then launch it with -vgui for the old UI but friends network won’t work.

**Comment by brunosantanaa** [comment]
I confirm the problem in Ubuntu 22.04, but only when executed by the graphical interface if I execute by the terminal works normally.

**Comment by kisak-valve** [comment]
Hello @brunosantanaa, that pair of symptoms points towards #9383.

**Comment by tn464** [comment]
Same issue here with Hyper-V Ubuntu 20.04.2 LTS.  Occasionally, it gets past the loading user data screen; but then the UI doesn't load properly.  Its there, but its transparent.  Moving the mouse around I can sometimes find menus and dropdowns, none-the-less unusable.

Running from terminal with -vgui works but as stated by others, some functions fail like the friend list.  Some games are fine, others crash immediately (Hammerwatch fails for me).

**Comment by neilmartindev** [comment]
Same issue here, works fine with the open source drivers for my RTX 3070 but the performance is garbage for games.

Going to try the .deb instead and see what steam support say.

**Comment by yxding95** [comment]
You can check whether the GPU driver is OK, I found the issue solved after installing the driver.

**Comment by 01d55** [comment]
I see roughly the same symptoms as reported here. Because I previously had a working client, I have a saved login and steam proceeds without prompting me for login information. I get the same result in terminal as I do from the launcher icon. The vgui option appears to get me a working client, with a visual style I recognize but not what is currently defaulted to in the windows client.
Terminal log: 
```
steam.sh[4228]: Running Steam on ubuntu 22.04 64-bit
steam.sh[4228]: STEAM_RUNTIME is enabled automatically
setup.sh[4345]: Steam runtime environment up-to-date!
steam.sh[4228]: Steam client's requirements are satisfied
[2023-07-24 00:39:38] Startup - updater built Jul 10 2023 23:58:24
[2023-07-24 00:39:38] Startup - Steam Client launched with: '/home/notuser/.local/share/Steam/ubuntu12_32/steam' '--restart'
07/24 00:39:38 Init: Installing breakpad exception handler for appid(steam)/version(1689034492)/tid(4415)
[2023-07-24 00:39:38] Loading cached metrics from disk (/home/notuser/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-24 00:39:38] Using the following download hosts for Public, Realm steamglobal
[2023-07-24 00:39:38] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-07-24 00:39:38] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-07-24 00:39:38] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-24 00:39:38] Verifying installation...
[2023-07-24 00:39:38] Verification complete
Loaded SDL version 3.0.0-1782-g214d5daa3
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf706e370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf706ccc0
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[4500]: Runtime for steamwebhelper: defaulting to /home/notuser/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[4500]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
CAppInfoCacheReadFromDiskThread took 45 milliseconds to initialize
Failed to init SteamVR because it isn't installed
local (potentially out of sync) copy of roaming config loaded - 982 bytes.
BRefreshApplicationsInLibrary 1: 0ms
roaming config store loaded successfully - 982 bytes.
migrating temporary roaming config store
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
System startup time: 1.89 seconds
[2023-07-24 00:41:39] Background update loop checking for update. . .
[2023-07-24 00:41:39] Checking for available updates...
[2023-07-24 00:41:39] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=4099594348
[2023-07-24 00:41:39] Manifest download: send request
[2023-07-24 00:41:39] Manifest download: waiting for download to finish
[2023-07-24 00:41:39] Manifest download: finished
[2023-07-24 00:41:39] Download skipped: /steam_client_ubuntu12?t=4099594348 version 1689034492, installed version 1689034492, existing pending version 0
[2023-07-24 00:41:39] Nothing to do
```

**Comment by PLAYERUNKNOWNHatsune01** [comment]
The issue still exist. I'm on openSuse TumbleWeed

**Comment by pdfrod** [comment]
Started having this issue today on Ubuntu 22.04.2. It was working fine yesterday.

**Comment by pdfrod** [comment]
It seems that the problem for me was that the Nouveau drivers were being used instead of the Nvidia ones. I'm not sure how the Nvidia drivers were replaced by the Nouveau drivers, but after switching back to the Nvidia drivers, the problem got fixed.

**Comment by nawwwww** [comment]
Exactly the same issue here.
Nvidia drivers, RTX 2060, infinite loading screen during "Loading user data"
The only solution that worked was to run `steam -vgui`

**Comment by Synaxis** [comment]
> Started having this issue today on Ubuntu 22.04.2. It was working fine yesterday.

Have you installed updates? Please share your apt log ?

**Comment by pdfrod** [comment]
> > Started having this issue today on Ubuntu 22.04.2. It was working fine yesterday.
> 
> Have you installed updates? Please share your apt log ?

Judging by the logs, it seems that an update triggered by unattended-upgrades caused my Nvidia drivers to be removed. I didn't even realized that unattended-upgrades was on by default.

[Here](https://github.com/ValveSoftware/steam-for-linux/files/12244962/apt-logs.tar.gz) are my apt logs.

**Comment by matthewmills0** [comment]
I have an RTX 3080 that was on nvidia-driver-525. I've since upgraded to -535 and it fixed this issue for me. 

Budgie 10.7.1, Ubuntu 23.04, Linux 6.2.0-26-generic, X11

**Comment by im7mortal** [comment]
I have QubesOS. I tried steam snap and deb installation  on Ubuntu 22.04 and Debian qubes(VMs). 
Sometimes it stack at "Loading user data", sometimes it can go through but then main window is just black and the friend's window works . 
With `-vgui` it dispay main window but I still can't play any games. 
I think I started to have problems around the same time when issue was open or even before. I am sure I could play some games at April. 

It's very annoying. :(

**Comment by rbrooklyn** [comment]
I have managed to fix this for my system.

KDE Neon LTS. GTX 1660 Ti. This probably applies to other Ubuntu based systems as well.

If you get the response of a "version mismatch" (sorry don't remember the exact error now) when you try to run `nvidia-smi` from the terminal, then this is being caused by the nvidia drivers and the kernel driver not being the same version and this is what is causing steam to fail to start. I also found the "Green With Envy" app refused to start.

If `nvidia-smi` and "Green With Envy" works for you then this probably isn't the issue. Good luck with your hunt to fixing this.

If you're on AMD this definitely won't help.

Easiest way to fix is to uninstall all the nvidia things:
`sudo apt purge nvidia*`
then reboot (yes, actually reboot please). This will give you the free "Nouveau" driver which will work but won't be useful for games in most systems.
Then I did:
`sudo pkcon install nvidia-driver-535` -- this will take a while to install as it has to compile some software, be patient.
Try `sudo apt install nvidia-driver-535` if pkcon isn't found.
Then reboot.
Then run `nvidia-smi` again and you'll get information about your installation instead of an error.
If you're using the flatpak version of Steam, also do: `flatpak update` to ensure it grabs the correct nvidia runtimes.
Then start steam and it should behave again.

I also tried (this isn't an instruction, don't do this, this paragraph is informational only): sudo apt install --reinstall linux-modules-nvidia-535-6.2.0-26-generic libnvidia-common-535 nvidia-driver-535 nvidia-kernel-common-535 nvidia-kernel-source-535 which _should_ have also fixed the issue.
However that command killed the display completely for me and never fixed the problem. A proper removal, reboot, reinstall is what fixed it for me. I do remember having the screen turn off during a update the other day, so presumably this was the cause for me.

If this is the cause for you (and it probably is if it used to work and you're on a Ubuntu based system) then this isn't a Steam bug, but a distribution issue.

**Comment by neilmartindev** [comment]
I kept getting an error when running `nvidia-smi`. I uninstalled nvidia with `sudo apt purge nvidia*` and then reinstalled the 470 drivers (to test) and installed `sudo apt install nvidia-cuda-toolkit` ontop of it. After doing that, it seems to be working as normal and nvidia-smi has a healthy output.

Currently running GeForce RTX 3070.

**Comment by PetriPiira** [comment]
> I have managed to fix this for my system.
>...
> If this is the cause for you (and it probably is if it used to work and you're on a Ubuntu based system) then this isn't a Steam bug, but a distribution issue.

Thanks!

This helped for me, GTX  3060 and Xubuntu 22.05. I ran sudo apt purge nvidia\*, and installed the additional drivers again using the dialog (nvidia-driver-535)

**Comment by leder11011** [comment]
@rbrooklyn 
This didn't solve it for me.
I never had issue width nvidia-smi but still have error as in OP.

**Comment by ake117** [comment]
I'm using GTX 3060 and Ubuntu 22.04.
After upgrade driver from 525 to 535 then restart.
This fix for me.

**Comment by symo521** [comment]
I am also experiencing this same issue on my server pc, however I am using an intel arc a770, not an nvidia card so I don't believe it's isolated just to nvidia cards.

**Comment by neil-tan** [comment]
On an Ubuntu 20.04, NVIDIA RTX 3090, I resolved this by:
- Purging all nvidia packages
- Reboot
- Installing nvidia driver version 535
- Reboot
- Ensuring X has been configured corrected by running `sudo nvidia-xconfig` or `sudo nvidia-config -c path_to_your_existing_xconf_file`
- Reboot
- Start steam by running `__NV_PRIME_RENDER_OFFLOAD=1 steam` or `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia steam`
- In steam setting, enable beta updates

If you are running a headless machine and using a dummy display, here’s my partial xconf for your reference. Note that the screen’s device has been changed to the dummy device instead of nvidia’s

```

Section "Device"
    Identifier     "Card0"
    Driver         "nvidia"
EndSection

Section "Device"
  Identifier "Card1"
  Driver "dummy"
  VideoRam 256000
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Card1"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"

    # Modes "1600x900_60.00"
        Depth       24
        Modes      "1920x1080_60.00"
    EndSubSection
EndSection
```

**Comment by im7mortal** [comment]
It's definitily not nvidia related. I have laptop with integrated gpu. I use QubesOS. It based on XEN vm. 
To launch steam I created Debian 11 vm. And I have this issue. I also tried it on Jammy with the same result

**Comment by rabbitscreams** [comment]
seconding that this isn't just an nvidia thing. i have an intel card on Linux Mint Cinnamon edition and i have tried uninstalling, reinstalling, running it from every avenue i could think of, tried running it with `steam -vgui`, and so on. steam previously worked just fine for me right up until the GUI update.

**Comment by luis-a-montes** [comment]
Same issue on a Rizen CPU 5 with Radeon RX 6600 graphics running Ubuntu 22.04. I just rebooted and Steam stopped working stuck in loading user data

**Comment by DzenDyn** [comment]
Hello guys. Have same issue on Ubuntu 23.04 installed today. And issue appears only on wayland.
My way to fix: logout, press gear at right-bottom corner and select ubuntu, not ubuntu wayland, then login and run steam.

**Comment by CyberAndrii** [comment]
For me it works when I run on kernel version `6.2.0-26-generic` but doesn't work on `5.19.0-50-generic`. Noticed this after I installed `nvidia-driver-535` (before it was a X server's driver) and it stopped booting up (black screen) so I selected a different version of the kernel in GRUB's advanced options.

**Comment by luis-a-montes** [comment]
Funny. For me, it worked when I went back to 5.19.0-50-generic

> For me it works when I run on kernel version `6.2.0-26-generic` but doesn't work on `5.19.0-50-generic`. Noticed this after I installed `nvidia-driver-535` (before it was an X server's driver) and it stopped booting up (black screen) so I selected a different version of the kernel in GRUB's advanced options.

**Comment by wildjames** [comment]
Another vote for it not being NVIDIA related - I have the same symptoms on the [steam headless docker image](https://github.com/Steam-Headless/docker-steam-headless) running on an unRAID server, with a 5700XT.

**Comment by leder11011** [comment]
> 



> Hello guys. Have same issue on Ubuntu 23.04 installed today. And issue appears only on wayland.
> My way to fix: logout, press gear at right-bottom corner and select ubuntu, not ubuntu wayland, then login and run steam.

this is not working for me, though! On xserver the steam client doesn't even display the splash screen.

**Comment by Synaxis** [comment]
@leder11011 @DzenDyn try Steam snap

**Comment by leder11011** [comment]
@Synaxis yes, Ty! Well come back to you...

**Comment by leder11011** [comment]
Thank you: that solved the startup of steam client. I have a follow up...

**Comment by Omoorion** [comment]
Hello everyone!
I did some testing using Ubuntu 22.04.3 with steam installed from FlatHub.
I found out that steam does not load properly and gets stuck in the "loading user data" screen on some versions of the linux KERNEL.
for example, the newest kernel version - 6.5  does not work.
However, Kernel version - 6.2.2 works well with steam and doesn't produce the bug.
Idk the details of it, but steam as of now just doesn't work with some newer or older versions of the kernel apperantly.
I wrote this comment as a short-term solution for those in need, as I didn't see any other comment that covered this topic!
Hope this solves it for you too, enjoy.

**Comment by leder11011** [comment]
Thank you: snap solved the loading screen issue for me, but introduced a
different bug "CPU rendering" instead of GPU rendering.

Synaxis ***@***.***> schrieb am Fr., 1. Sept. 2023, 00:19:

**Comment by OMGUSED** [comment]
Just had this issue with Linux Mint 21.1 and since the kernel was mentioned, I changed the distro-specific kernel to an older version and it worked. The faulty distro Kernel 6.2.0-32 is the problematic. Switching back to  Kernel 6.2.0-31 got me past the user data stage

**Comment by im7mortal** [comment]
It was already 3 months as I didn't play any games (last Saturday I registered to GOG).  The issue not related nor Nvidia nor Ubuntu Linux . I have following kernel version. **6.1.42-1.qubes.fc32.x86_64 x86_64** from vm where I host steam,   my laptop doesn't have GPU.

How we can get attention to this issue? 

**I registered to GOG last Saturday**, their game distribution is nice. I got a game for 2 euros and then just downloaded huge sh file. That is it. And I have my games! 
With Steam I can't access my games!

**Comment by shymega** [comment]
I found that using Nixpkgs-unstable's version of Sway/wlroots breaks both the native Steam, and the Flatpak Steam. When I downgraded to Nixpkgs-23.05 Sway/wlroots, the issue was fixed.

It does not break on KDE, with an AMDGPU or Intel Xe. Two machines exhibit the same behaviour, one with AMD CPU and AMD integrated graphics, and one with Intel CPU + Xe Graphics.

**Comment by cobyforrester** [comment]
Same issue on arch after not using my PC for 6 months and updating everything, it previously worked
### System
- Arch Linux
- Kernel: `6.1.52-1-lts`
- GPU: `NVIDIA GeForce RTX 3050`
- Running without a desktop, so no wayland: `XDG_SESSION_TYPE=tty` (using i3 as my desktop)
- Nvidia packages: `nvidia-lts-1:535.104.05-9`, `nvidia-535.104.05-5` (neither work)
- steam installed through pacman

### Failed attempts
- Reinstall all things nvidia
- Switch to the non-LTS, latest kernel
- `steam --reset`
- Run steam with `-vgui` or  `-no-cef-sandbox`
- `nvidia-smi` runs without issue
- Installing steam through flatpak has the exact same issue

**Comment by im7mortal** [comment]
@cobyforrester I refreshed steam and also steam updated themself. Problem is still here.

**Comment by jsgf** [comment]
I found it was still having this problem with Wayland, but it works with X11.

**Comment by acranglesim** [comment]
I get the same issue with ubuntu 23.04 / 23.10 - nvidia driver 535. Works on X11, hangs at loading user data on wayland.

**Comment by im7mortal** [comment]
What is a way to get an attention to the problem?
I didn't play any steam game for 4 months

I especially pissed off that I just can't start **MY** games. Why I would need this steam wrapper? I payed for them! :rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::ra:rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage:ge::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage::rage:

**Comment by shymega** [comment]
> What is a way to get an attention to the problem? I didn't play any steam game for 4 months
> 
> I especially pissed off that I just can't start **MY** games. Why I would need this steam wrapper? I payed for them! 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡:ra😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡ge:😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

I don't think spamming the issue tracker with emojis, and swearing is gonna help the matter.

**Comment by febs** [comment]
I removed "nomodeset" from the kerne boot options in grub.cfg and that solved the issue for me.

**Comment by LinuxRocks101** [comment]
At least spamming the thread with emojis is noticeable. So maybe someone at Valve will see this easier. lol
________________________________

**Comment by Swishfox** [comment]
After hours of trying, I finally fixed this issue. Installing steam via flatpak (see: https://wiki.archlinux.org/title/Steam) and running 'flatpak run --socket=session-bus com.valvesoftware.Steam -cef-disable-gpu' worked for me. Note that Steam should be written with a capital S. Please let me know if this helps anyone! This is my first comment I believe, so feedback is welcome.

**Comment by normanbrobinson** [comment]
> ...running 'flatpak run --socket=session-bus com.valvesoftware.Steam -cef-disable-gpu' worked for me: Pop!_OS 22.04 LTS, X11, Gnome, running on AMD Ryzen 7 7840u with radeon 780m graphics on Framework Laptop 13. THANK YOU!

**Comment by acranglesim** [comment]
After swapping to X11 and disabling these settings in settings->interface:
enable smooth scrolling
enable GPU accelerated rendering
enable hardware video decoding

Rebooting, and swapping back to wayland - steam now launches fine. However, I then run into the issue that all games i've tried (that work on x11) launch to a black screen but with audio (i.e cyberpunk 2077). Nvidia driver 535 and 545. Hopefully this helps someone though.

**Comment by shymega** [comment]
My original suspicion was that this is Mesa-related. I'm on NixOS, and I reproduced the hang with both Flatpak and the native executable. However, given it worked fine on KDE Plasma (Wayland+X11), I ruled it out being Mesa. It could be related to `wlroots`, but since the last Steam update, on Flatpak and native, it works fine for me now. My focus is making a wrapper for Wemod now.

If anyone at Valve is seeing this comment, I hypothesise that this are indeed multiple issues at play. I think the first issue is network-related, and the second issue is graphical acceleration. It does not appear limited to Linux, as there's a report of it happening on Windows. 

We need to gather data on system environments so that Valve can isolate the bug. Seeing as it seems to have started with the graphical overhaul, I suspect a bug with that, as well as networking.

**Comment by theflu** [comment]
I opened a ticket with "Steam Support" they said they "refreshed" my account on their and it is working now.

**Comment by timo-krnmr** [comment]
> I opened a ticket with "Steam Support" they said they "refreshed" my account on their and it is working now.

What exactly do you mean by "refresh", could this be something we can do ourselves somewhere?
Though it sounded like it was an unrelated non Wayland issue for you, given you were having issues on Win10 also, it might still be worth a try.

**Comment by theflu** [comment]
> > I opened a ticket with "Steam Support" they said they "refreshed" my account on their and it is working now.
> 
> What exactly do you mean by "refresh", could this be something we can do ourselves somewhere? Though it sounded like it was an unrelated non Wayland issue for you, given you were having issues on Win10 also, it might still be worth a try.

This is the response they sent it doesn't seem like something we could do ourselves.
`I refreshed your account on our end.

Please try the following steps to resolve the login issue you are encountering:

1) Try exiting the Steam client completely, restart it and try again.

2) If that does not work, please try to remove the account from the initial login screen. On the "Who's playing" box that shows when you first start Steam, hover over the account's image with your mouse. Select the "..." icon. Select the "Remove this account?" option. Select "Remove account" button. After the account is removed, restart Steam and try logging in.

3) If that does not work, we would then recommend clearing your web browser's stored cookies and then retrying.

Let us know if you continue to have problems.

Steam Support`

**Comment by LinuxRocks101** [comment]
![Guessing game...](http://github.com/ValveSoftware/steam-for-linux/assets/108767657/81afdab4-bdb1-4a61-bca3-9ba69b769dbc)

**Comment by kgibsonprogramming** [comment]
Finally solved this on a fresh install of Fedora 39 and AMD card by removing 'nomodeset' in grub. Install had defaulted to llvmpipe instead of using the graphics card, after changing this steam continued to load with no issues.

**Comment by skuzad25** [comment]
Running the Steam big picture mode fixed it for me.

**Comment by akruppa** [comment]
I have this problem, too, as of today. Last change I did to my system was update Mesa from 22.? to 23.3.4. OpenSuse Tumbleweed.

**Comment by akruppa** [comment]
I think the problem for me was caused by a partial system update. I had updated only Mesa (all packages whose name starts with mesa), but not other packages. I did a full system update now, it seems that everything works again. Case of user error.

**Comment by xxxx81** [comment]
For me under LMDE6 (Debian 12) it runs with the parameter "-cef-in-process-gpu" I had to try for quite a while until I found that out before it was absolutely impossible to get it to start and always hung at loading user data.

**Comment by sguergachi** [comment]
Happening for me with KDE and CachyOS

**Comment by ivanguy** [comment]
For me the problem was an unconnected drive configured with x-systemd.automount. Even though i removed steam library from it, steam appears to still try to access it indefinetly(~2m30s). Maybe connected to https://github.com/systemd/systemd/issues/2181.
